import { useSyncExternalStore } from "react";
import { backend } from "../backend";

/**
 * Runtime themes (issue #36).
 *
 * This file is the ONE place literal hex lives in the renderer. A palette has
 * three consumers that cannot share a mechanism — Tailwind's `--color-*`
 * tokens (CSS), xterm's ITheme (canvas, cannot read CSS), and shiki's theme
 * (tokens are emitted as inline `style={{ color }}`) — so a theme that lived
 * only in `style.css` would still leave two palettes drifting behind it. Each
 * `Theme` below carries all three, authored together, so a switch is atomic.
 *
 * `style.css` keeps the graphite `@theme` block as the *build-time* default;
 * `applyTheme` overrides those same custom properties on the root element,
 * which Tailwind v4 utilities dereference at paint time (`.bg-surface` is
 * `background-color: var(--color-surface)`), so no CSS rebuild is involved.
 * Consequence: `graphite`'s `tokens` must stay byte-identical to that block.
 *
 * Every theme keeps the reservation from ADR-0004: `signal` is agent liveness
 * and success only, `copper` attention, `rose` failure, `iris` the user's own
 * voice. A borrowed palette (Monokai, Solarized) is re-mapped onto those four
 * roles rather than copied slot-for-slot, because the "is it working?" glance
 * is a property of the reservation, not of any particular hue.
 */

export interface Theme {
  id: string;
  label: string;
  /** Drives `color-scheme` and the dark-chrome utilities. */
  dark: boolean;
  /** Every `--color-*` token from style.css's @theme block. */
  tokens: Record<string, string>;
  /** The xterm ITheme, replacing TERM_THEME. */
  term: Record<string, string>;
  /** The shiki theme's colours, replacing GRAPHITE's literals. */
  code: {
    foreground: string;
    comment: string;
    string: string;
    constant: string;
    keyword: string;
    function: string;
    type: string;
    property: string;
    punctuation: string;
    inserted: string;
    deleted: string;
  };
}

export const THEMES: readonly Theme[] = [
  {
    id: "graphite",
    label: "Graphite",
    dark: true,
    tokens: {
      "--color-void": "#0a0b0d",
      "--color-sunken": "#0e1013",
      "--color-surface": "#14171b",
      "--color-raised": "#1a1e23",
      "--color-overlay": "#22272e",
      "--color-hover": "#2a3037",
      "--color-line": "#23282f",
      "--color-line-soft": "#1b1f24",
      "--color-line-strong": "#333a43",
      "--color-ink": "#e8ecf1",
      "--color-ink-mid": "#a8b2bf",
      "--color-ink-dim": "#6f7b8a",
      "--color-ink-faint": "#4a5361",
      "--color-signal": "#4ade9f",
      "--color-signal-dim": "#2a8f65",
      "--color-signal-wash": "#0f2a20",
      "--color-copper": "#f0a868",
      "--color-copper-dim": "#a8703c",
      "--color-copper-wash": "#2a1e12",
      "--color-rose": "#f2748c",
      "--color-rose-dim": "#a34355",
      "--color-rose-wash": "#2b1419",
      "--color-iris": "#9d8cf5",
      "--color-iris-dim": "#6152a8",
      "--color-iris-wash": "#1c1830",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#14171b",
      foreground: "#e8ecf1",
      cursor: "#4ade9f",
      cursorAccent: "#14171b",
      selectionBackground: "#9d8cf559",
      selectionInactiveBackground: "#9d8cf52e",
      black: "#0e1013",
      red: "#f2748c",
      green: "#4ade9f",
      yellow: "#f0a868",
      blue: "#7fa9f0",
      magenta: "#9d8cf5",
      cyan: "#66d9d2",
      white: "#a8b2bf",
      brightBlack: "#4a5361",
      brightRed: "#ef9cad",
      brightGreen: "#7ee3ba",
      brightYellow: "#edbe95",
      brightBlue: "#a2bff0",
      brightMagenta: "#b6acf4",
      brightCyan: "#91dfdc",
      brightWhite: "#e8ecf1",
    },
    code: {
      foreground: "#e8ecf1",
      comment: "#5f6b7c",
      string: "#e0b184",
      constant: "#e39db5",
      keyword: "#9d8cf5",
      function: "#7fb8e8",
      type: "#6fc7d4",
      property: "#a8c5e8",
      punctuation: "#a8b2bf",
      inserted: "#8fd4b8",
      deleted: "#f2748c",
    },
  },
  {
    id: "dark-modern",
    label: "Dark Modern",
    dark: true,
    tokens: {
      "--color-void": "#141414",
      "--color-sunken": "#181818",
      "--color-surface": "#1f1f1f",
      "--color-raised": "#252526",
      "--color-overlay": "#2d2d30",
      "--color-hover": "#37373d",
      "--color-line": "#2b2b2b",
      "--color-line-soft": "#242424",
      "--color-line-strong": "#3c3c3c",
      "--color-ink": "#e7e7e7",
      "--color-ink-mid": "#b5b5b5",
      "--color-ink-dim": "#8b8b8b",
      "--color-ink-faint": "#5f5f5f",
      "--color-signal": "#4ec9a2",
      "--color-signal-dim": "#2f8468",
      "--color-signal-wash": "#12271f",
      "--color-copper": "#dcb67a",
      "--color-copper-dim": "#957a4d",
      "--color-copper-wash": "#2a2114",
      "--color-rose": "#f14c4c",
      "--color-rose-dim": "#a13636",
      "--color-rose-wash": "#2c1616",
      "--color-iris": "#9c8cf0",
      "--color-iris-dim": "#61549c",
      "--color-iris-wash": "#1d1a2e",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#1f1f1f",
      foreground: "#e7e7e7",
      cursor: "#4ec9a2",
      cursorAccent: "#1f1f1f",
      selectionBackground: "#9c8cf059",
      selectionInactiveBackground: "#9c8cf02e",
      black: "#181818",
      red: "#f14c4c",
      green: "#4ec9a2",
      yellow: "#dcb67a",
      blue: "#569cd6",
      magenta: "#9c8cf0",
      cyan: "#4ec9b0",
      white: "#b5b5b5",
      brightBlack: "#5f5f5f",
      brightRed: "#ee7f7f",
      brightGreen: "#80d3b9",
      brightYellow: "#e0c69e",
      brightBlue: "#86b5dc",
      brightMagenta: "#b5aaed",
      brightCyan: "#80d3c2",
      brightWhite: "#e7e7e7",
    },
    code: {
      foreground: "#e7e7e7",
      comment: "#6a9955",
      string: "#ce9178",
      constant: "#b5cea8",
      keyword: "#9c8cf0",
      function: "#dcdcaa",
      type: "#4ec9b0",
      property: "#9cdcfe",
      punctuation: "#b5b5b5",
      inserted: "#7cd6a7",
      deleted: "#f14c4c",
    },
  },
  {
    id: "monokai",
    label: "Monokai",
    dark: true,
    tokens: {
      "--color-void": "#1b1c18",
      "--color-sunken": "#22231e",
      "--color-surface": "#272822",
      "--color-raised": "#2f302a",
      "--color-overlay": "#3a3b34",
      "--color-hover": "#49483e",
      "--color-line": "#3b3c35",
      "--color-line-soft": "#2f302a",
      "--color-line-strong": "#54554c",
      "--color-ink": "#f8f8f2",
      "--color-ink-mid": "#c8c8bd",
      "--color-ink-dim": "#9a9a8d",
      "--color-ink-faint": "#75715e",
      "--color-signal": "#a6e22e",
      "--color-signal-dim": "#6f9720",
      "--color-signal-wash": "#222a12",
      "--color-copper": "#fd971f",
      "--color-copper-dim": "#ac6715",
      "--color-copper-wash": "#2e2011",
      "--color-rose": "#f92672",
      "--color-rose-dim": "#a81b4e",
      "--color-rose-wash": "#2c1220",
      "--color-iris": "#ae81ff",
      "--color-iris-dim": "#7455ab",
      "--color-iris-wash": "#241d33",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#a6e22e",
      cursorAccent: "#272822",
      selectionBackground: "#ae81ff59",
      selectionInactiveBackground: "#ae81ff2e",
      black: "#22231e",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#fd971f",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#66d9ef",
      white: "#c8c8bd",
      brightBlack: "#75715e",
      brightRed: "#f96b9c",
      brightGreen: "#c1e96f",
      brightYellow: "#fbb765",
      brightBlue: "#96e3f0",
      brightMagenta: "#c6a8fb",
      brightCyan: "#96e3f0",
      brightWhite: "#f8f8f2",
    },
    code: {
      foreground: "#f8f8f2",
      comment: "#75715e",
      string: "#e6db74",
      constant: "#ae81ff",
      keyword: "#ae81ff",
      function: "#a6e22e",
      type: "#66d9ef",
      property: "#fd971f",
      punctuation: "#c8c8bd",
      inserted: "#a6e22e",
      deleted: "#f92672",
    },
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    dark: true,
    tokens: {
      "--color-void": "#00212b",
      "--color-sunken": "#002028",
      "--color-surface": "#002b36",
      "--color-raised": "#01323d",
      "--color-overlay": "#073642",
      "--color-hover": "#0c4553",
      "--color-line": "#0b3c49",
      "--color-line-soft": "#04303b",
      "--color-line-strong": "#14505f",
      "--color-ink": "#eee8d5",
      "--color-ink-mid": "#93a1a1",
      "--color-ink-dim": "#839496",
      "--color-ink-faint": "#586e75",
      "--color-signal": "#2aa198",
      "--color-signal-dim": "#1c6b65",
      "--color-signal-wash": "#032b2e",
      "--color-copper": "#cb4b16",
      "--color-copper-dim": "#8a330f",
      "--color-copper-wash": "#2a1a10",
      "--color-rose": "#dc322f",
      "--color-rose-dim": "#94211f",
      "--color-rose-wash": "#2b1315",
      "--color-iris": "#6c71c4",
      "--color-iris-dim": "#484c85",
      "--color-iris-wash": "#151d33",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#002b36",
      foreground: "#eee8d5",
      cursor: "#2aa198",
      cursorAccent: "#002b36",
      selectionBackground: "#6c71c459",
      selectionInactiveBackground: "#6c71c42e",
      black: "#002028",
      red: "#dc322f",
      green: "#2aa198",
      yellow: "#cb4b16",
      blue: "#268bd2",
      magenta: "#6c71c4",
      cyan: "#2aa198",
      white: "#93a1a1",
      brightBlack: "#586e75",
      brightRed: "#e26e66",
      brightGreen: "#6bb8ac",
      brightYellow: "#d77f55",
      brightBlue: "#68aad3",
      brightMagenta: "#9798ca",
      brightCyan: "#6bb8ac",
      brightWhite: "#eee8d5",
    },
    code: {
      foreground: "#eee8d5",
      comment: "#5d757c",
      string: "#b58900",
      constant: "#d33682",
      keyword: "#6c71c4",
      function: "#268bd2",
      type: "#2aa198",
      property: "#93a1a1",
      punctuation: "#93a1a1",
      inserted: "#859900",
      deleted: "#dc322f",
    },
  },
  {
    id: "one-dark",
    label: "One Dark",
    dark: true,
    tokens: {
      "--color-void": "#1b1f27",
      "--color-sunken": "#21252e",
      "--color-surface": "#282c34",
      "--color-raised": "#2f343e",
      "--color-overlay": "#383e4a",
      "--color-hover": "#404756",
      "--color-line": "#363c46",
      "--color-line-soft": "#2d323b",
      "--color-line-strong": "#4b5263",
      "--color-ink": "#dfe3ea",
      "--color-ink-mid": "#abb2bf",
      "--color-ink-dim": "#848e9c",
      "--color-ink-faint": "#5f6773",
      "--color-signal": "#98c379",
      "--color-signal-dim": "#69845c",
      "--color-signal-wash": "#1e2a1c",
      "--color-copper": "#d19a66",
      "--color-copper-dim": "#8a6c51",
      "--color-copper-wash": "#2b2317",
      "--color-rose": "#e06c75",
      "--color-rose-dim": "#93515a",
      "--color-rose-wash": "#2e1d20",
      "--color-iris": "#c678dd",
      "--color-iris-dim": "#845896",
      "--color-iris-wash": "#2a1e31",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#282c34",
      foreground: "#dfe3ea",
      cursor: "#98c379",
      cursorAccent: "#282c34",
      selectionBackground: "#c678dd59",
      selectionInactiveBackground: "#c678dd2e",
      black: "#21252e",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#d19a66",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5f6773",
      brightRed: "#e09098",
      brightGreen: "#adcd9b",
      brightYellow: "#d5b08e",
      brightBlue: "#87bfee",
      brightMagenta: "#ce98e1",
      brightCyan: "#7fc4ce",
      brightWhite: "#dfe3ea",
    },
    code: {
      foreground: "#dfe3ea",
      comment: "#7f848e",
      string: "#98c379",
      constant: "#d19a66",
      keyword: "#c678dd",
      function: "#61afef",
      type: "#e5c07b",
      property: "#e06c75",
      punctuation: "#abb2bf",
      inserted: "#98c379",
      deleted: "#e06c75",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    dark: true,
    tokens: {
      "--color-void": "#191a24",
      "--color-sunken": "#20222c",
      "--color-surface": "#282a36",
      "--color-raised": "#2f3240",
      "--color-overlay": "#383b4b",
      "--color-hover": "#44475a",
      "--color-line": "#3a3d4d",
      "--color-line-soft": "#2e3140",
      "--color-line-strong": "#535776",
      "--color-ink": "#f8f8f2",
      "--color-ink-mid": "#c0c4d8",
      "--color-ink-dim": "#8e94b0",
      "--color-ink-faint": "#636a8a",
      "--color-signal": "#50fa7b",
      "--color-signal-dim": "#3fa35e",
      "--color-signal-wash": "#173222",
      "--color-copper": "#ffb86c",
      "--color-copper-dim": "#a57c55",
      "--color-copper-wash": "#332818",
      "--color-rose": "#ff5555",
      "--color-rose-dim": "#a54348",
      "--color-rose-wash": "#331b1d",
      "--color-iris": "#bd93f9",
      "--color-iris-dim": "#7e67a7",
      "--color-iris-wash": "#2a2140",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#50fa7b",
      cursorAccent: "#282a36",
      selectionBackground: "#bd93f959",
      selectionInactiveBackground: "#bd93f92e",
      black: "#20222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#c0c4d8",
      brightBlack: "#636a8a",
      brightRed: "#fd8684",
      brightGreen: "#82f99f",
      brightYellow: "#f3f9ab",
      brightBlue: "#cfb1f7",
      brightMagenta: "#fd9fd3",
      brightCyan: "#aceefa",
      brightWhite: "#f8f8f2",
    },
    code: {
      foreground: "#f8f8f2",
      comment: "#6272a4",
      string: "#f1fa8c",
      constant: "#bd93f9",
      keyword: "#ff79c6",
      function: "#50fa7b",
      type: "#8be9fd",
      property: "#ffb86c",
      punctuation: "#c0c4d8",
      inserted: "#50fa7b",
      deleted: "#ff5555",
    },
  },
  {
    id: "nord",
    label: "Nord",
    dark: true,
    tokens: {
      "--color-void": "#232831",
      "--color-sunken": "#292e39",
      "--color-surface": "#2e3440",
      "--color-raised": "#353c4a",
      "--color-overlay": "#3b4252",
      "--color-hover": "#434c5e",
      "--color-line": "#3b4252",
      "--color-line-soft": "#333a47",
      "--color-line-strong": "#4c566a",
      "--color-ink": "#eceff4",
      "--color-ink-mid": "#c2cbdc",
      "--color-ink-dim": "#94a0b8",
      "--color-ink-faint": "#68758d",
      "--color-signal": "#a3be8c",
      "--color-signal-dim": "#72846c",
      "--color-signal-wash": "#28321f",
      "--color-copper": "#d08770",
      "--color-copper-dim": "#8c645c",
      "--color-copper-wash": "#32241c",
      "--color-rose": "#bf616a",
      "--color-rose-dim": "#824e58",
      "--color-rose-wash": "#301c20",
      "--color-iris": "#b48ead",
      "--color-iris-dim": "#7c687f",
      "--color-iris-wash": "#2d2331",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#2e3440",
      foreground: "#eceff4",
      cursor: "#a3be8c",
      cursorAccent: "#2e3440",
      selectionBackground: "#b48ead59",
      selectionInactiveBackground: "#b48ead2e",
      black: "#292e39",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#c2cbdc",
      brightBlack: "#68758d",
      brightRed: "#cc8c93",
      brightGreen: "#b9cdab",
      brightYellow: "#ebd6aa",
      brightBlue: "#a1b8d0",
      brightMagenta: "#c5abc2",
      brightCyan: "#a6cedb",
      brightWhite: "#eceff4",
    },
    code: {
      foreground: "#eceff4",
      comment: "#7b88a1",
      string: "#a3be8c",
      constant: "#b48ead",
      keyword: "#81a1c1",
      function: "#88c0d0",
      type: "#8fbcbb",
      property: "#d8dee9",
      punctuation: "#c2cbdc",
      inserted: "#a3be8c",
      deleted: "#bf616a",
    },
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    dark: true,
    tokens: {
      "--color-void": "#1d2021",
      "--color-sunken": "#232526",
      "--color-surface": "#282828",
      "--color-raised": "#32302f",
      "--color-overlay": "#3c3836",
      "--color-hover": "#504945",
      "--color-line": "#3c3836",
      "--color-line-soft": "#302e2d",
      "--color-line-strong": "#5a524c",
      "--color-ink": "#f2e5bc",
      "--color-ink-mid": "#d5c4a1",
      "--color-ink-dim": "#a89984",
      "--color-ink-faint": "#7c6f64",
      "--color-signal": "#b8bb26",
      "--color-signal-dim": "#7c7d27",
      "--color-signal-wash": "#2a2c10",
      "--color-copper": "#fe8019",
      "--color-copper-dim": "#a45b1f",
      "--color-copper-wash": "#332312",
      "--color-rose": "#fb4934",
      "--color-rose-dim": "#a23b2f",
      "--color-rose-wash": "#331a15",
      "--color-iris": "#d3869b",
      "--color-iris-dim": "#8b5f6b",
      "--color-iris-wash": "#2f2126",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#282828",
      foreground: "#f2e5bc",
      cursor: "#b8bb26",
      cursorAccent: "#282828",
      selectionBackground: "#d3869b59",
      selectionInactiveBackground: "#d3869b2e",
      black: "#232526",
      red: "#fb4934",
      green: "#b8bb26",
      yellow: "#fabd2f",
      blue: "#83a598",
      magenta: "#d3869b",
      cyan: "#8ec07c",
      white: "#d5c4a1",
      brightBlack: "#7c6f64",
      brightRed: "#f8785d",
      brightGreen: "#c9c853",
      brightYellow: "#f8c959",
      brightBlue: "#a4b8a3",
      brightMagenta: "#dca2a5",
      brightCyan: "#accb8f",
      brightWhite: "#f2e5bc",
    },
    code: {
      foreground: "#f2e5bc",
      comment: "#9d8f7c",
      string: "#b8bb26",
      constant: "#d3869b",
      keyword: "#fb4934",
      function: "#fabd2f",
      type: "#8ec07c",
      property: "#83a598",
      punctuation: "#d5c4a1",
      inserted: "#b8bb26",
      deleted: "#fb4934",
    },
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    dark: true,
    tokens: {
      "--color-void": "#121218",
      "--color-sunken": "#16161e",
      "--color-surface": "#1a1b26",
      "--color-raised": "#20212e",
      "--color-overlay": "#282a3a",
      "--color-hover": "#33364a",
      "--color-line": "#292b3d",
      "--color-line-soft": "#20222f",
      "--color-line-strong": "#3d405c",
      "--color-ink": "#c8d3f5",
      "--color-ink-mid": "#a9b4de",
      "--color-ink-dim": "#828bb8",
      "--color-ink-faint": "#5d6488",
      "--color-signal": "#9ece6a",
      "--color-signal-dim": "#67834d",
      "--color-signal-wash": "#20291a",
      "--color-copper": "#ff9e64",
      "--color-copper-dim": "#9f674a",
      "--color-copper-wash": "#302216",
      "--color-rose": "#f7768e",
      "--color-rose-dim": "#9a5062",
      "--color-rose-wash": "#2e1a24",
      "--color-iris": "#bb9af7",
      "--color-iris-dim": "#77659f",
      "--color-iris-wash": "#262038",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#1a1b26",
      foreground: "#c8d3f5",
      cursor: "#9ece6a",
      cursorAccent: "#1a1b26",
      selectionBackground: "#bb9af759",
      selectionInactiveBackground: "#bb9af72e",
      black: "#16161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b4de",
      brightBlack: "#5d6488",
      brightRed: "#e992ad",
      brightGreen: "#abd094",
      brightYellow: "#d9ba92",
      brightBlue: "#91b1f6",
      brightMagenta: "#bfabf6",
      brightCyan: "#94d0fc",
      brightWhite: "#c8d3f5",
    },
    code: {
      foreground: "#c8d3f5",
      comment: "#6a739e",
      string: "#9ece6a",
      constant: "#ff9e64",
      keyword: "#bb9af7",
      function: "#7aa2f7",
      type: "#2ac3de",
      property: "#7dcfff",
      punctuation: "#a9b4de",
      inserted: "#9ece6a",
      deleted: "#f7768e",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    dark: true,
    tokens: {
      "--color-void": "#11111b",
      "--color-sunken": "#181825",
      "--color-surface": "#1e1e2e",
      "--color-raised": "#262637",
      "--color-overlay": "#313244",
      "--color-hover": "#3b3c52",
      "--color-line": "#313244",
      "--color-line-soft": "#27273a",
      "--color-line-strong": "#45475a",
      "--color-ink": "#cdd6f4",
      "--color-ink-mid": "#a9b1d6",
      "--color-ink-dim": "#8288ab",
      "--color-ink-faint": "#5f6486",
      "--color-signal": "#a6e3a1",
      "--color-signal-dim": "#6d9071",
      "--color-signal-wash": "#1e2f22",
      "--color-copper": "#fab387",
      "--color-copper-dim": "#9e7462",
      "--color-copper-wash": "#31251c",
      "--color-rose": "#f38ba8",
      "--color-rose-dim": "#9a5d75",
      "--color-rose-wash": "#2f1d2a",
      "--color-iris": "#cba6f7",
      "--color-iris-dim": "#826da3",
      "--color-iris-wash": "#292140",
      "--color-edge-hi": "rgb(255 255 255 / 0.05)",
      "--color-edge-lo": "rgb(0 0 0 / 0.4)",
    },
    term: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#a6e3a1",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#cba6f759",
      selectionInactiveBackground: "#cba6f72e",
      black: "#181825",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#cba6f7",
      cyan: "#94e2d5",
      white: "#a9b1d6",
      brightBlack: "#5f6486",
      brightRed: "#e8a2bf",
      brightGreen: "#b2dfba",
      brightYellow: "#ecdec4",
      brightBlue: "#9dbef8",
      brightMagenta: "#ccb4f6",
      brightCyan: "#a5dede",
      brightWhite: "#cdd6f4",
    },
    code: {
      foreground: "#cdd6f4",
      comment: "#7f849c",
      string: "#a6e3a1",
      constant: "#fab387",
      keyword: "#cba6f7",
      function: "#89b4fa",
      type: "#f9e2af",
      property: "#89dceb",
      punctuation: "#a9b1d6",
      inserted: "#a6e3a1",
      deleted: "#f38ba8",
    },
  },
  {
    id: "light",
    label: "Light",
    dark: false,
    tokens: {
      "--color-void": "#e8ecf0",
      "--color-sunken": "#f1f4f7",
      "--color-surface": "#fafbfc",
      "--color-raised": "#ffffff",
      "--color-overlay": "#ffffff",
      "--color-hover": "#e6ebf0",
      "--color-line": "#d8dee5",
      "--color-line-soft": "#e7ecf1",
      "--color-line-strong": "#b9c2cc",
      "--color-ink": "#12161b",
      "--color-ink-mid": "#41505f",
      "--color-ink-dim": "#5f6f7e",
      "--color-ink-faint": "#8c9aa8",
      "--color-signal": "#0f7d55",
      "--color-signal-dim": "#14a06d",
      "--color-signal-wash": "#d7f0e4",
      "--color-copper": "#a3560c",
      "--color-copper-dim": "#c97a2a",
      "--color-copper-wash": "#f8e8d5",
      "--color-rose": "#b31d3a",
      "--color-rose-dim": "#d24a63",
      "--color-rose-wash": "#fbe5ea",
      "--color-iris": "#4a34b8",
      "--color-iris-dim": "#6f5ad0",
      "--color-iris-wash": "#eae5fb",
      "--color-edge-hi": "rgb(255 255 255 / 0.9)",
      "--color-edge-lo": "rgb(15 23 32 / 0.10)",
    },
    term: {
      background: "#fafbfc",
      foreground: "#12161b",
      cursor: "#0f7d55",
      cursorAccent: "#fafbfc",
      selectionBackground: "#4a34b859",
      selectionInactiveBackground: "#4a34b82e",
      black: "#12161b",
      red: "#b31d3a",
      green: "#0f7d55",
      yellow: "#a3560c",
      blue: "#1c5fb0",
      magenta: "#4a34b8",
      cyan: "#0b7078",
      white: "#41505f",
      brightBlack: "#5f6f7e",
      brightRed: "#7e1b30",
      brightGreen: "#105b42",
      brightYellow: "#734111",
      brightBlue: "#19477f",
      brightMagenta: "#382a84",
      brightCyan: "#0d5259",
      brightWhite: "#12161b",
    },
    code: {
      foreground: "#12161b",
      comment: "#6a7885",
      string: "#984b1a",
      constant: "#a11a6b",
      keyword: "#4a34b8",
      function: "#1c5fb0",
      type: "#0b7078",
      property: "#2a5a8a",
      punctuation: "#41505f",
      inserted: "#0f7d55",
      deleted: "#b31d3a",
    },
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    dark: false,
    tokens: {
      "--color-void": "#e6e0cd",
      "--color-sunken": "#eee8d5",
      "--color-surface": "#f7f1de",
      "--color-raised": "#fdf6e3",
      "--color-overlay": "#fffaec",
      "--color-hover": "#e9e2cf",
      "--color-line": "#ded8c4",
      "--color-line-soft": "#eee8d5",
      "--color-line-strong": "#bfb99f",
      "--color-ink": "#073642",
      "--color-ink-mid": "#586e75",
      "--color-ink-dim": "#657b83",
      "--color-ink-faint": "#93a1a1",
      "--color-signal": "#1a7d76",
      "--color-signal-dim": "#2aa198",
      "--color-signal-wash": "#cce8e2",
      "--color-copper": "#a3480f",
      "--color-copper-dim": "#cb4b16",
      "--color-copper-wash": "#f5decc",
      "--color-rose": "#b02724",
      "--color-rose-dim": "#dc322f",
      "--color-rose-wash": "#f7dcd9",
      "--color-iris": "#4f53a3",
      "--color-iris-dim": "#6c71c4",
      "--color-iris-wash": "#e0e1f2",
      "--color-edge-hi": "rgb(255 255 255 / 0.9)",
      "--color-edge-lo": "rgb(15 23 32 / 0.10)",
    },
    term: {
      background: "#f7f1de",
      foreground: "#073642",
      cursor: "#1a7d76",
      cursorAccent: "#f7f1de",
      selectionBackground: "#4f53a359",
      selectionInactiveBackground: "#4f53a32e",
      black: "#073642",
      red: "#b02724",
      green: "#1a7d76",
      yellow: "#a3480f",
      blue: "#1c6fa8",
      magenta: "#4f53a3",
      cyan: "#1a7d76",
      white: "#586e75",
      brightBlack: "#657b83",
      brightRed: "#782c2e",
      brightGreen: "#146665",
      brightYellow: "#704220",
      brightBlue: "#155c86",
      brightMagenta: "#374983",
      brightCyan: "#146665",
      brightWhite: "#073642",
    },
    code: {
      foreground: "#073642",
      comment: "#7c8d8d",
      string: "#8a6800",
      constant: "#a32468",
      keyword: "#4f53a3",
      function: "#1c6fa8",
      type: "#1a7d76",
      property: "#586e75",
      punctuation: "#586e75",
      inserted: "#5f7000",
      deleted: "#b02724",
    },
  },
];

export const DEFAULT_THEME_ID = "graphite";

/**
 * Mirror of the store's `themeId`. The renderer needs the palette before the
 * first backend round-trip resolves, and the pre-paint boot script needs it
 * synchronously, so localStorage — not the backend — is the read path here.
 */
const KEY = "omp-ui.themeId";

/**
 * The theme applied when nothing else resolves — an unknown id, an empty
 * store, or storage that refuses to be read.
 */
const DEFAULT_THEME: Theme = THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? THEMES[0];

/** Unknown id (renamed theme, hand-edited storage) degrades, never throws. */
export function resolveTheme(id: string | undefined): Theme {
  return THEMES.find((t) => t.id === id) ?? DEFAULT_THEME;
}

let current: Theme = DEFAULT_THEME;
const listeners = new Set<() => void>();

/**
 * The single runtime writer. Everything a palette touches that is not a
 * Tailwind utility — `color-scheme`, the persisted mirror, the native window
 * chrome — is repainted here, so no caller has to remember the list.
 *
 * Every side effect is individually guarded rather than assumed: the store
 * calls this during its own boot, and the store's tests run in vitest's node
 * environment with no `document` and no `localStorage`.
 */
export function applyTheme(theme: Theme): void {
  current = theme;

  if (typeof document !== "undefined") {
    const root = document.documentElement;
    // Tailwind v4 emits each `@theme` token as a `:root` custom property and
    // utilities that dereference it, so overriding the properties here
    // re-themes every utility and every base rule with no CSS rebuild.
    for (const [k, v] of Object.entries(theme.tokens)) root.style.setProperty(k, v);
    root.style.colorScheme = theme.dark ? "dark" : "light";
    // For the light-theme utilities and for debugging only — the palette
    // rides the custom properties above, not this attribute.
    root.dataset.theme = theme.id;
  }

  try {
    // The pre-paint boot script reads this mirror, so persisting is what
    // keeps the next launch from flashing graphite before the store loads.
    window.localStorage.setItem(KEY, theme.id);
  } catch {
    // Storage unavailable (or no DOM at all): the palette still applies.
  }

  // Native chrome is painted by the OS, not CSS — the frameless titlebar
  // overlay only changes through main. The bridge is absent under test, and
  // main already swallows platform errors, so neither a missing bridge nor a
  // rejected call may take the switch down with it.
  try {
    void backend
      ?.setWindowChrome(theme.tokens["--color-void"], theme.tokens["--color-ink-mid"])
      ?.catch(() => {});
  } catch {
    // No bridge: native chrome keeps its previous colour.
  }

  for (const cb of listeners) cb();
}

function subscribe(cb: () => void): () => void {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

/** The applied theme's id — lets a caller skip a redundant re-apply. */
export function currentThemeId(): string {
  return current.id;
}

/** Current theme, live across every consumer (terminal, code blocks, chrome). */
export function useTheme(): Theme {
  return useSyncExternalStore(subscribe, () => current);
}

// Boot from the persisted mirror so the palette is right on the first paint,
// well before the store's first backend round-trip resolves.
try {
  applyTheme(resolveTheme(window.localStorage.getItem(KEY) ?? undefined));
} catch {
  // No storage (or no DOM): the default is already applied.
}
