// PROTOTYPE (#754): throwaway.
// A trimmed copy of core's browser-pane-extension.ts: one hidden custom
// message naming the vault tools, armed by `/omp-ui-vault-754 arm <json>`
// and re-sent after a compaction, branch, or session switch.
// core's writeLineageArtifact and generatedRootBindingSource are not exported
// from @omp-ui/core and core stays untouched, so both are inlined here.
import * as fs from "node:fs";
import * as path from "node:path";

const EXTENSION_NAME = "omp-ui-vault-754.ts";
export const PROTO754_COMMAND = "omp-ui-vault-754";
const CUSTOM_TYPE = "omp-ui:vault-754";

/** §5.6 verbatim; `{vaultName}` and `{how}` are filled from the arm JSON. */
const MESSAGE_TEMPLATE =
  "omp-ui connected this session to the user's Obsidian knowledge vault \"{vaultName}\". Tools: omp-ui_vault_search, omp-ui_vault_read, omp-ui_vault_write{how}. The vault holds the user's own notes (meetings, plans, ideas) and an omp-ui/ folder for notes you write. Search before you write, both to avoid duplicates and to find the user's notes worth linking. When this session settles a decision, learns a lesson worth keeping, or the user asks, write one note per topic: a short Title Case title, no folders, a plain markdown body, no frontmatter (omp-ui adds it). Link the user's notes as [[Title]] and omp-ui notes with the link the tool returns. Never write secrets, tokens, or raw transcripts. The user's notes outside omp-ui/ are read-only.";

function extensionSource(): string {
  return `// Generated by omp-ui (PROTOTYPE #754). Rewritten on every spawn; edits are not preserved.

const COMMAND = ${JSON.stringify(PROTO754_COMMAND)};
const CUSTOM_TYPE = ${JSON.stringify(CUSTOM_TYPE)};
const TEMPLATE = ${JSON.stringify(MESSAGE_TEMPLATE)};

interface VaultSession {
  isStreaming?: boolean;
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface VaultUi {
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface VaultExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: { description?: string; handler: (args: string, ctx: { ui: VaultUi }) => Promise<void> },
  ) => void;
  on?: (event: string, handler: (...args: unknown[]) => void) => void;
}

export default function (pi: VaultExtensionApi) {
  let rootSession: VaultSession | null = null;
  let message: string | null = null;
  let delivered = false;
  let warnedUnavailable = false;
  let ui: VaultUi | null = null;
  function captureRoot(candidate: VaultSession): boolean {
    if (rootSession === null) {
      rootSession = candidate;
      return true;
    }
    return candidate === rootSession;
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: VaultSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: VaultSession, ...args: unknown[]): unknown {
        captureRoot(this);
        return call.apply(this, args);
      };
    }
  } catch {
    // Without the hook there is no root to deliver to; deliver() warns once.
  }

  async function deliver(): Promise<void> {
    const active = rootSession;
    if (message === null) return;
    if (!active || typeof active.sendCustomMessage !== "function") {
      if (!warnedUnavailable) {
        warnedUnavailable = true;
        ui?.notify("omp-ui vault prototype: this omp cannot carry the guidance to the agent", "warning");
      }
      return;
    }
    try {
      await active.sendCustomMessage(
        { customType: CUSTOM_TYPE, content: message, display: false, attribution: "agent" },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
      delivered = true;
    } catch {
      // Retried by the next arm or session event.
    }
  }

  let chain: Promise<void> = Promise.resolve();
  function serialize(work: () => Promise<void>): Promise<void> {
    const next = chain.then(work, work);
    chain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui vault prototype guidance (#754)",
    handler: (args: string, ctx: { ui: VaultUi }) =>
      serialize(async () => {
        ui = ctx.ui;
        const trimmed = args.trim();
        if (!trimmed.startsWith("arm ")) {
          ctx.ui.notify("omp-ui vault prototype: unknown command", "warning");
          return;
        }
        let parsed: { vaultName?: unknown; discoverable?: unknown };
        try {
          parsed = JSON.parse(trimmed.slice(4));
        } catch {
          ctx.ui.notify("omp-ui vault prototype: malformed arm payload", "warning");
          return;
        }
        if (typeof parsed.vaultName !== "string" || typeof parsed.discoverable !== "boolean") {
          ctx.ui.notify("omp-ui vault prototype: malformed arm payload", "warning");
          return;
        }
        message = TEMPLATE.replace("{vaultName}", parsed.vaultName).replace(
          "{how}",
          parsed.discoverable ? " (call each with write xd://<name>)" : "",
        );
        delivered = false;
        await deliver();
      }),
  });

  if (typeof pi.on === "function") {
    for (const eventName of ["session_compact", "session_branch", "session_switch"]) {
      pi.on(eventName, () => {
        delivered = false;
        if (message !== null) void serialize(deliver);
      });
    }
  }
  void delivered;
}
`;
}

/** Writes the guidance extension into the lineage dir and returns its path for `-e`. */
export function writeProto754GuidanceExtension(lineageDir: string): string {
  const file = path.join(lineageDir, EXTENSION_NAME);
  fs.mkdirSync(lineageDir, { recursive: true });
  fs.writeFileSync(file, extensionSource(), "utf8");
  return file;
}

/** The arm command for initialCommands. */
export function proto754ArmMessage(vaultName: string, discoverable: boolean): string {
  return `/${PROTO754_COMMAND} arm ${JSON.stringify({ vaultName, discoverable })}`;
}

export const PROTO754_GUIDANCE_CHARS = MESSAGE_TEMPLATE.length;
