import * as fs from "node:fs";
import * as path from "node:path";
import { ADVISOR_STATS_COMMAND, ADVISOR_STATS_KEY } from "./advisor-stats";

/**
 * omp's rpc surface exposes no advisor accounting (ADR-0005, verified against
 * v17.1.8): `get_session_stats` returns no advisor breakdown and `get_state`
 * reports neither cost nor context. The live `AgentSession` does — its public
 * `getAdvisorStats()` returns exactly cost, context tokens, and context window,
 * the fields the TUI status line's `$2.67 (sub) + $0.41 (adv)` is built from.
 *
 * What *is* reachable is the same unsupported surface ADR-0007's plan mode
 * uses: omp hands extensions an `ExtensionContext` whose `sessionManager`
 * exposes no advisor read, but the `AgentSession` itself carries
 * `getAdvisorStats()` as a public method. So omp-ui ships a generated `-e`
 * extension, written into the session's lineage dir and passed alongside the
 * plan extension, that hooks `AgentSession.prototype.prompt` to capture the
 * live session and publishes a reduced stats view over `ui.setStatus`.
 *
 * The extension publishes at moments that cannot contaminate a live turn:
 * after each `AgentSession.prompt()` resolves, when its slash command runs for
 * a manual/initial fetch, and from a low-frequency in-process poll. The poll
 * exists because omp runs the advisor review async to the primary loop — its
 * cost lands *after* `prompt()` resolves, so a publish keyed only to turn ends
 * permanently trails by one review (a readout stuck at $0 until the next
 * turn). The poll reads `getAdvisorCost()` — a plain sum over a small map,
 * nothing re-tokenized — and only when the total moved does it pay for the
 * full `getAdvisorStats()` publish. Publishing from inside omp spares the
 * renderer from sending a slash prompt mid-stream, which an active turn could
 * misfile as a steer or reach the model as literal text.
 *
 * `getAdvisorStats()` re-tokenizes the advisor transcript, so both the
 * turn-end publish and the poll are gated: the former behind a cheap
 * `getAdvisorStatusOverview()` check, the latter behind the cost delta — a
 * session running advisor-off pays a no-op map sum per poll and publishes
 * nothing.
 *
 * Note this extension and the plan extension each patch `AgentSession.prompt`.
 * That is safe because both wrappers forward `this` untouched — whichever loads
 * second chains through the first and both capture the same live session.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-advisor-stats.ts";

export function advisorStatsExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source. A template rather than a checked-in file because it is
 * delivered per-lineage next to the transcript, and because the constants above
 * are the wire contract — they must not drift between the two sides.
 *
 * If the hook throws, or the captured object lacks `getAdvisorStats`, the
 * extension publishes `available: false` with a reason and the HUD omits the
 * element rather than half-rendering a fabricated zero.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(ADVISOR_STATS_KEY)};
const COMMAND = ${JSON.stringify(ADVISOR_STATS_COMMAND)};
// Advisor reviews land async, after prompt() resolves — poll a cheap change
// probe and publish only when it moves.
const POLL_MS = 2000;

/** setInterval's handle, minus the Node/DOM ambiguity — unref exists under Bun/Node. */
interface PollTimer {
  unref?: () => void;
}

interface StatsSession {
  getAdvisorStatusOverview?: () => { configured?: boolean };
  getAdvisorCost?: () => number;
  getAdvisorAgent?: () => { state?: { messages?: unknown[] } } | undefined;
  /** omp's registry — the same isUsingOAuth check its own TUI cost segment uses. */
  modelRegistry?: { isUsingOAuth?: (model: unknown) => boolean };
  getAdvisorStats: () => {
    configured?: boolean;
    active?: boolean;
    model?: { id?: string } | string;
    contextWindow?: number;
    contextTokens?: number;
    cost?: number;
    tokens?: { total?: number };
  };
}

interface StatsUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatsUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  let session: StatsSession | null = null;
  let unavailable: string | undefined;
  let ui: StatsUi | null = null;
  let lastProbe: string | null = null;
  let pollTimer: PollTimer | null = null;

  // Capture the live AgentSession, exactly as the plan extension does.
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      unavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: StatsSession, ...a: unknown[]) => unknown;
      // Auto-publish after each primary turn fully resolves. The advisor reviews
      // a turn after it ends, so publishing on resolution captures that review.
      prototype.prompt = function (this: StatsSession, ...args: unknown[]): unknown {
        session = this;
        const result = call.apply(this, args);
        const tail =
          result && typeof (result as Promise<unknown>).then === "function"
            ? (result as Promise<unknown>).then
            : null;
        const atEnd = (): void => {
          try {
            maybePublish();
          } catch {
            /* a publish failure must never take the turn down with it */
          }
        };
        if (tail) (tail.call(result, atEnd, atEnd));
        else atEnd();
        return result;
      };
    }
  } catch (err) {
    unavailable = "could not hook AgentSession: " + String(err);
  }

  /** Cheap gate: only pay the re-tokenize cost when the advisor is configured. */
  function advisorConfigured(): boolean {
    try {
      const overview = session?.getAdvisorStatusOverview;
      return typeof overview === "function" ? overview.call(session).configured === true : true;
    } catch {
      return true;
    }
  }

  function maybePublish(): void {
    if (advisorConfigured()) publish();
  }

  /**
   * The advisor's accounting accrues asynchronously — omp folds a review's
   * usage in after the primary turn already resolved — so turn-end publishes
   * alone permanently trail by one review (a readout stuck at $0). This poll
   * reads two cheap signals: getAdvisorCost() (a plain sum over a small map)
   * and the advisor transcript length via getAdvisorAgent() — the latter
   * because a subscription-billed advisor accrues at $0 forever, which a
   * cost-only gate would read as "nothing changed". Only a moved probe pays
   * for the full re-tokenizing getAdvisorStats() publish. Unref'd so it never
   * holds the process open.
   */
  function probeAdvisor(): string | null {
    const active = session;
    if (!active) return null;
    let cost = 0;
    if (typeof active.getAdvisorCost === "function") cost = active.getAdvisorCost();
    let messages = 0;
    if (typeof active.getAdvisorAgent === "function") {
      messages = active.getAdvisorAgent()?.state?.messages?.length ?? 0;
    }
    return cost + ":" + messages;
  }

  function startPoll(): void {
    if (pollTimer) return;
    const timer = setInterval(() => {
      try {
        const probe = probeAdvisor();
        if (probe === null || probe === lastProbe) return;
        lastProbe = probe;
        maybePublish();
      } catch {
        /* a poll failure must never surface as anything */
      }
    }, POLL_MS);
    // Bun and Node both hang an unref off the interval handle; never hold the
    // process open for a HUD tick.
    pollTimer = timer as unknown as PollTimer;
    pollTimer.unref?.();
  }

  function publish(): void {
    if (!ui) return;
    if (unavailable) {
      ui.setStatus(STATUS_KEY, JSON.stringify({ available: false, unavailable }));
      return;
    }
    const active = session;
    if (!active || typeof active.getAdvisorStats !== "function") {
      ui.setStatus(STATUS_KEY, JSON.stringify({
        available: false,
        unavailable: active ? "omp session is missing getAdvisorStats" : "no active omp session",
      }));
      return;
    }
    let stats;
    try {
      stats = active.getAdvisorStats();
    } catch (err) {
      ui.setStatus(STATUS_KEY, JSON.stringify({
        available: false,
        unavailable: "getAdvisorStats failed: " + String(err),
      }));
      return;
    }
    const model =
      typeof stats.model === "string" ? stats.model : (stats.model?.id ?? null);
    // Subscription-billed (OAuth) models legitimately accrue $0 — omp's own TUI
    // renders "(sub)" for them. Surface the fact so the HUD can too, instead of
    // showing a $0.0000 that reads as a broken counter.
    let subscription = false;
    try {
      const check = active.modelRegistry?.isUsingOAuth;
      if (typeof check === "function" && stats.model && typeof stats.model === "object") {
        subscription = check.call(active.modelRegistry, stats.model) === true;
      }
    } catch {
      /* a billing probe failure must never break the publish */
    }
    ui.setStatus(STATUS_KEY, JSON.stringify({
      available: true,
      configured: stats.configured === true,
      active: stats.active === true,
      model,
      subscription,
      contextWindow: stats.contextWindow ?? 0,
      contextTokens: stats.contextTokens ?? 0,
      cost: stats.cost ?? 0,
      totalTokens: stats.tokens?.total ?? 0,
    }));
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui advisor spend and context",
    handler: async (_args: string, ctx: { ui: StatsUi }) => {
      ui = ctx.ui;
      publish();
      // The ui channel exists from here on, so live ticking can start.
      startPoll();
    },
  });
}
`;
}

/**
 * Writes the advisor-stats extension into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeAdvisorStatsExtension(lineageDir: string): string {
  const file = advisorStatsExtensionPath(lineageDir);
  fs.mkdirSync(lineageDir, { recursive: true });
  fs.writeFileSync(file, extensionSource(), "utf8");
  return file;
}
