import * as path from "node:path";
import { ADVISOR_STATS_COMMAND, ADVISOR_STATS_KEY } from "./advisor-stats";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * OMP's rpc surface has no advisor accounting. The public methods on each live
 * `AgentSession` do. This generated extension patches `AgentSession.prompt`,
 * binds the first prompt as the root live session, and tracks every later
 * session by `sessionManager.getSessionId()` as a descendant.
 *
 * The root advisor switch is a ceiling. Before a descendant prompt reaches its
 * original implementation, the wrapper disables that descendant when the root
 * is off. A root that is on does not enable children; OMP's per-agent setting
 * still decides. If the guard cannot be enforced, accounting becomes
 * unavailable but the prompt continues.
 *
 * Root `getAdvisorStats()` supplies configuration, model, subscription, and
 * context fields. Cost and total tokens add the root and every descendant.
 * Descendant snapshots survive disposal, while a root session-id change clears
 * the registry. The cheap 2-second probe likewise sums costs and advisor
 * message counts across the tree before paying for a full stats walk.
 *
 * The extension and plan extension both patch `AgentSession.prompt`. Both
 * wrappers forward `this`, so load order only determines wrapper order.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-advisor-stats.ts";

export function advisorStatsExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source is generated per lineage so its wire constants cannot
 * drift from the renderer. Missing control or accounting methods publish
 * `available: false`; advisor instrumentation never aborts a user prompt.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(ADVISOR_STATS_KEY)};
const COMMAND = ${JSON.stringify(ADVISOR_STATS_COMMAND)};
const POLL_MS = 2000;

interface PollTimer {
  unref?: () => void;
}

interface AdvisorSnapshot {
  cost: number;
  totalTokens: number;
}

interface StatsSession {
  sessionManager?: { getSessionId?: () => string | undefined };
  isAdvisorEnabled?: () => boolean;
  setAdvisorEnabled?: (enabled: boolean) => void;
  getAdvisorStatusOverview?: () => { configured?: boolean };
  getAdvisorCost?: () => number;
  getAdvisorAgent?: () => { state?: { messages?: unknown[] } } | undefined;
  modelRegistry?: { isUsingOAuth?: (model: unknown) => boolean };
  getAdvisorStats?: () => {
    configured?: boolean;
    active?: boolean;
    model?: { id?: string } | string;
    contextWindow?: number;
    contextTokens?: number;
    cost?: number;
    tokens?: { total?: number };
  };
}

interface DescendantState {
  session: StatsSession;
  snapshot?: AdvisorSnapshot;
}

interface StatsUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatsUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  let rootSession: StatsSession | null = null;
  let rootSessionId: string | null = null;
  const descendants = new Map<string, DescendantState>();
  let persistentUnavailable: string | undefined;
  let treeUnavailable: string | undefined;
  let ui: StatsUi | null = null;
  let lastProbe: string | null = null;
  let pollTimer: PollTimer | null = null;

  function unavailableReason(): string | undefined {
    return persistentUnavailable ?? treeUnavailable;
  }

  function publishUnavailable(reason: string): void {
    ui?.setStatus(STATUS_KEY, JSON.stringify({ available: false, unavailable: reason }));
  }

  function markTreeUnavailable(reason: string): void {
    treeUnavailable ??= reason;
    publishUnavailable(treeUnavailable);
  }

  function sessionId(session: StatsSession): string | null {
    const manager = session.sessionManager;
    const getSessionId = manager?.getSessionId;
    if (typeof getSessionId !== "function") return null;
    try {
      const id = getSessionId.call(manager);
      return typeof id === "string" && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  function bindPromptSession(candidate: StatsSession): { descendant: boolean; rootSwitched: boolean } {
    if (!rootSession) {
      rootSession = candidate;
      rootSessionId = sessionId(candidate);
      return { descendant: false, rootSwitched: false };
    }
    if (candidate === rootSession) {
      const currentId = sessionId(candidate);
      const rootSwitched = currentId !== null && rootSessionId !== null && currentId !== rootSessionId;
      if (rootSwitched) {
        descendants.clear();
        treeUnavailable = undefined;
        lastProbe = null;
      }
      if (currentId !== null) rootSessionId = currentId;
      return { descendant: false, rootSwitched };
    }

    const id = sessionId(candidate);
    if (!id) {
      markTreeUnavailable("descendant session is missing sessionManager.getSessionId");
      return { descendant: true, rootSwitched: false };
    }
    for (const [knownId, state] of descendants) {
      if (state.session === candidate && knownId !== id) descendants.delete(knownId);
    }
    const previous = descendants.get(id);
    descendants.set(id, { session: candidate, snapshot: previous?.snapshot });
    return { descendant: true, rootSwitched: false };
  }

  function enforceRootCeiling(child: StatsSession): void {
    const root = rootSession;
    if (!root) return;
    if (typeof root.isAdvisorEnabled !== "function") {
      markTreeUnavailable("root session is missing isAdvisorEnabled");
      return;
    }
    let rootEnabled: boolean;
    try {
      rootEnabled = root.isAdvisorEnabled();
    } catch (err) {
      markTreeUnavailable("root isAdvisorEnabled failed: " + String(err));
      return;
    }
    if (rootEnabled) return;
    if (typeof child.isAdvisorEnabled !== "function") {
      markTreeUnavailable("descendant session is missing isAdvisorEnabled");
      return;
    }
    let childEnabled: boolean;
    try {
      childEnabled = child.isAdvisorEnabled();
    } catch (err) {
      markTreeUnavailable("descendant isAdvisorEnabled failed: " + String(err));
      return;
    }
    if (!childEnabled) return;
    if (typeof child.setAdvisorEnabled !== "function") {
      markTreeUnavailable("descendant session is missing setAdvisorEnabled");
      return;
    }
    try {
      child.setAdvisorEnabled(false);
    } catch (err) {
      markTreeUnavailable("descendant setAdvisorEnabled failed: " + String(err));
    }
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      persistentUnavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: StatsSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: StatsSession, ...args: unknown[]): unknown {
        const binding = bindPromptSession(this);
        if (binding.descendant) enforceRootCeiling(this);
        const result = call.apply(this, args);
        const tail =
          result && typeof (result as Promise<unknown>).then === "function"
            ? (result as Promise<unknown>).then
            : null;
        const atEnd = (): void => {
          try {
            if (binding.descendant || binding.rootSwitched) publish();
            else maybePublish();
          } catch {
            /* advisor accounting must never take down user work */
          }
        };
        if (tail) (tail.call(result, atEnd, atEnd));
        else atEnd();
        return result;
      };
    }
  } catch (err) {
    persistentUnavailable = "could not hook AgentSession: " + String(err);
  }

  function sessionConfigured(session: StatsSession): boolean {
    try {
      const overview = session.getAdvisorStatusOverview;
      return typeof overview === "function" ? overview.call(session).configured === true : true;
    } catch {
      return true;
    }
  }

  function advisorConfigured(): boolean {
    if (unavailableReason()) return true;
    if (rootSession && sessionConfigured(rootSession)) return true;
    for (const state of descendants.values()) {
      if (sessionConfigured(state.session)) return true;
    }
    return false;
  }

  function maybePublish(): void {
    if (advisorConfigured()) publish();
  }

  function finite(value: unknown): number {
    return typeof value === "number" && Number.isFinite(value) ? value : 0;
  }

  function sessionProbe(session: StatsSession, fallbackCost = 0): [number, number] {
    let cost = fallbackCost;
    try {
      if (typeof session.getAdvisorCost === "function") cost = finite(session.getAdvisorCost());
    } catch {
      /* a disposed descendant keeps its last successful cost */
    }
    let messages = 0;
    try {
      if (typeof session.getAdvisorAgent === "function") {
        messages = session.getAdvisorAgent()?.state?.messages?.length ?? 0;
      }
    } catch {
      /* a disposed descendant contributes no live message probe */
    }
    return [cost, messages];
  }

  function probeAdvisor(): string | null {
    if (!rootSession) return null;
    let cost = 0;
    let messages = 0;
    const rootProbe = sessionProbe(rootSession);
    cost += rootProbe[0];
    messages += rootProbe[1];
    for (const state of descendants.values()) {
      const childProbe = sessionProbe(state.session, state.snapshot?.cost ?? 0);
      cost += childProbe[0];
      messages += childProbe[1];
    }
    return cost + ":" + messages;
  }

  function startPoll(): void {
    if (pollTimer) return;
    const timer = setInterval(() => {
      try {
        const probe = probeAdvisor();
        if (probe === null || probe === lastProbe) return;
        lastProbe = probe;
        maybePublish();
      } catch {
        /* a poll failure must never surface */
      }
    }, POLL_MS);
    pollTimer = timer as unknown as PollTimer;
    pollTimer.unref?.();
  }

  function publish(): void {
    if (!ui) return;
    const unavailable = unavailableReason();
    if (unavailable) {
      publishUnavailable(unavailable);
      return;
    }
    const root = rootSession;
    if (!root || typeof root.getAdvisorStats !== "function") {
      publishUnavailable(root ? "root omp session is missing getAdvisorStats" : "no active omp session");
      return;
    }
    let stats;
    try {
      stats = root.getAdvisorStats();
    } catch (err) {
      publishUnavailable("root getAdvisorStats failed: " + String(err));
      return;
    }

    let cost = finite(stats.cost);
    let totalTokens = finite(stats.tokens?.total);
    let active = stats.active === true;
    for (const [id, state] of descendants) {
      const getStats = state.session.getAdvisorStats;
      if (typeof getStats !== "function") {
        if (!state.snapshot) {
          treeUnavailable = "descendant " + id + " is missing getAdvisorStats";
          publishUnavailable(treeUnavailable);
          return;
        }
      } else {
        try {
          const childStats = getStats.call(state.session);
          state.snapshot = {
            cost: finite(childStats.cost),
            totalTokens: finite(childStats.tokens?.total),
          };
          active = active || childStats.active === true;
        } catch (err) {
          if (!state.snapshot) {
            treeUnavailable = "descendant " + id + " getAdvisorStats failed: " + String(err);
            publishUnavailable(treeUnavailable);
            return;
          }
        }
      }
      cost += state.snapshot?.cost ?? 0;
      totalTokens += state.snapshot?.totalTokens ?? 0;
    }

    const model =
      typeof stats.model === "string" ? stats.model : (stats.model?.id ?? null);
    let subscription = false;
    try {
      const check = root.modelRegistry?.isUsingOAuth;
      if (typeof check === "function" && stats.model && typeof stats.model === "object") {
        subscription = check.call(root.modelRegistry, stats.model) === true;
      }
    } catch {
      /* a billing probe failure must never break the publish */
    }
    ui.setStatus(STATUS_KEY, JSON.stringify({
      available: true,
      configured: stats.configured === true,
      active,
      model,
      subscription,
      contextWindow: finite(stats.contextWindow),
      contextTokens: finite(stats.contextTokens),
      cost,
      totalTokens,
    }));
    lastProbe = probeAdvisor();
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui advisor spend and context",
    handler: async (_args: string, ctx: { ui: StatsUi }) => {
      ui = ctx.ui;
      publish();
      startPoll();
    },
  });
}
`;
}

/**
 * Writes the advisor-stats extension into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeAdvisorStatsExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, advisorStatsExtensionPath(lineageDir), extensionSource());
}
