import * as fs from "node:fs";
import * as path from "node:path";
import { ADVISOR_STATS_COMMAND, ADVISOR_STATS_KEY } from "./advisor-stats";

/**
 * omp's rpc surface exposes no advisor accounting (ADR-0005, verified against
 * v17.1.8): `get_session_stats` returns no advisor breakdown and `get_state`
 * reports neither cost nor context. The live `AgentSession` does — its public
 * `getAdvisorStats()` returns exactly cost, context tokens, and context window,
 * the fields the TUI status line's `$2.67 (sub) + $0.41 (adv)` is built from.
 *
 * What *is* reachable is the same unsupported surface ADR-0007's plan mode
 * uses: omp hands extensions an `ExtensionContext` whose `sessionManager`
 * exposes no advisor read, but the `AgentSession` itself carries
 * `getAdvisorStats()` as a public method. So omp-ui ships a generated `-e`
 * extension, written into the session's lineage dir and passed alongside the
 * plan extension, that hooks `AgentSession.prototype.prompt` to capture the
 * live session and publishes a reduced stats view over `ui.setStatus`.
 *
 * The extension publishes twice, both at moments that cannot contaminate a
 * live turn: after each `AgentSession.prompt()` resolves (i.e. after a primary
 * turn fully ends — exactly when the advisor's review of that turn has landed),
 * and when its slash command runs for a manual/initial fetch. Publishing from
 * inside omp spares the renderer from sending a slash prompt mid-stream, which
 * an active turn could misfile as a steer or reach the model as literal text.
 *
 * `getAdvisorStats()` re-tokenizes the advisor transcript, so the turn-end
 * publish is gated behind a cheap `getAdvisorStatusOverview()` check that skips
 * it entirely when no advisor is configured — a session running advisor-off
 * pays nothing per turn.
 *
 * Note this extension and the plan extension each patch `AgentSession.prompt`.
 * That is safe because both wrappers forward `this` untouched — whichever loads
 * second chains through the first and both capture the same live session.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-advisor-stats.ts";

export function advisorStatsExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source. A template rather than a checked-in file because it is
 * delivered per-lineage next to the transcript, and because the constants above
 * are the wire contract — they must not drift between the two sides.
 *
 * If the hook throws, or the captured object lacks `getAdvisorStats`, the
 * extension publishes `available: false` with a reason and the HUD omits the
 * element rather than half-rendering a fabricated zero.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(ADVISOR_STATS_KEY)};
const COMMAND = ${JSON.stringify(ADVISOR_STATS_COMMAND)};

interface StatsSession {
  getAdvisorStatusOverview?: () => { configured?: boolean };
  getAdvisorStats: () => {
    configured?: boolean;
    active?: boolean;
    model?: { id?: string } | string;
    contextWindow?: number;
    contextTokens?: number;
    cost?: number;
    tokens?: { total?: number };
  };
}

interface StatsUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatsUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  let session: StatsSession | null = null;
  let unavailable: string | undefined;
  let ui: StatsUi | null = null;

  // Capture the live AgentSession, exactly as the plan extension does.
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      unavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: StatsSession, ...a: unknown[]) => unknown;
      // Auto-publish after each primary turn fully resolves. The advisor reviews
      // a turn after it ends, so publishing on resolution captures that review.
      prototype.prompt = function (this: StatsSession, ...args: unknown[]): unknown {
        session = this;
        const result = call.apply(this, args);
        const tail =
          result && typeof (result as Promise<unknown>).then === "function"
            ? (result as Promise<unknown>).then
            : null;
        const atEnd = (): void => {
          try {
            maybePublish();
          } catch {
            /* a publish failure must never take the turn down with it */
          }
        };
        if (tail) (tail.call(result, atEnd, atEnd));
        else atEnd();
        return result;
      };
    }
  } catch (err) {
    unavailable = "could not hook AgentSession: " + String(err);
  }

  /** Cheap gate: only pay the re-tokenize cost when the advisor is configured. */
  function advisorConfigured(): boolean {
    try {
      const overview = session?.getAdvisorStatusOverview;
      return typeof overview === "function" ? overview.call(session).configured === true : true;
    } catch {
      return true;
    }
  }

  function maybePublish(): void {
    if (advisorConfigured()) publish();
  }

  function publish(): void {
    if (!ui) return;
    if (unavailable) {
      ui.setStatus(STATUS_KEY, JSON.stringify({ available: false, unavailable }));
      return;
    }
    const active = session;
    if (!active || typeof active.getAdvisorStats !== "function") {
      ui.setStatus(STATUS_KEY, JSON.stringify({
        available: false,
        unavailable: active ? "omp session is missing getAdvisorStats" : "no active omp session",
      }));
      return;
    }
    let stats;
    try {
      stats = active.getAdvisorStats();
    } catch (err) {
      ui.setStatus(STATUS_KEY, JSON.stringify({
        available: false,
        unavailable: "getAdvisorStats failed: " + String(err),
      }));
      return;
    }
    const model =
      typeof stats.model === "string" ? stats.model : (stats.model?.id ?? null);
    ui.setStatus(STATUS_KEY, JSON.stringify({
      available: true,
      configured: stats.configured === true,
      active: stats.active === true,
      model,
      contextWindow: stats.contextWindow ?? 0,
      contextTokens: stats.contextTokens ?? 0,
      cost: stats.cost ?? 0,
      totalTokens: stats.tokens?.total ?? 0,
    }));
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui advisor spend and context",
    handler: async (_args: string, ctx: { ui: StatsUi }) => {
      ui = ctx.ui;
      publish();
    },
  });
}
`;
}

/**
 * Writes the advisor-stats extension into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeAdvisorStatsExtension(lineageDir: string): string {
  const file = advisorStatsExtensionPath(lineageDir);
  fs.mkdirSync(lineageDir, { recursive: true });
  fs.writeFileSync(file, extensionSource(), "utf8");
  return file;
}
