import * as path from "node:path";
import {
  AUTORESEARCH_COMMAND,
  AUTORESEARCH_CONTROL_TYPE,
  AUTORESEARCH_GOAL_CHAR_LIMIT,
  AUTORESEARCH_SLASH,
  AUTORESEARCH_STATUS_BYTE_LIMIT,
  AUTORESEARCH_STATUS_KEY,
  AUTORESEARCH_TOOLS,
} from "./autoresearch";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * omp's `/autoresearch` runs entirely inside omp (verified on v18.2.4): the
 * command toggles mode by appending `autoresearch-control` custom entries to
 * the session, the loop lives in omp's tools, and the TUI dashboard is a
 * `setWidget` frame no native tab renders. Nothing on the rpc wire says whether
 * autoresearch is on, what the goal is, or which loop tool just finished.
 *
 * This generated extension is a read-only status bridge (Experiments Lab,
 * omp-ui #559). It reduces the root session's branch to `mode`/`goal` by
 * walking `sessionManager.getBranch()`, watches `tool_execution_end` for the
 * loop's own tools, and publishes one snapshot on {@link AUTORESEARCH_STATUS_KEY}
 * through the existing `setStatus` frame. It never mounts a tool, never runs a
 * continuation loop, never opens a dialog and never writes omp's database:
 * run history is read from SQLite by autoresearch-store.ts.
 *
 * Every API this touches is unsupported surface, so every one is probed: a
 * missing `getBranch` publishes `unavailable` with the reason and leaves
 * ordinary prompting untouched.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-autoresearch.ts";

export function autoresearchExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants are interpolated
 * from autoresearch.ts so the publishing side can never drift from the parser
 * the main process and the renderers share.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(AUTORESEARCH_STATUS_KEY)};
const COMMAND = ${JSON.stringify(AUTORESEARCH_COMMAND)};
const CONTROL_TYPE = ${JSON.stringify(AUTORESEARCH_CONTROL_TYPE)};
const SLASH_PREFIX = "/" + ${JSON.stringify(AUTORESEARCH_SLASH)};
const TOOLS: readonly string[] = ${JSON.stringify(AUTORESEARCH_TOOLS)};
const BYTE_LIMIT = ${AUTORESEARCH_STATUS_BYTE_LIMIT};
const GOAL_LIMIT = ${AUTORESEARCH_GOAL_CHAR_LIMIT};

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface SessionLike {
  sessionManager?: Record<string, unknown>;
  subscribe?: (listener: (event: Record<string, unknown>) => void) => unknown;
  registerSessionChangeCallback?: (listener: () => void) => unknown;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

interface LastTool {
  name: string;
  at: number;
  isError: boolean;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function utf8Length(text: string): number {
  let bytes = 0;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code < 0x80) bytes += 1;
    else if (code < 0x800) bytes += 2;
    else if (code >= 0xdc00 && code < 0xe000) bytes += 0;
    else if (code >= 0xd800 && code < 0xdc00) {
      bytes += 4;
      i++;
    } else bytes += 3;
  }
  return bytes;
}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);

  let rootSession: SessionLike | null = null;
  let ui: StatusUi | null = null;
  let revision = 0;
  let lastDigest = "";
  /** Set only when the prompt hook could not be installed; outranks every read. */
  let hookBroken: string | null = null;
  /** Why the last control read failed; null means mode/goal are trustworthy. */
  let broken: string | null = null;
  let mode: "on" | "off" = "off";
  let goal: string | null = null;
  let lastTool: LastTool | null = null;
  const unsubscribe = new Array<() => void>();

  function sessionIdOf(session: SessionLike | null): string | null {
    const read = asRecord(session?.sessionManager)?.getSessionId;
    if (typeof read !== "function") return null;
    try {
      const id = (read as () => unknown).call(session?.sessionManager);
      return isString(id) && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  /**
   * Reduces the root branch to the latest control state. omp appends one
   * \`autoresearch-control\` entry per toggle: "on" (optionally carrying a
   * goal), "off", or "clear". A record without a goal keeps the previous goal;
   * "clear" drops it. Every walk starts from off/null so a rewound branch
   * never inherits state from entries that are no longer on it.
   */
  function readControl(): void {
    mode = "off";
    goal = null;
    if (hookBroken !== null) {
      broken = hookBroken;
      return;
    }
    if (rootSession === null) {
      broken = "no omp session has prompted yet";
      return;
    }
    const manager = asRecord(rootSession.sessionManager);
    const getBranch = manager?.getBranch;
    if (typeof getBranch !== "function") {
      broken = "sessionManager.getBranch is missing";
      return;
    }
    let entries: unknown;
    try {
      entries = (getBranch as () => unknown).call(manager);
    } catch (error) {
      broken = "sessionManager.getBranch failed: " + String(error);
      return;
    }
    if (!Array.isArray(entries)) {
      broken = "sessionManager.getBranch returned no array";
      return;
    }
    broken = null;
    for (const raw of entries) {
      const entry = asRecord(raw);
      if (entry === null || entry.type !== "custom" || entry.customType !== CONTROL_TYPE) continue;
      const data = asRecord(entry.data);
      if (data === null) continue;
      mode = data.mode === "on" ? "on" : "off";
      goal = data.mode === "clear" ? null : isString(data.goal) ? data.goal : goal;
    }
  }

  function publish(force: boolean): void {
    if (ui === null) return;
    const sessionId = sessionIdOf(rootSession) ?? "";
    const digest = JSON.stringify([sessionId, broken === null, mode, goal, lastTool]);
    if (!force && digest === lastDigest) return;
    const goalTruncated = goal !== null && goal.length > GOAL_LIMIT;
    const snapshot: Record<string, unknown> = {
      version: 1,
      processKey,
      sessionId,
      revision: revision + 1,
      available: broken === null,
      unavailable: broken,
      mode,
      goal: goalTruncated ? (goal as string).slice(0, GOAL_LIMIT) : goal,
      goalTruncated,
      lastTool,
    };
    // An impossible payload is published as unavailable, never as half a goal.
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      snapshot.available = false;
      snapshot.unavailable = "autoresearch snapshot exceeded " + BYTE_LIMIT + " bytes";
      snapshot.goal = null;
      snapshot.goalTruncated = false;
      json = JSON.stringify(snapshot);
    }
    revision += 1;
    lastDigest = digest;
    ui.setStatus(STATUS_KEY, json);
  }

  function refresh(force: boolean): void {
    try {
      readControl();
      publish(force);
    } catch {
      /* a bridge never breaks the stream it observes */
    }
  }

  function onEvent(event: Record<string, unknown>): void {
    try {
      const type = event.type;
      if (type === "tool_execution_end") {
        const name = event.toolName;
        if (!isString(name) || TOOLS.indexOf(name) < 0) return;
        lastTool = { name, at: Date.now(), isError: event.isError === true };
        refresh(false);
        return;
      }
      if (type === "agent_end") refresh(false);
    } catch {
      /* a bridge event handler must never take down the session's stream */
    }
  }

  function bindRoot(session: SessionLike): void {
    if (rootSession !== null) return;
    rootSession = session;
    bindShutdown(session);
    const subscribe = session.subscribe;
    if (typeof subscribe === "function") {
      try {
        const off = subscribe.call(session, (event) => onEvent(asRecord(event) ?? {}));
        if (typeof off === "function") unsubscribe.push(off);
      } catch {
        /* an unsubscribable session still answers the arm command */
      }
    }
    const sessionChange = session.registerSessionChangeCallback;
    if (typeof sessionChange === "function") {
      try {
        const off = sessionChange.call(session, () => {
          // /new and /branch: the previous session's tool activity is gone,
          // and the new branch is read from scratch.
          lastTool = null;
          refresh(true);
        });
        if (typeof off === "function") unsubscribe.push(off);
      } catch {
        /* an older runtime republishes on the next agent_end */
      }
    }
  }

  /** Same root-shutdown discipline the goal bridge uses. */
  function bindShutdown(session: SessionLike): void {
    const target = session as unknown as Record<string, unknown>;
    for (const method of ["dispose", "disconnect", "cleanup", "shutdown"]) {
      try {
        const original = target[method];
        if (typeof original !== "function") continue;
        const call = original as (...args: unknown[]) => unknown;
        target[method] = function (this: unknown, ...args: unknown[]): unknown {
          const result = call.apply(this, args);
          try {
            if (this === session) teardown();
          } catch {
            /* shutdown bookkeeping never breaks the session */
          }
          return result;
        };
      } catch {
        /* a sealed or throwing shutdown hook is not our session's problem */
      }
    }
  }

  function teardown(): void {
    for (const off of unsubscribe.splice(0)) {
      try {
        off();
      } catch {
        /* a runtime that refuses unsubscribe is leaving anyway */
      }
    }
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype !== undefined && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: SessionLike, ...args: unknown[]) => unknown;
      prototype.prompt = function (this: SessionLike, ...args: unknown[]): unknown {
        const isRoot = rootSession === null || this === rootSession;
        const invoke = (): unknown => call.apply(this, args);
        if (!isRoot) return invoke();
        bindRoot(this);
        const text = isString(args[0]) ? (args[0] as string).trim() : null;
        if (text === null || !text.startsWith(SLASH_PREFIX)) return invoke();
        // \`/autoresearch\` (bare, off, clear, or a goal) is an omp command:
        // it appends a control entry and settles without a model turn, so no
        // agent_end will follow. Republish once omp has handled it.
        return Promise.resolve(invoke()).then(
          (value) => {
            refresh(false);
            return value;
          },
          (error) => {
            refresh(false);
            throw error;
          },
        );
      };
    }
  } catch (error) {
    hookBroken = "could not hook AgentSession.prompt: " + String(error);
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui autoresearch status bridge",
    handler: async (args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      if (isString(args) && args.trim() !== "") {
        throw new Error("omp-ui-autoresearch: unsupported command args");
      }
      // The arm arrives as a root prompt, so the wrapper has already bound the
      // root; with no prompt seen yet the snapshot reports that honestly.
      readControl();
      publish(true);
    },
  });
}
`;
}

/**
 * Writes the autoresearch bridge into the lineage dir and returns its path, to
 * be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeAutoresearchExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, autoresearchExtensionPath(lineageDir), extensionSource());
}
