import * as path from "node:path";
import {
  BROWSER_PANE_COMMAND,
  BROWSER_PANE_CUSTOM_TYPE,
  BROWSER_PANE_ENDPOINT_PATTERN,
  BROWSER_PANE_INSTRUCTION_PARTS,
} from "./browser-pane";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * The agent learns the browser pane's endpoint (#519, ADR-0029) from this
 * generated extension: the spawner arms it with `/omp-ui-browser-pane set
 * <json>` in `initialCommands`, and it delivers ONE hidden custom message
 * (`display: false`) naming `browser.open({ app: { cdp_url } })` and the
 * endpoint's rules to the root session. No prompt suffix, no system-prompt
 * append: about 180 tokens once per omp process, re-queued after a compaction,
 * branch, or session switch so a rebuilt context still carries it (#530).
 *
 * The endpoint is host-local and never reaches a renderer (#532); the owning
 * main process is the only party that ever names it, and only inside omp.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-browser-pane.ts";

export function browserPaneExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the command name, custom type,
 * instruction text, and endpoint pattern are interpolated from browser-pane.ts
 * so the two sides of the channel can never drift.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.

const COMMAND = ${JSON.stringify(BROWSER_PANE_COMMAND)};
const CUSTOM_TYPE = ${JSON.stringify(BROWSER_PANE_CUSTOM_TYPE)};
const INSTRUCTION_PARTS: readonly [string, string] = ${JSON.stringify(BROWSER_PANE_INSTRUCTION_PARTS)};
const ENDPOINT_RE = new RegExp(${JSON.stringify(BROWSER_PANE_ENDPOINT_PATTERN)});

/** The slice of omp's AgentSession this extension drives. */
interface PaneSession {
  isStreaming?: boolean;
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface PaneUi {
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface PaneExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: PaneUi }) => Promise<void>;
    },
  ) => void;
  on?: (event: string, handler: (...args: unknown[]) => void) => void;
}

export default function (pi: PaneExtensionApi) {
  // The first prompting AgentSession. omp dispatches slash commands through
  // prompt, so the arming command itself binds the root; no later prompt —
  // descendant or not — may retarget it (ADR-0008 discipline).
  let rootSession: PaneSession | null = null;
  /** The endpoint the spawner armed; null after \`clear\`. */
  let endpoint: string | null = null;
  /** The endpoint the root has been told about; null until delivered or after a context rebuild. */
  let delivered: string | null = null;
  let warnedUnavailable = false;
  let ui: PaneUi | null = null;

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: PaneSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: PaneSession, ...args: unknown[]): unknown {
        if (rootSession === null) rootSession = this;
        return call.apply(this, args);
      };
    }
  } catch {
    // Without the hook there is no root to deliver to; deliver() warns once.
  }

  /**
   * Sends the hidden instruction to the root. A rejection leaves \`delivered\`
   * unchanged so the next \`set\` or session event retries.
   */
  async function deliver(): Promise<void> {
    const active = rootSession;
    const target = endpoint;
    if (target === null) return;
    if (!active || typeof active.sendCustomMessage !== "function") {
      if (!warnedUnavailable) {
        warnedUnavailable = true;
        ui?.notify("omp-ui browser pane: this omp cannot carry the endpoint to the agent", "warning");
      }
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: CUSTOM_TYPE,
          content: INSTRUCTION_PARTS[0] + target + INSTRUCTION_PARTS[1],
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
      delivered = target;
    } catch {
      // Retried by the next set or session event.
    }
  }

  /** Strict parse of the \`set\` payload: exactly { cdpUrl } matching the loopback token-path shape. */
  function parseSetArgs(args: string): string | null {
    let parsed: unknown;
    try {
      parsed = JSON.parse(args);
    } catch {
      return null;
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null;
    if (!("cdpUrl" in parsed) || Object.keys(parsed).length !== 1) return null;
    const cdpUrl: unknown = parsed.cdpUrl;
    if (typeof cdpUrl !== "string" || !ENDPOINT_RE.test(cdpUrl)) return null;
    return cdpUrl;
  }

  // Two quick \`set\`s must not interleave their deliveries.
  let chain: Promise<void> = Promise.resolve();
  function serialize(work: () => Promise<void>): Promise<void> {
    const next = chain.then(work, work);
    chain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui browser pane endpoint",
    handler: (args: string, ctx: { ui: PaneUi }) =>
      serialize(async () => {
        ui = ctx.ui;
        const trimmed = args.trim();
        if (trimmed === "clear") {
          endpoint = null;
          return;
        }
        if (!trimmed.startsWith("set ")) {
          ctx.ui.notify("omp-ui browser pane: unknown command", "warning");
          return;
        }
        const cdpUrl = parseSetArgs(trimmed.slice(4));
        if (cdpUrl === null) {
          ctx.ui.notify("omp-ui browser pane: malformed endpoint", "warning");
          return;
        }
        endpoint = cdpUrl;
        if (endpoint !== delivered) await deliver();
      }),
  });

  // A compaction, branch, or switch rebuilds the context the hidden message
  // lived in; queue it again so the agent keeps its endpoint (#530).
  if (typeof pi.on === "function") {
    for (const eventName of ["session_compact", "session_branch", "session_switch"]) {
      pi.on(eventName, () => {
        delivered = null;
        if (endpoint !== null) void serialize(deliver);
      });
    }
  }
}
`;
}

/**
 * Writes the browser pane extension into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeBrowserPaneExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, browserPaneExtensionPath(lineageDir), extensionSource());
}
