import * as path from "node:path";
import {
  CAPABILITIES_COMMAND,
  CAPABILITIES_STATUS_KEY,
  CAPABILITY_DESCRIPTION_LIMIT,
  CAPABILITY_STATUS_BYTE_LIMIT,
} from "./capabilities";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * OMP exposes its live capability surface (skills, tools, MCP ownership) only
 * through the methods on the running `AgentSession`. This generated extension
 * patches `AgentSession.prompt`, binds the FIRST prompting session as the root
 * (ADR-0008 discipline — descendant sessions never replace it), and samples
 * that root's public methods into the `omp-ui:capabilities` status channel.
 *
 * The sample is read-only by construction: `skills` is read as data (never
 * `loadSkills()`/`refreshSkills()` and never the system prompt), and MCP
 * ownership comes exclusively from the scalar metadata on the object
 * `getToolByName` returns — a tool is never relabeled MCP because its name
 * looks like one. Access facts (enabled/active/xdev/eval-bridge) are probed
 * per method; a missing or throwing method yields `null` fields, never a
 * fabricated `false`.
 *
 * Every root prompt settles force a snapshot (so `/new` and branch transitions
 * replace the inventory immediately), and a 2-second unref'd digest poll catches
 * changes that land outside a prompt. An over-budget roster is replaced whole
 * by a `payload-too-large` snapshot — omp-ui never ships a partial inventory.
 * Sampling failures can never reject a user prompt.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-capabilities.ts";

export function capabilitiesExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants and limits are
 * interpolated from capabilities.ts so the publishing side can never drift
 * from the parser the main process and renderer share.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(CAPABILITIES_STATUS_KEY)};
const COMMAND = ${JSON.stringify(CAPABILITIES_COMMAND)};
const DESC_LIMIT = ${CAPABILITY_DESCRIPTION_LIMIT};
const BYTE_LIMIT = ${CAPABILITY_STATUS_BYTE_LIMIT};
const POLL_MS = 2000;
const CONTROL_CHARS = /[\\u0000-\\u001f\\u007f-\\u009f]/g;

interface PollTimer {
  unref?: () => void;
}

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface SessionLike {
  sessionManager?: { getSessionId?: () => unknown };
  skills?: unknown;
  skillsSettings?: { enableSkillCommands?: unknown };
  getAllToolInfos?: () => unknown;
  getEnabledToolNames?: () => unknown;
  getActiveToolNames?: () => unknown;
  getMountedXdevToolNames?: () => unknown;
  getEvalBridgeToolNames?: () => unknown;
  getToolByName?: (name: string) => unknown;
  version?: unknown;
  ompVersion?: unknown;
}

interface SkillRow {
  name: string;
  description: string;
  descriptionTruncated: boolean;
  filePath: string;
  source: string | null;
  scope: string | null;
  hidden: boolean | null;
}

interface ToolRow {
  name: string;
  description: string;
  descriptionTruncated: boolean;
  source: string;
  sourcePath: string | null;
  enabled: boolean | null;
  direct: boolean | null;
  xdev: boolean | null;
  evalBridge: boolean | null;
  mcpDigest: string;
}

interface SectionSample<T> {
  reason: string | null;
  rows: T[];
}

interface DraftSection {
  status: string;
  items?: unknown[];
  reason?: string;
}

interface DraftSnapshot {
  version: number;
  processKey: string;
  sessionId: string | null;
  revision: number;
  updatedAt: number;
  ompVersion: string | null;
  skillCommandsEnabled: boolean | null;
  skills: DraftSection;
  tools: DraftSection;
}

interface ExtensionApi {
  pi?: {
    AgentSession?: { prototype?: Record<string, unknown> };
    version?: unknown;
    ompVersion?: unknown;
  };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);
  let rootSession: SessionLike | null = null;
  let ui: StatusUi | null = null;
  let pollTimer: PollTimer | null = null;
  let lastDigest: string | null = null;
  let revision = 0;

  function capped(value: unknown): { text: string; truncated: boolean } {
    const text = typeof value === "string" ? value.replace(CONTROL_CHARS, " ") : "";
    return text.length > DESC_LIMIT
      ? { text: text.slice(0, DESC_LIMIT), truncated: true }
      : { text, truncated: false };
  }

  function utf8Length(text: string): number {
    let bytes = 0;
    for (let i = 0; i < text.length; i++) {
      const code = text.charCodeAt(i);
      if (code < 0x80) bytes += 1;
      else if (code < 0x800) bytes += 2;
      else if (code >= 0xdc00 && code < 0xe000) bytes += 0;
      else if (code >= 0xd800 && code < 0xdc00) { bytes += 4; i++; }
      else bytes += 3;
    }
    return bytes;
  }

  function sessionIdOf(session: SessionLike | null): string | null {
    const manager = session?.sessionManager;
    const fn = manager?.getSessionId;
    if (typeof fn !== "function") return null;
    try {
      const id = fn.call(manager);
      return typeof id === "string" && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  function probeVersion(): string | null {
    try {
      const candidates = [pi.pi?.version, pi.pi?.ompVersion, rootSession?.version, rootSession?.ompVersion];
      for (const candidate of candidates) {
        if (typeof candidate === "string" && candidate.length > 0) return candidate;
      }
    } catch {
      /* a hostile version getter still yields a valid snapshot */
    }
    return null;
  }

  function probeSkillCommands(root: SessionLike | null): boolean | null {
    try {
      const value = root?.skillsSettings?.enableSkillCommands;
      return typeof value === "boolean" ? value : null;
    } catch {
      return null;
    }
  }

  function nameSet(root: SessionLike, method: string): Set<string> | null {
    const fn = (root as unknown as Record<string, unknown>)[method];
    if (typeof fn !== "function") return null;
    try {
      const value = (fn as () => unknown).call(root);
      if (!Array.isArray(value)) return null;
      const names = new Set<string>();
      for (const item of value) {
        if (typeof item === "string") names.add(item);
      }
      return names;
    } catch {
      return null;
    }
  }

  function sampleSkills(root: SessionLike | null): SectionSample<SkillRow> {
    if (!root) return { reason: "missing-api", rows: [] };
    let raw: unknown;
    try {
      raw = root.skills;
    } catch {
      return { reason: "read-failed", rows: [] };
    }
    if (!Array.isArray(raw)) return { reason: "missing-api", rows: [] };
    try {
      const rows: SkillRow[] = [];
      for (const entry of raw as Record<string, unknown>[]) {
        if (entry === null || typeof entry !== "object" || Array.isArray(entry)) continue;
        if (typeof entry.name !== "string" || entry.name.length === 0) continue;
        const description = capped(entry.description);
        const source = entry._source;
        const level = source !== null && typeof source === "object"
          ? (source as Record<string, unknown>).level
          : null;
        rows.push({
          name: entry.name,
          description: description.text,
          descriptionTruncated: description.truncated,
          filePath: typeof entry.filePath === "string" ? entry.filePath : "",
          source: typeof entry.source === "string" ? entry.source : null,
          scope: level === "user" || level === "project" ? level : null,
          hidden: typeof entry.hide === "boolean" ? entry.hide : null,
        });
      }
      return { reason: null, rows };
    } catch {
      return { reason: "read-failed", rows: [] };
    }
  }

  function originOf(value: unknown): string | null {
    if (typeof value !== "string") return null;
    const label = value.toLowerCase();
    return label === "builtin" || label === "extension" || label === "mcp" || label === "sdk" ? label : null;
  }

  function toolSourceOf(entry: Record<string, unknown>): string {
    const direct = originOf(entry.source) ?? originOf(entry.kind);
    if (direct !== null) return direct;
    const info = entry.sourceInfo;
    if (info !== null && typeof info === "object" && !Array.isArray(info)) {
      const record = info as Record<string, unknown>;
      for (const field of ["kind", "type", "source", "provider"]) {
        const origin = originOf(record[field]);
        if (origin !== null) return origin;
      }
    }
    return "unknown";
  }

  function synthesizedScoped(entry: Record<string, unknown>): boolean {
    if (entry.scope === "temporary" || entry.sourceScope === "temporary") return true;
    const source = entry._source;
    if (source !== null && typeof source === "object"
      && (source as Record<string, unknown>).level === "temporary") return true;
    const info = entry.sourceInfo;
    if (info !== null && typeof info === "object" && !Array.isArray(info)) {
      const record = info as Record<string, unknown>;
      for (const field of ["scope", "kind"]) {
        const value = record[field];
        if (typeof value === "string") {
          const label = value.toLowerCase();
          if (label.includes("temp") || label.includes("memory")) return true;
        }
      }
    }
    return false;
  }

  function sampleTools(root: SessionLike | null): SectionSample<ToolRow> {
    if (!root) return { reason: "missing-api", rows: [] };
    const list = root.getAllToolInfos;
    if (typeof list !== "function") return { reason: "missing-api", rows: [] };
    let raw: unknown;
    try {
      raw = list.call(root);
    } catch {
      return { reason: "read-failed", rows: [] };
    }
    if (!Array.isArray(raw)) return { reason: "read-failed", rows: [] };
    try {
      const enabled = nameSet(root, "getEnabledToolNames");
      const direct = nameSet(root, "getActiveToolNames");
      const xdev = nameSet(root, "getMountedXdevToolNames");
      const evalBridge = nameSet(root, "getEvalBridgeToolNames");
      const rows: ToolRow[] = [];
      for (const entry of raw as Record<string, unknown>[]) {
        if (entry === null || typeof entry !== "object" || Array.isArray(entry)) continue;
        if (typeof entry.name !== "string" || entry.name.length === 0) continue;
        const description = capped(entry.description);
        const infoServer = typeof entry.mcpServerName === "string" ? entry.mcpServerName : null;
        const infoTool = typeof entry.mcpToolName === "string" ? entry.mcpToolName : null;
        rows.push({
          name: entry.name,
          description: description.text,
          descriptionTruncated: description.truncated,
          source: toolSourceOf(entry),
          sourcePath: synthesizedScoped(entry) || typeof entry.sourcePath !== "string"
            ? null
            : entry.sourcePath,
          enabled: enabled === null ? null : enabled.has(entry.name),
          direct: direct === null ? null : direct.has(entry.name),
          xdev: xdev === null ? null : xdev.has(entry.name),
          evalBridge: evalBridge === null ? null : evalBridge.has(entry.name),
          mcpDigest: infoServer !== null && infoTool !== null ? infoServer + "\\u0000" + infoTool : "",
        });
      }
      return { reason: null, rows };
    } catch {
      return { reason: "read-failed", rows: [] };
    }
  }

  function mcpOwnership(root: SessionLike | null, name: string): [string | null, string | null] {
    const fn = root?.getToolByName;
    if (typeof fn !== "function" || root === null) return [null, null];
    try {
      const tool = fn.call(root, name);
      if (tool !== null && typeof tool === "object" && !Array.isArray(tool)) {
        const record = tool as Record<string, unknown>;
        const server = record.mcpServerName;
        const toolName = record.mcpToolName;
        if (typeof server === "string" && typeof toolName === "string") return [server, toolName];
      }
    } catch {
      /* unknown ownership, never a guess */
    }
    return [null, null];
  }

  function digestOf(
    sessionIdValue: string | null,
    skillCommandsEnabled: boolean | null,
    skills: SectionSample<SkillRow>,
    tools: SectionSample<ToolRow>,
  ): string {
    const skillRows = skills.reason === null
      ? skills.rows.map((row) => [row.name, row.description, row.descriptionTruncated, row.filePath, row.source, row.scope, row.hidden])
      : ["unavailable", skills.reason];
    const toolRows = tools.reason === null
      ? tools.rows.map((row) => [row.name, row.description, row.descriptionTruncated, row.source, row.enabled, row.direct, row.xdev, row.evalBridge, row.mcpDigest])
      : ["unavailable", tools.reason];
    return JSON.stringify([sessionIdValue, skillCommandsEnabled, skillRows, toolRows]);
  }

  function publish(force: boolean): void {
    if (!ui) return;
    const root = rootSession;
    const sessionIdValue = sessionIdOf(root);
    const skillCommandsEnabled = probeSkillCommands(root);
    const skills = sampleSkills(root);
    const tools = sampleTools(root);
    const digest = digestOf(sessionIdValue, skillCommandsEnabled, skills, tools);
    if (!force && digest === lastDigest) return;
    const snapshot: DraftSnapshot = {
      version: 1,
      processKey,
      sessionId: sessionIdValue,
      revision: revision + 1,
      updatedAt: Date.now(),
      ompVersion: probeVersion(),
      skillCommandsEnabled,
      skills: skills.reason === null
        ? { status: "available", items: skills.rows }
        : { status: "unavailable", reason: skills.reason },
      tools: tools.reason === null
        ? {
            status: "available",
            items: tools.rows.map((row) => {
              const ownership = mcpOwnership(root, row.name);
              return {
                name: row.name,
                description: row.description,
                descriptionTruncated: row.descriptionTruncated,
                source: row.source,
                sourcePath: row.sourcePath,
                enabled: row.enabled,
                direct: row.direct,
                xdev: row.xdev,
                evalBridge: row.evalBridge,
                mcpServerName: ownership[0],
                mcpToolName: ownership[1],
              };
            }),
          }
        : { status: "unavailable", reason: tools.reason },
    };
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      const dropped: DraftSection = { status: "unavailable", reason: "payload-too-large" };
      snapshot.skills = dropped;
      snapshot.tools = dropped;
      json = JSON.stringify(snapshot);
    }
    revision += 1;
    lastDigest = digest;
    ui.setStatus(STATUS_KEY, json);
  }

  function stopPoll(): void {
    if (!pollTimer) return;
    try {
      clearInterval(pollTimer as unknown as number);
    } catch {
      /* a runtime that refuses clearInterval still loses its handle */
    }
    pollTimer = null;
  }

  function startPoll(): void {
    if (pollTimer) return;
    const timer = setInterval(() => {
      try {
        publish(false);
      } catch {
        /* a poll failure must never surface in the session */
      }
    }, POLL_MS);
    pollTimer = timer as unknown as PollTimer;
    try {
      pollTimer.unref?.();
    } catch {
      /* an unref-less runtime keeps the interval as-is */
    }
  }

  function bindRootShutdown(root: SessionLike): void {
    const target = root as unknown as Record<string, unknown>;
    for (const method of ["dispose", "disconnect", "cleanup", "shutdown"]) {
      try {
        const original = target[method];
        if (typeof original !== "function") continue;
        target[method] = function (this: unknown, ...args: unknown[]): unknown {
          const result = (original as (...a: unknown[]) => unknown).apply(this, args);
          try {
            if (this === root) stopPoll();
          } catch {
            /* shutdown hook bookkeeping never breaks the session */
          }
          return result;
        };
      } catch {
        /* a sealed or throwing dispose hook is not our session's problem */
      }
    }
  }

  function captureRoot(candidate: SessionLike): boolean {
    if (rootSession === null) {
      rootSession = candidate;
      bindRootShutdown(candidate);
      return true;
    }
    return candidate === rootSession;
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: SessionLike, ...args: unknown[]) => unknown;
      prototype.prompt = function (this: SessionLike, ...args: unknown[]): unknown {
        const isRoot = captureRoot(this);
        const result = call.apply(this, args);
        const tail =
          result && typeof (result as Promise<unknown>).then === "function"
            ? (result as Promise<unknown>).then
            : null;
        const atEnd = (): void => {
          if (!isRoot) return;
          try {
            publish(true);
          } catch {
            /* capability sampling must never take down a user prompt */
          }
        };
        if (tail) (tail.call(result, atEnd, atEnd));
        else atEnd();
        return result;
      };
    }
  } catch {
    /* missing root binding: every publish degrades to unavailable sections */
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui session capabilities",
    handler: async (_args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      try {
        publish(true);
      } catch {
        /* the arm command itself still succeeds on a failing sample */
      }
      startPoll();
    },
  });
}
`;
}

/**
 * Writes the capabilities bridge into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from
 * an older omp-ui build can never outvote the current wire contract.
 */
export function writeCapabilitiesExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, capabilitiesExtensionPath(lineageDir), extensionSource());
}
