import * as path from "node:path";
import {
  CAPABILITIES_COMMAND,
  CAPABILITIES_STATUS_KEY,
  CAPABILITIES_TOOL_ARG_PREFIX,
  CAPABILITY_DESCRIPTION_LIMIT,
  CAPABILITY_STATUS_BYTE_LIMIT,
  TOOL_MUTATION_STATUSES,
} from "./capabilities";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * OMP exposes its live capability surface (skills, tools, MCP ownership) only
 * through the methods on the running `AgentSession`. This generated extension
 * patches `AgentSession.prompt`, binds the FIRST prompting session as the root
 * (ADR-0008 discipline — descendant sessions never replace it), and samples
 * that root's public methods into the `omp-ui:capabilities` status channel.
 *
 * The roster sample is read-only by construction: `skills` is read as data (never
 * `loadSkills()`/`refreshSkills()` and never the system prompt), and MCP
 * ownership comes exclusively from the scalar metadata on the object
 * `getToolByName` returns — a tool is never relabeled MCP because its name
 * looks like one. Access facts (enabled/active/xdev/eval-bridge) are probed
 * per method; a missing or throwing method yields `null` fields, never a
 * fabricated `false`.
 *
 * The bridge is no longer purely read-only: the same hidden command carries a
 * `tool <json>` verb that applies one session-local tool enable/disable — OMP
 * runtime state only, never config, restart, or an auto prompt. It never
 * trusts RPC success: it re-checks identity, deadline, and runtime state
 * inside omp's registry queue (when the runtime exposes one; its absence is
 * never a refusal), applies from freshly read rosters via
 * `setActiveToolPresentation`, and confirms the result by readback. Every
 * snapshot carries `toolControl` and the retained `toolMutation` (cleared
 * when the root session id changes), and every completion force-publishes.
 * An accepted mutation takes a root-local barrier: a second concurrent
 * mutation or an in-flight non-capability root prompt reports `busy`, later
 * root prompts queue behind the mutation, and the 2-second poll never
 * mutates.
 *
 * Every root prompt settles force a snapshot (so `/new` and branch transitions
 * replace the inventory immediately), and a 2-second unref'd digest poll catches
 * changes that land outside a prompt. An over-budget roster is replaced whole
 * by a `payload-too-large` snapshot — omp-ui never ships a partial inventory.
 * Sampling failures can never reject a user prompt.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-capabilities.ts";

export function capabilitiesExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants and limits are
 * interpolated from capabilities.ts so the publishing side can never drift
 * from the parser the main process and renderer share.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(CAPABILITIES_STATUS_KEY)};
const COMMAND = ${JSON.stringify(CAPABILITIES_COMMAND)};
const TOOL_ARG_PREFIX = ${JSON.stringify(CAPABILITIES_TOOL_ARG_PREFIX)};
const MUTATION_STATUSES = ${JSON.stringify(TOOL_MUTATION_STATUSES)};
const ARM_MESSAGE = "/" + COMMAND;
const TOOL_COMMAND_PREFIX = ARM_MESSAGE + " " + TOOL_ARG_PREFIX;
const CONTROL_APIS = [
  "getEnabledToolNames",
  "getMountedXdevToolNames",
  "getAllToolInfos",
  "setActiveToolPresentation",
  "getPlanModeState",
];
const DESC_LIMIT = ${CAPABILITY_DESCRIPTION_LIMIT};
const BYTE_LIMIT = ${CAPABILITY_STATUS_BYTE_LIMIT};
const POLL_MS = 2000;
const CONTROL_CHARS = /[\\u0000-\\u001f\\u007f-\\u009f]/g;

interface PollTimer {
  unref?: () => void;
}

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface SessionLike {
  sessionManager?: { getSessionId?: () => unknown };
  skills?: unknown;
  skillsSettings?: { enableSkillCommands?: unknown };
  getAllToolInfos?: () => unknown;
  getEnabledToolNames?: () => unknown;
  getActiveToolNames?: () => unknown;
  getMountedXdevToolNames?: () => unknown;
  getEvalBridgeToolNames?: () => unknown;
  getToolByName?: (name: string) => unknown;
  /** Re-entrant registry lock; optional — its absence never refuses a mutation. */
  runToolRegistryMutation?: (work: () => Promise<unknown>, signal?: unknown) => unknown;
  setActiveToolPresentation?: (
    enabled: string[],
    mounted: string[],
    forcePromptRefresh?: boolean,
    signal?: unknown,
  ) => unknown;
  getPlanModeState?: () => unknown;
  isStreaming?: unknown;
  isAborting?: unknown;
  queuedMessageCount?: unknown;
  version?: unknown;
  ompVersion?: unknown;
}

interface SkillRow {
  name: string;
  description: string;
  descriptionTruncated: boolean;
  filePath: string;
  source: string | null;
  scope: string | null;
  hidden: boolean | null;
}

interface ToolRow {
  name: string;
  description: string;
  descriptionTruncated: boolean;
  source: string;
  sourcePath: string | null;
  enabled: boolean | null;
  direct: boolean | null;
  xdev: boolean | null;
  evalBridge: boolean | null;
  mcpDigest: string;
}

interface SectionSample<T> {
  reason: string | null;
  rows: T[];
}

interface DraftSection {
  status: string;
  items?: unknown[];
  reason?: string;
}

interface DraftSnapshot {
  version: number;
  processKey: string;
  sessionId: string | null;
  revision: number;
  updatedAt: number;
  ompVersion: string | null;
  skillCommandsEnabled: boolean | null;
  skills: DraftSection;
  tools: DraftSection;
  toolControl: string;
  toolMutation: DraftToolMutation | null;
}

interface ToolMutationRequest {
  id: string;
  processKey: string;
  sessionId: string | null;
  name: string;
  enabled: boolean;
  expiresAt: number;
}

interface DraftToolMutation {
  id: string;
  name: string;
  enabled: boolean;
  status: string;
}

interface ExtensionApi {
  pi?: {
    AgentSession?: { prototype?: Record<string, unknown> };
    version?: unknown;
    ompVersion?: unknown;
  };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function expiredRequest(request: ToolMutationRequest): boolean {
  return request.expiresAt - Date.now() <= 0;
}

function signalAborted(signal: unknown): boolean {
  try {
    return (signal as { aborted?: boolean } | undefined)?.aborted === true;
  } catch {
    return false;
  }
}

/**
 * Strict allowlist parse mirroring parseCapabilityToolMutationRequest in
 * capabilities.ts: exact field set, exact types. Malformed payloads return
 * null so the handler throws instead of falling into the arm path.
 */
function parseToolRequest(json: string): ToolMutationRequest | null {
  let value: unknown;
  try {
    value = JSON.parse(json);
  } catch {
    return null;
  }
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).sort();
  const expected = ["enabled", "expiresAt", "id", "name", "processKey", "sessionId"];
  if (keys.length !== expected.length) return null;
  for (let i = 0; i < expected.length; i++) if (keys[i] !== expected[i]) return null;
  if (typeof record.id !== "string" || record.id.length === 0) return null;
  if (typeof record.processKey !== "string" || record.processKey.length === 0) return null;
  if (record.sessionId !== null && typeof record.sessionId !== "string") return null;
  if (typeof record.name !== "string" || record.name.length === 0) return null;
  if (record.enabled !== true && record.enabled !== false) return null;
  if (typeof record.expiresAt !== "number" || !Number.isFinite(record.expiresAt)) return null;
  return {
    id: record.id,
    processKey: record.processKey,
    sessionId: record.sessionId as string | null,
    name: record.name,
    enabled: record.enabled,
    expiresAt: record.expiresAt,
  };
}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);
  let rootSession: SessionLike | null = null;
  let ui: StatusUi | null = null;
  let pollTimer: PollTimer | null = null;
  let lastDigest: string | null = null;
  let revision = 0;
  let mutationInFlight: Promise<void> | null = null;
  let promptInFlight = 0;
  let toolMutation: DraftToolMutation | null = null;
  let toolMutationSessionId: string | null = null;

  function capped(value: unknown): { text: string; truncated: boolean } {
    const text = typeof value === "string" ? value.replace(CONTROL_CHARS, " ") : "";
    return text.length > DESC_LIMIT
      ? { text: text.slice(0, DESC_LIMIT), truncated: true }
      : { text, truncated: false };
  }

  function utf8Length(text: string): number {
    let bytes = 0;
    for (let i = 0; i < text.length; i++) {
      const code = text.charCodeAt(i);
      if (code < 0x80) bytes += 1;
      else if (code < 0x800) bytes += 2;
      else if (code >= 0xdc00 && code < 0xe000) bytes += 0;
      else if (code >= 0xd800 && code < 0xdc00) { bytes += 4; i++; }
      else bytes += 3;
    }
    return bytes;
  }

  function sessionIdOf(session: SessionLike | null): string | null {
    const manager = session?.sessionManager;
    const fn = manager?.getSessionId;
    if (typeof fn !== "function") return null;
    try {
      const id = fn.call(manager);
      return typeof id === "string" && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  function probeVersion(): string | null {
    try {
      const candidates = [pi.pi?.version, pi.pi?.ompVersion, rootSession?.version, rootSession?.ompVersion];
      for (const candidate of candidates) {
        if (typeof candidate === "string" && candidate.length > 0) return candidate;
      }
    } catch {
      /* a hostile version getter still yields a valid snapshot */
    }
    return null;
  }

  function probeSkillCommands(root: SessionLike | null): boolean | null {
    try {
      const value = root?.skillsSettings?.enableSkillCommands;
      return typeof value === "boolean" ? value : null;
    } catch {
      return null;
    }
  }

  function nameSet(root: SessionLike, method: string): Set<string> | null {
    const fn = (root as unknown as Record<string, unknown>)[method];
    if (typeof fn !== "function") return null;
    try {
      const value = (fn as () => unknown).call(root);
      if (!Array.isArray(value)) return null;
      const names = new Set<string>();
      for (const item of value) {
        if (typeof item === "string") names.add(item);
      }
      return names;
    } catch {
      return null;
    }
  }

  function sampleSkills(root: SessionLike | null): SectionSample<SkillRow> {
    if (!root) return { reason: "missing-api", rows: [] };
    let raw: unknown;
    try {
      raw = root.skills;
    } catch {
      return { reason: "read-failed", rows: [] };
    }
    if (!Array.isArray(raw)) return { reason: "missing-api", rows: [] };
    try {
      const rows: SkillRow[] = [];
      for (const entry of raw as Record<string, unknown>[]) {
        if (entry === null || typeof entry !== "object" || Array.isArray(entry)) continue;
        if (typeof entry.name !== "string" || entry.name.length === 0) continue;
        const description = capped(entry.description);
        const source = entry._source;
        const level = source !== null && typeof source === "object"
          ? (source as Record<string, unknown>).level
          : null;
        rows.push({
          name: entry.name,
          description: description.text,
          descriptionTruncated: description.truncated,
          filePath: typeof entry.filePath === "string" ? entry.filePath : "",
          source: typeof entry.source === "string" ? entry.source : null,
          scope: level === "user" || level === "project" ? level : null,
          hidden: typeof entry.hide === "boolean" ? entry.hide : null,
        });
      }
      return { reason: null, rows };
    } catch {
      return { reason: "read-failed", rows: [] };
    }
  }

  function originOf(value: unknown): string | null {
    if (typeof value !== "string") return null;
    const label = value.toLowerCase();
    return label === "builtin" || label === "extension" || label === "mcp" || label === "sdk" ? label : null;
  }

  function toolSourceOf(entry: Record<string, unknown>): string {
    const direct = originOf(entry.source) ?? originOf(entry.kind);
    if (direct !== null) return direct;
    const info = entry.sourceInfo;
    if (info !== null && typeof info === "object" && !Array.isArray(info)) {
      const record = info as Record<string, unknown>;
      for (const field of ["kind", "type", "source", "provider"]) {
        const origin = originOf(record[field]);
        if (origin !== null) return origin;
      }
    }
    return "unknown";
  }

  function synthesizedScoped(entry: Record<string, unknown>): boolean {
    if (entry.scope === "temporary" || entry.sourceScope === "temporary") return true;
    const source = entry._source;
    if (source !== null && typeof source === "object"
      && (source as Record<string, unknown>).level === "temporary") return true;
    const info = entry.sourceInfo;
    if (info !== null && typeof info === "object" && !Array.isArray(info)) {
      const record = info as Record<string, unknown>;
      for (const field of ["scope", "kind"]) {
        const value = record[field];
        if (typeof value === "string") {
          const label = value.toLowerCase();
          if (label.includes("temp") || label.includes("memory")) return true;
        }
      }
    }
    return false;
  }

  function sampleTools(root: SessionLike | null): SectionSample<ToolRow> {
    if (!root) return { reason: "missing-api", rows: [] };
    const list = root.getAllToolInfos;
    if (typeof list !== "function") return { reason: "missing-api", rows: [] };
    let raw: unknown;
    try {
      raw = list.call(root);
    } catch {
      return { reason: "read-failed", rows: [] };
    }
    if (!Array.isArray(raw)) return { reason: "read-failed", rows: [] };
    try {
      const enabled = nameSet(root, "getEnabledToolNames");
      const direct = nameSet(root, "getActiveToolNames");
      const xdev = nameSet(root, "getMountedXdevToolNames");
      const evalBridge = nameSet(root, "getEvalBridgeToolNames");
      const rows: ToolRow[] = [];
      for (const entry of raw as Record<string, unknown>[]) {
        if (entry === null || typeof entry !== "object" || Array.isArray(entry)) continue;
        if (typeof entry.name !== "string" || entry.name.length === 0) continue;
        const description = capped(entry.description);
        const infoServer = typeof entry.mcpServerName === "string" ? entry.mcpServerName : null;
        const infoTool = typeof entry.mcpToolName === "string" ? entry.mcpToolName : null;
        rows.push({
          name: entry.name,
          description: description.text,
          descriptionTruncated: description.truncated,
          source: toolSourceOf(entry),
          sourcePath: synthesizedScoped(entry) || typeof entry.sourcePath !== "string"
            ? null
            : entry.sourcePath,
          enabled: enabled === null ? null : enabled.has(entry.name),
          direct: direct === null ? null : direct.has(entry.name),
          xdev: xdev === null ? null : xdev.has(entry.name),
          evalBridge: evalBridge === null ? null : evalBridge.has(entry.name),
          mcpDigest: infoServer !== null && infoTool !== null ? infoServer + "\\u0000" + infoTool : "",
        });
      }
      return { reason: null, rows };
    } catch {
      return { reason: "read-failed", rows: [] };
    }
  }

  function mcpOwnership(root: SessionLike | null, name: string): [string | null, string | null] {
    const fn = root?.getToolByName;
    if (typeof fn !== "function" || root === null) return [null, null];
    try {
      const tool = fn.call(root, name);
      if (tool !== null && typeof tool === "object" && !Array.isArray(tool)) {
        const record = tool as Record<string, unknown>;
        const server = record.mcpServerName;
        const toolName = record.mcpToolName;
        if (typeof server === "string" && typeof toolName === "string") return [server, toolName];
      }
    } catch {
      /* unknown ownership, never a guess */
    }
    return [null, null];
  }

  function hasControlApis(root: SessionLike | null): boolean {
    if (root === null) return false;
    const probes = root as unknown as Record<string, unknown>;
    for (const method of CONTROL_APIS) {
      if (typeof probes[method] !== "function") return false;
    }
    return true;
  }

  /**
   * toolControl is "available" only when every required control probe is
   * present and the four read-only ones answer without throwing or returning
   * garbage. runToolRegistryMutation and the busy getters are optional
   * observations; their absence must not flip this to "unsupported".
   */
  function controlStateOf(root: SessionLike | null): boolean {
    if (!hasControlApis(root)) return false;
    try {
      if (!Array.isArray(root?.getAllToolInfos?.())) return false;
      if (!Array.isArray(root?.getEnabledToolNames?.())) return false;
      if (!Array.isArray(root?.getMountedXdevToolNames?.())) return false;
      root?.getPlanModeState?.();
    } catch {
      return false;
    }
    return true;
  }

  function identityMatches(root: SessionLike | null, request: ToolMutationRequest): boolean {
    if (root === null || root !== rootSession) return false;
    if (request.processKey !== processKey) return false;
    if (request.sessionId !== null && sessionIdOf(root) !== request.sessionId) return false;
    return true;
  }

  function recordToolMutation(request: ToolMutationRequest, status: string): void {
    toolMutation = {
      id: request.id,
      name: request.name,
      enabled: request.enabled,
      status: MUTATION_STATUSES.indexOf(status) >= 0 ? status : "not-applied",
    };
    toolMutationSessionId = sessionIdOf(rootSession);
  }

  /** Refused or confirmed: the completion always force-publishes. */
  function completeMutation(request: ToolMutationRequest, status: string): void {
    recordToolMutation(request, status);
    try {
      publish(true);
    } catch {
      /* a refusal settles as a published status, never as a prompt failure */
    }
  }

  async function runMutation(request: ToolMutationRequest): Promise<void> {
    const root = rootSession;
    if (root === null || !identityMatches(root, request)) {
      completeMutation(request, "stale");
      return;
    }
    if (expiredRequest(request)) {
      completeMutation(request, "expired");
      return;
    }
    if (mutationInFlight !== null) {
      completeMutation(request, "busy");
      return;
    }
    await executeMutation(root, request);
  }

  async function executeMutation(root: SessionLike, request: ToolMutationRequest): Promise<void> {
    let release!: () => void;
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    // The barrier is set synchronously before the first await: the second
    // concurrent mutation reads "busy", and later root prompts queue here.
    mutationInFlight = gate;
    const controller = typeof AbortController === "function" ? new AbortController() : null;
    const remaining = request.expiresAt - Date.now();
    const timer = remaining > 0
      ? setTimeout(() => {
          try {
            controller?.abort();
          } catch {
            /* an abort-less controller falls back to the deadline rechecks */
          }
        }, remaining)
      : null;
    let status: string;
    try {
      status = await performMutation(root, request, controller);
    } catch {
      status = expiredRequest(request) ? "expired" : "apply-failed";
    } finally {
      // Rejection-safe release: the barrier can never outlive this call.
      if (timer !== null) {
        try {
          clearTimeout(timer);
        } catch {
          /* a runtime that refuses clearTimeout still loses the deadline hook */
        }
      }
      mutationInFlight = null;
      release();
    }
    completeMutation(request, status);
  }

  async function performMutation(
    root: SessionLike,
    request: ToolMutationRequest,
    controller: AbortController | null,
  ): Promise<string> {
    const signal = controller ? controller.signal : undefined;
    let outcome = "not-applied";
    let ran = false;
    const work = async (): Promise<string> => {
      ran = true;
      outcome = await mutateLocked(root, request, signal);
      return outcome;
    };
    const run = root.runToolRegistryMutation;
    // The queue is a serialization nicety, not a requirement: an omp without
    // it applies directly (our root-local barrier already excludes rivals).
    if (typeof run !== "function") return await work();
    // omp may swallow handler errors inside the queue; the closed-over outcome
    // keeps the truth even when the queue resolves without surfacing work's result.
    try {
      await run.call(root, work, signal);
    } catch (error) {
      if (!ran) throw error;
    }
    return outcome;
  }

  async function mutateLocked(
    root: SessionLike,
    request: ToolMutationRequest,
    signal?: unknown,
  ): Promise<string> {
    if (!identityMatches(root, request)) return "stale";
    if (expiredRequest(request)) return "expired";
    if (!hasControlApis(root)) return "unsupported";
    let infos: unknown;
    let enabledNames: unknown;
    let xdevNames: unknown;
    let planState: unknown;
    let runtimeBusy = false;
    try {
      infos = root.getAllToolInfos?.();
      enabledNames = root.getEnabledToolNames?.();
      xdevNames = root.getMountedXdevToolNames?.();
      planState = root.getPlanModeState?.();
      // Busy getters are optional: present-and-busy refuses, missing defers
      // to the root-prompt barrier installed in the prompt wrapper.
      runtimeBusy =
        root.isStreaming === true ||
        root.isAborting === true ||
        (typeof root.queuedMessageCount === "number" && root.queuedMessageCount > 0);
    } catch {
      return "unsupported";
    }
    if (!Array.isArray(infos) || !Array.isArray(enabledNames) || !Array.isArray(xdevNames)) {
      return "unsupported";
    }
    if (runtimeBusy || promptInFlight > 0) return "busy";
    if (signalAborted(signal) || expiredRequest(request)) return "expired";
    let known = false;
    for (const entry of infos as unknown[]) {
      if (entry !== null && typeof entry === "object" && !Array.isArray(entry)
        && (entry as Record<string, unknown>).name === request.name) {
        known = true;
        break;
      }
    }
    if (!known) return "unknown-tool";
    const planOn = planState !== null && typeof planState === "object" && !Array.isArray(planState)
      && (planState as Record<string, unknown>).enabled === true;
    if (planOn && request.name === "write" && request.enabled === false) return "mode-required";
    // Fresh registry membership only — never filtered or published rows.
    const enabledStrings = (enabledNames as unknown[]).filter(isString);
    const enabledSet = new Set(enabledStrings);
    if (enabledSet.has(request.name) === request.enabled) {
      // Already satisfied: an idempotent applied with a fresh confirmation
      // publish and no setter call.
      return "applied";
    }
    const nextEnabled = request.enabled
      ? enabledStrings.concat([request.name])
      : enabledStrings.filter((name) => name !== request.name);
    const nextMounted = (xdevNames as unknown[])
      .filter(isString)
      .filter((name) => nextEnabled.indexOf(name) >= 0);
    try {
      await root.setActiveToolPresentation?.(nextEnabled, nextMounted, false, signal);
    } catch {
      return signalAborted(signal) || expiredRequest(request) ? "expired" : "apply-failed";
    }
    let readback: unknown;
    try {
      readback = root.getEnabledToolNames?.();
    } catch {
      return "not-applied";
    }
    if (!Array.isArray(readback)) return "not-applied";
    const retained = new Set((readback as unknown[]).filter(isString)).has(request.name);
    return retained === request.enabled ? "applied" : "not-applied";
  }

  function digestOf(
    sessionIdValue: string | null,
    skillCommandsEnabled: boolean | null,
    skills: SectionSample<SkillRow>,
    tools: SectionSample<ToolRow>,
    toolControl: string,
    mutation: DraftToolMutation | null,
  ): string {
    const skillRows = skills.reason === null
      ? skills.rows.map((row) => [row.name, row.description, row.descriptionTruncated, row.filePath, row.source, row.scope, row.hidden])
      : ["unavailable", skills.reason];
    const toolRows = tools.reason === null
      ? tools.rows.map((row) => [row.name, row.description, row.descriptionTruncated, row.source, row.enabled, row.direct, row.xdev, row.evalBridge, row.mcpDigest])
      : ["unavailable", tools.reason];
    const mutationRow = mutation === null
      ? null
      : [mutation.id, mutation.name, mutation.enabled, mutation.status];
    return JSON.stringify([sessionIdValue, skillCommandsEnabled, skillRows, toolRows, toolControl, mutationRow]);
  }

  function publish(force: boolean): void {
    if (!ui) return;
    const root = rootSession;
    const sessionIdValue = sessionIdOf(root);
    if (toolMutation !== null && sessionIdValue !== toolMutationSessionId) {
      // A root session id change (/new, branch) outranks any retained result.
      toolMutation = null;
      toolMutationSessionId = null;
    }
    const skillCommandsEnabled = probeSkillCommands(root);
    const skills = sampleSkills(root);
    const tools = sampleTools(root);
    const toolControl = controlStateOf(root) ? "available" : "unsupported";
    const digest = digestOf(sessionIdValue, skillCommandsEnabled, skills, tools, toolControl, toolMutation);
    if (!force && digest === lastDigest) return;
    const snapshot: DraftSnapshot = {
      version: 1,
      processKey,
      sessionId: sessionIdValue,
      revision: revision + 1,
      updatedAt: Date.now(),
      ompVersion: probeVersion(),
      skillCommandsEnabled,
      skills: skills.reason === null
        ? { status: "available", items: skills.rows }
        : { status: "unavailable", reason: skills.reason },
      tools: tools.reason === null
        ? {
            status: "available",
            items: tools.rows.map((row) => {
              const ownership = mcpOwnership(root, row.name);
              return {
                name: row.name,
                description: row.description,
                descriptionTruncated: row.descriptionTruncated,
                source: row.source,
                sourcePath: row.sourcePath,
                enabled: row.enabled,
                direct: row.direct,
                xdev: row.xdev,
                evalBridge: row.evalBridge,
                mcpServerName: ownership[0],
                mcpToolName: ownership[1],
              };
            }),
          }
        : { status: "unavailable", reason: tools.reason },
      toolControl,
      toolMutation,
    };
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      const dropped: DraftSection = { status: "unavailable", reason: "payload-too-large" };
      snapshot.skills = dropped;
      snapshot.tools = dropped;
      json = JSON.stringify(snapshot);
    }
    revision += 1;
    lastDigest = digest;
    ui.setStatus(STATUS_KEY, json);
  }

  function stopPoll(): void {
    if (!pollTimer) return;
    try {
      clearInterval(pollTimer as unknown as number);
    } catch {
      /* a runtime that refuses clearInterval still loses its handle */
    }
    pollTimer = null;
  }

  function startPoll(): void {
    if (pollTimer) return;
    const timer = setInterval(() => {
      try {
        publish(false);
      } catch {
        /* a poll failure must never surface in the session */
      }
    }, POLL_MS);
    pollTimer = timer as unknown as PollTimer;
    try {
      pollTimer.unref?.();
    } catch {
      /* an unref-less runtime keeps the interval as-is */
    }
  }

  function bindRootShutdown(root: SessionLike): void {
    const target = root as unknown as Record<string, unknown>;
    for (const method of ["dispose", "disconnect", "cleanup", "shutdown"]) {
      try {
        const original = target[method];
        if (typeof original !== "function") continue;
        target[method] = function (this: unknown, ...args: unknown[]): unknown {
          const result = (original as (...a: unknown[]) => unknown).apply(this, args);
          try {
            if (this === root) stopPoll();
          } catch {
            /* shutdown hook bookkeeping never breaks the session */
          }
          return result;
        };
      } catch {
        /* a sealed or throwing dispose hook is not our session's problem */
      }
    }
  }

  function captureRoot(candidate: SessionLike): boolean {
    if (rootSession === null) {
      rootSession = candidate;
      bindRootShutdown(candidate);
      return true;
    }
    return candidate === rootSession;
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: SessionLike, ...args: unknown[]) => unknown;
      prototype.prompt = function (this: SessionLike, ...args: unknown[]): unknown {
        const isRoot = captureRoot(this);
        const text = typeof args[0] === "string" ? (args[0] as string).trim() : null;
        const capability = text !== null
          && (text === ARM_MESSAGE || text.startsWith(TOOL_COMMAND_PREFIX));
        const counted = isRoot && !capability;
        const invoke = (): unknown => {
          if (counted) promptInFlight += 1;
          let result: unknown;
          try {
            result = call.apply(this, args);
          } catch (error) {
            if (counted) promptInFlight -= 1;
            throw error;
          }
          const settle = (): void => {
            if (counted) promptInFlight -= 1;
            if (!isRoot) return;
            try {
              publish(true);
            } catch {
              /* capability sampling must never take down a user prompt */
            }
          };
          const tail =
            result && typeof (result as Promise<unknown>).then === "function"
              ? (result as Promise<unknown>).then
              : null;
          if (tail) tail.call(result, settle, settle);
          else settle();
          return result;
        };
        // An accepted mutation first: ordinary root prompts queue here and
        // then invoke the original prompt unchanged (same value, same error).
        // Capability commands and descendant sessions never queue.
        if (counted && mutationInFlight !== null) return mutationInFlight.then(invoke);
        return invoke();
      };
    }
  } catch {
    /* missing root binding: every publish degrades to unavailable sections */
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui session capabilities",
    handler: async (args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      const trimmed = typeof args === "string" ? args.trim() : "";
      if (trimmed === "") {
        try {
          publish(true);
        } catch {
          /* the arm command itself still succeeds on a failing sample */
        }
        startPoll();
        return;
      }
      if (!trimmed.startsWith(TOOL_ARG_PREFIX)) {
        throw new Error("omp-ui-capabilities: unsupported command args");
      }
      const request = parseToolRequest(trimmed.slice(TOOL_ARG_PREFIX.length));
      if (request === null) {
        throw new Error("omp-ui-capabilities: malformed tool mutation request");
      }
      await runMutation(request);
    },
  });
}
`;
}

/**
 * Writes the capabilities bridge into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from
 * an older omp-ui build can never outvote the current wire contract.
 */
export function writeCapabilitiesExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, capabilitiesExtensionPath(lineageDir), extensionSource());
}
