import * as path from "node:path";
import {
  GOAL_COMMAND,
  GOAL_COMMAND_ARG_PREFIX,
  GOAL_CONTINUATION_CUSTOM_TYPE,
  GOAL_GUIDED_CUSTOM_TYPE,
  GOAL_MODE_TRANSITION_KEY,
  GOAL_OBJECTIVE_CHAR_LIMIT,
  GOAL_SETTLE_MS,
  GOAL_START_CUSTOM_TYPE,
  GOAL_STATUS_BYTE_LIMIT,
  GOAL_STATUS_KEY,
} from "./goal";
import { writeLineageArtifact } from "./lineage-artifact";

/**
 * omp's goal family is TUI-only: `goal` and `guided-goal` define `handleTui`
 * and no `handle`, `available-commands.ts` excludes definitions without
 * `handle`, and the noninteractive dispatcher skips them — so over rpc-ui a
 * `/goal` line is forwarded to the model as literal prompt text. What *is*
 * reachable is `AgentSession` itself: `goalRuntime` plus
 * `getGoalModeState`/`setGoalModeState`/`promptCustomMessage` and the runtime's
 * own mutation methods are the same surface omp's goal tool drives.
 *
 * This generated extension therefore owns the whole goal lifecycle inside the
 * owned OMP process (ADR-0007/0008 delivery): command parsing, omp runtime
 * mutation, restore-on-resume, and the single autonomous continuation loop that
 * omp's `InteractiveMode` owns in a terminal and that no native session has.
 * The renderer never runs a goal loop; main keeps a read-only snapshot.
 *
 * omp's runtime stays the only accountant and the only writer of durable goal
 * state: the bridge calls `createGoal`/`replaceGoal`/`resumeGoal`/`pauseGoal`/
 * `dropGoal`/`onBudgetMutated` and reads `getGoalModeState()` back. It never
 * edits a transcript and never keeps a second token counter.
 *
 * Activation is admitted through one root-local mode-transition chain shared
 * with the plan bridge under `Symbol.for("omp-ui:mode-transition")`: the
 * runtime's activation methods are wrapped compositionally, so a model tool
 * call and a native command pass the same check that Plan entry makes. That
 * chain is never held across a dialog or a model turn, and a goal command never
 * holds it while calling a wrapped method (that would deadlock).
 *
 * Every API this needs is unsupported surface, so every one is probed: a
 * missing method publishes `unavailable` with the reason and leaves ordinary
 * prompting untouched, rather than faking a goal or starting an unowned loop.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-goal.ts";

export function goalExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants are interpolated
 * from goal.ts so the publishing side can never drift from the parser the main
 * process and the renderers share.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(GOAL_STATUS_KEY)};
const COMMAND = ${JSON.stringify(GOAL_COMMAND)};
const ARG_PREFIX = ${JSON.stringify(GOAL_COMMAND_ARG_PREFIX)};
const ARM_MESSAGE = "/" + COMMAND;
const OBJECTIVE_LIMIT = ${GOAL_OBJECTIVE_CHAR_LIMIT};
const BYTE_LIMIT = ${GOAL_STATUS_BYTE_LIMIT};
const SETTLE_MS = ${GOAL_SETTLE_MS};
const TRANSITION_KEY = ${JSON.stringify(GOAL_MODE_TRANSITION_KEY)};
const GOAL_TOOL = "goal";
const PLAN_KEEP = "Drop the current goal before entering Plan mode.";
const CONTINUATION_TYPE = ${JSON.stringify(GOAL_CONTINUATION_CUSTOM_TYPE)};
const START_TYPE = ${JSON.stringify(GOAL_START_CUSTOM_TYPE)};
const GUIDED_TYPE = ${JSON.stringify(GOAL_GUIDED_CUSTOM_TYPE)};
const SUBCOMMANDS = ["set", "show", "pause", "resume", "drop", "budget"];
const SESSION_APIS = [
  "getGoalModeState",
  "setGoalModeState",
  "promptCustomMessage",
  "prompt",
  "subscribe",
  "subscribeRunState",
  "registerSessionChangeCallback",
  "getPlanModeState",
  "getEnabledToolNames",
];
const RUNTIME_APIS = [
  "createGoal",
  "replaceGoal",
  "resumeGoal",
  "pauseGoal",
  "dropGoal",
  "onBudgetMutated",
  "onThreadResumed",
  "clearAccounting",
  "buildContinuationPrompt",
];
const MANAGER_APIS = ["getSessionId", "buildSessionContext", "appendModeChange"];
/** What the interview asks for, per omp-ui's guided-goal contract. */
const GUIDED_INTERVIEW =
  "Interview the user to define one concrete objective, its constraints and " +
  "observable completion criteria. Ask for missing information before acting. " +
  "Once the user confirms the objective, create it with the goal tool and " +
  "begin work. Do not create a goal before confirmation.";
const BUSY_REFUSAL = "Stop the current turn before starting or replacing a goal.";
const NO_PROGRESS_PAUSE = "Goal continuation made no tool progress; resume to continue.";

interface PollTimer {
  unref?: () => void;
}

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
  notify: (message: string, level?: "info" | "warning" | "error") => void;
  select?: (title: string, options: string[]) => Promise<string | undefined>;
  input?: (title: string, placeholder?: string) => Promise<string | undefined>;
  editor?: (title: string, prefill?: string) => Promise<string | undefined>;
  confirm?: (title: string, message: string) => Promise<boolean>;
}

interface GoalWire {
  id?: unknown;
  objective?: unknown;
  status?: unknown;
  tokenBudget?: unknown;
  tokensUsed?: unknown;
  timeUsedSeconds?: unknown;
  createdAt?: unknown;
  updatedAt?: unknown;
}

interface GoalLike extends GoalWire {
  id: string;
  objective: string;
  status: string;
  tokensUsed: number;
  timeUsedSeconds: number;
  createdAt: number;
  updatedAt: number;
}

interface StateLike {
  enabled?: unknown;
  mode?: unknown;
  goal?: GoalLike;
}

interface SessionLike {
  isStreaming?: unknown;
  isAborting?: unknown;
  isCompacting?: unknown;
  hasPostPromptWork?: unknown;
  queuedMessageCount?: unknown;
  goalRuntime?: unknown;
  settings?: { get?: (key: string) => unknown };
  sessionManager?: Record<string, unknown>;
  getGoalModeState?: () => unknown;
  setGoalModeState?: (state: unknown) => void;
  promptCustomMessage?: (message: Record<string, unknown>) => Promise<unknown>;
  subscribe?: (listener: (event: Record<string, unknown>) => void) => unknown;
  subscribeRunState?: (listener: (state?: string) => void) => unknown;
  registerSessionChangeCallback?: (listener: () => void) => unknown;
  getPlanModeState?: () => unknown;
  getVibeModeState?: () => unknown;
  getEnabledToolNames?: () => unknown;
  getMountedXdevToolNames?: () => unknown;
  getAllToolInfos?: () => unknown;
  hasBuiltInTool?: (name: string) => unknown;
  setActiveToolPresentation?: (
    enabled: string[],
    mounted: string[],
    forcePromptRefresh?: boolean,
  ) => unknown;
  setActiveToolsByName?: (names: string[]) => unknown;
  runToolRegistryMutation?: (work: () => Promise<unknown>) => unknown;
  abort?: (...args: unknown[]) => unknown;
}

interface CommandRequest {
  requestId: string;
  sessionId: string;
  processKey: string;
  command: string;
  args: string;
}

interface CommandResult {
  requestId: string;
  ok: boolean;
  text: string;
}

interface DraftGoal {
  id: string;
  objective: string;
  status: string;
  tokenBudget: number | null;
  tokensUsed: number;
  timeUsedSeconds: number;
  createdAt: number;
  updatedAt: number;
}

interface DialogContext {
  sessionId: string;
  goalId: string | null;
  generation: number;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

function asRecord(value: unknown): Record<string, unknown> | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function utf8Length(text: string): number {
  let bytes = 0;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code < 0x80) bytes += 1;
    else if (code < 0x800) bytes += 2;
    else if (code >= 0xdc00 && code < 0xe000) bytes += 0;
    else if (code >= 0xd800 && code < 0xdc00) {
      bytes += 4;
      i++;
    } else bytes += 3;
  }
  return bytes;
}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);
  const wrapped = new WeakSet<object>();

  let rootSession: SessionLike | null = null;
  let ui: StatusUi | null = null;
  let revision = 0;
  let lastDigest = "";
  let generation = 0;
  /** Set only by a probe that failed; null means the bridge can drive goals. */
  let broken: string | null = null;
  /** Why goals stopped being driven autonomously, distinct from omp's own states. */
  let pauseReason: string | null = null;
  let continuation: "idle" | "scheduled" | "running" = "idle";
  let settleTimer: PollTimer | null = null;
  let dialogsOpen = 0;
  /** agent_end saw work left pending; the run-state listener retries the check. */
  let idleCheckPending = false;
  /** A final erroring turn must pause only once omp's maintenance has settled. */
  let pendingErrorPause: string | null = null;
  let continuationTurnInFlight = false;
  let turnHadToolExecution = false;
  let lastResult: CommandResult | null = null;
  let lastResultSessionId: string | null = null;
  let mutationChain: Promise<void> = Promise.resolve();
  let restoring: Promise<void> | null = null;
  let restoredSessionId: string | null = null;
  const unsubscribe = new Array<() => void>();

  // ---------------------------------------------------------------- readers

  function sessionIdOf(session: SessionLike | null): string | null {
    const read = asRecord(session?.sessionManager)?.getSessionId;
    if (typeof read !== "function") return null;
    try {
      const id = (read as () => unknown).call(session?.sessionManager);
      return isString(id) && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  function stateOf(session: SessionLike | null): StateLike | null {
    const read = session?.getGoalModeState;
    if (typeof read !== "function") return null;
    try {
      const state = asRecord(read.call(session));
      return state !== null && asRecord(state.goal) !== null ? state : null;
    } catch {
      return null;
    }
  }

  /** omp's goal record as a wire object, or null when there is nothing to show. */
  function goalOf(session: SessionLike | null): DraftGoal | null {
    const goal = asRecord(stateOf(session)?.goal);
    if (goal === null) return null;
    return {
      id: isString(goal.id) ? goal.id : "",
      objective: isString(goal.objective) ? goal.objective : "",
      status: isString(goal.status) ? goal.status : "",
      tokenBudget: typeof goal.tokenBudget === "number" ? goal.tokenBudget : null,
      tokensUsed: typeof goal.tokensUsed === "number" ? goal.tokensUsed : 0,
      timeUsedSeconds: typeof goal.timeUsedSeconds === "number" ? goal.timeUsedSeconds : 0,
      createdAt: typeof goal.createdAt === "number" ? goal.createdAt : 0,
      updatedAt: typeof goal.updatedAt === "number" ? goal.updatedAt : 0,
    };
  }

  /** True for the states a goal can still move through: not complete, not dropped. */
  function unfinished(goal: DraftGoal | null): boolean {
    return goal !== null && goal.id !== "" && goal.status !== "complete" && goal.status !== "dropped";
  }

  function armed(goal: DraftGoal | null): boolean {
    return goal !== null && (goal.status === "active" || goal.status === "budget-limited");
  }

  function runtimeSettingOn(): boolean | null {
    const get = asRecord(rootSession?.settings)?.get;
    if (typeof get !== "function") return null;
    try {
      const value = (get as (key: string) => unknown).call(rootSession?.settings, "goal.enabled");
      return typeof value === "boolean" ? value : null;
    } catch {
      return null;
    }
  }

  /** The composed plan read — including the plan bridge's own guard view. */
  function planOn(): boolean {
    const read = rootSession?.getPlanModeState;
    if (typeof read !== "function") return false;
    try {
      return asRecord(read.call(rootSession))?.enabled === true;
    } catch {
      return false;
    }
  }

  function vibeOn(): boolean {
    const read = rootSession?.getVibeModeState;
    if (typeof read !== "function") return false;
    try {
      return asRecord(read.call(rootSession))?.enabled === true;
    } catch {
      return false;
    }
  }

  function roster(): string[] | null {
    const read = rootSession?.getEnabledToolNames;
    if (typeof read !== "function") return null;
    try {
      const names = read.call(rootSession);
      return Array.isArray(names) ? (names as unknown[]).filter(isString) : null;
    } catch {
      return null;
    }
  }

  /** null means "cannot tell", which never licenses an autonomous turn. */
  function goalToolEnabled(): boolean | null {
    const names = roster();
    return names === null ? null : names.indexOf(GOAL_TOOL) >= 0;
  }

  function goalToolKnown(): boolean {
    const infos = rootSession?.getAllToolInfos;
    if (typeof infos === "function") {
      try {
        const rows = infos.call(rootSession);
        if (Array.isArray(rows)) {
          return (rows as unknown[]).some(
            (row) => asRecord(row)?.name === GOAL_TOOL,
          );
        }
      } catch {
        /* fall through to the older probe */
      }
    }
    const builtin = rootSession?.hasBuiltInTool;
    if (typeof builtin !== "function") return false;
    try {
      return builtin.call(rootSession, GOAL_TOOL) === true;
    } catch {
      return false;
    }
  }

  function busy(): boolean {
    const session = rootSession;
    if (session === null) return true;
    try {
      return (
        session.isStreaming === true ||
        session.isAborting === true ||
        session.isCompacting === true ||
        session.hasPostPromptWork === true ||
        (typeof session.queuedMessageCount === "number" && session.queuedMessageCount > 0)
      );
    } catch {
      return true;
    }
  }

  // ------------------------------------------------------- the shared chain

  /**
   * The one mode-transition chain, shared with the plan bridge through a
   * realm-wide symbol. Kept as a plain queue object so neither extension has to
   * know which of them loaded first.
   */
  function chain(): { queue: Promise<void> } {
    const global = globalThis as unknown as Record<string, unknown>;
    const key = Symbol.for(TRANSITION_KEY);
    let box = asRecord(global[key as unknown as string]);
    if (box === null) {
      const created = { queue: Promise.resolve() };
      try {
        (global as Record<symbol, unknown>)[key] = created;
      } catch {
        /* a runtime that refuses new symbols keeps our local chain */
      }
      return created;
    }
    const queue = box.queue;
    if (queue instanceof Promise) return box as unknown as { queue: Promise<void> };
    const reset = { queue: Promise.resolve() };
    box.queue = reset.queue;
    return reset;
  }

  function inTransition(work: () => Promise<void>): Promise<void> {
    const box = chain();
    const next = box.queue.then(work, work);
    box.queue = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  /** Arrival order for goal state mutations; never held across a dialog or turn. */
  function serialize(work: () => Promise<void>): Promise<void> {
    const next = mutationChain.then(work, work);
    mutationChain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  // --------------------------------------------------------------- publish

  function brokenReason(): string | null {
    if (broken !== null) return broken;
    if (rootSession === null) return "no omp session has prompted yet";
    const session = rootSession as unknown as Record<string, unknown>;
    const missing = SESSION_APIS.filter((name) => typeof session[name] !== "function");
    if (missing.length > 0) return "omp session is missing: " + missing.join(", ");
    const manager = asRecord(session.sessionManager);
    const missingManager = manager === null
      ? MANAGER_APIS
      : MANAGER_APIS.filter((name) => typeof manager[name] !== "function");
    if (missingManager.length > 0) return "sessionManager is missing: " + missingManager.join(", ");
    if (typeof asRecord(session.settings)?.get !== "function") return "session settings cannot be read";
    const runtime = asRecord(session.goalRuntime);
    if (runtime === null) return "this omp session exposes no goalRuntime";
    const missingRuntime = RUNTIME_APIS.filter((name) => typeof runtime[name] !== "function");
    if (missingRuntime.length > 0) return "goalRuntime is missing: " + missingRuntime.join(", ");
    if (typeof session.setActiveToolPresentation !== "function" &&
      typeof session.setActiveToolsByName !== "function") {
      return "this omp session can apply no tool roster";
    }
    return null;
  }

  function digestOf(goal: DraftGoal | null, enabled: boolean, result: CommandResult | null): string {
    return JSON.stringify([
      sessionIdOf(rootSession),
      brokenReason() === null,
      goal === null ? null : [
        goal.id,
        goal.objective,
        goal.status,
        goal.tokenBudget,
        goal.tokensUsed,
        goal.timeUsedSeconds,
        goal.createdAt,
        goal.updatedAt,
      ],
      enabled,
      continuation,
      pauseReason,
      result === null ? null : [result.requestId, result.ok, result.text],
    ]);
  }

  function publish(force: boolean): void {
    if (ui === null) return;
    const reason = brokenReason();
    const goal = goalOf(rootSession);
    const result = sessionIdOf(rootSession) === lastResultSessionId ? lastResult : null;
    const enabled = reason === null && armed(goal);
    const digest = digestOf(goal, enabled, result);
    if (!force && digest === lastDigest) return;
    const snapshot: Record<string, unknown> = {
      version: 1,
      processKey,
      sessionId: sessionIdOf(rootSession) ?? "",
      revision: revision + 1,
      available: reason === null,
      unavailable: reason,
      enabled,
      goal: goal === null || goal.id === ""
        ? null
        : {
            id: goal.id,
            objective: goal.objective,
            status: goal.status,
            tokenBudget: goal.tokenBudget,
            tokensUsed: goal.tokensUsed,
            timeUsedSeconds: goal.timeUsedSeconds,
            createdAt: goal.createdAt,
            updatedAt: goal.updatedAt,
          },
      continuation,
      pauseReason,
      result,
    };
    // An impossible payload is published as unavailable, never as half a goal
    // and never as "no goal": the objective is never truncated on the wire.
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      snapshot.available = false;
      snapshot.unavailable = "goal snapshot exceeded " + BYTE_LIMIT + " bytes";
      snapshot.enabled = false;
      snapshot.goal = null;
      json = JSON.stringify(snapshot);
    }
    revision += 1;
    lastDigest = digest;
    ui.setStatus(STATUS_KEY, json);
  }

  // ------------------------------------------------------------- reporting

  function settle(request: CommandRequest, ok: boolean, text: string): void {
    lastResult = { requestId: request.requestId, ok, text };
    lastResultSessionId = sessionIdOf(rootSession);
    try {
      publish(true);
    } catch {
      /* a command always settles as a published status, never as a prompt failure */
    }
  }

  function details(goal: DraftGoal | null): string {
    if (goal === null || goal.id === "") return "No goal is set.";
    const budget =
      goal.tokenBudget === null
        ? goal.tokensUsed + " used (unbounded)"
        : goal.tokensUsed + " of " + goal.tokenBudget + " used, " +
          Math.max(0, goal.tokenBudget - goal.tokensUsed) + " remaining";
    const status = goal.status === "active" && runtimeSettingOn() === false
      ? "active (goal support is disabled)"
      : goal.status;
    return [
      "Objective: " + goal.objective,
      "Status: " + status,
      "Tokens: " + budget,
      "Elapsed: " + Math.max(0, Math.round(goal.timeUsedSeconds)) + " seconds",
    ].join("\\n");
  }

  // ------------------------------------------------------------- admission

  /**
   * The single activation check, run inside the shared chain before omp's own
   * runtime method. \`kind\` distinguishes what may activate: a recovery budget
   * edit for a paused goal is admitted because it cannot start anything.
   */
  function refusalFor(kind: string, goal: DraftGoal | null): string | null {
    if (kind === "budget") {
      return unfinished(goal) ? null : "There is no unfinished goal to budget.";
    }
    if (planOn()) return PLAN_KEEP;
    if (vibeOn()) return "Exit vibe mode before starting a goal.";
    if (kind === "activate") {
      const setting = runtimeSettingOn();
      if (setting === null) return "This omp build cannot report goal.enabled.";
      if (setting === false) return "Goal support is disabled (goal.enabled).";
      if (!goalToolKnown()) return "This omp session has no goal tool registered.";
    }
    return null;
  }

  /**
   * Composition over the captured root's runtime so model tool calls and native
   * commands are admitted identically. Receivers, return values and errors are
   * preserved; the chain is acquired for the check plus the original call only.
   */
  function admitRuntime(session: SessionLike): void {
    const runtime = asRecord(session.goalRuntime);
    if (runtime === null || wrapped.has(runtime)) return;
    wrapped.add(runtime);
    for (const method of ["createGoal", "replaceGoal", "resumeGoal", "onBudgetMutated"]) {
      const original = runtime[method];
      if (typeof original !== "function") continue;
      const call = original as (...args: unknown[]) => unknown;
      const activation = method === "onBudgetMutated" ? "budget" : "activate";
      runtime[method] = function (this: unknown, ...args: unknown[]): unknown {
        const session = rootSession;
        return inTransition(async () => {
          const refusal = refusalFor(activation, goalOf(session));
          if (refusal !== null) throw new Error(refusal);
          return await call.apply(this, args);
        });
      };
    }
  }

  /**
   * Tool preparation for a command that starts goal work. Applied from freshly
   * read rosters so every unrelated tool and mounted device survives, and
   * confirmed by readback. The registry lock is released before any runtime
   * activation, so the shared chain is never reached while it is held.
   */
  async function prepareGoalTool(): Promise<string | null> {
    const session = rootSession;
    if (session === null) return "no omp session";
    if (goalToolEnabled() === true && goalToolKnown()) return null;
    if (!goalToolKnown()) return "This omp session has no goal tool registered.";
    const run = session.runToolRegistryMutation;
    let failure: string | null = null;
    const work = async (): Promise<void> => {
      const enabled = roster();
      if (enabled === null) {
        failure = "This omp build cannot report its tool roster.";
        return;
      }
      if (enabled.indexOf(GOAL_TOOL) >= 0) return;
      const mounted = asRecord(session)?.getMountedXdevToolNames;
      const mountedNames = typeof mounted === "function"
        ? ((mounted.call(session) as unknown[] | null) ?? []).filter(isString)
        : [];
      const next = enabled.concat([GOAL_TOOL]);
      const nextMounted = mountedNames.filter((name) => next.indexOf(name) >= 0);
      const present = session.setActiveToolPresentation;
      try {
        if (typeof present === "function") {
          await Promise.resolve(present.call(session, next, nextMounted, false));
        } else {
          await Promise.resolve(session.setActiveToolsByName?.(next));
        }
      } catch (error) {
        failure = "The goal tool could not be enabled: " + String(error);
      }
    };
    try {
      if (typeof run === "function") await Promise.resolve(run.call(session, work));
      else await work();
    } catch (error) {
      if (failure === null) failure = "The goal tool could not be enabled: " + String(error);
    }
    if (failure !== null) return failure;
    if (goalToolEnabled() !== true) return "The goal tool is still disabled after enabling it.";
    return null;
  }

  // ------------------------------------------------------------- dialogs

  function context(): DialogContext {
    return {
      sessionId: sessionIdOf(rootSession) ?? "",
      goalId: goalOf(rootSession)?.id ?? null,
      generation,
    };
  }

  /**
   * Whether the run moved to another session between now and \`captured\`. Any
   * command step that spans a wait must re-check this: state belonging to a
   * replaced session is never applied to its successor.
   */
  function sessionStale(captured: DialogContext): string | null {
    if (captured.generation !== generation) return "The session changed before this command finished.";
    if (captured.sessionId !== (sessionIdOf(rootSession) ?? "")) {
      return "The session changed before this command finished.";
    }
    return null;
  }

  /**
   * A dialog answered after its goal was replaced is rejected rather than
   * applied to whatever took that goal's place.
   */
  function stillCurrent(captured: DialogContext): string | null {
    const session = sessionStale(captured);
    if (session !== null) return session;
    if (captured.goalId !== (goalOf(rootSession)?.id ?? null)) {
      return "The goal changed while the dialog was open.";
    }
    return null;
  }

  async function askEditor(title: string, prefill: string | undefined): Promise<string | undefined> {
    const editor = ui?.editor;
    if (typeof editor !== "function") return undefined;
    dialogsOpen += 1;
    try {
      return await editor.call(ui, title, prefill);
    } catch {
      return undefined;
    } finally {
      dialogsOpen -= 1;
      publish(true);
    }
  }

  async function askSelect(title: string, options: string[]): Promise<string | undefined> {
    const select = ui?.select;
    if (typeof select !== "function") return undefined;
    dialogsOpen += 1;
    try {
      return await select.call(ui, title, options);
    } catch {
      return undefined;
    } finally {
      dialogsOpen -= 1;
      publish(true);
    }
  }

  async function askInput(title: string, prefill: string | undefined): Promise<string | undefined> {
    const input = ui?.input;
    if (typeof input !== "function") return undefined;
    dialogsOpen += 1;
    try {
      return await input.call(ui, title, prefill);
    } catch {
      return undefined;
    } finally {
      dialogsOpen -= 1;
      publish(true);
    }
  }

  async function askConfirm(title: string, message: string): Promise<boolean> {
    const confirm = ui?.confirm;
    if (typeof confirm !== "function") return true;
    dialogsOpen += 1;
    try {
      return (await confirm.call(ui, title, message)) === true;
    } catch {
      return false;
    } finally {
      dialogsOpen -= 1;
      publish(true);
    }
  }

  // ------------------------------------------------------- mutations, work

  function runtimeOf(): Record<string, unknown> | null {
    return asRecord(rootSession?.goalRuntime);
  }

  /** Starts work outside the mutation chain: a turn must never hold it. */
  function startWork(customType: string, content: string): void {
    const session = rootSession;
    const send = session?.promptCustomMessage;
    if (session === null || typeof send !== "function") return;
    const captured = context();
    void Promise.resolve(
      send.call(session, { customType, content, display: true, attribution: "agent" }),
    )
      .then(() => {
        try {
          publish(true);
        } catch {
          /* a settled turn always republishes, and a publish failure stays quiet */
        }
      })
      .catch((error: unknown) => {
        pauseFor("The goal turn could not start: " + String(error), captured);
      });
  }

  /** A pause the bridge itself decided, attributed and de-duplicated by goal. */
  function pauseFor(reason: string, captured?: DialogContext): void {
    const session = rootSession;
    const runtime = runtimeOf();
    if (session === null || runtime === null) return;
    if (captured !== undefined && stillCurrent(captured) !== null) return;
    const goal = goalOf(session);
    if (!armed(goal)) return;
    cancelSettle();
    pauseReason = reason;
    continuationTurnInFlight = false;
    const pause = runtime.pauseGoal;
    if (typeof pause !== "function") return;
    void Promise.resolve(pause.call(runtime))
      .then(() => publish(true))
      .catch(() => publish(true));
  }

  /** One clean end of a goal turn: schedule the next autonomous step. */
  function scheduleContinuation(): void {
    if (goalOf(rootSession)?.status !== "active") return;
    if (settleTimer === null) {
      const timer = setTimeout(() => {
        settleTimer = null;
        evaluateIdle(true);
      }, SETTLE_MS);
      settleTimer = timer as unknown as PollTimer;
      try {
        settleTimer.unref?.();
      } catch {
        /* an unref-less runtime keeps the timer as-is */
      }
    }
    continuation = "scheduled";
    publish(true);
  }

  function cancelSettle(): void {
    if (settleTimer === null) return;
    try {
      clearTimeout(settleTimer as unknown as number);
    } catch {
      /* a runtime that refuses clearTimeout still loses its handle */
    }
    settleTimer = null;
    if (continuation === "scheduled") {
      continuation = "idle";
      publish(true);
    }
  }

  /** Everything that must hold at dispatch time, re-read at fire time. */
  function dispatchable(): { ok: true } | { ok: false; keepWaiting: boolean } {
    if (ui === null || brokenReason() !== null) return { ok: false, keepWaiting: false };
    if (restoring !== null) return { ok: false, keepWaiting: true };
    if (dialogsOpen > 0) return { ok: false, keepWaiting: true };
    const goal = goalOf(rootSession);
    if (goal === null || goal.status !== "active") return { ok: false, keepWaiting: false };
    if (planOn() || vibeOn()) return { ok: false, keepWaiting: false };
    const setting = runtimeSettingOn();
    if (setting === false) {
      pauseFor("Goal support is disabled (goal.enabled); the goal was paused.");
      return { ok: false, keepWaiting: false };
    }
    const enabled = goalToolEnabled();
    if (enabled === false) {
      pauseFor("The goal tool was disabled during an active goal.");
      return { ok: false, keepWaiting: false };
    }
    if (busy()) return { ok: false, keepWaiting: true };
    return { ok: true };
  }

  function evaluateIdle(fromTimer: boolean): void {
    if (pendingErrorPause !== null && armed(goalOf(rootSession))) {
      const reason = pendingErrorPause;
      pendingErrorPause = null;
      pauseFor(reason);
      return;
    }
    if (continuationTurnInFlight) return;
    const gate = dispatchable();
    if (gate.ok === false) {
      idleCheckPending = gate.keepWaiting;
      if (gate.keepWaiting && !fromTimer) {
        scheduleContinuation();
      } else if (!gate.keepWaiting) {
        cancelSettle();
      }
      return;
    }
    idleCheckPending = false;
    const runtime = runtimeOf();
    const build = asRecord(runtime)?.buildContinuationPrompt;
    if (typeof build !== "function") {
      broken = "goalRuntime.buildContinuationPrompt is not a function";
      cancelSettle();
      publish(true);
      return;
    }
    let prompt: unknown;
    try {
      prompt = build.call(runtime);
    } catch (error) {
      pauseFor("The continuation prompt could not be built: " + String(error));
      return;
    }
    if (!isString(prompt) || prompt.length === 0) {
      cancelSettle();
      return;
    }
    const send = rootSession?.promptCustomMessage;
    if (typeof send !== "function") {
      broken = "promptCustomMessage is not a function";
      cancelSettle();
      publish(true);
      return;
    }
    // Latched immediately before the root is invoked.
    const captured = context();
    continuation = "running";
    continuationTurnInFlight = true;
    turnHadToolExecution = false;
    publish(true);
    void Promise.resolve(
      send.call(rootSession, {
        customType: CONTINUATION_TYPE,
        content: prompt,
        display: false,
        attribution: "agent",
      }),
    )
      .then(() => {
        if (captured.generation === generation) {
          continuationTurnInFlight = false;
          continuation = "idle";
          publish(true);
        }
      })
      .catch((error: unknown) => {
        continuationTurnInFlight = false;
        continuation = "idle";
        pauseFor("The goal continuation could not run: " + String(error), captured);
      });
  }

  // ------------------------------------------------------------ restoration

  function validSavedGoal(value: unknown): GoalLike | null {
    const goal = asRecord(value);
    if (goal === null) return null;
    if (!isString(goal.id) || goal.id.length === 0) return null;
    if (!isString(goal.objective)) return null;
    if (!isString(goal.status)) return null;
    const known = ["active", "paused", "budget-limited", "complete", "dropped"];
    if (known.indexOf(goal.status) < 0) return null;
    const numeric = [goal.tokensUsed, goal.timeUsedSeconds, goal.createdAt, goal.updatedAt];
    for (const value of numeric) {
      if (typeof value !== "number" || !Number.isFinite(value) || value < 0) return null;
    }
    if (goal.tokenBudget !== undefined &&
      !(typeof goal.tokenBudget === "number" && Number.isSafeInteger(goal.tokenBudget) && goal.tokenBudget > 0)) {
      return null;
    }
    return goal as unknown as GoalLike;
  }

  /**
   * Read omp's own branch context and arm exactly what it says. An active saved
   * goal comes back paused: omp's \`onThreadResumed\` without a preserved goal is
   * what stops a restart from spending on its own. Runs inside the shared chain
   * so a Plan entry can never read a half-restored goal.
   */
  function restore(): Promise<void> {
    const pending = restoring;
    if (pending !== null) return pending;
    const task = inTransition(async () => {
      const session = rootSession;
      if (session === null) return;
      const id = sessionIdOf(session);
      cancelSettle();
      pendingErrorPause = null;
      continuationTurnInFlight = false;
      const runtime = runtimeOf();
      if (typeof asRecord(runtime)?.clearAccounting === "function") {
        try {
          asRecord(runtime)?.clearAccounting?.();
        } catch {
          /* omp keeps its own accounting; a failed clear is omp's to live with */
        }
      }
      const manager = asRecord(session.sessionManager);
      const build = manager === null ? undefined : manager.buildSessionContext;
      if (typeof build !== "function") {
        broken = "sessionManager.buildSessionContext is not a function";
        return;
      }
      let contextValue: unknown;
      try {
        contextValue = build.call(manager);
      } catch (error) {
        broken = "the session context could not be read: " + String(error);
        return;
      }
      const sessionContext = asRecord(contextValue);
      const mode = sessionContext === null ? null : sessionContext.mode;
      if (mode === "goal" || mode === "goal_paused") {
        const goal = validSavedGoal(asRecord(sessionContext.modeData)?.goal);
        if (goal === null) {
          // Never fabricate a goal and never rewrite the transcript over it.
          broken = "the saved goal in this session's transcript is malformed";
          return;
        }
        if (typeof session.setGoalModeState !== "function") return;
        session.setGoalModeState({ enabled: mode === "goal", mode: "active", goal });
        const resumed = asRecord(runtime)?.onThreadResumed;
        if (typeof resumed === "function") {
          try {
            await Promise.resolve(resumed.call(runtime));
          } catch (error) {
            broken = "the saved goal could not be resumed: " + String(error);
            return;
          }
        }
      } else if (typeof session.setGoalModeState === "function") {
        session.setGoalModeState(undefined);
      }
      pauseReason = null;
      restoredSessionId = id;
      continuation = "idle";
    })
      .catch((error: unknown) => {
        broken = "goal restoration failed: " + String(error);
      })
      .then(() => {
        restoring = null;
        try {
          publish(true);
        } catch {
          /* a restored session still publishes on the next event */
        }
      });
    restoring = task;
    return task;
  }

  // --------------------------------------------------------------- verbs

  function parseArgs(args: string): { sub: string | null; rest: string } {
    const trimmed = args.trim();
    if (trimmed === "") return { sub: null, rest: "" };
    const match = /^(\\S+)(?:\\s+([\\s\\S]*))?$/.exec(trimmed);
    if (match === null) return { sub: null, rest: trimmed };
    const first = match[1].toLowerCase();
    if (SUBCOMMANDS.indexOf(first) >= 0) {
      return { sub: first, rest: match[2] === undefined ? "" : match[2].trim() };
    }
    return { sub: null, rest: trimmed };
  }

  /** The strict budget spelling: a plain positive safe integer, or \`off\`. */
  function parseBudget(raw: string): number | null | "off" {
    const text = raw.trim();
    if (text.toLowerCase() === "off") return "off";
    if (!/^[0-9]+$/.test(text)) return null;
    const value = Number(text);
    return Number.isSafeInteger(value) && value > 0 ? value : null;
  }

  function refuseBusy(request: CommandRequest): boolean {
    if (!busy()) return false;
    settle(request, false, BUSY_REFUSAL);
    return true;
  }

  async function runGoal(request: CommandRequest): Promise<void> {
    const parsed = parseArgs(request.args);
    if (parsed.sub === "show") {
      if (parsed.rest !== "") return settle(request, false, "/goal show takes no arguments.");
      const goal = goalOf(rootSession);
      return settle(request, goal !== null, details(goal));
    }
    if (parsed.sub === "pause") return runPause(request, parsed.rest);
    if (parsed.sub === "resume") return runResume(request, parsed.rest);
    if (parsed.sub === "drop") return runDrop(request, parsed.rest);
    if (parsed.sub === "budget") return runBudget(request, parsed.rest);
    if (parsed.sub === "set") return runSet(request, parsed.rest, true);
    return runPlain(request, parsed.rest);
  }

  /** \`/goal\` bare (menu) and \`/goal <objective>\` (create) share one entry. */
  async function runPlain(request: CommandRequest, rest: string): Promise<void> {
    const goal = goalOf(rootSession);
    if (rest !== "") {
      if (goal === null || goal.id === "") return create(request, rest);
      if (goal.status === "complete") {
        return settle(request, false, "The previous goal is complete. Use /goal set " + rest);
      }
      return settle(
        request,
        false,
        "This session already has a goal (" + goal.status + "): " + goal.objective +
          ". Use /goal set to replace it, /goal resume to resume it, or /goal drop to remove it.",
      );
    }
    if (goal === null || goal.id === "" || goal.status === "dropped") {
      const objective = await askEditor("Goal objective", undefined);
      if (objective === undefined || objective.trim() === "") {
        return settle(request, true, "Goal creation cancelled.");
      }
      return create(request, objective.trim());
    }
    if (goal.status === "complete") {
      // The details are the answer whether or not the offer is taken, so they
      // are reported before anything is asked.
      settle(request, true, "Complete goal:\\n" + details(goal) + "\\nUse /goal set <objective> to start a new goal.");
      const choice = await askSelect("Goal complete: " + brief(goal), ["Set new goal"]);
      if (choice === undefined) return;
      const objective = await askEditor("Goal objective", undefined);
      if (objective === undefined || objective.trim() === "") return;
      return create(request, objective.trim());
    }
    const items = goal.status === "paused"
      ? ["Resume", "Show details", "Adjust budget", "Drop"]
      : ["Show details", "Adjust budget", "Pause", "Drop"];
    const choice = await askSelect(
      goal.status === "paused" ? "Goal paused: " + brief(goal) : "Goal: " + brief(goal) + " (" + goal.status + ")",
      items,
    );
    if (choice === undefined) return settle(request, true, "cancelled");
    if (choice === "Show details") return settle(request, true, details(goalOf(rootSession)));
    if (choice === "Adjust budget") return runBudget(request, "");
    if (choice === "Pause") return runPause(request, "");
    if (choice === "Drop") return runDrop(request, "");
    if (choice === "Resume") return runResume(request, "");
    return settle(request, true, "cancelled");
  }

  function brief(goal: DraftGoal): string {
    return goal.objective.length > 48 ? goal.objective.slice(0, 47) + "\\u2026" : goal.objective;
  }

  /**
   * The reason a finished turn ended badly, or null when it ended cleanly or
   * was interrupted. An interrupt is omp's own to pause on (\`abort\` reaches
   * \`goalRuntime.onTaskAborted\`), so the bridge never re-pauses or restarts it.
   */
  function terminalError(event: Record<string, unknown>): string | null {
    if (!Array.isArray(event.messages)) return null;
    const messages = event.messages as unknown[];
    for (let i = messages.length - 1; i >= 0; i--) {
      const message = asRecord(messages[i]);
      if (message === null || message.role !== "assistant") continue;
      if (message.stopReason === "aborted") return null;
      if (message.stopReason !== "error") return null;
      const detail = isString(message.errorMessage) ? ": " + message.errorMessage : "";
      return "The goal turn ended in an error" + detail;
    }
    return null;
  }

  async function runSet(request: CommandRequest, rest: string, fromSet: boolean): Promise<void> {
    const goal = goalOf(rootSession);
    if (goal !== null && goal.status === "paused") {
      return settle(request, false, "Resume the current goal first, or drop it before setting a new objective.");
    }
    let objective = rest;
    if (objective === "") {
      const answered = await askEditor("Goal objective", undefined);
      if (answered === undefined || answered.trim() === "") {
        return settle(request, true, "cancelled");
      }
      objective = answered.trim();
    }
    if (goal !== null && armed(goal)) return replace(request, objective);
    void fromSet;
    return create(request, objective);
  }

  async function create(request: CommandRequest, objective: string): Promise<void> {
    if (objective.length > OBJECTIVE_LIMIT) {
      return settle(request, false, "Goal objective exceeds " + OBJECTIVE_LIMIT + " characters.");
    }
    if (refuseBusy(request)) return;
    const reason = brokenReason();
    if (reason !== null) return settle(request, false, "Goal commands are unavailable: " + reason);
    const refusal = refusalFor("activate", goalOf(rootSession));
    if (refusal !== null) return settle(request, false, refusal);
    const toolProblem = await prepareGoalTool();
    if (toolProblem !== null) return settle(request, false, toolProblem);
    const captured = context();
    let failure: string | null = null;
    try {
      await serialize(async () => {
        const again = refusalFor("activate", goalOf(rootSession));
        if (again !== null) {
          failure = again;
          return;
        }
        const runtime = runtimeOf();
        const make = runtime === null ? undefined : runtime.createGoal;
        if (typeof make !== "function") {
          failure = "goalRuntime.createGoal is not a function";
          return;
        }
        const state = await Promise.resolve(make.call(runtime, { objective }));
        if (asRecord(asRecord(state)?.goal) === null) failure = "omp created no goal";
      });
    } catch (error) {
      failure = String(error);
    }
    const stale = sessionStale(captured);
    if (stale !== null) return settle(request, false, stale);
    pauseReason = null;
    settle(request, true, "Goal set: " + objective);
    startWork(START_TYPE, objective);
  }

  async function replace(request: CommandRequest, objective: string): Promise<void> {
    if (objective.length > OBJECTIVE_LIMIT) {
      return settle(request, false, "Goal objective exceeds " + OBJECTIVE_LIMIT + " characters.");
    }
    if (refuseBusy(request)) return;
    const refusal = refusalFor("activate", goalOf(rootSession));
    if (refusal !== null) return settle(request, false, refusal);
    const toolProblem = await prepareGoalTool();
    if (toolProblem !== null) return settle(request, false, toolProblem);
    const captured = context();
    let failure: string | null = null;
    try {
      await serialize(async () => {
        const runtime = runtimeOf();
        const swap = runtime === null ? undefined : runtime.replaceGoal;
        if (typeof swap !== "function") {
          failure = "goalRuntime.replaceGoal is not a function";
          return;
        }
        const state = await Promise.resolve(swap.call(runtime, { objective }));
        if (asRecord(asRecord(state)?.goal) === null) failure = "omp replaced no goal";
      });
    } catch (error) {
      failure = String(error);
    }
    if (failure !== null) return settle(request, false, failure);
    const stale = sessionStale(captured);
    if (stale !== null) return settle(request, false, stale);
    pauseReason = null;
    settle(request, true, "Goal replaced: " + objective);
    startWork(START_TYPE, objective);
  }

  async function runPause(request: CommandRequest, rest: string): Promise<void> {
    if (rest !== "") return settle(request, false, "/goal pause takes no arguments.");
    const goal = goalOf(rootSession);
    if (goal === null || goal.id === "") return settle(request, true, "There is no goal to pause.");
    if (goal.status === "paused") return settle(request, true, "The goal is already paused.");
    if (goal.status === "complete") return settle(request, true, "The goal is already complete.");
    cancelSettle();
    const captured = context();
    let failure: string | null = null;
    await serialize(async () => {
      const runtime = runtimeOf();
      const pause = runtime === null ? undefined : runtime.pauseGoal;
      if (typeof pause !== "function") {
        failure = "goalRuntime.pauseGoal is not a function";
        return;
      }
      await Promise.resolve(pause.call(runtime));
    }).catch((error: unknown) => {
      failure = String(error);
    });
    if (failure !== null) return settle(request, false, failure);
    const stale = stillCurrent(captured);
    if (stale !== null) return settle(request, false, stale);
    pauseReason = "Paused by /goal pause.";
    settle(request, true, "Goal paused. An in-progress turn may still finish; no further turns are started.");
  }

  async function runResume(request: CommandRequest, rest: string): Promise<void> {
    if (rest !== "") return settle(request, false, "/goal resume takes no arguments.");
    const goal = goalOf(rootSession);
    if (goal === null || goal.id === "") return settle(request, false, "There is no paused goal to resume.");
    if (goal.status === "active") return settle(request, true, "The goal is already active.");
    if (goal.status === "complete") return settle(request, false, "The goal is already complete.");
    if (goal.status !== "paused") return settle(request, false, "Only a paused goal can be resumed.");
    if (refuseBusy(request, "the goal")) return;
    if (goal.tokenBudget !== null && goal.tokensUsed >= goal.tokenBudget) {
      return settle(
        request,
        false,
        "This goal has used " + goal.tokensUsed + " of its " + goal.tokenBudget +
          " token budget. Raise or clear the budget with /goal budget before resuming.",
      );
    }
    const refusal = refusalFor("activate", goal);
    if (refusal !== null) return settle(request, false, refusal);
    const toolProblem = await prepareGoalTool();
    if (toolProblem !== null) return settle(request, false, toolProblem);
    const captured = context();
    let failure: string | null = null;
    await serialize(async () => {
      const again = refusalFor("activate", goalOf(rootSession));
      if (again !== null) {
        failure = again;
        return;
      }
      const runtime = runtimeOf();
      const resume = runtime === null ? undefined : runtime.resumeGoal;
      if (typeof resume !== "function") {
        failure = "goalRuntime.resumeGoal is not a function";
        return;
      }
      await Promise.resolve(resume.call(runtime));
    }).catch((error: unknown) => {
      failure = String(error);
    });
    if (failure !== null) return settle(request, false, failure);
    const stale = stillCurrent(captured);
    if (stale !== null) return settle(request, false, stale);
    pauseReason = null;
    settle(request, true, "Goal resumed.");
    scheduleContinuation();
  }

  async function runDrop(request: CommandRequest, rest: string): Promise<void> {
    if (rest !== "") return settle(request, false, "/goal drop takes no arguments.");
    const goal = goalOf(rootSession);
    if (goal === null || goal.id === "") return settle(request, true, "There is no goal to drop.");
    const captured = context();
    const confirmed = await askConfirm(
      "Drop goal?",
      "This removes the goal record. Accumulated usage stays in the session log.",
    );
    if (!confirmed) return settle(request, true, "cancelled");
    const stale = stillCurrent(captured);
    if (stale !== null) return settle(request, false, stale);
    cancelSettle();
    let failure: string | null = null;
    await serialize(async () => {
      const runtime = runtimeOf();
      const drop = runtime === null ? undefined : runtime.dropGoal;
      if (typeof drop !== "function") {
        failure = "goalRuntime.dropGoal is not a function";
        return;
      }
      await Promise.resolve(drop.call(runtime));
    }).catch((error: unknown) => {
      failure = String(error);
    });
    if (failure !== null) return settle(request, false, failure);
    pauseReason = null;
    settle(request, true, "Goal dropped. A running turn is not aborted; it finishes on its own.");
  }

  async function runBudget(request: CommandRequest, rest: string): Promise<void> {
    const goal = goalOf(rootSession);
    if (!unfinished(goal)) {
      return settle(request, false, "There is no unfinished goal to budget.");
    }
    let raw = rest;
    if (raw === "") {
      const captured = context();
      const prefill = goal !== null && goal.tokenBudget !== null ? String(goal.tokenBudget) : undefined;
      const answered = await askInput("Goal budget (a positive token count, or off)", prefill);
      if (answered === undefined || answered.trim() === "") return settle(request, true, "cancelled");
      const stale = stillCurrent(captured);
      if (stale !== null) return settle(request, false, stale);
      raw = answered.trim();
    }
    const parsed = parseBudget(raw);
    if (parsed === null) {
      return settle(request, false, "Goal budget must be a positive integer or \`off\`.");
    }
    const next = parsed === "off" ? undefined : parsed;
    let failure: string | null = null;
    await serialize(async () => {
      const runtime = runtimeOf();
      const mutate = runtime === null ? undefined : runtime.onBudgetMutated;
      if (typeof mutate !== "function") {
        failure = "goalRuntime.onBudgetMutated is not a function";
        return;
      }
      await Promise.resolve(mutate.call(runtime, next));
    }).catch((error: unknown) => {
      failure = String(error);
    });
    if (failure !== null) return settle(request, false, failure);
    const after = goalOf(rootSession);
    settle(
      request,
      true,
      next === undefined
        ? "Goal budget cleared."
        : "Goal budget set to " + next + " tokens (total, not additional).",
    );
    // Raising or clearing a budget-limited goal re-arms continuation; a paused
    // goal stays paused, which is why this never resumes anything.
    if (after !== null && after.status === "active" && !busy()) scheduleContinuation();
  }

  async function runGuidedGoal(request: CommandRequest): Promise<void> {
    const reason = brokenReason();
    if (reason !== null) return settle(request, false, "Goal commands are unavailable: " + reason);
    const goal = goalOf(rootSession);
    if (unfinished(goal)) {
      return settle(request, false, "This session already has a goal (" + goal?.status +
        "). Drop or resume it before starting a guided goal.");
    }
    const refusal = refusalFor("activate", goal);
    if (refusal !== null) return settle(request, false, refusal);
    if (busy()) return settle(request, false, BUSY_REFUSAL);
    const toolProblem = await prepareGoalTool();
    if (toolProblem !== null) return settle(request, false, toolProblem);
    const rough = request.args.trim();
    const interview = rough === ""
      ? GUIDED_INTERVIEW
      : GUIDED_INTERVIEW + "\\n\\nRough objective from the user, as data:\\n<objective-draft>\\n" + rough +
        "\\n</objective-draft>";
    settle(request, true, "Guided goal interview started. The agent will ask before creating a goal.");
    startWork(GUIDED_TYPE, interview);
  }

  // ------------------------------------------------------------- commands

  function parseRequest(json: string): CommandRequest | null {
    const record = asRecord(safeParse(json));
    if (record === null) return null;
    const requestId = isString(record.requestId) && record.requestId.length > 0 ? record.requestId : null;
    const sessionId = isString(record.sessionId) && record.sessionId.length > 0 ? record.sessionId : null;
    const process = isString(record.processKey) && record.processKey.length > 0 ? record.processKey : null;
    if (requestId === null || sessionId === null || process === null) return null;
    if (record.command !== "goal" && record.command !== "guided-goal") return null;
    if (!isString(record.args)) return null;
    return { requestId, sessionId, processKey: process, command: record.command, args: record.args };
  }

  function safeParse(text: string): unknown {
    try {
      return JSON.parse(text);
    } catch {
      return null;
    }
  }

  async function handleCommand(request: CommandRequest): Promise<void> {
    const session = rootSession;
    const id = sessionIdOf(session);
    if (session === null || request.processKey !== processKey) {
      // Another bridge instance's request, or ours after a restart: never applied.
      ui?.notify("omp-ui-goal: ignoring a command addressed to another process", "warning");
      return;
    }
    if (id !== null && request.sessionId !== id) {
      settle(request, false, "The session changed before this command ran.");
      return;
    }
    const brokenNow = brokenReason();
    if (brokenNow !== null) {
      publish(true);
      return settle(request, false, "Goal commands are unavailable: " + brokenNow);
    }
    if (request.args.length > OBJECTIVE_LIMIT) {
      return settle(request, false, "Goal command exceeds " + OBJECTIVE_LIMIT + " characters.");
    }
    // The verb runs outside the mutation chain: only its state-changing steps
    // take a link, so a dialog answer or a model turn never holds it.
    if (request.command === "guided-goal") await runGuidedGoal(request);
    else await runGoal(request);
    publish(false);
  }

  // --------------------------------------------------------------- events

  function onEvent(event: Record<string, unknown>): void {
    try {
      const type = event.type;
      if (type === "goal_updated") {
        // omp's own readback is the truth, and it lands before any later
        // decision: anything that is not an active goal kills the timer now,
        // so a model-issued complete or drop is never followed by a goal turn.
        const goal = goalOf(rootSession);
        if (goal === null || goal.status !== "active") cancelSettle();
        if (armed(goal)) idleCheckPending = true;
        publish(true);
        return;
      }
      if (type === "agent_start") {
        turnHadToolExecution = false;
        cancelSettle();
        idleCheckPending = false;
        return;
      }
      if (type === "tool_execution_end") {
        turnHadToolExecution = true;
        return;
      }
      if (type === "agent_end") {
        const willContinue = event.willContinue;
        if (continuationTurnInFlight && !turnHadToolExecution &&
          armed(goalOf(rootSession)) && willContinue !== true) {
          pendingErrorPause = NO_PROGRESS_PAUSE;
        }
        const failure = terminalError(event);
        if (failure !== null) pendingErrorPause = failure;
        continuationTurnInFlight = false;
        turnHadToolExecution = false;
        if (willContinue !== true) {
          idleCheckPending = true;
          if (armed(goalOf(rootSession))) scheduleContinuation();
          else cancelSettle();
        }
        publish(false);
        return;
      }
    } catch {
      /* a bridge event handler must never take down the session's stream */
    }
  }

  function bindRoot(session: SessionLike): void {
    if (rootSession !== null) return;
    rootSession = session;
    generation += 1;
    admitRuntime(session);
    bindAbort(session);
    bindShutdown(session);
    const subscribe = session.subscribe;
    if (typeof subscribe === "function") {
      try {
        const off = subscribe.call(session, (event) => onEvent(asRecord(event) ?? {}));
        if (typeof off === "function") unsubscribe.push(off);
      } catch {
        /* an unsubscribable session still answers commands */
      }
    }
    const runState = session.subscribeRunState;
    if (typeof runState === "function") {
      try {
        const off = runState.call(session, () => {
          // Maintenance (compaction, deferred flushes) settles here: retry the
          // pending idle check rather than dispatching blind.
          if (idleCheckPending || continuation === "scheduled") evaluateIdle(false);
        });
        if (typeof off === "function") unsubscribe.push(off);
      } catch {
        /* run-state observation is a nicety; agent_end still drives the loop */
      }
    }
    const sessionChange = session.registerSessionChangeCallback;
    if (typeof sessionChange === "function") {
      try {
        const off = sessionChange.call(session, () => {
          // /new and /branch: the previous generation is gone, so nothing of it
          // may survive into the next session's goal state.
          generation += 1;
          cancelSettle();
          pendingErrorPause = null;
          continuationTurnInFlight = false;
          pauseReason = null;
          lastResult = null;
          lastResultSessionId = null;
          restoredSessionId = null;
          void restore();
        });
        if (typeof off === "function") unsubscribe.push(off);
      } catch {
        /* an older runtime keeps restoration on the arm command */
      }
    }
  }

  /** Stop invalidates the pending timer synchronously, before omp aborts. */
  function bindAbort(session: SessionLike): void {
    const target = session as unknown as Record<string, unknown>;
    const original = target.abort;
    if (typeof original !== "function") return;
    const call = original as (...args: unknown[]) => unknown;
    try {
      target.abort = function (this: unknown, ...args: unknown[]): unknown {
        try {
          if (this === session) {
            cancelSettle();
            continuationTurnInFlight = false;
            idleCheckPending = false;
          }
        } catch {
          /* abort bookkeeping never blocks omp's abort */
        }
        return call.apply(this, args);
      };
    } catch {
      /* a sealed abort hook leaves omp's own pause-on-abort in charge */
    }
  }

  /** Same root-shutdown discipline the capabilities bridge uses. */
  function bindShutdown(session: SessionLike): void {
    const target = session as unknown as Record<string, unknown>;
    for (const method of ["dispose", "disconnect", "cleanup", "shutdown"]) {
      try {
        const original = target[method];
        if (typeof original !== "function") continue;
        const call = original as (...args: unknown[]) => unknown;
        target[method] = function (this: unknown, ...args: unknown[]): unknown {
          const result = call.apply(this, args);
          try {
            if (this === session) teardown();
          } catch {
            /* shutdown bookkeeping never breaks the session */
          }
          return result;
        };
      } catch {
        /* a sealed or throwing shutdown hook is not our session's problem */
      }
    }
  }

  function teardown(): void {
    cancelSettle();
    for (const off of unsubscribe.splice(0)) {
      try {
        off();
      } catch {
        /* a runtime that refuses unsubscribe is leaving anyway */
      }
    }
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype !== undefined && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: SessionLike, ...args: unknown[]) => unknown;
      prototype.prompt = function (this: SessionLike, ...args: unknown[]): unknown {
        const isRoot = rootSession === null || this === rootSession;
        const text = isString(args[0]) ? (args[0] as string).trim() : null;
        const bridge = text !== null && (text === ARM_MESSAGE ||
          text.startsWith(ARM_MESSAGE + " " + ARG_PREFIX));
        const invoke = (): unknown => call.apply(this, args);
        if (!isRoot) return invoke();
        bindRoot(this);
        // A user prompt wins the settle window outright; the bridge's own
        // arm/command prompts are not user work and must not cancel it.
        if (!bridge) cancelSettle();
        const pending = restoring;
        if (pending === null || bridge) return invoke();
        // Ordinary prompting waits for restoration so the model never sees a
        // half-restored goal, and a Plan entry never checks goals before it.
        return pending.then(invoke, invoke);
      };
    }
  } catch (error) {
    broken = "could not hook AgentSession.prompt: " + String(error);
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui goal mode control",
    handler: async (args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      const trimmed = isString(args) ? args.trim() : "";
      if (trimmed === "") {
        // The arm arrives as a root prompt, so the wrapper has already bound the
        // root; with no prompt seen yet there is nothing to restore and
        // publishing reports that honestly.
        const id = sessionIdOf(rootSession);
        if (id !== null && id !== restoredSessionId) await restore();
        publish(true);
        return;
      }
      if (!trimmed.startsWith(ARG_PREFIX)) {
        throw new Error("omp-ui-goal: unsupported command args");
      }
      const request = parseRequest(trimmed.slice(ARG_PREFIX.length));
      if (request === null) {
        throw new Error("omp-ui-goal: malformed goal command request");
      }
      await handleCommand(request);
    },
  });
}
`;
}

/**
 * Writes the goal bridge into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an older
 * omp-ui build can never outvote the current wire contract.
 */
export function writeGoalExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, goalExtensionPath(lineageDir), extensionSource());
}
