import * as path from "node:path";
import { writeLineageArtifact } from "./lineage-artifact";
import { generatedRootBindingSource } from "./generated-extension-source";

/**
 * The agent learns where to file decisions and lessons (#766, ADR-0048) from
 * this generated extension: the spawner resolves the project's Knowledge home
 * and arms the extension whenever a vault is registered: the write part when
 * the home touches a vault, and the Day write-up part (#768) for every native
 * session, with
 * `/omp-ui-knowledge-vault set <json>` in `initialCommands`. The extension
 * delivers ONE hidden custom message (`display: false`) carrying that guidance
 * to the root session, re-queued after a compaction, branch, or session switch
 * so a rebuilt context still carries it. Same shape as browser-pane-extension.ts.
 */

export const KNOWLEDGE_VAULT_COMMAND = "omp-ui-knowledge-vault";
export const KNOWLEDGE_VAULT_CUSTOM_TYPE = "omp-ui:knowledge-vault";
/** The generated command accepts 1 to this many UTF-16 units of guidance. */
export const KNOWLEDGE_VAULT_TEXT_MAX = 4_000;
/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-knowledge-vault.ts";

export function knowledgeVaultExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/** Rewritten on every spawn, like every generated bridge. */
export function writeKnowledgeVaultExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, knowledgeVaultExtensionPath(lineageDir), extensionSource());
}

/** The hidden slash command the spawner pushes through initialCommands. */
export function knowledgeVaultArmMessage(text: string): string {
  return `/${KNOWLEDGE_VAULT_COMMAND} set ${JSON.stringify({ text })}`;
}

const BOTH_SUFFIX =
  "This project also keeps decisions in its repo docs/: write the full note there with your file tools, then create a short vault note with the title, a one-line gist, and the repo path.";

const DAY_WRITE_UP =
  'If the user asks for a note of everything worked on today, read omp-ui://sessions, then omp-ui://sessions/<id>/summary for each session it lists, then write one Day write-up yourself in this session with omp-ui_vault_create, project false, titled "<date> Day Write-up" with the date from the index heading. Subagents can read those resources but cannot call the vault tools. If the note already exists, read it and replace its body with omp-ui_vault_edit.';

/** Null when there is nothing to say: no vault-touching home and no day part. No sentence names plan mode (#757). */
export function knowledgeVaultGuidance(input: {
  write: { vault: string; both: boolean } | null;
  dayWriteUp: boolean;
}): string | null {
  const parts: string[] = [];
  if (input.write !== null) {
    const write = `omp-ui connected this session to the user's Obsidian vault "${input.write.vault}". The omp-ui_vault_* tools read the whole vault and write only inside its omp-ui home folder. Search before you write, to skip duplicates and to find the user's own notes worth linking. Write a vault note when a decision settles, at that moment, not at the end of the session. Also write one whenever you learn a lesson worth keeping: a wrong assumption, a trap, a fix that took several tries. Write-ups, and anything the user asks you to record, belong there too. One note per topic: a Title Case title and a plain markdown body; omp-ui adds the frontmatter and the index link. Link the user's notes as [[Title]] and omp-ui notes with the link the tool returns. Summarize and link the user's own notes; quote them only when the user asks, and only into vault notes. Never write secrets, tokens, or raw transcripts.`;
    parts.push(input.write.both ? `${write} ${BOTH_SUFFIX}` : write);
  }
  if (input.dayWriteUp) parts.push(DAY_WRITE_UP);
  return parts.length === 0 ? null : parts.join("\n\n");
}

/**
 * The generated source imports nothing; the command name, custom type, and
 * length cap are interpolated from this module so the two sides of the channel
 * can never drift.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.

const COMMAND = ${JSON.stringify(KNOWLEDGE_VAULT_COMMAND)};
const CUSTOM_TYPE = ${JSON.stringify(KNOWLEDGE_VAULT_CUSTOM_TYPE)};
const TEXT_MAX = ${KNOWLEDGE_VAULT_TEXT_MAX};

/** The slice of omp's AgentSession this extension drives. */
interface VaultSession {
  isStreaming?: boolean;
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface VaultUi {
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface VaultExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: VaultUi }) => Promise<void>;
    },
  ) => void;
  on?: (event: string, handler: (...args: unknown[]) => void) => void;
}

export default function (pi: VaultExtensionApi) {
  // The first prompting AgentSession. omp dispatches slash commands through
  // prompt, so the arming command itself binds the root; no later prompt —
  // descendant or not — may retarget it (ADR-0008 discipline).
  let rootSession: VaultSession | null = null;
  /** The guidance the spawner armed; null until the first set. */
  let text: string | null = null;
  /** The guidance the root has been told; null until delivered or after a context rebuild. */
  let delivered: string | null = null;
  let warnedUnavailable = false;
  let ui: VaultUi | null = null;
  ${generatedRootBindingSource("VaultSession")}

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: VaultSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: VaultSession, ...args: unknown[]): unknown {
        captureRoot(this);
        return call.apply(this, args);
      };
    }
  } catch {
    // Without the hook there is no root to deliver to; deliver() warns once.
  }

  /**
   * Sends the hidden guidance to the root. A rejection leaves the delivered
   * text unchanged so the next set or session event retries.
   */
  async function deliver(): Promise<void> {
    const active = rootSession;
    const target = text;
    if (target === null) return;
    if (!active || typeof active.sendCustomMessage !== "function") {
      if (!warnedUnavailable) {
        warnedUnavailable = true;
        ui?.notify("omp-ui knowledge vault: this omp cannot carry the guidance to the agent", "warning");
      }
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: CUSTOM_TYPE,
          content: target,
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
      delivered = target;
    } catch {
      // Retried by the next set or session event.
    }
  }

  /** Strict parse of the set payload: exactly { text } holding 1 to TEXT_MAX units. */
  function parseSetArgs(args: string): string | null {
    let parsed: unknown;
    try {
      parsed = JSON.parse(args);
    } catch {
      return null;
    }
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null;
    if (!("text" in parsed) || Object.keys(parsed).length !== 1) return null;
    const value: unknown = parsed.text;
    if (typeof value !== "string" || value.length < 1 || value.length > TEXT_MAX) return null;
    return value;
  }

  // Two quick sets must not interleave their deliveries.
  let chain: Promise<void> = Promise.resolve();
  function serialize(work: () => Promise<void>): Promise<void> {
    const next = chain.then(work, work);
    chain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui knowledge vault guidance",
    handler: (args: string, ctx: { ui: VaultUi }) =>
      serialize(async () => {
        ui = ctx.ui;
        const trimmed = args.trim();
        if (!trimmed.startsWith("set ")) {
          ctx.ui.notify("omp-ui knowledge vault: unknown command", "warning");
          return;
        }
        const next = parseSetArgs(trimmed.slice(4));
        if (next === null) {
          ctx.ui.notify("omp-ui knowledge vault: malformed guidance", "warning");
          return;
        }
        text = next;
        if (text !== delivered) await deliver();
      }),
  });

  // A compaction, branch, or switch rebuilds the context the hidden message
  // lived in; queue it again so the agent keeps its guidance.
  if (typeof pi.on === "function") {
    for (const eventName of ["session_compact", "session_branch", "session_switch"]) {
      pi.on(eventName, () => {
        delivered = null;
        if (text !== null) void serialize(deliver);
      });
    }
  }
}
`;
}
