import * as path from "node:path";
import { LIMITS_COMMAND, LIMITS_STATUS_KEY } from "./limits";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  generatedAsRecordSource,
  generatedRootBindingSource,
  generatedSessionIdSource,
} from "./generated-extension-source";

/**
 * omp's rpc surface has no rate-window state (issue #673): no rpc command
 * returns rate windows and no outbound frame carries them — what
 * `get_state.usageLimit` (omp ≥ 18.6.3) reports since issue #777 is the
 * account STAGE, not windows, and the HUD renders it separately from session
 * state, so this bridge and that chip are complementary, not redundant. The
 * public method on the live `AgentSession` does —
 * `fetchUsageReports()` is what `/usage` and the TUI status line use. This
 * generated extension patches `AgentSession.prototype.prompt`, binds the
 * first prompt as the root session, and publishes the root provider's rate
 * windows over `ui.setStatus`.
 *
 * Fetch discipline mirrors omp's own status-line backoff (18.4.0 reduced
 * usage-endpoint probing deliberately): the bridge fetches on command and at
 * prompt completion only when the last fetch is at least five minutes old.
 * It never runs a fast timer, and every failure publishes an
 * `available: false` snapshot with the reason instead of throwing into the
 * agent. A pre-18.4 omp without `fetchUsageReports` degrades to an
 * unavailable snapshot the HUD renders as nothing.
 *
 * Field spellings here (`amount.usedFraction`, `window.resetsAt`,
 * `scope.windowId`, `bucket.utilization`, `resetCredits.bankedCount`) are
 * the shapes omp's own `/usage` formatter reads; every hop is a guarded
 * read, so an older omp that reports nothing yields an empty snapshot
 * rather than a crash.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-limits.ts";

export function limitsExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source is generated per lineage so its wire constants cannot
 * drift from the renderer.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(LIMITS_STATUS_KEY)};
const COMMAND = ${JSON.stringify(LIMITS_COMMAND)};
/** omp's own status-line backoff: usage endpoints get probed at most this often. */
const FETCH_COOLDOWN_MS = 5 * 60 * 1000;

${generatedAsRecordSource()}

interface LimitsSession {
  sessionManager?: { getSessionId?: () => string | undefined };
  model?: unknown;
  oauth?: unknown;
  fetchUsageReports?: (signal?: unknown) => Promise<unknown> | unknown;
}

interface LimitsUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: LimitsUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  let rootSession: LimitsSession | null = null;
  ${generatedSessionIdSource("LimitsSession")}
  ${generatedRootBindingSource("LimitsSession")}
  let ui: LimitsUi | null = null;
  let lastFetchAtMs = 0;
  let fetching = false;

  function publishUnavailable(reason: string): void {
    ui?.setStatus(STATUS_KEY, JSON.stringify({ available: false, unavailable: reason }));
  }

  function finiteOrNull(value: unknown): number | null {
    return typeof value === "number" && Number.isFinite(value) ? value : null;
  }

  /**
   * The report for the session's provider. When the same provider reports
   * several stored accounts, prefer the one matching the resolved oauth
   * identity; otherwise the freshest, otherwise the first. The per-account
   * matrix stays /usage's job.
   */
  function selectReport(reports: unknown[], provider: string): Record<string, unknown> | null {
    const matches: Record<string, unknown>[] = [];
    for (const value of reports) {
      const report = asRecord(value);
      if (report !== null && report.provider === provider) matches.push(report);
    }
    if (matches.length === 0) return null;
    if (matches.length === 1) return matches[0];
    let identity: string | null = null;
    try {
      const oauth = asRecord(rootSession?.oauth);
      const identityFn = oauth?.identity;
      if (oauth !== null && typeof identityFn === "function") {
        const resolved = (identityFn as (p: string, s: string | null) => unknown).call(
          oauth,
          provider,
          sessionIdOf(rootSession),
        );
        if (typeof resolved === "string" && resolved !== "") identity = resolved;
      }
    } catch {
      /* identity is a preference, never a requirement */
    }
    if (identity !== null) {
      for (const report of matches) {
        for (const key of ["account", "email", "identity"]) {
          if (report[key] === identity) return report;
        }
      }
    }
    let best = matches[0];
    let bestAt = -Infinity;
    for (const report of matches) {
      const at =
        finiteOrNull(report.fetchedAtMs) ??
        finiteOrNull(report.updatedAtMs) ??
        finiteOrNull(report.fetchedAt) ??
        0;
      if (at > bestAt) {
        bestAt = at;
        best = report;
      }
    }
    return best;
  }

  function windowsOf(report: Record<string, unknown> | null): unknown[] {
    if (report === null) return [];
    const limits = Array.isArray(report.limits) ? report.limits : [];
    const windows: unknown[] = [];
    for (const value of limits) {
      const limit = asRecord(value);
      if (limit === null || typeof limit.label !== "string" || limit.label === "") continue;
      const amount = asRecord(limit.amount);
      const bucket = asRecord(limit.bucket);
      const window = asRecord(limit.window);
      const usedFraction = finiteOrNull(amount?.usedFraction);
      const utilization = finiteOrNull(bucket?.utilization);
      const percent = usedFraction !== null ? usedFraction * 100 : utilization;
      const resetsAtMs = finiteOrNull(window?.resetsAt);
      // omp's own OK() rule: a window must carry a percent or a reset time.
      if (percent === null && resetsAtMs === null) continue;
      const scope = asRecord(limit.scope);
      const id = typeof scope?.windowId === "string" && scope.windowId !== "" ? scope.windowId : limit.label;
      windows.push({ id, label: limit.label, percent, resetsAtMs });
    }
    return windows;
  }

  async function fetchAndPublish(): Promise<void> {
    if (!ui) return;
    const root = rootSession;
    if (!root) {
      publishUnavailable("no active omp session");
      return;
    }
    if (typeof root.fetchUsageReports !== "function") {
      publishUnavailable("this omp build does not report provider usage");
      return;
    }
    fetching = true;
    lastFetchAtMs = Date.now();
    try {
      const fetched = await root.fetchUsageReports();
      const reports = Array.isArray(fetched) ? fetched : null;
      if (reports === null) {
        publishUnavailable("provider usage reports are unreadable");
        return;
      }
      const model = asRecord(root.model);
      const provider = typeof model?.provider === "string" ? model.provider : null;
      const report = provider === null ? null : selectReport(reports, provider);
      const resetCredits = asRecord(report?.resetCredits);
      const banked = finiteOrNull(resetCredits?.bankedCount);
      ui.setStatus(
        STATUS_KEY,
        JSON.stringify({
          available: true,
          provider,
          windows: windowsOf(report),
          bankedResets: banked !== null && banked > 0 ? Math.floor(banked) : 0,
          fetchedAtMs: lastFetchAtMs,
        }),
      );
    } catch (err) {
      publishUnavailable("provider usage fetch failed: " + String(err));
    } finally {
      fetching = false;
    }
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      publishUnavailable("AgentSession.prototype.prompt is not a function");
    } else {
      const call = originalPrompt as (this: LimitsSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: LimitsSession, ...args: unknown[]): unknown {
        captureRoot(this);
        const result = call.apply(this, args);
        const tail =
          result && typeof (result as Promise<unknown>).then === "function"
            ? (result as Promise<unknown>).then
            : null;
        const atEnd = (): void => {
          try {
            // Status-line backoff: turn ends only re-probe past the cooldown.
            if (!fetching && Date.now() - lastFetchAtMs >= FETCH_COOLDOWN_MS) void fetchAndPublish();
          } catch {
            /* quota reporting must never take down user work */
          }
        };
        if (tail) (tail.call(result, atEnd, atEnd));
        else atEnd();
        return result;
      };
    }
  } catch (err) {
    publishUnavailable("could not hook AgentSession: " + String(err));
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui provider rate-window snapshot",
    handler: async (_args: string, ctx: { ui: LimitsUi }) => {
      ui = ctx.ui;
      // The explicit pull bypasses the cooldown; auto-fetches never do.
      if (!fetching) await fetchAndPublish();
      else if (rootSession === null) publishUnavailable("no active omp session");
    },
  });
}
`;
}

/**
 * Writes the limits extension into the lineage dir and returns its path, to
 * be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeLimitsExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, limitsExtensionPath(lineageDir), extensionSource());
}
