import * as fs from "node:fs";
import * as path from "node:path";
import {
  MCP_CONNECTION_STATUS_CHANNEL,
  MCP_RUNTIME_STATUS_COMMAND,
  MCP_RUNTIME_STATUS_KEY,
} from "./mcp-status";

/** The generated bridge lives and dies with its lineage. */
const EXTENSION_NAME = "omp-ui-mcp-status.ts";

export function mcpStatusExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const EVENT_CHANNEL = ${JSON.stringify(MCP_CONNECTION_STATUS_CHANNEL)};
const STATUS_KEY = ${JSON.stringify(MCP_RUNTIME_STATUS_KEY)};
const COMMAND = ${JSON.stringify(MCP_RUNTIME_STATUS_COMMAND)};
const AUTH_MARKER = /(?:^|\\W)(?:401|403|oauth|unauthorized|forbidden|authentication|authorization|credential|token)(?:$|\\W)/i;

interface RuntimeFailure {
  serverName: string;
  kind: "auth" | "connection";
}

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  events?: { on?: (channel: string, handler: (event: unknown) => void) => unknown };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  const pending = new Set<string>();
  const connected = new Set<string>();
  const failed = new Map<string, RuntimeFailure>();
  let ui: StatusUi | null = null;

  function displayName(value: string): string {
    return value.replace(/[\\u0000-\\u001f\\u007f-\\u009f]/g, " ").slice(0, 160);
  }

  function publish(): void {
    if (!ui) return;
    ui.setStatus(STATUS_KEY, JSON.stringify({
      pendingServers: [...pending],
      connectedServers: [...connected],
      failedServers: [...failed.values()],
    }));
  }

  function validStringArray(value: unknown): value is string[] {
    return Array.isArray(value) && value.every((item) => typeof item === "string");
  }

  function receive(event: unknown): void {
    if (event === null || typeof event !== "object" || Array.isArray(event)) return;
    const value = event as Record<string, unknown>;
    if (value.type === "connecting") {
      if (!validStringArray(value.serverNames)) return;
      pending.clear();
      connected.clear();
      failed.clear();
      for (const rawName of value.serverNames) pending.add(displayName(rawName));
      publish();
      return;
    }
    if (value.type === "connected") {
      if (typeof value.serverName !== "string") return;
      const serverName = displayName(value.serverName);
      pending.delete(serverName);
      failed.delete(serverName);
      connected.add(serverName);
      publish();
      return;
    }
    if (value.type === "failed") {
      if (typeof value.serverName !== "string" || typeof value.error !== "string") return;
      if (value.sourcePath !== undefined && typeof value.sourcePath !== "string") return;
      const serverName = displayName(value.serverName);
      pending.delete(serverName);
      connected.delete(serverName);
      failed.set(serverName, {
        serverName,
        kind: AUTH_MARKER.test(value.error) ? "auth" : "connection",
      });
      publish();
    }
  }

  try {
    if (typeof pi.events?.on === "function") pi.events.on(EVENT_CHANNEL, receive);
  } catch {
    // Missing or broken event buses degrade to an empty snapshot.
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui MCP runtime status",
    handler: async (_args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      publish();
    },
  });
}
`;
}

/** Writes a fresh status bridge and returns the path passed to omp as `-e`. */
export function writeMcpStatusExtension(lineageDir: string): string {
  const file = mcpStatusExtensionPath(lineageDir);
  fs.mkdirSync(lineageDir, { recursive: true });
  fs.writeFileSync(file, extensionSource(), "utf8");
  return file;
}
