import * as fs from "node:fs";
import * as path from "node:path";
import {
  PLAN_COMMAND,
  PLAN_EXECUTE,
  PLAN_REFINE,
  PLAN_REVIEW_SENTINEL,
  PLAN_STATUS_KEY,
} from "./plan";

/**
 * omp's plan mode has no rpc surface (verified against v17.1.8): the
 * `RpcCommand` union carries no plan variant, `get_state` reports no mode,
 * `/plan` defines only `handleTui` so rpc-ui falls through and sends it to the
 * model as literal text, and `plan.defaultOnStartup` is read by
 * `InteractiveMode`/`print-mode` only. `--plan-yolo` does arm in rpc-ui, but it
 * auto-approves on the model's first proposal, which is the opposite of a
 * review gate.
 *
 * What *is* reachable is `AgentSession` itself: it carries the whole plan API
 * as public methods (`setPlanModeState`, `setPlanProposalHandler`,
 * `preparePlanForReview`, …). So omp-ui ships a generated omp extension,
 * written into the session's lineage dir and passed as `-e` at spawn — the same
 * per-lineage delivery ADR-0005 uses for the advisor overlay.
 *
 * The extension talks to omp-ui over two channels that already exist in the
 * rpc-ui protocol, so no new frame types are invented:
 * - `ui.setStatus(PLAN_STATUS_KEY, json)` publishes plan state (one-way).
 * - `ui.select("<PLAN_REVIEW_SENTINEL><json>", …)` requests approval and blocks
 *   the agent until the renderer answers.
 *
 * The wire constants live in ./plan, which the renderer imports directly.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-plan.ts";

export function planExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source. A template rather than a checked-in file because it is
 * delivered per-lineage next to the transcript, and because the constants above
 * are the wire contract — they must not drift between the two sides.
 *
 * Two `AgentSession.prototype` methods are patched. `prompt` captures the live
 * session: omp's `ExtensionContext` exposes `sessionManager` (a
 * `ReadonlySessionManager` whose 20 picked methods contain no plan API) but
 * never the `AgentSession`. `getPlanModeState` is wrapped so that, while the
 * mode is on, omp's own plan-mode write guard sees plan mode — without omp's
 * per-turn plan-authoring mandate, which omp injects off a private field no
 * caller can reach, so arming real state would drag the mandate back in
 * (ADR-0013).
 *
 * Both are unsupported surface, so both share one contract: if a patch throws,
 * or if the plan methods are missing on the captured object, the extension
 * publishes `unavailable` and the UI disables the toggle rather than
 * half-working.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodePath from "node:path";

const STATUS_KEY = ${JSON.stringify(PLAN_STATUS_KEY)};
const REVIEW_SENTINEL = ${JSON.stringify(PLAN_REVIEW_SENTINEL)};
const COMMAND = ${JSON.stringify(PLAN_COMMAND)};
const EXECUTE = ${JSON.stringify(PLAN_EXECUTE)};
const REFINE = ${JSON.stringify(PLAN_REFINE)};

/**
 * Sent hidden when plan mode is entered, in place of omp's own per-turn
 * plan-mode context. That context is the plan-authoring mandate this mode
 * removes, and it is unreachable in any case: omp injects it off a private
 * field this extension cannot arm (ADR-0013). This instruction describes the
 * mode omp-ui actually wants — read-only exploration that answers in place,
 * with a plan written and proposed only when the user asks for one.
 */
const READ_ONLY_PLAN_INSTRUCTION =
  "This session is in plan mode: read-only, enforced by omp's own plan-mode write guard" +
  " — working-tree writes, deletes, renames, and state-changing commands are " +
  "rejected; only local:// session artifacts may be written.\\n\\n" +
  "Default behavior: answer in place. Explore with read/search tools and " +
  "respond directly. Do NOT write a plan unless the user's own prompt asks for one" +
  ", and NEVER write to xd://propose without having written a plan file this " +
  "turn.\\n\\n" +
  "When the user does ask for a plan: choose a short kebab-case <slug>, write " +
  "the plan to local://<slug>-plan.md with the write tool, then request review " +
  "by writing the same <slug> as plain text to xd://propose. The plan is an " +
  "execution spec — a competent implementer who never saw this conversation " +
  "executes it top to bottom with zero design decisions left open: ground every " +
  "claim in code you actually read, give exact signatures/paths/callsites, and " +
  "state edge-case handling. Writing the slug blocks your turn until the user " +
  "answers execute, refine, or defers; a plan file with no propose write stays " +
  "unreviewed, so always propose a plan you were asked to write.";

/** Notified when the instruction above cannot be delivered. The mode stays on. */
const MODE_INSTRUCTION_UNAVAILABLE =
  "plan-mode instruction unavailable on this omp; the write guard still applies";

/**
 * Sent to the agent (hidden, like omp's own plan-mode context) when the
 * session plans in html format. omp hardcodes local://<slug>-plan.md across
 * its propose gate, write guard, and slug derivation, so the markdown plan
 * stays canonical and the html file is a companion rendition for the reviewer.
 */
const HTML_PLAN_INSTRUCTION =
  "This session reviews plans as HTML. In addition to the canonical " +
  "local://<slug>-plan.md (still required — write it as usual; it remains the " +
  "execution spec the implementer receives), you MUST maintain an HTML " +
  "rendition at local://<slug>-plan.html (same slug). Write it before writing " +
  "the slug to xd://propose, and rewrite it after every revision so both files " +
  "carry the same decisions and steps. The HTML file is what the human reviewer " +
  "sees: a complete, self-contained document — inline CSS only, no external " +
  "resources, no JavaScript (scripts will not run). Use the extra expressiveness " +
  "(layout, tables, callouts, inline SVG diagrams) to make the plan easier to " +
  "review.";

/** Notified once when the html rendition cannot be requested at all. */
const HTML_UNAVAILABLE =
  "HTML plan rendition unavailable on this omp; falling back to markdown plans";

/** What omp's plan-mode write guard reads, and what the wrapper below fakes. */
interface PlanModeState {
  enabled?: boolean;
  planFilePath?: string;
  workflow?: string;
}

/** The slice of omp's AgentSession this extension drives. */
interface PlanSession {
  isStreaming?: boolean;
  sessionManager: {
    getArtifactsDir?: () => string | null;
    appendModeChange: (mode: string, data?: { planFilePath: string }) => void;
  };
  getPlanModeState: () => PlanModeState | undefined;
  setPlanModeState: (
    state: { enabled: boolean; planFilePath: string; workflow?: string } | undefined,
  ) => void;
  getPlanReferencePath: () => string;
  setPlanReferencePath: (path: string) => void;
  setPlanProposalHandler: (handler: ((title: string) => Promise<ToolResult>) | null) => void;
  preparePlanForReview: (title: string) => Promise<ToolResult>;
  setActiveToolsByName: (names: string[]) => Promise<void>;
  getEnabledToolNames: () => string[];
  hasBuiltInTool?: (name: string) => boolean;
  /**
   * Delivers a hidden instruction into the conversation. Unsupported surface
   * like the rest of this session access; absent on an older omp, in which
   * case html plans degrade to markdown.
   */
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  details?: { planFilePath?: string; title?: string };
}

interface PlanUi {
  setStatus: (key: string, text: string | undefined) => void;
  select: (title: string, options: string[]) => Promise<string | undefined>;
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface PlanExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: PlanUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: PlanExtensionApi) {
  let session: PlanSession | null = null;
  let unavailable: string | undefined;
  let approved = false;
  // Which format the renderer asked for on the last \`on\`. A bare \`on\` typed by
  // hand keeps markdown — the renderer always sends the format explicitly.
  let format: "html" | "md" = "md";
  let previousTools: string[] | undefined;
  let ui: PlanUi | null = null;
  // Plan mode's on/off flag. Named for what it enforces: while set, the
  // getPlanModeState wrapper below fakes enabled state so omp's own write
  // guard treats the working tree as read-only.
  let readOnly = false;
  // The unwrapped prototype method. Every read the extension itself does goes
  // through this, so the extension never sees its own fake.
  let realGetPlanModeState: ((this: PlanSession) => PlanModeState | undefined) | null = null;

  // Capture the live AgentSession. omp hands extensions no reference to it.
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      unavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: PlanSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: PlanSession, ...args: unknown[]): unknown {
        session = this;
        return call.apply(this, args);
      };
    }
  } catch (err) {
    unavailable = "could not hook AgentSession: " + String(err);
  }

  // Show omp's write guard a plan-mode session without arming real plan state,
  // which would also arm omp's per-turn plan-authoring mandate (ADR-0013).
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const real = prototype?.getPlanModeState;
    if (!prototype || typeof real !== "function") {
      unavailable = "AgentSession.prototype.getPlanModeState is not a function";
    } else {
      const call = real as (this: PlanSession) => PlanModeState | undefined;
      realGetPlanModeState = call;
      prototype.getPlanModeState = function (this: PlanSession) {
        const state = call.call(this);
        // Real plan state always wins: any omp-internal arming path behaves
        // exactly as it does today.
        if (state?.enabled === true || !readOnly) return state;
        return {
          enabled: true,
          planFilePath: this.getPlanReferencePath?.() || "local://PLAN.md",
          workflow: "parallel",
        };
      };
    }
  } catch (err) {
    unavailable = "could not wrap getPlanModeState: " + String(err);
  }

  const REQUIRED = [
    "getPlanModeState",
    "setPlanModeState",
    "getPlanReferencePath",
    "setPlanReferencePath",
    "setPlanProposalHandler",
    "preparePlanForReview",
    "setActiveToolsByName",
    "getEnabledToolNames",
  ];

  /** Null when the session is usable; otherwise the reason it is not. */
  function unusable(): string | undefined {
    if (unavailable) return unavailable;
    const active = session;
    if (!active) return "no active omp session";
    const record = active as unknown as Record<string, unknown>;
    const missing = REQUIRED.filter(name => typeof record[name] !== "function");
    return missing.length > 0 ? "omp session is missing: " + missing.join(", ") : undefined;
  }

  /** \`local://x.md\` -> absolute path under the session's artifact sandbox. */
  function absolutePlanPath(planFilePath: string | null): string | null {
    if (!planFilePath) return null;
    const artifactsDir = session?.sessionManager?.getArtifactsDir?.();
    if (!artifactsDir) return null;
    const match = /^local:\\/{0,2}(.+)$/.exec(planFilePath);
    if (!match) return null;
    const relative = match[1];
    // Never let a crafted plan name escape the sandbox.
    const root = nodePath.resolve(artifactsDir, "local");
    const resolved = nodePath.resolve(root, relative);
    if (resolved !== root && !resolved.startsWith(root + nodePath.sep)) return null;
    return resolved;
  }

  function publish(): void {
    if (!ui) return;
    const active = session;
    const state = active && realGetPlanModeState ? realGetPlanModeState.call(active) : undefined;
    const enabled = state?.enabled === true || readOnly;
    // \`||\`, not \`??\`: getPlanReferencePath returns "" when no plan is pinned,
    // and the renderer reads a falsy path as "no plan file yet".
    const planFilePath = enabled
      ? (state?.planFilePath || active?.getPlanReferencePath?.() || null)
      : null;
    const status = {
      enabled,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
      approved,
      unavailable: unusable(),
    };
    ui.setStatus(STATUS_KEY, JSON.stringify(status));
  }

  async function exitPlanMode(active: PlanSession): Promise<void> {
    active.setPlanProposalHandler(null);
    // Defensive no-op: this extension never sets real plan state, but an
    // omp-internal path might have, and that would outlive the flag below.
    active.setPlanModeState(undefined);
    readOnly = false;
    if (previousTools) await active.setActiveToolsByName(previousTools);
    previousTools = undefined;
    active.sessionManager.appendModeChange("none");
  }

  /**
   * Installed while plan mode is active; \`xd://propose\` dispatches the plan
   * title here. Blocks the agent on the renderer's answer, so a plan is never
   * executed without a decision.
   */
  async function onProposal(active: PlanSession, dialog: PlanUi, title: string): Promise<ToolResult> {
    // Validates the artifact and resolves the real slug the agent wrote to.
    const result = await active.preparePlanForReview(title);
    const details = result.details ?? {};
    const planFilePath = details.planFilePath ?? active.getPlanReferencePath();
    const request = {
      title: details.title ?? title,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
      planHtmlAbsPath:
        format === "html" ? absolutePlanPath(planFilePath.replace(/\\.md$/, ".html")) : null,
    };

    let answer: string | undefined;
    try {
      answer = await dialog.select(REVIEW_SENTINEL + JSON.stringify(request), [EXECUTE, REFINE]);
    } catch {
      // A dropped dialog is a refusal, never a silent approval.
      answer = undefined;
    }

    if (answer !== EXECUTE) {
      // Refinement keeps plan mode active for another turn. Nothing to promote
      // into plan state: the ToolResult below names the file to revise.
      publish();
      return {
        content: [
          {
            type: "text",
            text:
              "Plan refinement requested. The user's revision notes may arrive as a " +
              "follow-up message; incorporate them, revise " +
              planFilePath +
              ", then write its title to xd://propose again when ready." +
              (format === "html"
                ? " Also rewrite " +
                  planFilePath.replace(/\\.md$/, ".html") +
                  " to match the revised plan."
                : ""),
          },
        ],
        details,
      };
    }

    // Accepted: pin the plan as the session's reference so whichever
    // implementation context the renderer chooses can read it, then leave plan
    // mode so write access returns. Crucially the agent does NOT implement
    // here — the renderer issues a separate implementation prompt (same
    // session, compacted, or a fresh session), so stop and wait for it.
    active.setPlanReferencePath(planFilePath);
    await exitPlanMode(active);
    approved = true;
    publish();
    return {
      content: [
        {
          type: "text",
          text:
            "Plan accepted and pinned as the reference at " +
            planFilePath +
            ". Plan mode exited. Do NOT start the implementation yet — a separate " +
            "implementation prompt will be issued. Stop and wait for it.",
        },
      ],
      details,
    };
  }

  async function enterPlanMode(active: PlanSession): Promise<void> {
    const planFilePath = active.getPlanReferencePath() || "local://PLAN.md";
    previousTools = active.getEnabledToolNames();
    // write stays active: plan mode's read-only guarantee is enforced by omp's
    // own plan-mode write guard, and the plan file itself needs writing.
    const tools = active.hasBuiltInTool?.("write")
      ? [...new Set([...previousTools, "write"])]
      : previousTools;
    await active.setActiveToolsByName(tools);
    readOnly = true;
    active.setPlanProposalHandler(title => {
      const dialog = ui;
      // Plan mode is only reachable through the command that sets \`ui\`.
      if (!dialog) throw new Error("omp-ui plan mode has no UI channel");
      return onProposal(active, dialog, title);
    });
    active.sessionManager.appendModeChange("plan", { planFilePath });
    await sendModeInstruction(active);
    if (format === "html") await requestHtmlRendition(active);
  }

  /**
   * Asks the agent to keep an html rendition beside the canonical plan. If the
   * session cannot carry the instruction, drop to markdown rather than promise
   * the reviewer a rendition nothing will write.
   */
  async function requestHtmlRendition(active: PlanSession): Promise<void> {
    if (typeof active.sendCustomMessage !== "function") {
      format = "md";
      ui?.notify(HTML_UNAVAILABLE, "warning");
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-format",
          content: HTML_PLAN_INSTRUCTION,
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
    } catch {
      format = "md";
      ui?.notify(HTML_UNAVAILABLE, "warning");
    }
  }

  /**
   * Delivers the read-only plan-mode instruction. The mode stays armed when
   * this fails: read-only is enforced by omp's write guard, not by the message,
   * so a session that cannot carry hidden instructions is still read-only — it
   * just loses the steering that keeps the agent from planning unprompted.
   */
  async function sendModeInstruction(active: PlanSession): Promise<void> {
    if (typeof active.sendCustomMessage !== "function") {
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-mode",
          content: READ_ONLY_PLAN_INSTRUCTION,
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
    } catch {
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
    }
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui plan mode control",
    handler: async (args: string, ctx: { ui: PlanUi }) => {
      ui = ctx.ui;
      const reason = unusable();
      const active = session;
      if (reason || !active) {
        publish();
        ctx.ui.notify("Plan mode unavailable: " + (reason ?? "no active omp session"), "error");
        return;
      }
      // \`on|off\` then an optional format; absent verb toggles.
      const tokens = args.trim().toLowerCase().split(/\\s+/).filter(t => t !== "");
      const on = realGetPlanModeState?.call(active)?.enabled === true || readOnly;
      const next = tokens[0] === "on" ? true : tokens[0] === "off" ? false : !on;
      if (tokens[1] === "html" || tokens[1] === "md") format = tokens[1];
      if (next === on) {
        publish();
        return;
      }
      if (next) await enterPlanMode(active);
      else await exitPlanMode(active);
      publish();
    },
  });
}
`;
}

/**
 * Writes the plan extension into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an older
 * omp-ui build can never outvote the current wire contract.
 */
export function writePlanExtension(lineageDir: string): string {
  const file = planExtensionPath(lineageDir);
  fs.mkdirSync(lineageDir, { recursive: true });
  fs.writeFileSync(file, extensionSource(), "utf8");
  return file;
}
