import * as path from "node:path";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  PLAN_COMMAND,
  PLAN_EXECUTE,
  PLAN_REFINE,
  PLAN_REVIEW_SENTINEL,
  PLAN_STATUS_KEY,
} from "./plan";

/**
 * omp's plan mode has no rpc surface (verified against v17.1.8): the
 * `RpcCommand` union carries no plan variant, `get_state` reports no mode,
 * `/plan` defines only `handleTui` so rpc-ui falls through and sends it to the
 * model as literal text, and `plan.defaultOnStartup` is read by
 * `InteractiveMode`/`print-mode` only. `--plan-yolo` does arm in rpc-ui, but it
 * auto-approves on the model's first proposal, which is the opposite of a
 * review gate.
 *
 * What *is* reachable is `AgentSession` itself: it carries the whole plan API
 * as public methods (`setPlanModeState`, `setPlanProposalHandler`,
 * `preparePlanForReview`, …). So omp-ui ships a generated omp extension,
 * written into the session's lineage dir and passed as `-e` at spawn — the same
 * per-lineage delivery ADR-0005 uses for the advisor overlay.
 *
 * The extension talks to omp-ui over two channels that already exist in the
 * rpc-ui protocol, so no new frame types are invented:
 * - `ui.setStatus(PLAN_STATUS_KEY, json)` publishes plan state (one-way).
 * - `ui.select("<PLAN_REVIEW_SENTINEL><json>", …)` requests approval and blocks
 *   the agent until the renderer answers.
 *
 * The wire constants live in ./plan, which the renderer imports directly.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-plan.ts";

export function planExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source. A template rather than a checked-in file because it is
 * delivered per-lineage next to the transcript, and because the constants above
 * are the wire contract — they must not drift between the two sides.
 *
 * Two `AgentSession.prototype` methods are patched. `prompt` captures the live
 * session: omp's `ExtensionContext` exposes `sessionManager` (a
 * `ReadonlySessionManager` whose 20 picked methods contain no plan API) but
 * never the `AgentSession`. `getPlanModeState` is wrapped so that, while the
 * mode is on, omp's own plan-mode write guard sees plan mode — without omp's
 * per-turn plan-authoring mandate, which omp injects off a private field no
 * caller can reach, so arming real state would drag the mandate back in
 * (ADR-0013).
 *
 * Both are unsupported surface, so both share one contract: if a patch throws,
 * or if the plan methods are missing on the captured object, the extension
 * publishes `unavailable` and the UI disables the toggle rather than
 * half-working.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodePath from "node:path";
import * as nodeFs from "node:fs";

const STATUS_KEY = ${JSON.stringify(PLAN_STATUS_KEY)};
const REVIEW_SENTINEL = ${JSON.stringify(PLAN_REVIEW_SENTINEL)};
const COMMAND = ${JSON.stringify(PLAN_COMMAND)};
const EXECUTE = ${JSON.stringify(PLAN_EXECUTE)};
const REFINE = ${JSON.stringify(PLAN_REFINE)};

/**
 * Sent hidden when plan mode is entered, in place of omp's own per-turn
 * plan-mode context. That context is the plan-authoring mandate this mode
 * removes, and it is unreachable in any case: omp injects it off a private
 * field this extension cannot arm (ADR-0013). This instruction describes the
 * mode omp-ui actually wants — read-only exploration that answers in place,
 * with a plan written and proposed only when the user asks for one.
 *
 * The plan-file sentence is format-dependent: under html the plan IS the html
 * file and no markdown is written at all (ADR-0014).
 */
const PLAN_MODE_PREFIX =
  "Plan mode is ON as of this message; it supersedes every earlier omp-ui " +
  "plan-mode and plan-format instruction in this conversation.\\n\\n" +
  "This session is in plan mode: read-only, enforced by omp's own plan-mode write guard" +
  " — working-tree writes, deletes, renames, and state-changing commands are " +
  "rejected; only local:// session artifacts may be written.\\n\\n" +
  "Default behavior: answer in place. Explore with read/search tools and " +
  "respond directly. Do NOT write a plan unless the user's own prompt asks for one" +
  ", and NEVER write to xd://propose without having written a plan file this " +
  "turn.\\n\\n";

const MD_PLAN_BODY =
  "When the user does ask for a plan: choose a short kebab-case <slug>, write " +
  "the plan to local://<slug>-plan.md with the write tool, then request review " +
  "by writing the same <slug> as plain text to xd://propose. ";

const HTML_PLAN_BODY =
  "When the user does ask for a plan: choose a short kebab-case <slug>, write " +
  "the plan to local://<slug>-plan.html with the write tool, then request review " +
  "by writing the same <slug> as plain text to xd://propose. Write NO markdown plan: " +
  "in this session the HTML file is the one and only plan, and it is what " +
  "the implementer executes. Ignore any omp tooling text that names " +
  "local://<slug>-plan.md. The HTML must be a complete, self-contained document: " +
  "inline CSS only, no external resources, no JavaScript (scripts will not run). " +
  "Give the document an explicit light canvas and dark foreground; do not use " +
  "omp-ui CSS variables or inherit host or theme colors. Every normal-text " +
  "foreground/background pair must meet WCAG AA contrast of at least 4.5:1, " +
  "including readable text in every colored callout. Make the document " +
  "responsively fit any iframe with no horizontal page scrolling: include a " +
  "viewport meta tag, apply border-box sizing, use fluid widths capped by " +
  "max-width, wrap long code and paths, and fit tables within the viewport " +
  "without overflow. " +
  "Nothing in the document may overlap or clip: every heading, label, and caption " +
  "gets its own fully visible space, clear of every shape and every other text run. " +
  "Choose the diagram tool by what the figure represents. For a structured, " +
  "topological diagram — a flow, sequence, state machine, or ER model — write " +
  "mermaid source inside " +
  '<pre class="mermaid"> and omp-ui renders it to SVG at review time. Supported ' +
  "diagram types: flowchart, sequenceDiagram, stateDiagram-v2, erDiagram. Keep " +
  "labels short and quote any label containing punctuation. Escape literal < > & " +
  "inside diagram source as HTML entities. Color a mermaid diagram to match what " +
  "it depicts: use classDef for groups and style for one-offs (fill, stroke, and " +
  "text color only; both work under the renderer's strict security), keep fills " +
  "muted, and keep every label readable against its fill (WCAG AA 4.5:1). Pick " +
  "the flowchart direction to fit the content and the space, not by habit: " +
  "flowchart LR (or RL) for pipelines, timelines, and sequences so the chart " +
  "uses the column's width and stays short; flowchart TD for hierarchies and " +
  "strict top-down dependency; flowchart BT for a funnel converging on a root. " +
  "Do not default every chart to a tall TD stack — that wastes the width and " +
  "forces scrolling. Use subgraphs to group related nodes and labeled edges " +
  "(-->|text|) for branches. For a genuinely organic flow — branching, looping " +
  "back, or spatial in two dimensions — use hand-drawn inline SVG instead, " +
  "because mermaid's rectilinear auto-layout cannot represent it. If a " +
  "diagram fails to render it is shown as an error callout, so keep the " +
  "surrounding prose able to stand alone. Put each mermaid statement on its own " +
  "line — never chain classDef, class, or node statements together with " +
  "semicolons, which the parser rejects. " +
  "Hand-drawn inline SVG is the right tool when mermaid's rectangles and " +
  "rectilinear auto-layout cannot represent the figure: a spatial or pictorial " +
  "subject (a cross-section, a physical layout, a schematic whose geometry is " +
  "the content) or an organic flow that branches, loops back, or uses two " +
  "dimensions. When you hand-draw, " +
  "prevent overlap and clipping with a layout recipe, not eyeballing: pick a " +
  "viewBox and place every element on a coarse grid (10-unit cells); give every " +
  "label its own reserved cell, fully inside or fully outside a shape, never " +
  "straddling an edge; size the viewBox so the widest label fits at its font size " +
  "(estimate text width as 0.6 times font-size times character count); and keep " +
  "text out of rotated or clipped regions. The renderer passes hand-drawn SVG " +
  "through unchanged and the guardrail stylesheet scales it to the column, so a " +
  "well-formed viewBox is all you must get right. " +
  "Code blocks are highlighted at review time: put the language on the block's " +
  '<code> element — <pre><code class="language-python">…</code></pre> — and the ' +
  "renderer tokenizes the block in the active theme. Recognized: bash, c, cpp, " +
  "csharp, css, diff, docker, go, html, java, javascript, json, jsx, kotlin, " +
  "lua, markdown, php, python, ruby, rust, sql, swift, toml, tsx, typescript, " +
  "xml, yaml (also accepted: sh, shell, shellscript, zsh, c++, cs, dockerfile, " +
  "golang, js, jsonc, kt, md, py, rb, rs, ts, yml). A block without a recognized " +
  "language class renders plain, so keep any load-bearing code readable without " +
  "colour. " +
  "Use the expressiveness HTML gives you — layout, tables, " +
  "callouts, diagrams — to make the plan easier to review, and keep " +
  "the styling modest so the document stays mostly content. ";

const PLAN_SPEC_SUFFIX =
  "The plan is an execution spec — a competent implementer who never saw this " +
  "conversation executes it top to bottom with zero design decisions left open: " +
  "ground every claim in code you actually read, give exact signatures/paths/" +
  "callsites, and state edge-case handling. Writing the slug blocks your turn " +
  "until the user answers execute, refine, or defers; a plan file with no " +
  "propose write stays unreviewed, so always propose a plan you were asked to write.";

function planModeInstruction(fmt: "html" | "md"): string {
  return PLAN_MODE_PREFIX + (fmt === "html" ? HTML_PLAN_BODY : MD_PLAN_BODY) + PLAN_SPEC_SUFFIX;
}

/** Notified when the instruction above cannot be delivered. The mode stays on. */
const MODE_INSTRUCTION_UNAVAILABLE =
  "plan-mode instruction unavailable on this omp; the write guard still applies";

/**
 * Sent hidden when plan mode is left, mirroring the entry instruction. Exiting
 * otherwise changes nothing the model can see: the write guard is a tool-side
 * check, and appendModeChange("none") writes a transcript entry, not a message.
 * The entry instruction is a durable conversation message, so the mode has to be
 * closed in the same channel it was opened in (issue #117).
 */
const PLAN_MODE_EXIT_INSTRUCTION =
  "Build mode is ON as of this message. Plan mode is OFF. The read-only guard is lifted: you have " +
  "full write access to the working tree again, and state-changing commands are " +
  "allowed.\\n\\n" +
  "Every earlier omp-ui plan-mode and plan-format instruction in this conversation " +
  "is superseded and no longer applies — they described a mode that has ended. Do " +
  "NOT write plan artifacts, and NEVER write to xd://propose, unless a later " +
  "instruction turns plan mode back on. Carry out the user's request normally, " +
  "making the changes they ask for.";

/** Notified once when html plans cannot be driven; the session drops to md. */
const HTML_UNAVAILABLE =
  "HTML plans unavailable on this omp; falling back to markdown plans";

/** What omp's plan-mode write guard reads, and what the wrapper below fakes. */
interface PlanModeState {
  enabled?: boolean;
  planFilePath?: string;
  workflow?: string;
}

/** The slice of omp's AgentSession this extension drives. */
interface PlanSession {
  isStreaming?: boolean;
  sessionManager: {
    getArtifactsDir?: () => string | null;
    appendModeChange: (mode: string, data?: { planFilePath: string }) => void;
  };
  getPlanModeState: () => PlanModeState | undefined;
  setPlanModeState: (
    state: { enabled: boolean; planFilePath: string; workflow?: string } | undefined,
  ) => void;
  getPlanReferencePath: () => string;
  setPlanReferencePath: (path: string) => void;
  setPlanProposalHandler: (handler: ((title: string) => Promise<ToolResult>) | null) => void;
  preparePlanForReview: (title: string) => Promise<ToolResult>;
  setActiveToolsByName: (names: string[]) => Promise<void>;
  getEnabledToolNames: () => string[];
  hasBuiltInTool?: (name: string) => boolean;
  /**
   * Delivers a hidden instruction into the conversation. Unsupported surface
   * like the rest of this session access; absent on an older omp, in which
   * case html plans degrade to markdown.
   */
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  details?: { planFilePath?: string; title?: string };
  isError?: boolean;
}

interface PlanUi {
  setStatus: (key: string, text: string | undefined) => void;
  select: (title: string, options: string[]) => Promise<string | undefined>;
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface PlanExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: PlanUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: PlanExtensionApi) {
  let session: PlanSession | null = null;
  let unavailable: string | undefined;
  let approved = false;
  // Which format the renderer asked for on the last \`on\`. A bare \`on\` typed by
  // hand keeps markdown — the renderer always sends the format explicitly.
  let format: "html" | "md" = "md";
  let previousTools: string[] | undefined;
  let ui: PlanUi | null = null;
  // Plan mode's on/off flag. Named for what it enforces: while set, the
  // getPlanModeState wrapper below fakes enabled state so omp's own write
  // guard treats the working tree as read-only.
  let readOnly = false;
  // True while the agent holds an entry instruction that has not been retracted.
  // Exit only speaks when there is something to retract, so a session whose omp
  // cannot carry hidden instructions is never told it left a mode it was never
  // told it entered.
  let instructionDelivered = false;
  // The unwrapped prototype method. Every read the extension itself does goes
  // through this, so the extension never sees its own fake.
  let realGetPlanModeState: ((this: PlanSession) => PlanModeState | undefined) | null = null;

  // Capture the live AgentSession. omp hands extensions no reference to it.
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      unavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: PlanSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: PlanSession, ...args: unknown[]): unknown {
        session = this;
        return call.apply(this, args);
      };
    }
  } catch (err) {
    unavailable = "could not hook AgentSession: " + String(err);
  }

  // Show omp's write guard a plan-mode session without arming real plan state,
  // which would also arm omp's per-turn plan-authoring mandate (ADR-0013).
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const real = prototype?.getPlanModeState;
    if (!prototype || typeof real !== "function") {
      unavailable = "AgentSession.prototype.getPlanModeState is not a function";
    } else {
      const call = real as (this: PlanSession) => PlanModeState | undefined;
      realGetPlanModeState = call;
      prototype.getPlanModeState = function (this: PlanSession) {
        const state = call.call(this);
        // Real plan state always wins: any omp-internal arming path behaves
        // exactly as it does today.
        if (state?.enabled === true || !readOnly) return state;
        return {
          enabled: true,
          planFilePath: this.getPlanReferencePath?.() || "local://PLAN.md",
          workflow: "parallel",
        };
      };
    }
  } catch (err) {
    unavailable = "could not wrap getPlanModeState: " + String(err);
  }

  const REQUIRED = [
    "getPlanModeState",
    "setPlanModeState",
    "getPlanReferencePath",
    "setPlanReferencePath",
    "setPlanProposalHandler",
    "preparePlanForReview",
    "setActiveToolsByName",
    "getEnabledToolNames",
  ] as const;

  /** Null when the session is usable; otherwise the reason it is not. */
  function unusable(): string | undefined {
    if (unavailable) return unavailable;
    const active = session;
    if (!active) return "no active omp session";
    const missing = REQUIRED.filter(name => typeof active[name] !== "function");
    return missing.length > 0 ? "omp session is missing: " + missing.join(", ") : undefined;
  }

  /** \`local://x.md\` -> absolute path under the session's artifact sandbox. */
  function absolutePlanPath(planFilePath: string | null): string | null {
    if (!planFilePath) return null;
    const artifactsDir = session?.sessionManager?.getArtifactsDir?.();
    if (!artifactsDir) return null;
    const match = /^local:\\/{0,2}(.+)$/.exec(planFilePath);
    if (!match) return null;
    const relative = match[1];
    // Never let a crafted plan name escape the sandbox.
    const root = nodePath.resolve(artifactsDir, "local");
    const resolved = nodePath.resolve(root, relative);
    if (resolved !== root && !resolved.startsWith(root + nodePath.sep)) return null;
    return resolved;
  }

  /**
   * omp's own normalizePlanTitle + planSlugFromSupplied, replicated
   * (plan-mode/approved-plan.ts:21-48, 121-130) so the slug this extension
   * probes for is the same one omp would derive from the propose text.
   * Returns null for a title that sanitizes to nothing.
   */
  function slugFromTitle(title: string): string | null {
    const trimmed = title.trim();
    if (!trimmed) return null;
    if (trimmed.includes("/") || trimmed.includes("\\\\") || trimmed.includes("..")) return null;
    const sanitized = trimmed
      .replace(/\\.(?:md|html)$/i, "")
      .replace(/\\s+/g, "-")
      .replace(/[^A-Za-z0-9_-]/g, "")
      .replace(/-{2,}/g, "-")
      .replace(/^-+|-+$/g, "");
    if (!sanitized) return null;
    return sanitized.replace(/-plan$/i, "") || sanitized;
  }

  /** The session's local:// root, or null when omp exposes no artifacts dir. */
  function localRoot(): string | null {
    const artifactsDir = session?.sessionManager?.getArtifactsDir?.();
    return artifactsDir ? nodePath.resolve(artifactsDir, "local") : null;
  }

  /**
   * Every \`*-plan.html\` basename in the local root, newest first — the
   * fallback for a propose title that does not reconstruct the filename, and
   * the html analogue of omp's own listPlanFiles (plan-mode/plan-files.ts:24).
   */
  function listHtmlPlans(): string[] {
    const root = localRoot();
    if (!root) return [];
    try {
      return nodeFs
        .readdirSync(root, { withFileTypes: true })
        .filter(entry => entry.isFile() && /-plan\\.html$/i.test(entry.name))
        .map(entry => {
          let mtime = 0;
          try {
            mtime = nodeFs.statSync(nodePath.join(root, entry.name)).mtimeMs;
          } catch {
            // An unstattable entry sorts last rather than failing the scan.
          }
          return { name: entry.name, mtime };
        })
        .sort((a, b) => b.mtime - a.mtime)
        .map(entry => entry.name);
    } catch {
      return [];
    }
  }

  /**
   * The html plan a propose title refers to, as a local:// URL, or null when
   * none exists. Tries the slug omp would derive, then the newest html plan on
   * disk — the same precedence omp's resolveApprovedPlan uses for markdown.
   */
  function resolveHtmlPlan(title: string): string | null {
    const candidates: string[] = [];
    const slug = slugFromTitle(title);
    if (slug) candidates.push(slug + "-plan.html");
    for (const name of listHtmlPlans()) {
      if (!candidates.includes(name)) candidates.push(name);
    }
    for (const name of candidates) {
      const abs = absolutePlanPath("local://" + name);
      if (abs && nodeFs.existsSync(abs)) return "local://" + name;
    }
    return null;
  }

  /**
   * Whether this session can drive html plans at all. Both are hard
   * requirements: without sendCustomMessage the agent never learns to write
   * html, and without an artifacts dir no local:// path can be resolved or
   * probed. Either missing degrades the session to md with one warning rather
   * than producing a plan the review pane cannot show.
   */
  function htmlPlansUsable(active: PlanSession): boolean {
    if (typeof active.sendCustomMessage !== "function") return false;
    return localRoot() !== null;
  }

  function publish(): void {
    if (!ui) return;
    const active = session;
    const state = active && realGetPlanModeState ? realGetPlanModeState.call(active) : undefined;
    const enabled = state?.enabled === true || readOnly;
    // \`||\`, not \`??\`: getPlanReferencePath returns "" when no plan is pinned,
    // and the renderer reads a falsy path as "no plan file yet".
    const planFilePath = enabled
      ? (state?.planFilePath || active?.getPlanReferencePath?.() || null)
      : null;
    const status = {
      enabled,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
      approved,
      unavailable: unusable(),
    };
    ui.setStatus(STATUS_KEY, JSON.stringify(status));
  }

  async function exitPlanMode(
    active: PlanSession,
    options?: { announce?: boolean },
  ): Promise<void> {
    active.setPlanProposalHandler(null);
    // Defensive no-op: this extension never sets real plan state, but an
    // omp-internal path might have, and that would outlive the flag below.
    active.setPlanModeState(undefined);
    readOnly = false;
    if (previousTools) await active.setActiveToolsByName(previousTools);
    previousTools = undefined;
    active.sessionManager.appendModeChange("none");
    // The execute path answers the agent with a ToolResult that already says
    // plan mode exited, and the agent is blocked mid-turn inside its own
    // proposal — a steer there would land beside that answer.
    if (options?.announce === false) {
      instructionDelivered = false;
      return;
    }
    await sendExitInstruction(active);
  }

  /**
   * Installed while plan mode is active; \`xd://propose\` dispatches the plan
   * title here. Blocks the agent on the renderer's answer, so a plan is never
   * executed without a decision.
   *
   * Under html the extension resolves the artifact itself: omp's
   * preparePlanForReview routes through resolveApprovedPlan, which is
   * hardcoded to \`local://<slug>-plan.md\`. Nothing upstream requires that
   * call — the propose device only invokes this handler
   * (tools/resolve.ts:303-311) — so the html path skips it (ADR-0014). An html
   * session whose agent wrote markdown anyway still falls through to omp's
   * resolver rather than stranding the gate.
   */
  async function onProposal(active: PlanSession, dialog: PlanUi, title: string): Promise<ToolResult> {
    let planFilePath: string | null = format === "html" ? resolveHtmlPlan(title) : null;
    let details: { planFilePath?: string; title?: string } = {};

    if (planFilePath !== null) {
      details = { planFilePath, title };
    } else {
      try {
        const result = await active.preparePlanForReview(title);
        details = result.details ?? {};
        planFilePath = details.planFilePath ?? active.getPlanReferencePath() ?? null;
        if (planFilePath === "") planFilePath = null;
      } catch (err) {
        // md is omp's own contract: its ToolError is the right answer. Under
        // html the agent was told to write html, so answer in that spelling.
        if (format !== "html") throw err;
        planFilePath = null;
      }
      if (planFilePath === null) {
        const slug = slugFromTitle(title);
        publish();
        return {
          isError: true,
          content: [
            {
              type: "text",
              text:
                "No plan file found for \\"" + title + "\\". Write the finalized plan to local://" +
                (slug ?? "<slug>") +
                "-plan.html with the write tool, then write the same slug to xd://propose again.",
            },
          ],
        };
      }
    }

    const request = {
      title: details.title ?? title,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
    };

    let answer: string | undefined;
    try {
      answer = await dialog.select(REVIEW_SENTINEL + JSON.stringify(request), [EXECUTE, REFINE]);
    } catch {
      // A dropped dialog is a refusal, never a silent approval.
      answer = undefined;
    }

    if (answer !== EXECUTE) {
      // Refinement keeps plan mode active for another turn. Nothing to promote
      // into plan state: the ToolResult below names the file to revise.
      publish();
      return {
        content: [
          {
            type: "text",
            text:
              "Plan refinement requested. The user's revision notes may arrive as a " +
              "follow-up message; incorporate them, revise " +
              planFilePath +
              ", then write its title to xd://propose again when ready.",
          },
        ],
        details,
      };
    }

    // Accepted: pin the plan as the session's reference so whichever
    // implementation context the renderer chooses can read it, then leave plan
    // mode so write access returns. Crucially the agent does NOT implement
    // here — the renderer issues a separate implementation prompt (same
    // session, compacted, or a fresh session), so stop and wait for it.
    active.setPlanReferencePath(planFilePath);
    await exitPlanMode(active, { announce: false });
    approved = true;
    publish();
    return {
      content: [
        {
          type: "text",
          text:
            "Plan accepted and pinned as the reference at " +
            planFilePath +
            ". Plan mode exited. Do NOT start the implementation yet — a separate " +
            "implementation prompt will be issued. Stop and wait for it.",
        },
      ],
      details,
    };
  }

  async function enterPlanMode(active: PlanSession): Promise<void> {
    const planFilePath = active.getPlanReferencePath() || "local://PLAN.md";
    previousTools = active.getEnabledToolNames();
    // write stays active: plan mode's read-only guarantee is enforced by omp's
    // own plan-mode write guard, and the plan file itself needs writing.
    const tools = active.hasBuiltInTool?.("write")
      ? [...new Set([...previousTools, "write"])]
      : previousTools;
    await active.setActiveToolsByName(tools);
    readOnly = true;
    active.setPlanProposalHandler(title => {
      const dialog = ui;
      // Plan mode is only reachable through the command that sets \`ui\`.
      if (!dialog) throw new Error("omp-ui plan mode has no UI channel");
      return onProposal(active, dialog, title);
    });
    active.sessionManager.appendModeChange("plan", { planFilePath });
    // Decide the format before the instruction: it is the instruction that
    // tells the agent which single file to write.
    if (format === "html" && !htmlPlansUsable(active)) {
      format = "md";
      ui?.notify(HTML_UNAVAILABLE, "warning");
    }
    await sendModeInstruction(active);
  }

  /**
   * Delivers the read-only plan-mode instruction. The mode stays armed when
   * this fails: read-only is enforced by omp's write guard, not by the message,
   * so a session that cannot carry hidden instructions is still read-only — it
   * just loses the steering that keeps the agent from planning unprompted.
   */
  async function sendModeInstruction(active: PlanSession): Promise<void> {
    if (typeof active.sendCustomMessage !== "function") {
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-mode",
          content: planModeInstruction(format),
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
      instructionDelivered = true;
    } catch {
      // The html instruction never landed, so the agent will follow omp's own
      // markdown guidance — the session must follow it too.
      if (format === "html") {
        format = "md";
        ui?.notify(HTML_UNAVAILABLE, "warning");
      }
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
    }
  }

  /**
   * Retracts the entry instruction. Best effort and silent: the guard is already
   * down by the time this runs, and the next entry instruction supersedes any
   * stale copy, so a delivery failure must never fail the exit or warn.
   */
  async function sendExitInstruction(active: PlanSession): Promise<void> {
    if (!instructionDelivered) return;
    instructionDelivered = false;
    if (typeof active.sendCustomMessage !== "function") return;
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-mode-exit",
          content: PLAN_MODE_EXIT_INSTRUCTION,
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
    } catch {
      // Deliberately silent — see the doc comment.
    }
  }

  // omp dispatches each /omp-ui-plan through AgentSession.prototype.prompt without
  // waiting for the previous one, so two quick toggles interleave: an "off" that
  // lands while "on" is awaiting setActiveToolsByName reads a still-false readOnly,
  // decides it is a no-op, publishes enabled:false while the mode arms behind it,
  // and is swallowed (issue #118). One chain keeps transitions in arrival order.
  let chain: Promise<void> = Promise.resolve();

  function serialize(work: () => Promise<void>): Promise<void> {
    const next = chain.then(work, work);
    // A failed toggle must not wedge every later one.
    chain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui plan mode control",
    handler: (args: string, ctx: { ui: PlanUi }) =>
      serialize(async () => {
        ui = ctx.ui;
        const reason = unusable();
        const active = session;
        if (reason || !active) {
          publish();
          ctx.ui.notify("Plan mode unavailable: " + (reason ?? "no active omp session"), "error");
          return;
        }
        // \`on|off\` then an optional format; absent verb toggles.
        const tokens = args.trim().toLowerCase().split(/\\s+/).filter(t => t !== "");
        const on = realGetPlanModeState?.call(active)?.enabled === true || readOnly;
        const next = tokens[0] === "on" ? true : tokens[0] === "off" ? false : !on;
        if (tokens[1] === "html" || tokens[1] === "md") format = tokens[1];
        if (next === on) {
          publish();
          return;
        }
        if (next) await enterPlanMode(active);
        else await exitPlanMode(active);
        publish();
      }),
  });
}
`;
}

/**
 * Writes the plan extension into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an older
 * omp-ui build can never outvote the current wire contract.
 */
export function writePlanExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, planExtensionPath(lineageDir), extensionSource());
}
