import * as path from "node:path";
import { writeLineageArtifact } from "./lineage-artifact";
import { GOAL_MODE_TRANSITION_KEY } from "./goal";
import {
  PLAN_COMMAND,
  PLAN_EXECUTE,
  PLAN_REFINE,
  PLAN_REVIEW_SENTINEL,
  PLAN_STATUS_KEY,
} from "./plan";

/**
 * omp's plan mode has no rpc surface (verified against v17.1.8): the
 * `RpcCommand` union carries no plan variant, `get_state` reports no mode,
 * `/plan` defines only `handleTui` so rpc-ui falls through and sends it to the
 * model as literal text, and `plan.defaultOnStartup` is read by
 * `InteractiveMode`/`print-mode` only. `--plan-yolo` does arm in rpc-ui, but it
 * auto-approves on the model's first proposal, which is the opposite of a
 * review gate.
 *
 * What *is* reachable is `AgentSession` itself: it carries the whole plan API
 * as public methods (`setPlanModeState`, `setPlanProposalHandler`,
 * `preparePlanForReview`, …). So omp-ui ships a generated omp extension,
 * written into the session's lineage dir and passed as `-e` at spawn — the same
 * per-lineage delivery ADR-0005 uses for the advisor overlay.
 *
 * The extension talks to omp-ui over two channels that already exist in the
 * rpc-ui protocol, so no new frame types are invented:
 * - `ui.setStatus(PLAN_STATUS_KEY, json)` publishes plan state (one-way).
 * - `ui.select("<PLAN_REVIEW_SENTINEL><json>", …)` requests approval and blocks
 *   the agent until the renderer answers.
 *
 * The wire constants live in ./plan, which the renderer imports directly.
 *
 * Plan entry also joins the mode-transition chain the goal bridge shares under
 * `Symbol.for("omp-ui:mode-transition")`, and refuses an unfinished goal before
 * it takes omp's single persisted mode slot (ADR-0007/0013 boundary).
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-plan.ts";

export function planExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The extension source. A template rather than a checked-in file because it is
 * delivered per-lineage next to the transcript, and because the constants above
 * are the wire contract — they must not drift between the two sides.
 *
 * Two `AgentSession.prototype` methods are patched. `prompt` binds the FIRST
 * prompting session as the root: omp's `ExtensionContext` exposes
 * `sessionManager` (a `ReadonlySessionManager` whose 20 picked methods contain
 * no plan API) but never the `AgentSession`, and the `registerCommand` handler's
 * `this` is not a session either, so the prompt wrapper is the only correct
 * binding (ADR-0008 discipline: descendants never retarget the root).
 * `getPlanModeState` is wrapped so that, while the mode is on, omp's own
 * plan-mode write guard sees plan mode for every session — without omp's
 * per-turn plan-authoring mandate, which omp injects off a private field no
 * caller can reach, so arming real state would drag the mandate back in
 * (ADR-0013).
 *
 * Both are unsupported surface, so both share one contract: if a patch throws,
 * or if the plan methods are missing on the captured object, the extension
 * publishes `unavailable` and the UI disables the toggle rather than
 * half-working.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodePath from "node:path";
import * as nodeFs from "node:fs";

const STATUS_KEY = ${JSON.stringify(PLAN_STATUS_KEY)};
const REVIEW_SENTINEL = ${JSON.stringify(PLAN_REVIEW_SENTINEL)};
const COMMAND = ${JSON.stringify(PLAN_COMMAND)};
const EXECUTE = ${JSON.stringify(PLAN_EXECUTE)};
const REFINE = ${JSON.stringify(PLAN_REFINE)};
const TRANSITION_KEY = ${JSON.stringify(GOAL_MODE_TRANSITION_KEY)};

/** The single tool name plan mode borrows so the plan file can be written. */
const WRITE_TOOL = "write";

/**
 * Sent hidden when plan mode is entered, in place of omp's own per-turn
 * plan-mode context. That context is the plan-authoring mandate this mode
 * removes, and it is unreachable in any case: omp injects it off a private
 * field this extension cannot arm (ADR-0013). This instruction describes the
 * mode omp-ui actually wants — read-only exploration that answers in place,
 * with a plan written and proposed only when the user asks for one.
 *
 * The plan-file sentence is format-dependent: under html the plan IS the html
 * file and no markdown is written at all (ADR-0014).
 */
const PLAN_MODE_PREFIX =
  "Plan mode is ON as of this message; it supersedes every earlier omp-ui " +
  "plan-mode and plan-format instruction in this conversation.\\n\\n" +
  "This session is in plan mode: read-only, enforced by omp's own plan-mode write guard" +
  " — working-tree writes, deletes, renames, and state-changing commands are " +
  "rejected; only local:// session artifacts may be written.\\n\\n" +
  "Default behavior: answer in place. Explore with read/search tools and " +
  "respond directly. Do NOT write a plan unless the user's own prompt asks for one" +
  ", and NEVER write to xd://propose without having written a plan file this " +
  "turn.\\n\\n";

const MD_PLAN_BODY =
  "When the user does ask for a plan: choose a short kebab-case <slug>, write " +
  "the plan to local://<slug>-plan.md with the write tool, then request review " +
  "by writing the same <slug> as plain text to xd://propose. ";

const HTML_PLAN_BODY =
  "When the user does ask for a plan: choose a short kebab-case <slug>, write " +
  "the plan to local://<slug>-plan.html with the write tool, then request review " +
  "by writing the same <slug> as plain text to xd://propose. Write NO markdown plan: " +
  "in this session the HTML file is the one and only plan, and it is what " +
  "the implementer executes. Ignore any omp tooling text that names " +
  "local://<slug>-plan.md. The HTML must be a complete, self-contained document: " +
  "inline CSS only, no external resources, no JavaScript (scripts will not run). " +
  "omp-ui paints the page canvas and the reading ink from the active omp-ui " +
  "theme — light or dark — and discards plan-authored page and element colours, " +
  "so author no canvas, background, or text colour of your own and never assume " +
  "which one you are writing for: leave backgrounds transparent, write " +
  "\`border: 1px solid\` with no colour so a rule inherits the ink, and carry " +
  "emphasis with headings, \`<strong>\`, and \`<em>\` instead of hue. Every text " +
  "pair the renderer produces must meet WCAG AA contrast of at least 4.5:1, so " +
  "never place a label on a colour you hard-coded. Colour that must survive " +
  "belongs in SVG only. Make the document " +
  "responsively fit any iframe with no horizontal page scrolling: include a " +
  "viewport meta tag, apply border-box sizing, use fluid widths capped by " +
  "max-width, wrap long code and paths, and fit tables within the viewport " +
  "without overflow. " +
  "Nothing in the document may overlap or clip: every heading, label, and caption " +
  "gets its own fully visible space, clear of every shape and every other text run. " +
  "Choose the diagram tool by what the figure represents. For a structured, " +
  "topological diagram — a flow, sequence, state machine, or ER model — write " +
  "mermaid source inside " +
  '<pre class="mermaid"> and omp-ui renders it to SVG at review time. Supported ' +
  "diagram types: flowchart, sequenceDiagram, stateDiagram-v2, erDiagram. Keep " +
  "labels short and quote any label containing punctuation. Escape literal < > & " +
  "inside diagram source as HTML entities. Color a mermaid diagram to match what " +
  "it depicts: use classDef for groups and style for one-offs (fill and stroke; " +
  "both work under the renderer's strict security), keep fills muted. The " +
  "renderer already picks a diagram palette matched to the canvas it lands on " +
  "and, on a dark canvas, re-fits any authored \`fill:\` or \`stroke:\` hex so it " +
  "stays readable, so choose fills freely but never set a node \`color:\` — the " +
  "renderer owns label colour. Pick " +
  "the flowchart direction to fit the content and the space, not by habit: " +
  "flowchart LR (or RL) for pipelines, timelines, and sequences so the chart " +
  "uses the column's width and stays short; flowchart TD for hierarchies and " +
  "strict top-down dependency; flowchart BT for a funnel converging on a root. " +
  "Do not default every chart to a tall TD stack — that wastes the width and " +
  "forces scrolling. Use subgraphs to group related nodes and labeled edges " +
  "(-->|text|) for branches. For a genuinely organic flow — branching, looping " +
  "back, or spatial in two dimensions — use hand-drawn inline SVG instead, " +
  "because mermaid's rectilinear auto-layout cannot represent it. If a " +
  "diagram fails to render it is shown as an error callout, so keep the " +
  "surrounding prose able to stand alone. Put each mermaid statement on its own " +
  "line — never chain classDef, class, or node statements together with " +
  "semicolons, which the parser rejects. " +
  "Hand-drawn inline SVG is the right tool when mermaid's rectangles and " +
  "rectilinear auto-layout cannot represent the figure: a spatial or pictorial " +
  "subject (a cross-section, a physical layout, a schematic whose geometry is " +
  "the content) or an organic flow that branches, loops back, or uses two " +
  "dimensions. When you hand-draw, " +
  "prevent overlap and clipping with a layout recipe, not eyeballing: pick a " +
  "viewBox and place every element on a coarse grid (10-unit cells); give every " +
  "label its own reserved cell, fully inside or fully outside a shape, never " +
  "straddling an edge; size the viewBox so the widest label fits at its font size " +
  "(estimate text width as 0.6 times font-size times character count); and keep " +
  "text out of rotated or clipped regions. The renderer passes hand-drawn SVG " +
  "through unchanged and the guardrail stylesheet scales it to the column, so a " +
  "well-formed viewBox is all you must get right. For colour, draw with " +
  '\`stroke="currentColor"\` and \`fill="none"\`, and fill an area with ' +
  '\`fill="currentColor" fill-opacity="0.08"\` to \`"0.15"\` so it reads as a wash ' +
  "on either canvas; never set a \`fill\` on \`<text>\` — the renderer paints SVG " +
  "text with the canvas ink. " +
  "Code blocks are highlighted at review time: put the language on the block's " +
  '<code> element — <pre><code class="language-python">…</code></pre> — and the ' +
  "renderer tokenizes the block in the active theme. Recognized: bash, c, cpp, " +
  "csharp, css, diff, docker, go, html, java, javascript, json, jsx, kotlin, " +
  "lua, markdown, php, python, ruby, rust, sql, swift, toml, tsx, typescript, " +
  "xml, yaml (also accepted: sh, shell, shellscript, zsh, c++, cs, dockerfile, " +
  "golang, js, jsonc, kt, md, py, rb, rs, ts, yml). A block without a recognized " +
  "language class renders plain, so keep any load-bearing code readable without " +
  "colour. " +
  "Use the expressiveness HTML gives you — layout, tables, " +
  "callouts, diagrams — to make the plan easier to review, and keep " +
  "the styling modest so the document stays mostly content. ";

const PLAN_SPEC_SUFFIX =
  "The plan is an execution spec — a competent implementer who never saw this " +
  "conversation executes it top to bottom with zero design decisions left open: " +
  "ground every claim in code you actually read, give exact signatures/paths/" +
  "callsites, and state edge-case handling. Writing the slug blocks your turn " +
  "until the user answers execute, refine, or defers; a plan file with no " +
  "propose write stays unreviewed, so always propose a plan you were asked to write.";

function planModeInstruction(fmt: "html" | "md"): string {
  return PLAN_MODE_PREFIX + (fmt === "html" ? HTML_PLAN_BODY : MD_PLAN_BODY) + PLAN_SPEC_SUFFIX;
}

/** Notified when the instruction above cannot be delivered. The mode stays on. */
const MODE_INSTRUCTION_UNAVAILABLE =
  "plan-mode instruction unavailable on this omp; the write guard still applies";

/**
 * Sent hidden when plan mode is left, mirroring the entry instruction. Exiting
 * otherwise changes nothing the model can see: the write guard is a tool-side
 * check, and appendModeChange("none") writes a transcript entry, not a message.
 * The entry instruction is a durable conversation message, so the mode has to be
 * closed in the same channel it was opened in (issue #117).
 */
const PLAN_MODE_EXIT_INSTRUCTION =
  "Build mode is ON as of this message. Plan mode is OFF. The read-only guard is lifted: you have " +
  "full write access to the working tree again, and state-changing commands are " +
  "allowed.\\n\\n" +
  "Every earlier omp-ui plan-mode and plan-format instruction in this conversation " +
  "is superseded and no longer applies — they described a mode that has ended. Do " +
  "NOT write plan artifacts, and NEVER write to xd://propose, unless a later " +
  "instruction turns plan mode back on. Carry out the user's request normally, " +
  "making the changes they ask for.";

/** Notified once when html plans cannot be driven; the session drops to md. */
const HTML_UNAVAILABLE =
  "HTML plans unavailable on this omp; falling back to markdown plans";

/** What Plan entry answers with when a goal still owns the mode slot. */
const PLAN_GOAL_BLOCK = "Drop the current goal before entering Plan mode.";

/** What omp's plan-mode write guard reads, and what the wrapper below fakes. */
interface PlanModeState {
  enabled?: boolean;
  planFilePath?: string;
  workflow?: string;
}

/** The slice of omp's AgentSession this extension drives. */
interface PlanSession {
  isStreaming?: boolean;
  sessionManager: {
    getArtifactsDir?: () => string | null;
    appendModeChange: (mode: string, data?: { planFilePath: string }) => void;
    /** Which session the root currently is; the ownership token's subject. */
    getSessionId?: () => unknown;
  };
  getPlanModeState: () => PlanModeState | undefined;
  setPlanModeState: (
    state: { enabled: boolean; planFilePath: string; workflow?: string } | undefined,
  ) => void;
  getPlanReferencePath: () => string;
  setPlanReferencePath: (path: string) => void;
  setPlanProposalHandler: (handler: ((title: string) => Promise<ToolResult>) | null) => void;
  preparePlanForReview: (title: string) => Promise<ToolResult>;
  /** Legacy apply path; the presentation setter below is used when present. */
  setActiveToolsByName?: (names: string[]) => Promise<void>;
  /**
   * omp's presentation-aware apply path — the same call the capabilities bridge
   * applies with, so a plan transition and a tool toggle agree on which mounted
   * tools survive the write. Optional: an omp without it falls back to
   * \`setActiveToolsByName\`.
   */
  setActiveToolPresentation?: (
    enabled: string[],
    mounted: string[],
    forcePromptRefresh?: boolean,
  ) => unknown;
  getEnabledToolNames: () => string[];
  /** Mounted xd:// names; absent on an omp with no xdev surface. */
  getMountedXdevToolNames?: () => unknown;
  /** Every tool the session knows, enabled or not: the roster \`write\` is checked in. */
  getAllToolInfos?: () => unknown;
  /**
   * omp's re-entrant registry queue. The capabilities bridge serializes its
   * toggles on it, so a plan transition joins the same queue when the runtime
   * exposes one; its absence never blocks a transition.
   */
  runToolRegistryMutation?: (work: () => Promise<unknown>, signal?: unknown) => unknown;
  hasBuiltInTool?: (name: string) => boolean;
  /** omp's goal state, read only to decide whether Plan may take the mode slot. */
  getGoalModeState?: () => unknown;
  /**
   * Delivers a hidden instruction into the conversation. Unsupported surface
   * like the rest of this session access; absent on an older omp, in which
   * case html plans degrade to markdown.
   */
  sendCustomMessage?: (
    msg: { customType: string; content: string; display: boolean; attribution: string },
    opts: { deliverAs: "steer" | "nextTurn"; triggerTurn: boolean },
  ) => Promise<unknown>;
}

interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  details?: { planFilePath?: string; title?: string };
  isError?: boolean;
}

interface PlanUi {
  setStatus: (key: string, text: string | undefined) => void;
  select: (title: string, options: string[]) => Promise<string | undefined>;
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface PlanExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: PlanUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: PlanExtensionApi) {
  // The first prompting AgentSession. Every command operation runs on it, and
  // no later prompt — descendant or not — may retarget it (ADR-0008 discipline).
  let rootSession: PlanSession | null = null;
  let unavailable: string | undefined;
  let approved = false;
  // Which format the renderer asked for on the last \`on\`. A bare \`on\` typed by
  // hand keeps markdown — the renderer always sends the format explicitly.
  let format: "html" | "md" = "md";
  // Ownership of the one roster change plan mode makes, not a saved roster:
  // true only while THIS mode span added \`write\` to a roster that lacked it,
  // tagged with the session id whose roster was borrowed. Nothing else about
  // the user's tools is remembered, so a toggle made during Plan mode survives
  // the exit in both directions and a new session never has its own \`write\`
  // taken away as though this extension had added it.
  let tempWriteAdded = false;
  let tempWriteSessionId: string | null = null;
  let ui: PlanUi | null = null;
  // Plan mode's on/off flag. Named for what it enforces: while set, the
  // getPlanModeState wrapper below fakes enabled state so omp's own write
  // guard treats the working tree as read-only.
  let readOnly = false;
  // True while the agent holds an entry instruction that has not been retracted.
  // Exit only speaks when there is something to retract, so a session whose omp
  // cannot carry hidden instructions is never told it left a mode it was never
  // told it entered.
  let instructionDelivered = false;
  // The unwrapped prototype method. Every read the extension itself does goes
  // through this, so the extension never sees its own fake.
  let realGetPlanModeState: ((this: PlanSession) => PlanModeState | undefined) | null = null;

  // Bind the root AgentSession. omp hands extensions no reference to it, and
  // the command handler's \`this\` is not the session either, so the prototype
  // prompt wrapper is the only correct place to capture it — first prompt wins.
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (!prototype || typeof originalPrompt !== "function") {
      unavailable = "AgentSession.prototype.prompt is not a function";
    } else {
      const call = originalPrompt as (this: PlanSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: PlanSession, ...args: unknown[]): unknown {
        // Assign once: a subagent or branch session prompting must not move the
        // object every entry/exit transaction runs on.
        if (rootSession === null) rootSession = this;
        return call.apply(this, args);
      };
    }
  } catch (err) {
    unavailable = "could not hook AgentSession: " + String(err);
  }

  // Show omp's write guard a plan-mode session without arming real plan state,
  // which would also arm omp's per-turn plan-authoring mandate (ADR-0013).
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const real = prototype?.getPlanModeState;
    if (!prototype || typeof real !== "function") {
      unavailable = "AgentSession.prototype.getPlanModeState is not a function";
    } else {
      const call = real as (this: PlanSession) => PlanModeState | undefined;
      realGetPlanModeState = call;
      prototype.getPlanModeState = function (this: PlanSession) {
        const state = call.call(this);
        // Real plan state always wins: any omp-internal arming path behaves
        // exactly as it does today.
        if (state?.enabled === true || !readOnly) return state;
        return {
          enabled: true,
          planFilePath: this.getPlanReferencePath?.() || "local://PLAN.md",
          workflow: "parallel",
        };
      };
    }
  } catch (err) {
    unavailable = "could not wrap getPlanModeState: " + String(err);
  }

  const REQUIRED = [
    "getPlanModeState",
    "setPlanModeState",
    "getPlanReferencePath",
    "setPlanReferencePath",
    "setPlanProposalHandler",
    "preparePlanForReview",
    "getEnabledToolNames",
  ] as const;

  /** Null when the session is usable; otherwise the reason it is not. */
  function unusable(): string | undefined {
    if (unavailable) return unavailable;
    const active = rootSession;
    if (!active) return "no active omp session";
    const missing = REQUIRED.filter(name => typeof active[name] !== "function");
    if (missing.length > 0) return "omp session is missing: " + missing.join(", ");
    // At least one apply path must exist; either one is enough to borrow write.
    if (typeof active.setActiveToolPresentation !== "function" &&
      typeof active.setActiveToolsByName !== "function") {
      return "omp session is missing: setActiveToolPresentation, setActiveToolsByName";
    }
    return undefined;
  }

  /** \`local://x.md\` -> absolute path under the session's artifact sandbox. */
  function absolutePlanPath(planFilePath: string | null): string | null {
    if (!planFilePath) return null;
    const artifactsDir = rootSession?.sessionManager?.getArtifactsDir?.();
    if (!artifactsDir) return null;
    const match = /^local:\\/{0,2}(.+)$/.exec(planFilePath);
    if (!match) return null;
    const relative = match[1];
    // Never let a crafted plan name escape the sandbox.
    const root = nodePath.resolve(artifactsDir, "local");
    const resolved = nodePath.resolve(root, relative);
    if (resolved !== root && !resolved.startsWith(root + nodePath.sep)) return null;
    return resolved;
  }

  /**
   * omp's own normalizePlanTitle + planSlugFromSupplied, replicated
   * (plan-mode/approved-plan.ts:21-48, 121-130) so the slug this extension
   * probes for is the same one omp would derive from the propose text.
   * Returns null for a title that sanitizes to nothing.
   */
  function slugFromTitle(title: string): string | null {
    const trimmed = title.trim();
    if (!trimmed) return null;
    if (trimmed.includes("/") || trimmed.includes("\\\\") || trimmed.includes("..")) return null;
    const sanitized = trimmed
      .replace(/\\.(?:md|html)$/i, "")
      .replace(/\\s+/g, "-")
      .replace(/[^A-Za-z0-9_-]/g, "")
      .replace(/-{2,}/g, "-")
      .replace(/^-+|-+$/g, "");
    if (!sanitized) return null;
    return sanitized.replace(/-plan$/i, "") || sanitized;
  }

  /** The session's local:// root, or null when omp exposes no artifacts dir. */
  function localRoot(): string | null {
    const artifactsDir = rootSession?.sessionManager?.getArtifactsDir?.();
    return artifactsDir ? nodePath.resolve(artifactsDir, "local") : null;
  }

  /**
   * Every \`*-plan.html\` basename in the local root, newest first — the
   * fallback for a propose title that does not reconstruct the filename, and
   * the html analogue of omp's own listPlanFiles (plan-mode/plan-files.ts:24).
   */
  function listHtmlPlans(): string[] {
    const root = localRoot();
    if (!root) return [];
    try {
      return nodeFs
        .readdirSync(root, { withFileTypes: true })
        .filter(entry => entry.isFile() && /-plan\\.html$/i.test(entry.name))
        .map(entry => {
          let mtime = 0;
          try {
            mtime = nodeFs.statSync(nodePath.join(root, entry.name)).mtimeMs;
          } catch {
            // An unstattable entry sorts last rather than failing the scan.
          }
          return { name: entry.name, mtime };
        })
        .sort((a, b) => b.mtime - a.mtime)
        .map(entry => entry.name);
    } catch {
      return [];
    }
  }

  /**
   * The html plan a propose title refers to, as a local:// URL, or null when
   * none exists. Tries the slug omp would derive, then the newest html plan on
   * disk — the same precedence omp's resolveApprovedPlan uses for markdown.
   */
  function resolveHtmlPlan(title: string): string | null {
    const candidates: string[] = [];
    const slug = slugFromTitle(title);
    if (slug) candidates.push(slug + "-plan.html");
    for (const name of listHtmlPlans()) {
      if (!candidates.includes(name)) candidates.push(name);
    }
    for (const name of candidates) {
      const abs = absolutePlanPath("local://" + name);
      if (abs && nodeFs.existsSync(abs)) return "local://" + name;
    }
    return null;
  }

  /**
   * Whether this session can drive html plans at all. Both are hard
   * requirements: without sendCustomMessage the agent never learns to write
   * html, and without an artifacts dir no local:// path can be resolved or
   * probed. Either missing degrades the session to md with one warning rather
   * than producing a plan the review pane cannot show.
   */
  function htmlPlansUsable(active: PlanSession): boolean {
    if (typeof active.sendCustomMessage !== "function") return false;
    return localRoot() !== null;
  }

  function publish(): void {
    if (!ui) return;
    const active = rootSession;
    const state = active && realGetPlanModeState ? realGetPlanModeState.call(active) : undefined;
    const enabled = state?.enabled === true || readOnly;
    // \`||\`, not \`??\`: getPlanReferencePath returns "" when no plan is pinned,
    // and the renderer reads a falsy path as "no plan file yet".
    const planFilePath = enabled
      ? (state?.planFilePath || active?.getPlanReferencePath?.() || null)
      : null;
    const status = {
      enabled,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
      approved,
      unavailable: unusable(),
    };
    ui.setStatus(STATUS_KEY, JSON.stringify(status));
  }

  function isString(value: unknown): value is string {
    return typeof value === "string";
  }

  /** The session id omp reports, or null when omp does not say. */
  function sessionIdOf(active: PlanSession | null): string | null {
    const manager = active?.sessionManager;
    const read = manager?.getSessionId;
    if (typeof read !== "function") return null;
    try {
      const id = read.call(manager);
      return typeof id === "string" && id.length > 0 ? id : null;
    } catch {
      return null;
    }
  }

  /**
   * Run \`work\` on the runtime queue the capabilities bridge uses to serialize
   * tool toggles, so a plan transition and a toggle cannot interleave a read
   * with someone else's write. An omp with no queue applies directly — the
   * queue is interop, not a requirement. omp may swallow a handler error inside
   * the queue, so the failure travels out in a closure rather than being
   * trusted from the queue's own resolution.
   */
  async function routeQueue(active: PlanSession, work: () => Promise<void>): Promise<void> {
    const run = active.runToolRegistryMutation;
    if (typeof run !== "function") {
      await work();
      return;
    }
    let ran = false;
    // A box, not a bare \`unknown\`: "nothing thrown" and "thrown undefined" differ.
    let failure: { error: unknown } | null = null;
    try {
      await run.call(active, async () => {
        ran = true;
        try {
          await work();
        } catch (err) {
          failure = { error: err };
        }
      });
    } catch (err) {
      // omp may swallow a work error inside the queue; when the work never even
      // ran, the queue's own rejection is the failure to report.
      if (!ran) failure = { error: err };
    }
    if (failure !== null) throw failure.error;
    // Silence with no work is its own failure: a transition must never report a
    // tool change the queue never made.
    if (!ran) throw new Error("omp's tool registry queue never ran the transition");
  }

  /**
   * The enabled roster as of right now. A roster that is not an array is an
   * error, never an empty list: guessing one would drop every other tool.
   */
  function readEnabled(active: PlanSession): string[] {
    const names = active.getEnabledToolNames() as unknown;
    if (!Array.isArray(names)) throw new Error("getEnabledToolNames answered with no roster");
    return (names as unknown[]).filter(isString);
  }

  /** Mounted xd:// names; an omp with no xdev surface mounts nothing. */
  function readMounted(active: PlanSession): string[] {
    const read = active.getMountedXdevToolNames;
    if (typeof read !== "function") return [];
    const names = read.call(active) as unknown;
    return Array.isArray(names) ? (names as unknown[]).filter(isString) : [];
  }

  /** Whether the roster knows a write tool at all; unknown counts as no. */
  function writeInRoster(active: PlanSession): boolean {
    const list = active.getAllToolInfos;
    if (typeof list === "function") {
      try {
        const infos = list.call(active) as unknown;
        if (Array.isArray(infos)) {
          return (infos as unknown[]).some(info => info !== null && typeof info === "object" &&
            !Array.isArray(info) && (info as Record<string, unknown>).name === WRITE_TOOL);
        }
      } catch {
        /* fall through to the older probe */
      }
    }
    const builtin = active.hasBuiltInTool;
    if (typeof builtin !== "function") return false;
    try {
      return builtin.call(active, WRITE_TOOL) === true;
    } catch {
      return false;
    }
  }

  /**
   * Hand a freshly computed roster to omp: the presentation setter when the
   * runtime has one — the same call the capabilities bridge applies with, which
   * is why the mounted list it gets is the intersection, not the old mounts —
   * and the by-name setter on an omp that predates it.
   */
  async function applyTools(
    active: PlanSession,
    nextEnabled: string[],
    currentMounted: string[],
  ): Promise<void> {
    const present = active.setActiveToolPresentation;
    if (typeof present === "function") {
      const mounted = currentMounted.filter(name => nextEnabled.indexOf(name) >= 0);
      await Promise.resolve(present.call(active, nextEnabled, mounted, false));
      return;
    }
    const byName = active.setActiveToolsByName;
    if (typeof byName !== "function") throw new Error("this omp session can apply no tool roster");
    await byName.call(active, nextEnabled);
  }

  /**
   * Leave plan mode. The only roster change is handing back the write tool this
   * span borrowed, and only while that ownership is still live. A session id
   * change drops the ownership first: the session that borrowed write is gone,
   * its roster went with it, and the current session's own \`write\` — which it
   * may well have had from the start — must never be removed on its behalf, just
   * as no roster from the old session is ever replayed onto the new one.
   * A failed removal aborts the teardown instead of half-finishing it: the
   * guard, the ownership, and the proposal handler all stay so the mode remains
   * coherent and the exit can be retried.
   */
  async function exitPlanMode(
    active: PlanSession,
    options?: { announce?: boolean },
  ): Promise<void> {
    if (tempWriteAdded) {
      await routeQueue(active, async () => {
        if (!tempWriteAdded) return;
        if (sessionIdOf(active) !== tempWriteSessionId) {
          tempWriteAdded = false;
          tempWriteSessionId = null;
          return;
        }
        const enabled = readEnabled(active);
        // Already gone (the user turned it off during Plan): nothing changed,
        // so nothing is applied.
        if (enabled.indexOf(WRITE_TOOL) < 0) {
          tempWriteAdded = false;
          tempWriteSessionId = null;
          return;
        }
        await applyTools(active, enabled.filter(name => name !== WRITE_TOOL), readMounted(active));
        tempWriteAdded = false;
        tempWriteSessionId = null;
      });
    }
    active.setPlanProposalHandler(null);
    // Defensive no-op: this extension never sets real plan state, but an
    // omp-internal path might have, and that would outlive the flag below.
    active.setPlanModeState(undefined);
    readOnly = false;
    active.sessionManager.appendModeChange("none");
    // The execute path answers the agent with a ToolResult that already says
    // plan mode exited, and the agent is blocked mid-turn inside its own
    // proposal — a steer there would land beside that answer.
    if (options?.announce === false) {
      instructionDelivered = false;
      return;
    }
    await sendExitInstruction(active);
  }

  /**
   * Installed while plan mode is active; \`xd://propose\` dispatches the plan
   * title here. Blocks the agent on the renderer's answer, so a plan is never
   * executed without a decision.
   *
   * Under html the extension resolves the artifact itself: omp's
   * preparePlanForReview routes through resolveApprovedPlan, which is
   * hardcoded to \`local://<slug>-plan.md\`. Nothing upstream requires that
   * call — the propose device only invokes this handler
   * (tools/resolve.ts:303-311) — so the html path skips it (ADR-0014). An html
   * session whose agent wrote markdown anyway still falls through to omp's
   * resolver rather than stranding the gate.
   */
  async function onProposal(active: PlanSession, dialog: PlanUi, title: string): Promise<ToolResult> {
    let planFilePath: string | null = format === "html" ? resolveHtmlPlan(title) : null;
    let details: { planFilePath?: string; title?: string } = {};

    if (planFilePath !== null) {
      details = { planFilePath, title };
    } else {
      try {
        const result = await active.preparePlanForReview(title);
        details = result.details ?? {};
        planFilePath = details.planFilePath ?? active.getPlanReferencePath() ?? null;
        if (planFilePath === "") planFilePath = null;
      } catch (err) {
        // md is omp's own contract: its ToolError is the right answer. Under
        // html the agent was told to write html, so answer in that spelling.
        if (format !== "html") throw err;
        planFilePath = null;
      }
      if (planFilePath === null) {
        const slug = slugFromTitle(title);
        publish();
        return {
          isError: true,
          content: [
            {
              type: "text",
              text:
                "No plan file found for \\"" + title + "\\". Write the finalized plan to local://" +
                (slug ?? "<slug>") +
                "-plan.html with the write tool, then write the same slug to xd://propose again.",
            },
          ],
        };
      }
    }

    const request = {
      title: details.title ?? title,
      planFilePath,
      planAbsPath: absolutePlanPath(planFilePath),
    };

    let answer: string | undefined;
    try {
      answer = await dialog.select(REVIEW_SENTINEL + JSON.stringify(request), [EXECUTE, REFINE]);
    } catch {
      // A dropped dialog is a refusal, never a silent approval.
      answer = undefined;
    }

    if (answer !== EXECUTE) {
      // Refinement keeps plan mode active for another turn. Nothing to promote
      // into plan state: the ToolResult below names the file to revise.
      publish();
      return {
        content: [
          {
            type: "text",
            text:
              "Plan refinement requested. The user's revision notes may arrive as a " +
              "follow-up message; incorporate them, revise " +
              planFilePath +
              ", then write its title to xd://propose again when ready.",
          },
        ],
        details,
      };
    }

    // Accepted: pin the plan as the session's reference so whichever
    // implementation context the renderer chooses can read it, then leave plan
    // mode so write access returns. Crucially the agent does NOT implement
    // here — the renderer issues a separate implementation prompt (same
    // session, compacted, or a fresh session), so stop and wait for it.
    active.setPlanReferencePath(planFilePath);
    await exitPlanMode(active, { announce: false });
    approved = true;
    publish();
    return {
      content: [
        {
          type: "text",
          text:
            "Plan accepted and pinned as the reference at " +
            planFilePath +
            ". Plan mode exited. Do NOT start the implementation yet — a separate " +
            "implementation prompt will be issued. Stop and wait for it.",
        },
      ],
      details,
    };
  }

  async function enterPlanMode(active: PlanSession): Promise<void> {
    const planFilePath = active.getPlanReferencePath() || "local://PLAN.md";
    // A fresh span owns nothing yet, whatever an unfinished earlier span left.
    tempWriteAdded = false;
    tempWriteSessionId = null;
    // \`write\` is not the guard — omp's own plan-mode write guard is — but the
    // plan file still has to be writable, so the mode borrows that one tool name
    // from the roster exactly as it reads right now. No roster is snapshotted:
    // every other name belongs to the user and to the capabilities bridge.
    await routeQueue(active, async () => {
      const enabled = readEnabled(active);
      if (enabled.indexOf(WRITE_TOOL) >= 0) return;
      if (!writeInRoster(active)) return;
      await applyTools(active, enabled.concat(WRITE_TOOL), readMounted(active));
      tempWriteAdded = true;
      tempWriteSessionId = sessionIdOf(active);
    });
    readOnly = true;
    active.setPlanProposalHandler(title => {
      const dialog = ui;
      // Plan mode is only reachable through the command that sets \`ui\`.
      if (!dialog) throw new Error("omp-ui plan mode has no UI channel");
      return onProposal(active, dialog, title);
    });
    active.sessionManager.appendModeChange("plan", { planFilePath });
    // Decide the format before the instruction: it is the instruction that
    // tells the agent which single file to write.
    if (format === "html" && !htmlPlansUsable(active)) {
      format = "md";
      ui?.notify(HTML_UNAVAILABLE, "warning");
    }
    await sendModeInstruction(active);
  }

  /**
   * Delivers the read-only plan-mode instruction. The mode stays armed when
   * this fails: read-only is enforced by omp's write guard, not by the message,
   * so a session that cannot carry hidden instructions is still read-only — it
   * just loses the steering that keeps the agent from planning unprompted.
   */
  async function sendModeInstruction(active: PlanSession): Promise<void> {
    if (typeof active.sendCustomMessage !== "function") {
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
      return;
    }
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-mode",
          content: planModeInstruction(format),
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
      instructionDelivered = true;
    } catch {
      // The html instruction never landed, so the agent will follow omp's own
      // markdown guidance — the session must follow it too.
      if (format === "html") {
        format = "md";
        ui?.notify(HTML_UNAVAILABLE, "warning");
      }
      ui?.notify(MODE_INSTRUCTION_UNAVAILABLE, "warning");
    }
  }

  /**
   * Retracts the entry instruction. Best effort and silent: the guard is already
   * down by the time this runs, and the next entry instruction supersedes any
   * stale copy, so a delivery failure must never fail the exit or warn.
   */
  async function sendExitInstruction(active: PlanSession): Promise<void> {
    if (!instructionDelivered) return;
    instructionDelivered = false;
    if (typeof active.sendCustomMessage !== "function") return;
    try {
      await active.sendCustomMessage(
        {
          customType: "omp-ui:plan-mode-exit",
          content: PLAN_MODE_EXIT_INSTRUCTION,
          display: false,
          attribution: "agent",
        },
        { deliverAs: active.isStreaming ? "steer" : "nextTurn", triggerTurn: false },
      );
    } catch {
      // Deliberately silent — see the doc comment.
    }
  }

  // omp dispatches each /omp-ui-plan through AgentSession.prototype.prompt without
  // waiting for the previous one, so two quick toggles interleave: an "off" that
  // lands while "on" is awaiting its tool apply reads a still-false readOnly,
  // decides it is a no-op, publishes enabled:false while the mode arms behind it,
  // and is swallowed (issue #118). One chain keeps transitions in arrival order.
  let chain: Promise<void> = Promise.resolve();

  function serialize(work: () => Promise<void>): Promise<void> {
    const next = chain.then(work, work);
    // A failed toggle must not wedge every later one.
    chain = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  // Plan entry and goal activation are one decision, not two: whichever bridge
  // loaded first owns the queue under this realm-wide symbol, and both enter it
  // before they touch a mode. Without it, a model-originated \`goal create\` and
  // a Plan toggle can both pass their own check and leave the session in a mode
  // whose persisted slot says something else.
  function transitions(): { queue: Promise<void> } {
    const key = Symbol.for(TRANSITION_KEY);
    const global = globalThis as unknown as Record<symbol, unknown>;
    const existing = global[key];
    if (existing !== null && typeof existing === "object" && "queue" in existing) {
      const box = existing as { queue: unknown };
      if (box.queue instanceof Promise) return box as unknown as { queue: Promise<void> };
      const fresh = { queue: Promise.resolve() };
      box.queue = fresh.queue;
      return fresh;
    }
    const created = { queue: Promise.resolve() };
    try {
      global[key] = created;
    } catch {
      /* a runtime that refuses new symbols keeps the local chain below */
    }
    return created;
  }

  function inTransition(work: () => Promise<void>): Promise<void> {
    const box = transitions();
    const next = box.queue.then(work, work);
    box.queue = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  /**
   * An unfinished goal — paused or budget-limited included — blocks Plan entry:
   * omp persists one mode slot, and entering Plan would silently overwrite the
   * slot a resumable goal lives in. A completed goal blocks nothing.
   */
  function goalBlocksPlan(active: PlanSession): string | null {
    const read = active.getGoalModeState;
    if (typeof read !== "function") return null;
    let state: unknown;
    try {
      state = read.call(active);
    } catch {
      return null;
    }
    if (state === null || typeof state !== "object" || !("goal" in state)) return null;
    const goal: unknown = state.goal;
    if (goal === null || typeof goal !== "object" || !("status" in goal)) return null;
    const status: unknown = goal.status;
    if (status === undefined || status === "complete" || status === "dropped") return null;
    return PLAN_GOAL_BLOCK;
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui plan mode control",
    handler: (args: string, ctx: { ui: PlanUi }) =>
      serialize(async () => {
        ui = ctx.ui;
        const reason = unusable();
        const active = rootSession;
        if (reason || !active) {
          publish();
          ctx.ui.notify("Plan mode unavailable: " + (reason ?? "no active omp session"), "error");
          return;
        }
        // \`on|off\` then an optional format; absent verb toggles.
        const tokens = args.trim().toLowerCase().split(/\\s+/).filter(t => t !== "");
        const on = realGetPlanModeState?.call(active)?.enabled === true || readOnly;
        const next = tokens[0] === "on" ? true : tokens[0] === "off" ? false : !on;
        if (tokens[1] === "html" || tokens[1] === "md") format = tokens[1];
        if (next === on) {
          publish();
          return;
        }
        // Entry and exit join the shared chain *inside* this command's own
        // serialization: arrival order among toggles stays ours, and the mode
        // decision itself is the one every other bridge makes.
        if (next) {
          const blocked = await inTransition(async () => {
            const reason = goalBlocksPlan(active);
            if (reason !== null) return reason;
            await enterPlanMode(active);
            return null;
          });
          if (blocked !== null) {
            publish();
            ctx.ui.notify(blocked, "warning");
            return;
          }
        } else {
          await inTransition(() => exitPlanMode(active));
        }
        publish();
      }),
  });
}
`;
}

/**
 * Writes the plan extension into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an older
 * omp-ui build can never outvote the current wire contract.
 */
export function writePlanExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, planExtensionPath(lineageDir), extensionSource());
}
