import * as path from "node:path";
import {
  CODE_REVIEW_COMMAND,
  CODE_REVIEW_TOOL,
  CODE_REVIEW_USAGE,
  COMMIT_TARGET_COMMANDS,
  LOCAL_MERGE_BASE_COMMANDS,
  LOCAL_PARENT_COMMANDS,
  LOCAL_ROOT_COMMANDS,
  PR_TARGET_COMMANDS,
  RANGE_TARGET_COMMANDS,
  REVIEW_PLAYBOOK,
} from "./review";
import { REVIEW_ROSTER_SNAPSHOT_VERSION, reviewRosterSnapshotPath } from "./review-roster-snapshot";
import { writeLineageArtifact } from "./lineage-artifact";
import { generatedAsRecordSource } from "./generated-extension-source";

/**
 * The generated `/code-review` bridge (issue #728, ADR-0047 as amended). Both
 * surfaces — the slash command and the model-callable tool — read the roster
 * snapshot main wrote at spawn, resolve the target once with async git/gh
 * probes, and hand the launch to the model with `pi.sendMessage`
 * (deliverAs nextTurn, triggerTurn true): the binary exposes no callTool on
 * any extension ctx (probed against 18.6.0), so the model makes the single
 * batch `task` call, exactly like autoresearch's proposal flow. The batch
 * JSON rides inert-fenced so nothing in the repo's refs or roster can arm
 * magic keywords on the way through.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-code-review.ts";

export function reviewExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

function extensionSource(snapshotPath: string): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodeFs from "node:fs";
import * as nodeChildProcess from "node:child_process";

const COMMAND = ${JSON.stringify(CODE_REVIEW_COMMAND)};
const TOOL = ${JSON.stringify(CODE_REVIEW_TOOL)};
const USAGE = ${JSON.stringify(CODE_REVIEW_USAGE)};
const PLAYBOOK = ${JSON.stringify(REVIEW_PLAYBOOK)};
const LOCAL_MERGE_BASE = ${JSON.stringify(LOCAL_MERGE_BASE_COMMANDS)};
const LOCAL_PARENT = ${JSON.stringify(LOCAL_PARENT_COMMANDS)};
const LOCAL_ROOT = ${JSON.stringify(LOCAL_ROOT_COMMANDS)};
const COMMIT_TARGET = ${JSON.stringify(COMMIT_TARGET_COMMANDS)};
const RANGE_TARGET = ${JSON.stringify(RANGE_TARGET_COMMANDS)};
const PR_TARGET = ${JSON.stringify(PR_TARGET_COMMANDS)};
const SNAPSHOT_PATH = ${JSON.stringify(snapshotPath)};
const SNAPSHOT_VERSION = ${REVIEW_ROSTER_SNAPSHOT_VERSION};
const LAUNCH_TYPE = "omp-ui-code-review-launch";

const NAME_RE = /^[A-Za-z0-9._/@][A-Za-z0-9._/@^{}~/-]{0,254}$/;
const TARGET_KINDS = ["local", "commit", "pr"];

interface ZodFn {
  (...args: unknown[]): ZodFn;
  describe: (text: string) => ZodFn;
  optional: () => ZodFn;
  nullable: () => ZodFn;
}

interface ExtensionApi {
  cwd?: string;
  zod?: Record<string, (...args: unknown[]) => ZodFn>;
  sendMessage?: (message: Record<string, unknown>, options?: Record<string, unknown>) => Promise<unknown>;
  registerCommand: (
    name: string,
    options: { description?: string; handler: (args: string, ctx: Record<string, unknown>) => Promise<void> },
  ) => void;
  registerTool?: (definition: {
    name: string;
    label: string;
    description: string;
    parameters: unknown;
    execute: (
      toolCallId: string,
      params: unknown,
      signal: AbortSignal | undefined,
      onUpdate: unknown,
      ctx: Record<string, unknown> | undefined,
    ) => Promise<{ content: Array<{ type: "text"; text: string }>; isError?: boolean }>;
  }) => void;
}

export default function (pi: ExtensionApi): void {

${generatedAsRecordSource()}

type Target =
  | { kind: "local" }
  | { kind: "commit"; ref: string }
  | { kind: "range"; ref: string; from: string; to: string }
  | { kind: "pr"; number: string };

interface SnapshotEntry { name: string; model: string | null; instructions: string | null; targets: string[] | null }
interface Snapshot { instructions: string | null; reviewers: SnapshotEntry[]; configWarnings: string[] }

function fill(template: string, values: Record<string, string>): string {
  return template.replace(/@@([A-Z_]+)@@/g, (whole, key: string) => values[key] ?? whole);
}

function targetLabel(target: Target): string {
  if (target.kind === "local") return "local changes";
  if (target.kind === "pr") return "pull request #" + target.number;
  return target.ref;
}

// --- argument classification: the single implementation for command and tool.
const PR_USAGE = "usage: /code-review pr <number>";

/** A commit-or-range value; null when it is not one. \`A...B\` and multi-\`..\` values are rejected. */
function classifyRef(value: string): Target | null {
  if (!NAME_RE.test(value) || value.includes("...")) return null;
  const dots = value.indexOf("..");
  if (dots < 0) return { kind: "commit", ref: value };
  const fromRaw = value.slice(0, dots);
  const toRaw = value.slice(dots + 2);
  if (toRaw.includes("..") || (fromRaw === "" && toRaw === "")) return null;
  return { kind: "range", ref: value, from: fromRaw === "" ? "HEAD" : fromRaw, to: toRaw === "" ? "HEAD" : toRaw };
}

function parseArgs(args: string): { target: Target } | { usage: string } {
  const text = args.trim();
  if (text === "") return { target: { kind: "local" } };
  if (text === "pr") return { usage: PR_USAGE };
  const pr = /^pr\\s+(\\S+)$/u.exec(text);
  if (pr !== null) return /^[1-9][0-9]*$/.test(pr[1]!) ? { target: { kind: "pr", number: pr[1]! } } : { usage: PR_USAGE };
  if (/\\s/u.test(text)) return { usage: USAGE };
  const ref = classifyRef(text);
  return ref === null ? { usage: USAGE } : { target: ref };
}

// --- inert fencing (magic-keywords.ts inertBlock): a fence one backtick
// longer than any run inside, so nothing in the JSON can escape it.
function longestBacktickRun(text: string): number {
  let longest = 0;
  let run = 0;
  for (let i = 0; i < text.length; i++) {
    run = text[i] === "\`" ? run + 1 : 0;
    if (run > longest) longest = run;
  }
  return longest;
}

function inertBlock(text: string): string {
  const fence = "\`".repeat(Math.max(3, longestBacktickRun(text) + 1));
  return fence + "json\\n" + text + "\\n" + fence;
}

// --- process runner: async and cancellable, so a slow repo never blocks omp.
interface RunResult { ok: boolean; code: number | string | null; stdout: string; stderr: string }

/** Rejects only on abort; every other failure resolves with ok=false. stdin is closed at once. */
function run(cmd: string, args: string[], cwd: string, signal: AbortSignal | undefined, timeoutMs: number): Promise<RunResult> {
  return new Promise((resolve, reject) => {
    const child = nodeChildProcess.execFile(
      cmd,
      args,
      { cwd, encoding: "utf8", timeout: timeoutMs, maxBuffer: 4 * 1024 * 1024, signal, windowsHide: true },
      (error, stdout, stderr) => {
        if (error !== null && error.name === "AbortError") return reject(error);
        const code = error === null ? 0 : typeof error.code === "number" || typeof error.code === "string" ? error.code : null;
        resolve({ ok: code === 0, code, stdout, stderr });
      },
    );
    child.stdin?.end();
  });
}

const GIT_TIMEOUT = 10000;
const GH_TIMEOUT = 20000;
const git = (cwd: string, args: string[], signal: AbortSignal | undefined): Promise<RunResult> =>
  run("git", args, cwd, signal, GIT_TIMEOUT);

function firstLine(text: string): string {
  return text.trim().split("\\n")[0] ?? "";
}

/** The full commit id \`ref\` names, or null. */
async function commitOf(cwd: string, ref: string, signal: AbortSignal | undefined): Promise<string | null> {
  const r = await git(cwd, ["rev-parse", "--verify", "-q", ref + "^{commit}"], signal);
  return r.ok ? r.stdout.trim() : null;
}

function safeJson(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

// --- target resolution: once, to concrete commit ids every reviewer shares.
type Resolved = { ok: true; brief: string; note: string } | { ok: false; message: string };

const BASE_CANDIDATES = ["@{upstream}", "origin/HEAD", "origin/main", "origin/master", "main", "master"];

async function resolveLocal(cwd: string, signal: AbortSignal | undefined): Promise<Resolved> {
  const head = await commitOf(cwd, "HEAD", signal);
  let base: string | null = null;
  let brief = "";
  let note = "";
  if (head !== null) {
    for (const candidate of BASE_CANDIDATES) {
      const mb = await git(cwd, ["merge-base", "HEAD", candidate], signal);
      if (!mb.ok) continue;
      base = mb.stdout.trim();
      let ref = candidate;
      if (candidate === "@{upstream}") {
        const name = await git(cwd, ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"], signal);
        if (name.ok && name.stdout.trim() !== "") ref = name.stdout.trim();
      }
      brief = fill(LOCAL_MERGE_BASE, { BASE: base, REF: ref });
      note = "against the merge-base with " + ref + " (" + base.slice(0, 8) + ")";
      break;
    }
    if (base === null) {
      const parent = await commitOf(cwd, "HEAD~1", signal);
      if (parent !== null) {
        base = parent;
        brief = fill(LOCAL_PARENT, { BASE: base });
        note = "against HEAD's parent (" + base.slice(0, 8) + "); no upstream or default branch shares history";
      }
    }
  }
  if (base === null) {
    const tree = await git(cwd, ["hash-object", "-t", "tree", "--stdin"], signal);
    if (!tree.ok) return { ok: false, message: "Could not compute git's empty tree: " + firstLine(tree.stderr) };
    base = tree.stdout.trim();
    brief = fill(LOCAL_ROOT, { BASE: base });
    note = "against the empty tree (no parent commit)";
  }
  const diff = await git(cwd, ["diff", "--quiet", base], signal);
  if (diff.code !== 0 && diff.code !== 1) return { ok: false, message: "git diff failed: " + firstLine(diff.stderr) };
  const untracked = await git(cwd, ["ls-files", "--others", "--exclude-standard", "--full-name", "--", ":/"], signal);
  if (!untracked.ok && untracked.stdout === "") {
    return { ok: false, message: "git ls-files failed: " + firstLine(untracked.stderr) };
  }
  if (diff.code === 0 && untracked.stdout.trim() === "") {
    return { ok: false, message: "Nothing to review: no changes " + note + "." };
  }
  return { ok: true, brief, note };
}

async function resolveTarget(target: Target, cwd: string, signal: AbortSignal | undefined): Promise<Resolved> {
  if (target.kind === "local") return resolveLocal(cwd, signal);
  if (target.kind === "commit") {
    const sha = await commitOf(cwd, target.ref, signal);
    if (sha === null) return { ok: false, message: "Not a commit in this repository: " + target.ref };
    return { ok: true, brief: fill(COMMIT_TARGET, { SHA: sha, REF: target.ref }), note: "(" + sha.slice(0, 8) + ")" };
  }
  if (target.kind === "range") {
    const from = await commitOf(cwd, target.from, signal);
    if (from === null) return { ok: false, message: "Not a commit in this repository: " + target.from };
    const to = await commitOf(cwd, target.to, signal);
    if (to === null) return { ok: false, message: "Not a commit in this repository: " + target.to };
    const mb = await git(cwd, ["merge-base", from, to], signal);
    if (!mb.ok) return { ok: false, message: target.from + " and " + target.to + " share no history." };
    const count = await git(cwd, ["rev-list", "--count", from + ".." + to], signal);
    if (count.ok && count.stdout.trim() === "0") {
      return { ok: false, message: "Nothing to review: " + target.ref + " carries no commits." };
    }
    return {
      ok: true,
      brief: fill(RANGE_TARGET, { REF: target.ref, FROM: from, TO: to }),
      note: "(" + from.slice(0, 8) + "..." + to.slice(0, 8) + ")",
    };
  }
  // An abort rejects out of run() and propagates to runReview's catch.
  const view = await run("gh", ["pr", "view", target.number, "--json", "headRefOid,baseRefName"], cwd, signal, GH_TIMEOUT);
  if (view.code === "ENOENT") {
    return { ok: false, message: "/" + COMMAND + " pr needs the GitHub CLI (gh), installed and authenticated." };
  }
  if (!view.ok) return { ok: false, message: "gh could not read pull request #" + target.number + ": " + firstLine(view.stderr) };
  const data = asRecord(safeJson(view.stdout));
  const head = typeof data?.headRefOid === "string" ? data.headRefOid : "";
  const baseRef = typeof data?.baseRefName === "string" ? data.baseRefName : "";
  if (!/^[0-9a-f]{40,64}$/.test(head) || !NAME_RE.test(baseRef)) {
    return { ok: false, message: "gh returned an unreadable answer for pull request #" + target.number + "." };
  }
  return {
    ok: true,
    brief: fill(PR_TARGET, { PR: target.number, HEAD: head, BASE_REF: baseRef }),
    note: "(head " + head.slice(0, 8) + " into " + baseRef + ")",
  };
}

// --- the roster: main's spawn-time snapshot, never YAML here.
const SNAPSHOT_MISSING =
  "The reviewer roster was not loaded for this session; restart the session to load REVIEW.yml.";

function readSnapshot(): Snapshot | null {
  let raw: unknown;
  try {
    raw = JSON.parse(nodeFs.readFileSync(SNAPSHOT_PATH, "utf8"));
  } catch {
    return null;
  }
  const doc = asRecord(raw);
  if (doc === null || doc.version !== SNAPSHOT_VERSION || !Array.isArray(doc.reviewers) || !Array.isArray(doc.configWarnings)) return null;
  const strOrNull = (v: unknown): v is string | null => v === null || typeof v === "string";
  const instructions = doc.instructions;
  if (!strOrNull(instructions)) return null;
  const reviewers: SnapshotEntry[] = [];
  for (const item of doc.reviewers) {
    const r = asRecord(item);
    if (r === null || typeof r.name !== "string" || !/^[a-z][a-z0-9-]*$/.test(r.name)) return null;
    const model = r.model;
    const entryInstructions = r.instructions;
    if (!strOrNull(model) || !strOrNull(entryInstructions)) return null;
    const targets = r.targets;
    if (targets !== null && !(Array.isArray(targets) && targets.every((t) => TARGET_KINDS.includes(String(t))))) return null;
    reviewers.push({ name: r.name, model, instructions: entryInstructions, targets: targets === null ? null : targets.map(String) });
  }
  return { instructions, reviewers, configWarnings: doc.configWarnings.map(String) };
}

// --- launch
type TextResult = { content: Array<{ type: "text"; text: string }>; isError?: boolean };
type Outcome = { result: TextResult; level: "info" | "warning" | "error" };

function toolResult(text: string, isError: boolean): TextResult {
  return isError ? { content: [{ type: "text", text }], isError: true } : { content: [{ type: "text", text }] };
}

const fail = (text: string): Outcome => ({ result: toolResult(text, true), level: "error" });

async function runReview(target: Target, cwd: string, signal: AbortSignal | undefined): Promise<Outcome> {
  const roster = readSnapshot();
  if (roster === null) return fail(SNAPSHOT_MISSING);
  const warnings = roster.configWarnings.length === 0 ? "" : " Config warnings: " + roster.configWarnings.join("; ");
  if (roster.reviewers.length === 0) {
    return fail("The reviewer roster is empty: REVIEW.yml enables no valid reviewer." + warnings);
  }
  // A range answers to REVIEW.yml's \`commit\` targets kind.
  const kind = target.kind === "range" ? "commit" : target.kind;
  const selected = roster.reviewers.filter((r) => r.targets === null || r.targets.includes(kind));
  if (selected.length === 0) {
    return fail("No enabled reviewer covers " + kind + " targets; widen a reviewer's targets in REVIEW.yml.");
  }
  try {
    const inside = await git(cwd, ["rev-parse", "--is-inside-work-tree"], signal);
    if (!inside.ok) return fail("/" + COMMAND + " needs a git checkout; this cwd is not one.");
    const resolved = await resolveTarget(target, cwd, signal);
    if (!resolved.ok) return fail(resolved.message);
    if (signal?.aborted === true) return fail("Code review cancelled before launch.");
    if (typeof pi.sendMessage !== "function") return fail("This omp cannot start the reviewers turn.");
    const diff = "## Diff target\\n" + resolved.brief;
    const tasks = selected.map((r) => {
      const task: Record<string, unknown> = {
        name: "review-" + r.name,
        task: [PLAYBOOK, r.instructions ?? "", diff].filter((s) => s !== "").join("\\n\\n"),
      };
      if (r.model !== null) task.model = r.model;
      return task;
    });
    const batch = {
      context:
        "Code review roster (omp-ui /" + COMMAND + "). " +
        (roster.instructions ?? "Report defects in the diff only; every finding must cite a file and line from the diff."),
      tasks,
    };
    const prompt =
      "The user ran /" + COMMAND + " on " + targetLabel(target) + "; the reviewer roster has " + tasks.length +
      " entries. Call the \`task\` tool exactly once with these batch arguments, unchanged, then stop and wait: " +
      "the reviewer results arrive on their own turn later.\\n" +
      inertBlock(JSON.stringify(batch)) +
      "\\nWhen the batch call returns, report its job receipt. Never edit files yourself and never post to GitHub.";
    try {
      await pi.sendMessage({ customType: LAUNCH_TYPE, content: prompt, display: false }, { deliverAs: "nextTurn", triggerTurn: true });
    } catch (error) {
      return fail("The launch send failed: " + String(error));
    }
    const pinned = selected.filter((r) => r.model !== null).length;
    const text =
      "Queued " + selected.length + " reviewer(s) on " + targetLabel(target) + " " + resolved.note +
      (pinned > 0 ? ", " + pinned + " model-pinned" : "") +
      ". The session model starts them on its next turn; findings arrive as background results.";
    return {
      result: toolResult(text + warnings, false),
      level: warnings === "" ? "info" : "warning",
    };
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") return fail("Code review cancelled before launch.");
    throw error;
  }
}

pi.registerCommand(COMMAND, {
  description: "Review code with the REVIEW.yml roster as background agents",
  handler: async (args: string, ctx: Record<string, unknown>) => {
    const cwd = typeof ctx.cwd === "string" ? ctx.cwd : pi.cwd ?? process.cwd();
    const parsed = parseArgs(args);
    const outcome = "usage" in parsed ? fail(parsed.usage) : await runReview(parsed.target, cwd, undefined);
    const ui = asRecord(ctx.ui);
    const notify = ui?.notify;
    const text = outcome.result.content[0]!.text;
    if (typeof notify === "function") notify.call(ui, text, outcome.level);
    else process.stdout.write(text + "\\n");
  },
});

const zod = pi.zod;
if (typeof pi.registerTool === "function" && typeof zod?.object === "function") {
  pi.registerTool({
    name: TOOL,
    label: "code review",
    description:
      "Launch the project's code-review roster (REVIEW.yml) as background reviewer agents. " +
      "target: omit for local changes against the upstream or default branch; " +
      "{kind:'commit',value:'<ref>' or '<from>..<to>'} for a commit or range; " +
      "{kind:'pr',value:'<number>'} for a GitHub pull request. Reviewers never edit files or post anywhere. " +
      "The roster is the one loaded when the session started.",
    parameters: zod.object({
      target: zod
        .object({ kind: zod.string(), value: zod.string().nullable().optional() })
        .nullable()
        .optional()
        .describe("What to review; omit for local changes"),
    }),
    execute: async (
      _id: string,
      params: unknown,
      signal: AbortSignal | undefined,
      _onUpdate: unknown,
      ctx: Record<string, unknown> | undefined,
    ): Promise<TextResult> => {
      const p = asRecord(params) ?? {};
      const t = asRecord(p.target);
      const kind = t === null || t.kind === undefined || t.kind === null ? "local" : String(t.kind);
      if (!TARGET_KINDS.includes(kind)) return toolResult("target.kind must be local, commit, or pr", true);
      const value = t === null || t.value === undefined || t.value === null ? null : String(t.value);
      if (kind === "local" && value !== null) return toolResult("a local target carries no value", true);
      if (kind !== "local" && value === null) return toolResult("target.value is required for " + kind, true);
      let target: Target;
      if (kind === "local") target = { kind: "local" };
      else if (kind === "commit") {
        const ref = classifyRef(value!);
        if (ref === null) return toolResult("target.value must be a ref, sha, or <from>..<to> range", true);
        target = ref;
      } else {
        if (!/^[1-9][0-9]*$/.test(value!)) return toolResult("target.value must be a positive pull request number", true);
        target = { kind: "pr", number: value! };
      }
      const toolCtx = asRecord(ctx);
      const cwd = typeof toolCtx?.cwd === "string" ? toolCtx.cwd : pi.cwd ?? process.cwd();
      return (await runReview(target, cwd, signal)).result;
    },
  });
}
}
`;
}

/**
 * Writes the code-review bridge into the lineage dir and returns its path, to
 * be passed to omp as `-e`. Rewritten on every spawn so a stale copy can
 * never outvote the current wire contract.
 */
export function writeReviewExtension(lineageDir: string): string {
  return writeLineageArtifact(
    lineageDir,
    reviewExtensionPath(lineageDir),
    extensionSource(reviewRosterSnapshotPath(lineageDir)),
  );
}
