import * as path from "node:path";
import {
  CODE_REVIEW_COMMAND,
  CODE_REVIEW_TOOL,
  CODE_REVIEW_USAGE,
  COMMIT_RANGE_COMMANDS,
  COMMIT_TARGET_COMMANDS,
  LOCAL_TARGET_COMMANDS,
  LOCAL_TARGET_COMMANDS_DEGRADED,
  PR_TARGET_COMMANDS,
  REVIEW_PLAYBOOK,
  TARGET_VALUE_TOKEN,
} from "./review";
import { DEFAULT_REVIEWER, REVIEW_FILE_NAMES } from "./review-config";
import { writeLineageArtifact } from "./lineage-artifact";
import { generatedAsRecordSource } from "./generated-extension-source";

/**
 * The generated `/code-review` bridge (issue #728, ADR-0047). Both surfaces —
 * the slash command and the model-callable tool — compose the reviewer batch
 * and hand the launch to the model with `pi.sendMessage`
 * (deliverAs nextTurn, triggerTurn true): the binary exposes no callTool on
 * any extension ctx (probed against 18.6.0), so the model makes the single
 * batch `task` call, exactly like autoresearch's proposal flow. The batch
 * JSON rides inert-fenced so nothing in the repo's refs or roster can arm
 * magic keywords on the way through.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-code-review.ts";

export function reviewExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodeFs from "node:fs";
import * as nodeOs from "node:os";
import * as nodePath from "node:path";
import * as nodeChildProcess from "node:child_process";

const COMMAND = ${JSON.stringify(CODE_REVIEW_COMMAND)};
const TOOL = ${JSON.stringify(CODE_REVIEW_TOOL)};
const USAGE = ${JSON.stringify(CODE_REVIEW_USAGE)};
const TOKEN = ${JSON.stringify(TARGET_VALUE_TOKEN)};
const PLAYBOOK = ${JSON.stringify(REVIEW_PLAYBOOK)};
const LOCAL_TARGET = ${JSON.stringify(LOCAL_TARGET_COMMANDS)};
const LOCAL_TARGET_DEGRADED = ${JSON.stringify(LOCAL_TARGET_COMMANDS_DEGRADED)};
const COMMIT_TARGET = ${JSON.stringify(COMMIT_TARGET_COMMANDS)};
const COMMIT_RANGE = ${JSON.stringify(COMMIT_RANGE_COMMANDS)};
const PR_TARGET = ${JSON.stringify(PR_TARGET_COMMANDS)};
const DEFAULT_NAME = ${JSON.stringify(DEFAULT_REVIEWER.name)};
const FILE_NAMES = ${JSON.stringify(REVIEW_FILE_NAMES)};
const LAUNCH_TYPE = "omp-ui-code-review-launch";

const REF_RE = /^[0-9a-f]{7,40}(\\.[.][0-9a-f]{7,40})?$/;
const NAME_RE = /^[A-Za-z0-9._/@][A-Za-z0-9._/@^{}~/-]{0,254}$/;
const MAX_WALK = 64;
const MAX_STRING = 64 * 1024;
const MAX_REVIEWERS = 64;
const TARGET_KINDS = ["local", "commit", "pr"];

interface ReviewEntry {
  name: string;
  model: string | null;
  instructions: string | null;
  targets: string[] | null;
  enabled: boolean;
}

interface RosterResult {
  reviewers: ReviewEntry[];
  instructions: string | null;
  warnings: string[];
}

interface ZodFn {
  (...args: unknown[]): ZodFn;
  describe: (text: string) => ZodFn;
  optional: () => ZodFn;
  nullable: () => ZodFn;
}

interface ExtensionApi {
  cwd?: string;
  zod?: Record<string, (...args: unknown[]) => ZodFn>;
  sendMessage?: (message: Record<string, unknown>, options?: Record<string, unknown>) => Promise<unknown>;
  registerCommand: (
    name: string,
    options: { description?: string; handler: (args: string, ctx: Record<string, unknown>) => Promise<void> },
  ) => void;
  registerTool?: (definition: {
    name: string;
    label: string;
    description: string;
    parameters: unknown;
    execute: (
      toolCallId: string,
      params: unknown,
      signal: AbortSignal | undefined,
      onUpdate: unknown,
      ctx: Record<string, unknown> | undefined,
    ) => Promise<{ content: Array<{ type: "text"; text: string }>; isError?: boolean }>;
  }) => void;
}

export default function (pi: ExtensionApi): void {

${generatedAsRecordSource()}

function trimmed(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function fillTemplate(template: string, value: string): string {
  return template.split(TOKEN).join(value);
}

/** Same grammar as parseReviewArgs in core/review.ts; usage strings match. */
function parseArgs(args: string): { target: { kind: string; value: string | null } } | { usage: string } {
  const trimmedArgs = args.trim();
  if (trimmedArgs === "") return { target: { kind: "local", value: null } };
  const pr = /^pr(?:\\s+([1-9][0-9]*))$/u.exec(trimmedArgs);
  if (pr !== null) return { target: { kind: "pr", value: pr[1] } };
  if (/^pr$/u.test(trimmedArgs)) return { usage: "usage: /code-review pr <number>" };
  if (trimmedArgs.includes("\\n") || trimmedArgs.includes(" ")) return { usage: USAGE };
  if (REF_RE.test(trimmedArgs) || NAME_RE.test(trimmedArgs)) {
    return { target: { kind: "commit", value: trimmedArgs } };
  }
  return { usage: USAGE };
}

function targetBlock(target: { kind: string; value: string | null }, degraded: boolean): string {
  if (target.kind === "local") {
    return "## Diff target\\n" + (degraded ? LOCAL_TARGET_DEGRADED : LOCAL_TARGET);
  }
  const value = target.value ?? "";
  if (target.kind === "pr") return "## Diff target\\n" + fillTemplate(PR_TARGET, value);
  return "## Diff target\\n" + fillTemplate(value.includes("..") ? COMMIT_RANGE : COMMIT_TARGET, value);
}

// --- inert fencing (magic-keywords.ts inertBlock): a fence one backtick
// longer than any run inside, so nothing in the JSON can escape it.
function longestBacktickRun(text: string): number {
  let longest = 0;
  let run = 0;
  for (let i = 0; i < text.length; i++) {
    run = text[i] === "\`" ? run + 1 : 0;
    if (run > longest) longest = run;
  }
  return longest;
}

function inertBlock(text: string): string {
  const fence = "\`".repeat(Math.max(3, longestBacktickRun(text) + 1));
  return fence + "json\\n" + text + "\\n" + fence;
}

// --- REVIEW.yml discovery and the restricted subset parse (review-config.ts
// without js-yaml; that module is not importable from an extension).
function isFile(p: string): boolean {
  try {
    return nodeFs.statSync(p).isFile();
  } catch {
    return false;
  }
}

function vcsRootOf(cwd: string): string | null {
  let dir = nodePath.resolve(cwd);
  for (let i = 0; i < MAX_WALK; i++) {
    if (nodeFs.existsSync(nodePath.join(dir, ".git"))) return dir;
    const parent = nodePath.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
  return null;
}

function agentDir(): string {
  const env = process.env;
  if (env.PI_CODING_AGENT_DIR) return nodePath.resolve(env.PI_CODING_AGENT_DIR);
  const configRoot = nodePath.join(nodeOs.homedir(), env.PI_CONFIG_DIR || ".omp");
  return nodePath.join(configRoot, "agent");
}

interface Candidate {
  file: string;
  depth: number;
}

function discoverCandidates(cwd: string): Candidate[] {
  const out: Candidate[] = [];
  for (const name of FILE_NAMES) {
    const file = nodePath.join(agentDir(), name);
    if (isFile(file)) out.push({ file, depth: 0 });
  }
  const start = nodePath.resolve(cwd);
  const stop = vcsRootOf(start) ?? nodePath.resolve(nodeOs.homedir());
  let dir = start;
  const projects: Candidate[] = [];
  for (let i = 0; i < MAX_WALK; i++) {
    const rel = nodePath.relative(start, dir);
    const depth = rel === "" ? 0 : rel.split(nodePath.sep).length;
    const inOmp = nodePath.basename(dir) === ".omp";
    const dotDir = nodePath.basename(dir).startsWith(".");
    for (const base of [nodePath.join(dir, ".omp"), dir]) {
      const baseIsOmp = nodePath.basename(base) === ".omp";
      if (!baseIsOmp && dotDir && !inOmp) continue;
      for (const name of FILE_NAMES) {
        const file = nodePath.join(base, name);
        if (isFile(file)) projects.push({ file, depth });
      }
    }
    if (dir === stop) break;
    const parent = nodePath.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  projects.sort((a, b) => b.depth - a.depth);
  return out.concat(projects);
}

function unquote(raw: string): string {
  const text = raw.trim();
  if (text.length >= 2 && (text[0] === '"' || text[0] === "'") && text[text.length - 1] === text[0]) {
    const body = text.slice(1, -1);
    if (text[0] === "'") return body.replace(/''/g, "'");
    return body.replace(/\\\\(["\\\\bfnrtv]|u[0-9a-fA-F]{4}|.)/g, (m, g) => {
      switch (m[1]) {
        case "n": return "\\n";
        case "t": return "\\t";
        case "r": return "\\r";
        case "b": return "\\b";
        case "f": return "\\f";
        case "v": return "\\v";
        case "u": return String.fromCharCode(parseInt(g.slice(1), 16));
        default: return m[1];
      }
    });
  }
  const comment = text.search(/\\s#(\\s|$)/);
  const bare = comment >= 0 ? text.slice(0, comment).trim() : text;
  if (bare === "null" || bare === "~") return "";
  return bare;
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
}

interface PendingEntry {
  fields: Record<string, string | string[] | null>;
  warnings: string[];
}

function reviewEntry(pending: PendingEntry, file: string, out: ReviewEntry[], warnings: string[]): void {
  const label = file + ": reviewer \\"" + String(pending.fields.name ?? "") + "\\"";
  const name = slug(typeof pending.fields.name === "string" ? pending.fields.name : "");
  if (name === "" || !/^[a-z][a-z0-9-]*$/.test(name)) {
    warnings.push(label + " needs a name slugging to [a-z][a-z0-9-]*");
    return;
  }
  if (pending.warnings.length > 0) {
    for (const w of pending.warnings) warnings.push(label + " " + w);
    return;
  }
  let model: string | null = null;
  if (typeof pending.fields.model === "string") {
    model = unquote(pending.fields.model);
    if (model === "") model = null;
  }
  let instructions: string | null = null;
  if (typeof pending.fields.instructions === "string" && pending.fields.instructions.trim() !== "") {
    instructions = pending.fields.instructions;
  }
  let targets: string[] | null = null;
  if (Array.isArray(pending.fields.targets)) {
    const kinds = (pending.fields.targets as string[]).map((t) => unquote(t));
    if (kinds.some((k) => !TARGET_KINDS.includes(k))) {
      warnings.push(label + " targets must name local, commit, or pr");
      return;
    }
    targets = kinds.filter((k, idx) => kinds.indexOf(k) === idx);
  }
  const enabled =
    typeof pending.fields.enabled === "string" ? unquote(pending.fields.enabled) !== "false" : true;
  out.push({ name, model, instructions, targets, enabled });
}

function parseRosterYaml(text: string, file: string): { reviewers: ReviewEntry[]; instructions: string | null; warnings: string[] } {
  const warnings: string[] = [];
  const reviewers: ReviewEntry[] = [];
  let instructions: string | null = null;
  let sawReviewersKey = false;
  const lines = text.split("\\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    if (line.trim() === "" || /^\\s*#/.test(line)) {
      i++;
      continue;
    }
    const bare = line.replace(/\\s+#.*$/, "").trimEnd();
    if (bare.startsWith("instructions:")) {
      const rawValue = bare.slice("instructions:".length).trim();
      const block = /^([|>][-+]?[0-9]*)$/.exec(rawValue);
      if (block !== null) {
        const folded = block[1]!.startsWith(">");
        const body: string[] = [];
        i++;
        let indent = 0;
        while (i < lines.length && (lines[i] === undefined || lines[i]!.trim() === "" || /^\\s/.test(lines[i]!))) {
          const row = lines[i] ?? "";
          if (indent === 0 && row.trim() !== "") indent = (row.match(/^\\s*/)?.[0] ?? "").length;
          body.push(row.slice(indent));
          i++;
        }
        const joined = folded ? body.join(" ").replace(/ {2,}/g, " ") : body.join("\\n").replace(/\\n+$/, "");
        instructions = joined === "" ? null : joined.slice(0, MAX_STRING);
        continue;
      }
      if (rawValue === "") {
        warnings.push(file + ": instructions must be a string");
      } else {
        const value = unquote(rawValue);
        if (value !== "") instructions = value.slice(0, MAX_STRING);
      }
      i++;
      continue;
    }
    if (bare.startsWith("reviewers:")) {
      sawReviewersKey = true;
      const rest = bare.slice("reviewers:".length).trim();
      if (rest !== "" && rest !== "[]") warnings.push(file + ": reviewers must be a list");
      i++;
      let pending: PendingEntry | null = null;
      const flush = (): void => {
        if (pending !== null) reviewEntry(pending, file, reviewers, warnings);
        pending = null;
      };
      while (i < lines.length) {
        const raw = lines[i]!;
        if (raw.trim() === "" || /^\\s*#/.test(raw)) {
          i++;
          continue;
        }
        if (!raw.trimStart().startsWith("- ") && !/^\\s/.test(raw)) break;
        if (reviewers.length + (pending === null ? 0 : 1) >= MAX_REVIEWERS) {
          warnings.push(file + ": more than " + MAX_REVIEWERS + " reviewers");
          break;
        }
        if (raw.trimStart().startsWith("- ")) {
          flush();
          pending = { fields: {}, warnings: [] };
          const inline = /^-\\s+([A-Za-z_][A-Za-z0-9_-]*)\\s*:\\s*(.*)$/.exec(raw.trim());
          if (inline !== null) pending.fields[inline[1]!] = inline[2]!;
          else pending.warnings.push("entry must start with name: <slug>");
          i++;
          continue;
        }
        if (pending === null) {
          warnings.push(file + ": reviewers list is malformed at " + JSON.stringify(raw.trim()));
          i++;
          continue;
        }
        const kv = /^\\s+([A-Za-z_][A-Za-z0-9_-]*)\\s*:\\s*(.*)$/.exec(raw);
        if (kv === null) {
          pending.warnings.push("expected key: value");
          i++;
          continue;
        }
        const key = kv[1]!;
        const value = kv[2]!.trim();
        if (key === "targets") {
          const inlineList = /^\\[(.*)\\]$/.exec(value);
          if (value === "" || value === "null" || value === "~") {
            const list: string[] = [];
            let sawItem = false;
            i++;
            while (i < lines.length) {
              const item = /^\\s+-\\s+(.*)$/.exec(lines[i]!);
              if (item === null) break;
              sawItem = true;
              list.push(item[1]!.trim());
              i++;
            }
            pending.fields.targets = sawItem ? list : value === "" ? [] : null;
            if (value !== "" && !sawItem) pending.fields.targets = null;
            continue;
          } else if (inlineList !== null) {
            pending.fields.targets = inlineList[1] === "" ? [] : inlineList[1]!.split(",").map((s) => s.trim());
          } else {
            pending.warnings.push("targets must be a list of strings");
          }
          i++;
          continue;
        }
        if (key === "instructions" && /^(|[|>][-+]?[0-9]*)$/.test(value)) {
          const body: string[] = [];
          i++;
          let indent = 0;
          while (i < lines.length && (lines[i]!.trim() === "" || /^\\s{4,}/.test(lines[i]!))) {
            const row = lines[i]!;
            if (indent === 0 && row.trim() !== "") indent = (row.match(/^\\s*/)?.[0] ?? "").length;
            body.push(row.slice(Math.min(indent, 4)));
            i++;
          }
          const joined = value.startsWith(">") ? body.join(" ").replace(/ {2,}/g, " ") : body.join("\\n").replace(/\\n+$/, "");
          pending.fields.instructions = joined;
          continue;
        }
        pending.fields[key] = value;
        i++;
      }
      flush();
      continue;
    }
    warnings.push(file + ': unknown key "' + bare.split(":")[0]!.trim() + '"');
    i++;
  }
  if (!sawReviewersKey && instructions === null) warnings.push(file + ": file is empty");
  return { reviewers, instructions, warnings };
}

function readRoster(cwd: string): RosterResult {
  const merged = new Map<string, ReviewEntry>();
  const warnings: string[] = [];
  let instructions: string | null = null;
  let sawFile = false;
  for (const candidate of discoverCandidates(cwd)) {
    let text: string;
    try {
      text = nodeFs.readFileSync(candidate.file, "utf8");
    } catch {
      continue;
    }
    sawFile = true;
    const parsed = parseRosterYaml(text, candidate.file);
    for (const w of parsed.warnings) warnings.push(w);
    if (parsed.instructions !== null) instructions = parsed.instructions;
    for (const entry of parsed.reviewers) merged.set(entry.name, entry);
  }
  if (!sawFile && merged.size === 0) {
    merged.set(DEFAULT_NAME, { name: DEFAULT_NAME, model: null, instructions: null, targets: null, enabled: true });
  }
  return { reviewers: [...merged.values()].filter((r) => r.enabled), instructions, warnings };
}

function gitOk(cwd: string, args: string[]): boolean {
  try {
    return nodeChildProcess.spawnSync("git", args, { cwd, encoding: "utf8", timeout: 10000 }).status === 0;
  } catch {
    return false;
  }
}

/** True when the local target cannot resolve a merge-base (plan §Component 2). */
function degradedLocal(cwd: string): boolean {
  try {
    const upstream = nodeChildProcess.spawnSync(
      "git",
      ["rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}"],
      { cwd, encoding: "utf8", timeout: 10000 },
    );
    if (upstream.status === 0 && upstream.stdout.trim() !== "") return false;
  } catch {
    return true;
  }
  const root = nodeChildProcess.spawnSync("git", ["rev-parse", "--show-toplevel"], { cwd, encoding: "utf8", timeout: 10000 });
  const top = root.status === 0 ? root.stdout.trim() : cwd;
  for (const base of ["origin/HEAD", "origin/main", "origin/master", "main", "master"]) {
    if (gitOk(top, ["merge-base", "HEAD", base])) return false;
  }
  return true;
}

function launchPrompt(cwd: string, target: { kind: string; value: string | null }): { prompt: string; roster: RosterResult; degraded: boolean } {
  const roster = readRoster(cwd);
  const degraded = target.kind === "local" && degradedLocal(cwd);
  const diff = targetBlock(target, degraded);
  const items = roster.reviewers.map((r) => {
    const task: Record<string, unknown> = {
      name: "review-" + r.name,
      task: [PLAYBOOK, r.instructions ?? "", diff].filter((s) => s !== "").join("\\n\\n"),
    };
    if (r.model !== null) task.model = r.model;
    return task;
  });
  const batch = {
    context:
      "Code review roster (omp-ui /" + COMMAND + "). " +
      (roster.instructions ??
        "Report defects in the diff only; every finding must cite a file and line from the diff."),
    tasks: items,
  };
  const targetLabel =
    target.kind === "local"
      ? "local changes"
      : target.kind === "pr"
        ? "pull request #" + String(target.value)
        : String(target.value);
  const prompt =
    "The user ran /" + COMMAND + " on " + targetLabel + "; the reviewer roster has " + items.length +
    " entries. Call the \`task\` tool exactly once with these batch arguments, unchanged, then stop and wait: " +
    "the reviewer results arrive on their own turn later.\\n" +
    inertBlock(JSON.stringify(batch)) +
    "\\nWhen the batch call returns, report its job receipt. Never edit files yourself and never post to GitHub.";
  return { prompt, roster, degraded };
}


async function launch(cwd: string, target: { kind: string; value: string | null }): Promise<{ ok: boolean; message: string }> {
  const built = launchPrompt(cwd, target);
  if (built.roster.reviewers.length === 0) {
    return { ok: false, message: "The reviewer roster is empty: every REVIEW.yml entry is disabled." };
  }
  try {
    if (typeof pi.sendMessage !== "function") {
      return { ok: false, message: "This omp cannot start the reviewers turn." };
    }
    await pi.sendMessage(
      { customType: LAUNCH_TYPE, content: built.prompt, display: false },
      { deliverAs: "nextTurn", triggerTurn: true },
    );
  } catch (error) {
    return { ok: false, message: "The launch send failed: " + String(error) };
  }
  const models = built.roster.reviewers.filter((r) => r.model !== null).length;
  return {
    ok: true,
    message:
      "Reviewing " +
      (built.degraded ? "local changes (no merge-base; diffing HEAD~1) " : "") +
      "with " + built.roster.reviewers.length + " reviewer(s)" +
      (models > 0 ? ", " + models + " model-pinned" : "") +
      (built.roster.warnings.length > 0 ? ". Config warnings: " + built.roster.warnings.join("; ") : "."),
  };
}

type TextResult = { content: Array<{ type: "text"; text: string }>; isError?: boolean };

function toolResult(text: string, isError: boolean): TextResult {
  return isError ? { content: [{ type: "text", text }], isError: true } : { content: [{ type: "text", text }] };
}

async function reviewTarget(target: { kind: string; value: string | null }, cwd: string): Promise<TextResult> {
  const git = nodeChildProcess.spawnSync("git", ["rev-parse", "--is-inside-work-tree"], { cwd, encoding: "utf8", timeout: 10000 });
  if (git.status !== 0) return toolResult("/" + COMMAND + " needs a git checkout; this cwd is not one.", true);
  if (target.kind === "local") {
    const porcelain = nodeChildProcess.spawnSync("git", ["status", "--porcelain"], { cwd, encoding: "utf8", timeout: 10000 });
    const log = nodeChildProcess.spawnSync("git", ["rev-parse", "--verify", "HEAD"], { cwd, encoding: "utf8", timeout: 10000 });
    const empty = porcelain.status === 0 && porcelain.stdout.trim() === "" && log.status !== 0;
    if (empty) return toolResult("Nothing to review: no commits and no local changes.", true);
  }
  const launched = await launch(cwd, target);
  if (!launched.ok) return toolResult(launched.message, true);
  return toolResult(launched.message + " The reviewers run as background agents; their findings arrive as they finish.", false);
}

async function runReview(args: string, cwd: string): Promise<TextResult> {
  const parsed = parseArgs(args);
  if ("usage" in parsed) return toolResult(parsed.usage, true);
  return reviewTarget(parsed.target, cwd);
}

pi.registerCommand(COMMAND, {
  description: "Review code with the REVIEW.yml roster as background agents",
  handler: async (args: string, ctx: Record<string, unknown>) => {
    const cwd = typeof ctx.cwd === "string" ? ctx.cwd : pi.cwd ?? process.cwd();
    const result = await runReview(args, cwd);
    const ui = asRecord(ctx.ui);
    const notify = ui?.notify;
    const text = result.content[0]!.text;
    if (typeof notify === "function") notify.call(ui, text, result.isError ? "error" : "warning");
    else process.stdout.write(text + "\\n");
  },
});

const zod = pi.zod;
if (typeof pi.registerTool === "function" && typeof zod?.object === "function") {
  pi.registerTool({
    name: TOOL,
    label: "code review",
    description:
      "Launch the project's code-review roster (REVIEW.yml) as background reviewer agents. " +
      "target: omit for local changes since the merge-base; {kind:'commit',value:'<ref-or-range>'} for a commit or range; " +
      "{kind:'pr',value:'<number>'} for a GitHub pull request. Reviewers never edit files or post anywhere.",
    parameters: zod.object({
      target: zod
        .object({ kind: zod.string(), value: zod.string().nullable().optional() })
        .nullable()
        .optional()
        .describe("What to review; omit for local changes"),
    }),
    execute: async (
      _id: string,
      params: unknown,
      _signal: AbortSignal | undefined,
      _onUpdate: unknown,
      ctx: Record<string, unknown> | undefined,
    ): Promise<TextResult> => {
      const p = asRecord(params) ?? {};
      const t = asRecord(p.target);
      const kind = t === null || t.kind === undefined || t.kind === null ? "local" : String(t.kind);
      if (!TARGET_KINDS.includes(kind)) return toolResult("target.kind must be local, commit, or pr", true);
      const value = t === null || t.value === undefined || t.value === null ? null : String(t.value);
      if (kind === "local" && value !== null) return toolResult("a local target carries no value", true);
      if (kind !== "local" && value === null) return toolResult("target.value is required for " + kind, true);
      if (kind === "commit" && value !== null && !REF_RE.test(value) && !NAME_RE.test(value)) {
        return toolResult("target.value must be a ref, sha, or sha range", true);
      }
      if (kind === "pr" && value !== null && !/^[1-9][0-9]*$/.test(value)) {
        return toolResult("target.value must be a positive pull request number", true);
      }
      const toolCtx = asRecord(ctx);
      const cwd = typeof toolCtx?.cwd === "string" ? toolCtx.cwd : pi.cwd ?? process.cwd();
      return reviewTarget({ kind, value }, cwd);
    },
  });
}
}
`;
}

/**
 * Writes the code-review bridge into the lineage dir and returns its path, to
 * be passed to omp as `-e`. Rewritten on every spawn so a stale copy can
 * never outvote the current wire contract.
 */
export function writeReviewExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, reviewExtensionPath(lineageDir), extensionSource());
}
