import * as path from "node:path";
import {
  BTW_BUSY_REFUSAL,
  BTW_COMMAND,
  BTW_NO_MODEL_MESSAGE,
  BTW_QUESTION_CHAR_LIMIT,
  BTW_SNAPSHOT_ANSWER_CHAR_LIMIT,
  BTW_STATUS_BYTE_LIMIT,
  BTW_STATUS_KEY,
  BTW_TRUNCATION_MARKER,
  OMP_BTW_USER_TEMPLATE,
} from "./side-questions";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  generatedAsRecordSource,
  generatedRootBindingSource,
  generatedSessionIdSource,
  generatedUtf8LengthSource,
} from "./generated-extension-source";

/**
 * omp's `/btw` is TUI-only (see side-questions.ts). This generated extension is
 * the rpc-ui bridge: it runs omp's own `AgentSession.runEphemeralTurn` — the API
 * the TUI's BtwController uses — against the live session, keeps omp's
 * `btw-history/entry-<id>.json` file grammar so a topic started here is
 * browsable in omp's TUI overlay, and publishes the topic list over
 * `ui.setStatus` (issue #682).
 *
 * The ephemeral turn reuses the main transcript as context and appends nothing
 * to it or to the session file. Every unsupported API is probed: a missing
 * `runEphemeralTurn` publishes `available: false` with the reason and leaves
 * ordinary prompting untouched (the goal and tree bridges' discipline).
 *
 * This process is the single reader/writer of `btw-history/` for a native tab:
 * rpc-ui never runs omp's BtwController, and a terminal-tab session never
 * loads this bridge.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-btw.ts";

export function sideQuestionsExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports only node builtins; the wire constants are
 * interpolated from side-questions.ts so publisher and parser cannot drift.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
import * as nodeFs from "node:fs/promises";
import * as nodePath from "node:path";
import * as nodeCrypto from "node:crypto";

const STATUS_KEY = ${JSON.stringify(BTW_STATUS_KEY)};
const COMMAND = ${JSON.stringify(BTW_COMMAND)};
const QUESTION_LIMIT = ${BTW_QUESTION_CHAR_LIMIT};
const ANSWER_LIMIT = ${BTW_SNAPSHOT_ANSWER_CHAR_LIMIT};
const BYTE_LIMIT = ${BTW_STATUS_BYTE_LIMIT};
const TRUNCATION_MARKER = ${JSON.stringify(BTW_TRUNCATION_MARKER)};
const BUSY_REFUSAL = ${JSON.stringify(BTW_BUSY_REFUSAL)};
const NO_MODEL_MESSAGE = ${JSON.stringify(BTW_NO_MODEL_MESSAGE)};
const USER_TEMPLATE = ${JSON.stringify(OMP_BTW_USER_TEMPLATE)};
const PUBLISH_THROTTLE_MS = 200;
const ID_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,127}$/;
const UNAVAILABLE_REASON = "This omp cannot answer side questions natively (no ephemeral-turn API).";

${generatedAsRecordSource()}

${generatedUtf8LengthSource()}

type TurnStatus = "running" | "complete" | "cancelled" | "error" | "interrupted";

interface Turn {
  question: string;
  answer: string;
  status: TurnStatus;
  createdAt: number;
  updatedAt: number;
  error?: string;
}

interface HistoryRecord extends Turn {
  id: string;
  leafId: string | null;
  followUps?: Turn[];
}

interface ActiveRun {
  topicId: string;
  question: string;
  controller: AbortController;
}

interface Store {
  key: string;
  sessionId: string;
  /** \`<artifactsDir>/btw-history\`, or null while the session has no artifacts dir (memory-only). */
  dir: string | null;
  records: Map<string, HistoryRecord>;
  /** sha256 of each record's file as last read or written; absent = never on disk. */
  revisions: Map<string, string>;
  persistErrors: Map<string, string>;
  chain: Promise<unknown>;
  active: ActiveRun | null;
}

interface BtwModel {
  api?: unknown;
  provider?: unknown;
  id?: unknown;
}

interface BtwSession {
  model?: BtwModel | null;
  sessionManager?: Record<string, unknown>;
  runEphemeralTurn?: (options: {
    promptText: string;
    history?: unknown[];
    conversationKey?: string;
    onTextDelta?: (delta: string) => void;
    signal?: AbortSignal;
  }) => Promise<{ replyText?: unknown }>;
}

interface BtwUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface BtwCtx {
  ui?: BtwUi;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: BtwCtx) => Promise<void>;
    },
  ) => void;
  on?: (event: string, handler: (...args: unknown[]) => void) => void;
}

export default function (pi: ExtensionApi) {
  let rootSession: BtwSession | null = null;
  ${generatedSessionIdSource("BtwSession")}
  let ui: BtwUi | null = null;
  let current: Store | null = null;
  let opening: { key: string; promise: Promise<Store | null> } | null = null;
  let pendingBusy: string | undefined;
  let publishTimer: NodeJS.Timeout | null = null;
  let queue: Promise<unknown> = Promise.resolve();
  ${generatedRootBindingSource("BtwSession")}

  function serialize<T>(work: () => Promise<T>): Promise<T> {
    const next = queue.then(work, work);
    queue = next.then(
      () => undefined,
      () => undefined,
    );
    return next;
  }

  function manager(root: BtwSession | null): Record<string, unknown> | null {
    return asRecord(root?.sessionManager);
  }

  function callManager(root: BtwSession | null, name: string): unknown {
    const target = manager(root);
    const read = target === null ? undefined : target[name];
    if (typeof read !== "function") return undefined;
    try {
      return (read as () => unknown).call(target);
    } catch {
      return undefined;
    }
  }

  function artifactsDirOf(root: BtwSession | null): string | null {
    const value = callManager(root, "getArtifactsDir");
    return typeof value === "string" && value !== "" ? value : null;
  }

  function leafIdOf(root: BtwSession | null): string | null {
    const value = callManager(root, "getLeafId");
    return typeof value === "string" && value !== "" ? value : null;
  }

  async function ensureOnDisk(root: BtwSession): Promise<void> {
    const target = manager(root);
    const ensure = target === null ? undefined : target.ensureOnDisk;
    if (typeof ensure !== "function") return;
    try {
      await (ensure as () => Promise<unknown>).call(target);
    } catch {
      /* the topic then lives in memory until the session reaches disk */
    }
  }

  function isAvailable(root: BtwSession | null): root is BtwSession {
    return (
      root !== null &&
      typeof root.runEphemeralTurn === "function" &&
      sessionIdOf(root) !== null
    );
  }

  // ---------------------------------------------------------------- history files

  function sha256(text: string | Uint8Array): string {
    return nodeCrypto.createHash("sha256").update(text).digest("hex");
  }

  function readTurn(value: unknown, allowed: string[]): Turn | null {
    const raw = asRecord(value);
    if (raw === null) return null;
    for (const key of Object.keys(raw)) if (!allowed.includes(key)) return null;
    const statuses = ["running", "complete", "cancelled", "error", "interrupted"];
    const inRange = (n: unknown): n is number =>
      typeof n === "number" && Number.isFinite(n) && n >= 0 && n <= 8640000000000000;
    if (typeof raw.question !== "string" || typeof raw.answer !== "string") return null;
    if (typeof raw.status !== "string" || !statuses.includes(raw.status)) return null;
    if (!inRange(raw.createdAt) || !inRange(raw.updatedAt)) return null;
    if (raw.error !== undefined && typeof raw.error !== "string") return null;
    return {
      question: raw.question,
      answer: raw.answer,
      status: raw.status as TurnStatus,
      createdAt: raw.createdAt,
      updatedAt: raw.updatedAt,
      ...(raw.error !== undefined ? { error: raw.error } : {}),
    };
  }

  /** omp's BtwHistoryStore grammar: strict keys, id regex, no nested followUps. */
  function parseRecord(text: string, fileName: string): HistoryRecord | null {
    let raw: unknown;
    try {
      raw = JSON.parse(text);
    } catch {
      return null;
    }
    const record = asRecord(raw);
    if (record === null) return null;
    const turnKeys = ["question", "answer", "status", "createdAt", "updatedAt", "error"];
    const root = readTurn(record, [...turnKeys, "id", "leafId", "followUps"]);
    const id = record.id;
    if (root === null || typeof id !== "string" || !ID_PATTERN.test(id)) return null;
    if (record.leafId !== null && typeof record.leafId !== "string") return null;
    if (fileName !== "entry-" + id + ".json") return null;
    let followUps: Turn[] | undefined;
    if (record.followUps !== undefined) {
      if (!Array.isArray(record.followUps)) return null;
      followUps = [];
      for (const value of record.followUps) {
        const turn = readTurn(value, turnKeys);
        if (turn === null) return null;
        followUps.push(turn);
      }
    }
    return {
      ...root,
      id,
      leafId: record.leafId as string | null,
      ...(followUps !== undefined ? { followUps } : {}),
    };
  }

  /** omp's loader marks a turn still \`running\` at open time as \`interrupted\`. */
  function interruptedCopy(record: HistoryRecord): HistoryRecord {
    const fix = (turn: Turn): Turn =>
      turn.status === "running" ? { ...turn, status: "interrupted" } : turn;
    return {
      ...record,
      ...fix(record),
      ...(record.followUps !== undefined ? { followUps: record.followUps.map(fix) } : {}),
    };
  }

  async function readEntries(dir: string): Promise<{ record: HistoryRecord; revision: string }[]> {
    let names: string[];
    try {
      names = await nodeFs.readdir(dir);
    } catch {
      return [];
    }
    const out: { record: HistoryRecord; revision: string }[] = [];
    for (const name of names.sort()) {
      if (!name.endsWith(".json")) continue;
      try {
        const file = nodePath.join(dir, name);
        const stat = await nodeFs.lstat(file);
        if (!stat.isFile()) continue;
        const bytes = await nodeFs.readFile(file);
        const record = parseRecord(bytes.toString("utf8"), name);
        if (record !== null) out.push({ record, revision: sha256(bytes) });
      } catch {
        /* an unreadable entry is skipped, never fatal to the pane */
      }
    }
    return out;
  }

  async function writeRecord(store: Store, record: HistoryRecord): Promise<void> {
    const dir = store.dir;
    if (dir === null) return;
    const file = nodePath.join(dir, "entry-" + record.id + ".json");
    const json = JSON.stringify(record) + "\\n";
    await nodeFs.mkdir(dir, { recursive: true, mode: 0o700 });
    await nodeFs.chmod(dir, 0o700);
    let onDisk: string | undefined;
    try {
      onDisk = sha256(await nodeFs.readFile(file));
    } catch {
      onDisk = undefined;
    }
    if (onDisk !== store.revisions.get(record.id)) {
      throw new Error("BTW history conflict for " + record.id + "; reopen history before retrying");
    }
    const tmp = file + "." + process.pid + "." + nodeCrypto.randomUUID() + ".tmp";
    try {
      await nodeFs.writeFile(tmp, json, { encoding: "utf8", mode: 0o600, flag: "wx" });
      await nodeFs.rename(tmp, file);
    } finally {
      await nodeFs.rm(tmp, { force: true }).catch(() => undefined);
    }
    store.revisions.set(record.id, sha256(json));
  }

  /** Serialized, revision-guarded upsert. A failure marks the topic's publish, never throws. */
  function persist(store: Store, record: HistoryRecord): Promise<void> {
    if (store.dir === null) return Promise.resolve();
    const run = store.chain.then(() => writeRecord(store, record));
    store.chain = run.catch(() => undefined);
    return run.then(
      () => {
        store.persistErrors.delete(record.id);
      },
      (error: unknown) => {
        store.persistErrors.set(
          record.id,
          error instanceof Error ? error.message : String(error),
        );
      },
    );
  }

  // ---------------------------------------------------------------- store lifecycle

  async function openStore(root: BtwSession, key: string): Promise<Store> {
    const artifactsDir = artifactsDirOf(root);
    const store: Store = {
      key,
      sessionId: sessionIdOf(root) ?? "",
      dir: artifactsDir === null ? null : nodePath.join(artifactsDir, "btw-history"),
      records: new Map(),
      revisions: new Map(),
      persistErrors: new Map(),
      chain: Promise.resolve(),
      active: null,
    };
    if (store.dir !== null) {
      for (const entry of await readEntries(store.dir)) {
        store.records.set(entry.record.id, interruptedCopy(entry.record));
        store.revisions.set(entry.record.id, entry.revision);
      }
    }
    return store;
  }

  function keyOf(root: BtwSession): string | null {
    const id = sessionIdOf(root);
    return id === null ? null : id + "\\u0000" + (artifactsDirOf(root) ?? "");
  }

  /** The store for the root's CURRENT (sessionId, artifactsDir); state never leaks across sessions. */
  async function storeFor(root: BtwSession): Promise<Store | null> {
    const key = keyOf(root);
    if (key === null) return null;
    if (current !== null && current.key === key) return current;
    const memoryOnly = current;
    if (
      memoryOnly !== null &&
      memoryOnly.dir === null &&
      memoryOnly.sessionId === sessionIdOf(root) &&
      artifactsDirOf(root) !== null
    ) {
      // The session reached disk after topics were asked in memory: the same
      // store (a running turn holds it) moves onto disk and persists them.
      memoryOnly.key = key;
      memoryOnly.dir = nodePath.join(artifactsDirOf(root) as string, "btw-history");
      for (const entry of await readEntries(memoryOnly.dir)) {
        if (memoryOnly.records.has(entry.record.id)) continue;
        memoryOnly.records.set(entry.record.id, interruptedCopy(entry.record));
        memoryOnly.revisions.set(entry.record.id, entry.revision);
      }
      for (const record of memoryOnly.records.values()) {
        if (memoryOnly.active?.topicId !== record.id) void persist(memoryOnly, record);
      }
      return memoryOnly;
    }
    if (opening !== null && opening.key === key) return opening.promise;
    const promise = openStore(root, key).then((store) => {
      current = store;
      if (opening !== null && opening.promise === promise) opening = null;
      return store;
    });
    opening = { key, promise };
    return promise;
  }

  /** Re-scan the history dir; disk wins for every topic that is not running here. */
  async function reload(store: Store): Promise<void> {
    if (store.dir === null) return;
    for (const entry of await readEntries(store.dir)) {
      const id = entry.record.id;
      if (store.active !== null && store.active.topicId === id) continue;
      if (store.revisions.get(id) === entry.revision && store.records.has(id)) continue;
      store.records.set(id, interruptedCopy(entry.record));
      store.revisions.set(id, entry.revision);
      store.persistErrors.delete(id);
    }
    for (const [id, record] of store.records) {
      if (store.revisions.has(id)) continue;
      if (store.active !== null && store.active.topicId === id) continue;
      await persist(store, record);
    }
  }

  // ---------------------------------------------------------------- publishing

  function clip(text: string): string {
    return text.length > ANSWER_LIMIT ? text.slice(0, ANSWER_LIMIT) + TRUNCATION_MARKER : text;
  }

  function turnsOf(record: HistoryRecord): Turn[] {
    return [record, ...(record.followUps ?? [])];
  }

  function topicView(store: Store, record: HistoryRecord): Record<string, unknown> {
    const turns = turnsOf(record).map((turn) => ({
      question: turn.question,
      answer: clip(turn.answer),
      status: turn.status,
      updatedAt: turn.updatedAt,
      ...(turn.error !== undefined ? { error: turn.error } : {}),
    }));
    const persistError = store.persistErrors.get(record.id);
    const last = turns[turns.length - 1];
    if (persistError !== undefined && last.status !== "running") {
      last.status = "error";
      (last as Record<string, unknown>).error = persistError;
    }
    return {
      id: record.id,
      question: record.question,
      answer: last.answer,
      status: last.status,
      updatedAt: last.updatedAt,
      ...(last.error !== undefined ? { error: last.error } : {}),
      turns,
    };
  }

  function setStatus(payload: Record<string, unknown>): void {
    if (ui === null) return;
    ui.setStatus(STATUS_KEY, JSON.stringify(payload));
  }

  function publishUnavailable(reason: string): void {
    setStatus({
      available: false,
      unavailableReason: reason,
      active: null,
      topics: [],
      publishedAt: Date.now(),
    });
  }

  function publishNow(): void {
    if (publishTimer !== null) {
      clearTimeout(publishTimer);
      publishTimer = null;
    }
    if (ui === null) return;
    const root = rootSession;
    if (!isAvailable(root)) {
      publishUnavailable(UNAVAILABLE_REASON);
      return;
    }
    const store = current;
    if (store === null) return;
    const sorted = [...store.records.values()].sort((a, b) => {
      const delta = latestOf(b).updatedAt - latestOf(a).updatedAt;
      return delta !== 0 ? delta : a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
    });
    // Newest first, dropping the oldest topics that would break the byte budget.
    const topics: Record<string, unknown>[] = [];
    let bytes = 0;
    const reserve = 8 * 1024 + ANSWER_LIMIT * 2;
    for (const record of sorted) {
      const view = topicView(store, record);
      const size = utf8Length(JSON.stringify(view)) + 1;
      if (bytes + size + reserve > BYTE_LIMIT) break;
      bytes += size;
      topics.push(view);
    }
    let active: Record<string, unknown> | null = null;
    if (store.active !== null) {
      const record = store.records.get(store.active.topicId);
      active = {
        topicId: store.active.topicId,
        question: store.active.question,
        answer: record === undefined ? "" : clip(latestOf(record).answer),
      };
    }
    const busy = pendingBusy;
    pendingBusy = undefined;
    setStatus({
      available: true,
      ...(busy !== undefined ? { busy } : {}),
      active,
      topics,
      publishedAt: Date.now(),
    });
  }

  function latestOf(record: HistoryRecord): Turn {
    const turns = turnsOf(record);
    return turns[turns.length - 1];
  }

  /** Streaming deltas publish at most every PUBLISH_THROTTLE_MS; the final publish is immediate. */
  function publishSoon(): void {
    if (publishTimer !== null) return;
    publishTimer = setTimeout(() => {
      publishTimer = null;
      try {
        publishNow();
      } catch {
        /* a publish failure must never surface in the session */
      }
    }, PUBLISH_THROTTLE_MS);
    publishTimer.unref();
  }

  function refuse(message: string): void {
    pendingBusy = message;
    publishNow();
  }

  // ---------------------------------------------------------------- verbs

  function withLatest(record: HistoryRecord, patch: Partial<Turn>): HistoryRecord {
    const followUps = record.followUps;
    if (followUps !== undefined && followUps.length > 0) {
      return {
        ...record,
        followUps: [...followUps.slice(0, -1), { ...followUps[followUps.length - 1], ...patch }],
      };
    }
    return { ...record, ...patch };
  }

  function historyMessages(model: BtwModel, turns: Turn[]): unknown[] {
    const zero = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 };
    const messages: unknown[] = [];
    for (const turn of turns) {
      messages.push({
        role: "user",
        content: [{ type: "text", text: promptText(turn.question) }],
        attribution: "agent",
        timestamp: turn.createdAt,
      });
      if (turn.answer === "") continue;
      messages.push({
        role: "assistant",
        content: [{ type: "text", text: turn.answer }],
        api: model.api,
        provider: model.provider,
        model: model.id,
        usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, cost: zero },
        stopReason: "stop",
        timestamp: turn.updatedAt,
      });
    }
    return messages;
  }

  function promptText(question: string): string {
    return USER_TEMPLATE.replace("{{question}}", () => question);
  }

  function finish(store: Store, run: ActiveRun, patch: Partial<Turn>): void {
    const record = store.records.get(run.topicId);
    if (record === undefined || latestOf(record).status !== "running") return;
    const next = withLatest(record, { ...patch, updatedAt: Date.now() });
    store.records.set(run.topicId, next);
    if (store.active === run) store.active = null;
    void persist(store, next).then(() => {
      if (current === store) publishNow();
    });
    if (current === store) publishNow();
  }

  async function runTurn(
    root: BtwSession,
    store: Store,
    run: ActiveRun,
    model: BtwModel,
    prior: Turn[] | undefined,
  ): Promise<void> {
    let lastIncomplete = -1;
    (prior ?? []).forEach((turn, index) => {
      if (turn.status !== "complete") lastIncomplete = index;
    });
    try {
      const result = await (root.runEphemeralTurn as NonNullable<BtwSession["runEphemeralTurn"]>).call(root, {
        promptText: promptText(run.question),
        history: historyMessages(model, prior ?? []),
        conversationKey: "btw:" + run.topicId + ":" + (lastIncomplete + 1),
        onTextDelta: (delta: string) => {
          const record = store.records.get(run.topicId);
          if (record === undefined || latestOf(record).status !== "running") return;
          store.records.set(
            run.topicId,
            withLatest(record, { answer: latestOf(record).answer + delta, updatedAt: Date.now() }),
          );
          if (current === store) publishSoon();
        },
        signal: run.controller.signal,
      });
      const reply = typeof result?.replyText === "string" ? result.replyText : null;
      const record = store.records.get(run.topicId);
      finish(store, run, {
        status: "complete",
        answer: reply ?? (record === undefined ? "" : latestOf(record).answer),
      });
    } catch (error) {
      const aborted = run.controller.signal.aborted;
      finish(
        store,
        run,
        aborted
          ? { status: "cancelled" }
          : { status: "error", error: error instanceof Error ? error.message : String(error) },
      );
    }
  }

  async function ask(request: Record<string, unknown>): Promise<void> {
    const root = rootSession;
    if (!isAvailable(root)) {
      publishUnavailable(UNAVAILABLE_REASON);
      return;
    }
    const question = typeof request.question === "string" ? request.question.trim() : "";
    if (question === "") return refuse("A side question needs some text.");
    if (question.length > QUESTION_LIMIT) return refuse("That side question is too long.");
    await ensureOnDisk(root);
    const store = await storeFor(root);
    if (store === null) {
      publishUnavailable(UNAVAILABLE_REASON);
      return;
    }
    if (store.active !== null) return refuse(BUSY_REFUSAL);
    const topicId = typeof request.topicId === "string" ? request.topicId : undefined;
    const existing = topicId === undefined ? undefined : store.records.get(topicId);
    if (topicId !== undefined && (existing === undefined || latestOf(existing).status === "running"))
      return refuse("This side conversation is unavailable or still running.");
    const model = root.model ?? null;
    const now = Date.now();
    const turn: Turn =
      model === null
        ? { question, answer: "", status: "error", createdAt: now, updatedAt: now, error: NO_MODEL_MESSAGE }
        : { question, answer: "", status: "running", createdAt: now, updatedAt: now };
    const record: HistoryRecord =
      existing === undefined
        ? { ...turn, id: nodeCrypto.randomUUID(), leafId: leafIdOf(root) }
        : { ...existing, followUps: [...(existing.followUps ?? []), turn] };
    const prior = existing === undefined ? undefined : turnsOf(existing);
    store.records.set(record.id, record);
    if (model === null) {
      await persist(store, record);
      publishNow();
      return;
    }
    const run: ActiveRun = { topicId: record.id, question, controller: new AbortController() };
    store.active = run;
    await persist(store, record);
    publishNow();
    // Scheduled, never awaited: the command's ack must not ride a model turn.
    void runTurn(root, store, run, model, prior);
  }

  async function cancel(): Promise<void> {
    const store = current;
    const run = store === null ? null : store.active;
    if (store !== null && run !== null) {
      const record = store.records.get(run.topicId);
      if (record !== undefined && latestOf(record).status === "running") {
        const next = withLatest(record, { status: "cancelled", updatedAt: Date.now() });
        store.records.set(run.topicId, next);
        store.active = null;
        run.controller.abort();
        void persist(store, next).then(() => {
          if (current === store) publishNow();
        });
      }
    }
    publishNow();
  }

  async function refresh(): Promise<void> {
    const root = rootSession;
    if (!isAvailable(root)) {
      publishUnavailable(UNAVAILABLE_REASON);
      return;
    }
    const store = await storeFor(root);
    if (store === null) {
      publishUnavailable(UNAVAILABLE_REASON);
      return;
    }
    await reload(store);
    publishNow();
  }

  // ---------------------------------------------------------------- wiring

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: BtwSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: BtwSession, ...args: unknown[]): unknown {
        captureRoot(this);
        return call.apply(this, args);
      };
    }
  } catch {
    /* missing root binding: every publish degrades to unavailable */
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui side questions (/btw)",
    handler: (args: string, ctx: BtwCtx) =>
      serialize(async () => {
        if (ctx.ui) ui = ctx.ui;
        const trimmed = typeof args === "string" ? args.trim() : "";
        const match = /^(ask|cancel|refresh)(?:\\s+([\\s\\S]*))?$/.exec(trimmed);
        let request: Record<string, unknown> = {};
        if (match !== null && match[2] !== undefined) {
          try {
            request = asRecord(JSON.parse(match[2])) ?? {};
          } catch {
            request = {};
          }
        }
        try {
          if (match === null || match[1] === "refresh") await refresh();
          else if (match[1] === "ask") await ask(request);
          else await cancel();
        } catch (error) {
          refuse(error instanceof Error ? error.message : String(error));
        }
      }),
  });

  // A lineage /new, /branch, or resume changes (sessionId, artifactsDir): the
  // store re-keys on the next read, so republish from the new session's files.
  if (typeof pi.on === "function") {
    for (const eventName of ["session_start", "session_switch", "session_branch"]) {
      pi.on(eventName, (...eventArgs: unknown[]) => {
        const eventCtx = asRecord(eventArgs[1]) as BtwCtx | null;
        if (eventCtx?.ui) ui = eventCtx.ui;
        if (ui === null || rootSession === null) return;
        void serialize(refresh).catch(() => undefined);
      });
    }
    pi.on("session_shutdown", () => {
      if (publishTimer !== null) clearTimeout(publishTimer);
      publishTimer = null;
      current?.active?.controller.abort();
    });
  }
}
`;
}

/**
 * Writes the side-questions bridge into the lineage dir and returns its path,
 * to be passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeSideQuestionsExtension(lineageDir: string): string {
  return writeLineageArtifact(
    lineageDir,
    sideQuestionsExtensionPath(lineageDir),
    extensionSource(),
  );
}
