import * as path from "node:path";
import {
  SUBAGENT_CONTROL_ARG_PREFIX,
  SUBAGENT_CONTROL_COMMAND,
  SUBAGENT_CONTROL_STATUS_BYTE_LIMIT,
  SUBAGENT_CONTROL_STATUS_KEY,
  SUBAGENT_STEER_CHAR_LIMIT,
} from "./subagent-control";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  generatedAsRecordSource,
  generatedRootBindingSource,
  generatedUtf8LengthSource,
} from "./generated-extension-source";

/**
 * omp's rpc surface reads the subagent roster (`get_subagents`) but offers no
 * verb that steers, kills, or revives one subagent: AgentLifecycleManager
 * (ensureLive/release) and the AgentRegistry's live session refs are
 * in-process only — Agent Hub and the collab host are the only callers in the
 * verified 18.4.2 binary (ADR-0040). Per ADR-0007/0024 this generated
 * extension is the bridge: it drives omp's own APIs with hub-parity guard
 * order and refusal strings, and publishes each settled verb over
 * `ui.setStatus`, correlated by requestId (issue #684).
 *
 * The two managers arrive through LITERAL dynamic imports of omp's registry
 * subpaths (the same shim that resolves config/registry for the settings
 * reader, ADR-0036); a failed import degrades every verb to a `missing-api`
 * refusal, never a crash. The read side is untouched: `get_subagents` stays
 * the roster truth, and the bridge never re-implements omp's park/abort/
 * revive serialization — it calls the same entry points hub calls.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-subagent-control.ts";

export function subagentControlExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants are interpolated
 * from subagent-control.ts so publisher and parser cannot drift, and the
 * refusal sentences are omp's own (extracted from the 18.4.2 binary) so the
 * renderer never re-derives them.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(SUBAGENT_CONTROL_STATUS_KEY)};
const COMMAND = ${JSON.stringify(SUBAGENT_CONTROL_COMMAND)};
const ARG_PREFIX = ${JSON.stringify(SUBAGENT_CONTROL_ARG_PREFIX.slice(SUBAGENT_CONTROL_COMMAND.length + 1))};
const STEER_LIMIT = ${SUBAGENT_STEER_CHAR_LIMIT};
const BYTE_LIMIT = ${SUBAGENT_CONTROL_STATUS_BYTE_LIMIT};
const RESULT_CAP = 16;
const ACTIONS = ["steer", "kill", "revive"];
const ADVISOR_MESSAGE = (id: string) =>
  'Agent "' + id + '" is a read-only advisor transcript and cannot be messaged.';
const ADVISOR_KILL = (id: string) =>
  '"' + id + '" is a read-only advisor transcript \\u2014 cannot be killed.';
const ADVISOR_REVIVE = (id: string) =>
  '"' + id + '" is a read-only advisor transcript \\u2014 nothing to revive.';
const ABORTED_SENTENCE = (id: string) =>
  'Agent "' + id + '" was hard-aborted and cannot be messaged or revived. Its transcript remains readable at history://' + id + '.';
const PARKED_SENTENCE = (id: string, status: string) =>
  'Agent "' + id + '" is ' + status + ' \\u2014 only parked agents can be revived.';
const UNKNOWN_SENTENCE = (id: string) =>
  'Unknown agent "' + id + '" \\u2014 it was never registered or has been released. If a transcript exists, read history://' + id + '.';
const BUSY_SENTENCE = (id: string) =>
  'Another control action on "' + id + '" is already running.';

${generatedAsRecordSource()}

${generatedUtf8LengthSource()}

interface AgentSessionLike {
  abort?: (options?: { reason?: string }) => unknown;
  prompt?: (text: string, options?: { streamingBehavior?: string }) => unknown;
}

interface AgentRef {
  id: unknown;
  kind: unknown;
  status: unknown;
  session: unknown;
}

interface VerbRequest {
  requestId: string;
  agentId: string;
  action: string;
  text?: string;
}

interface Managers {
  /** AgentRegistry.get — the ref, or null when the id is unknown/released. */
  get(agentId: string): AgentRef | null;
  mainAgentId: unknown;
  ensureLive(agentId: string): Promise<unknown>;
  release(agentId: string, ref: AgentRef, options: { tombstone: boolean }): Promise<unknown>;
}

interface ControlUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: ControlUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);
  let rootSession: Record<string, unknown> | null = null;
  ${generatedRootBindingSource("Record<string, unknown>")}
  let ui: ControlUi | null = null;
  let revision = 0;
  /** Non-null when the registry/lifecycle globals could not be reached. */
  let broken: string | null = null;
  /** Settled verbs, oldest-first, ring-capped; the renderer correlates by requestId. */
  const results: Record<string, unknown>[] = [];
  /** Agent ids with a verb running right now; a second one is refused, not queued. */
  const inFlight: Record<string, true> = {};

  /** AgentRegistry.global() / AgentLifecycleManager.global(), or null when unreachable. */
  function globalOf(value: unknown): Record<string, unknown> | null {
    const owner = value as { global?: () => unknown } | null | undefined;
    if (owner === null || owner === undefined || typeof owner.global !== "function") return null;
    try {
      return asRecord(owner.global());
    } catch {
      return null;
    }
  }

  // omp's own managers, through the bundled-module shim (ADR-0036): the two
  // registry subpaths are LITERAL specifiers; a computed one does not resolve.
  let managers: Managers | null = null;
  const managersReady = Promise.all([
    // @ts-expect-error -- literal specifier resolves through omp's module shim only
    import("@oh-my-pi/pi-coding-agent/registry/agent-registry"),
    // @ts-expect-error -- literal specifier resolves through omp's module shim only
    import("@oh-my-pi/pi-coding-agent/registry/agent-lifecycle"),
  ]).then(
    ([registryMod, lifecycleMod]: unknown[]) => {
      const registryApi = globalOf(asRecord(registryMod)?.AgentRegistry);
      const lifecycleApi = globalOf(asRecord(lifecycleMod)?.AgentLifecycleManager);
      if (
        registryApi === null ||
        lifecycleApi === null ||
        typeof registryApi.get !== "function" ||
        typeof lifecycleApi.ensureLive !== "function" ||
        typeof lifecycleApi.release !== "function"
      ) {
        broken = "omp's agent registry/lifecycle globals are not reachable in this build";
        return;
      }
      managers = {
        get: (agentId: string): AgentRef | null => {
          try {
            return asRecord(
              (registryApi.get as (id: string) => unknown).call(registryApi, agentId),
            ) as AgentRef | null;
          } catch {
            return null;
          }
        },
        mainAgentId: asRecord(registryMod)?.MAIN_AGENT_ID,
        ensureLive: (agentId: string): Promise<unknown> =>
          (lifecycleApi.ensureLive as (id: string) => Promise<unknown>).call(
            lifecycleApi,
            agentId,
          ),
        release: (agentId: string, ref: AgentRef, options: { tombstone: boolean }): Promise<unknown> =>
          (lifecycleApi.release as (id: string, r: unknown, o: unknown) => Promise<unknown>).call(
            lifecycleApi,
            agentId,
            ref,
            options,
          ),
      };
    },
    () => {
      broken = "omp's agent registry/lifecycle modules did not resolve";
    },
  );

  // ------------------------------------------------------------------ publish

  /** The snapshot JSON; false when it cannot fit even with every result dropped. */
  function publishJson(): string | null {
    for (;;) {
      const json = JSON.stringify({
        available: broken === null,
        ...(broken === null ? {} : { reason: "missing-api" }),
        processKey,
        revision,
        results,
      });
      if (utf8Length(json) <= BYTE_LIMIT) return json;
      if (results.length === 0) return null;
      results.shift();
    }
  }

  /** Force-publish: every verb settles into a publish, never a silent ack. */
  function publish(): void {
    if (ui === null) return;
    const json = publishJson();
    if (json === null) {
      revision += 1;
      ui.setStatus(
        STATUS_KEY,
        JSON.stringify({
          available: false,
          reason: "payload-too-large",
          processKey,
          revision,
          results: [],
        }),
      );
      return;
    }
    ui.setStatus(STATUS_KEY, json);
  }

  function settle(
    request: { requestId: string; agentId: string; action: string },
    ok: boolean,
    error?: string,
  ): void {
    results.push({
      requestId: request.requestId,
      agentId: request.agentId,
      action: request.action,
      ok,
      ...(error === undefined ? {} : { error }),
      at: Date.now(),
    });
    while (results.length > RESULT_CAP) results.shift();
    revision += 1;
    publish();
  }

  // -------------------------------------------------------------------- verbs

  /** Hub's own guard order, mirrored: advisor, then aborted, then status. */
  function guardRef(
    request: { requestId: string; agentId: string; action: string },
    ref: AgentRef,
  ): string | null {
    const kind = typeof ref.kind === "string" ? ref.kind : "";
    const id = typeof ref.id === "string" ? ref.id : request.agentId;
    if (kind === "advisor") {
      return request.action === "kill"
        ? ADVISOR_KILL(id)
        : request.action === "revive"
          ? ADVISOR_REVIVE(id)
          : ADVISOR_MESSAGE(id);
    }
    if (kind !== "sub" || id === managers?.mainAgentId) {
      return 'Agent "' + id + '" is not a subagent and cannot be controlled here.';
    }
    const status = typeof ref.status === "string" ? ref.status : "";
    if (status === "aborted" && request.action !== "kill") return ABORTED_SENTENCE(id);
    if (request.action === "revive" && status !== "parked") return PARKED_SENTENCE(id, status);
    return null;
  }

  async function runVerb(
    request: { requestId: string; agentId: string; action: string; text?: string },
  ): Promise<void> {
    await managersReady;
    if (managers === null) {
      settle(request, false, broken ?? "omp's agent registry/lifecycle globals are not reachable");
      return;
    }
    if (inFlight[request.agentId] === true) {
      settle(request, false, BUSY_SENTENCE(request.agentId));
      return;
    }
    inFlight[request.agentId] = true;
    const verb = request.action;
    try {
      const ref = managers.get(request.agentId);
      if (ref === null) {
        settle(request, false, UNKNOWN_SENTENCE(request.agentId));
        return;
      }
      const refusal = guardRef(request, ref);
      if (refusal !== null) {
        settle(request, false, refusal);
        return;
      }
      if (verb === "kill") {
        // Hub's exact order: abort first, then the tombstoned release. release
        // owns the park-cancel/dispose serialization; this bridge never
        // re-implements it, and the tombstone keeps the row + history:// readable.
        if (ref.status === "running" && typeof ref.session === "object" && ref.session !== null) {
          const session = ref.session as AgentSessionLike;
          if (typeof session.abort === "function") {
            await session.abort.call(session, { reason: "Interrupted by user" });
          }
        }
        await managers.release(request.agentId, ref, { tombstone: true });
        settle(request, true);
        return;
      }
      if (verb === "revive") {
        await managers.ensureLive(request.agentId);
        settle(request, true);
        return;
      }
      // steer: ensureLive coalesces a mid-park race (hub's chat-composer path);
      // streamingBehavior "steer" lands mid-turn and starts the next turn idle.
      const session = await managers.ensureLive(request.agentId);
      const live = asRecord(session) as AgentSessionLike | null;
      if (live === null || typeof live.prompt !== "function") {
        settle(request, false, "The subagent session exposes no prompt() in this omp build.");
        return;
      }
      await live.prompt.call(live, request.text ?? "", { streamingBehavior: "steer" });
      settle(request, true);
    } catch (error) {
      console.error("Subagent control bridge: " + verb + " failed", error);
      settle(request, false, error instanceof Error ? error.message : String(error));
    } finally {
      delete inFlight[request.agentId];
    }
  }

  // ---------------------------------------------------------------- command

  /** Strict envelope: { v: 1, request: { requestId, agentId, action, text? } }. */
  function parseRequest(text: string): VerbRequest | null {
    const envelope = asRecord(JSON.parse(text));
    if (envelope === null) return null;
    const keys = Object.keys(envelope).sort();
    if (keys.length !== 2 || keys[0] !== "request" || keys[1] !== "v") return null;
    if (envelope.v !== 1) return null;
    const request = asRecord(envelope.request);
    if (request === null) return null;
    for (const key of Object.keys(request)) {
      if (key !== "requestId" && key !== "agentId" && key !== "action" && key !== "text")
        return null;
    }
    if (typeof request.requestId !== "string" || request.requestId === "") return null;
    if (typeof request.agentId !== "string" || request.agentId === "") return null;
    if (typeof request.action !== "string" || !ACTIONS.includes(request.action)) return null;
    if (request.text !== undefined && typeof request.text !== "string") return null;
    return {
      requestId: request.requestId,
      agentId: request.agentId,
      action: request.action,
      ...(request.text !== undefined ? { text: request.text } : {}),
    };
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui subagent control (steer / kill / revive)",
    handler: async (args: string, ctx: { ui: ControlUi }) => {
      ui = ctx.ui;
      const trimmed = typeof args === "string" ? args.trim() : "";
      if (trimmed === "" || trimmed === "arm") {
        // Arm: bind ui, resolve the globals, republish. No verb, no refusal.
        await managersReady;
        publish();
        return;
      }
      if (!trimmed.startsWith(ARG_PREFIX)) {
        throw new Error("omp-ui-subagent: unsupported command args");
      }
      let request: VerbRequest;
      try {
        const parsed = parseRequest(trimmed.slice(ARG_PREFIX.length));
        if (parsed === null) throw new Error("shape");
        request = parsed;
      } catch {
        throw new Error("omp-ui-subagent: malformed control request");
      }
      const steerText =
        request.action === "steer" && request.text !== undefined ? request.text.trim() : "";
      if (request.action === "steer" && steerText === "") {
        settle(request, false, "A steer needs some text for the agent.");
        return;
      }
      if (request.action === "steer" && steerText.length > STEER_LIMIT) {
        settle(request, false, "That steer is longer than " + STEER_LIMIT + " characters.");
        return;
      }
      await runVerb(request.action === "steer" ? { ...request, text: steerText } : request);
    },
  });

  // Root-session capture only: this bridge drives the registry globals, not
  // the root session — the binding is kept for parity with the other bridges
  // (the arm prompt also proves a root exists before the first publish).
  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype !== undefined && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: Record<string, unknown>, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: Record<string, unknown>, ...args: unknown[]): unknown {
        captureRoot(this);
        return call.apply(this, args);
      };
    }
  } catch {
    /* missing root binding: the command handler still binds ui */
  }

  publish();
}
`;
}

/**
 * Writes the subagent-control bridge into the lineage dir and returns its
 * path, to be passed to omp as `-e`. Rewritten on every spawn so a stale copy
 * from an older omp-ui build can never outvote the current wire contract.
 */
export function writeSubagentControlExtension(lineageDir: string): string {
  return writeLineageArtifact(
    lineageDir,
    subagentControlExtensionPath(lineageDir),
    extensionSource(),
  );
}
