import * as path from "node:path";
import {
  TREE_COMMAND,
  TREE_PREVIEW_CHAR_LIMIT,
  TREE_STATUS_BYTE_LIMIT,
  TREE_STATUS_KEY,
} from "./session-tree";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  generatedAsRecordSource,
  generatedSessionIdSource,
} from "./generated-extension-source";

/**
 * omp's rpc surface reads the session tree (`get_tree`) but offers no verb
 * that JUMPS to an arbitrary entry: `AgentSession.navigateTree(entryId,
 * { summarize })` is in-process only (verified against the managed binary:
 * the rpc dispatch switch has no case for it). Per ADR-0007/0024 this
 * generated extension is the bridge: it publishes the whole entry tree as a
 * `TreeSnapshot` over `ui.setStatus` and executes navigation against the
 * live session, so the omp-ui navigator can move the leaf between branches
 * (issue #680, Phase 2).
 *
 * Every API this needs is unsupported surface, so every one is probed: a
 * missing method publishes `available: false` with the reason and leaves
 * ordinary prompting untouched (the goal bridge's discipline). Navigation
 * while the session is streaming is refused outright — the same busy rule
 * the renderer's guard applies.
 *
 * The snapshot's identity is the root session's own id; the tree itself is
 * omp's, never a second copy: node previews are derived at publish time and
 * capped, and a publish over budget degrades to `payload-too-large` rather
 * than emitting half a tree.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-tree.ts";

export function treeExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants are interpolated
 * from session-tree.ts so publisher and parser cannot drift.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(TREE_STATUS_KEY)};
const COMMAND = ${JSON.stringify(TREE_COMMAND)};
const PREVIEW_LIMIT = ${TREE_PREVIEW_CHAR_LIMIT};
const BYTE_LIMIT = ${TREE_STATUS_BYTE_LIMIT};
const BUSY_REFUSAL = "Stop the current turn before navigating the session tree.";

${generatedAsRecordSource()}

interface TreeSession {
  isStreaming?: unknown;
  isCompacting?: unknown;
  sessionManager?: Record<string, unknown>;
  subscribe?: (listener: (event: Record<string, unknown>) => void) => unknown;
  navigateTree?: (entryId: string, options: { summarize: boolean }) => Promise<unknown>;
}

interface TreeUi {
  setStatus: (key: string, text: string | undefined) => void;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: TreeUi }) => Promise<void>;
    },
  ) => void;
}

export default function (pi: ExtensionApi) {
  let rootSession: TreeSession | null = null;
  ${generatedSessionIdSource("TreeSession")}
  let ui: TreeUi | null = null;
  let revision = 0;
  let navigation: { entryId: string; ok: boolean; error?: string; aborted?: boolean } | null = null;
  let subscribed = false;

  function publishUnavailable(reason: string): void {
    if (!ui) return;
    revision += 1;
    ui.setStatus(
      STATUS_KEY,
      JSON.stringify({
        available: false,
        reason,
        revision,
        leafId: null,
        activePath: [],
        nodes: [],
        ...(navigation === null ? {} : { navigation }),
      }),
    );
  }

  function readString(value: unknown): string {
    return typeof value === "string" ? value : "";
  }

  /** Joined text blocks — the rule omp's own branch listing applies. */
  function previewOf(entry: Record<string, unknown>): string {
    let raw = "";
    if (entry.type === "message") {
      const message = asRecord(entry.message);
      const content = message === null ? undefined : message.content;
      if (typeof content === "string") raw = content;
      else if (Array.isArray(content)) {
        const parts: string[] = [];
        for (const value of content) {
          const block = asRecord(value);
          if (block !== null && block.type === "text" && typeof block.text === "string")
            parts.push(block.text);
        }
        raw = parts.join(" ");
      }
    } else if (entry.type === "compaction") {
      raw = readString(entry.shortSummary) || readString(entry.summary);
    }
    const flat = raw.replace(/\\s+/g, " ").trim();
    return flat.length > PREVIEW_LIMIT ? flat.slice(0, PREVIEW_LIMIT) : flat;
  }

  function flattenNodes(roots: unknown[], nodes: Record<string, unknown>[]): void {
    for (const value of roots) {
      const node = asRecord(value);
      const entry = node === null ? null : asRecord(node.entry);
      if (node === null || entry === null) continue;
      const id = entry.id;
      if (typeof id === "string" && id !== "") {
        const message = asRecord(entry.message);
        nodes.push({
          id,
          parentId: typeof entry.parentId === "string" ? entry.parentId : null,
          type: readString(entry.type) || "unknown",
          ...(message !== null && typeof message.role === "string" ? { role: message.role } : {}),
          text: previewOf(entry),
          timestamp: readString(entry.timestamp),
        });
      }
      const children = node.children;
      if (Array.isArray(children)) flattenNodes(children, nodes);
    }
  }

  function getEntryOf(id: string): Record<string, unknown> | null {
    const manager = asRecord(rootSession?.sessionManager);
    const read = manager === null ? undefined : manager.getEntry;
    if (typeof read !== "function") return null;
    return asRecord((read as (entryId: string) => unknown).call(manager, id));
  }

  function leafIdOf(): string | null {
    const manager = asRecord(rootSession?.sessionManager);
    const read = manager === null ? undefined : manager.getLeafId;
    if (typeof read !== "function") return null;
    const value = (read as () => unknown).call(manager);
    return typeof value === "string" && value !== "" ? value : null;
  }

  function treeRoots(): unknown[] | string {
    const manager = asRecord(rootSession?.sessionManager);
    const read = manager === null ? undefined : manager.getTree;
    if (typeof read !== "function") return "missing-api";
    try {
      const value = (read as () => unknown).call(manager);
      if (!Array.isArray(value)) return "read-failed";
      return value;
    } catch {
      return "read-failed";
    }
  }

  function publish(): void {
    if (!ui) return;
    const root = rootSession;
    if (root === null) {
      publishUnavailable("missing-api");
      return;
    }
    const roots = treeRoots();
    if (typeof roots === "string") {
      publishUnavailable(roots);
      return;
    }
    const leafId = leafIdOf();
    if (leafId === null) {
      publishUnavailable("read-failed");
      return;
    }
    const nodes: Record<string, unknown>[] = [];
    try {
      flattenNodes(roots, nodes);
    } catch {
      publishUnavailable("read-failed");
      return;
    }
    // Root→leaf ids by walking the leaf's parents; a cycle or a missing
    // parent ends the walk where it stands rather than failing the snapshot.
    const activePath: string[] = [];
    const seen = new Set<string>();
    let cursor: string | null = leafId;
    while (cursor !== null && !seen.has(cursor)) {
      seen.add(cursor);
      activePath.push(cursor);
      const entry = getEntryOf(cursor);
      const parent = entry === null ? null : entry.parentId;
      cursor = typeof parent === "string" && parent !== "" ? parent : null;
    }
    activePath.reverse();
    revision += 1;
    const snapshot = {
      available: true,
      revision,
      leafId,
      activePath,
      nodes,
      ...(navigation === null ? {} : { navigation }),
    };
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      publishUnavailable("payload-too-large");
      return;
    }
    ui.setStatus(STATUS_KEY, json);
  }

  function isBusy(): boolean {
    const root = rootSession;
    if (root === null) return false;
    return root.isStreaming === true || root.isCompacting === true;
  }

  function subscribeEvents(root: TreeSession): void {
    if (subscribed || typeof root.subscribe !== "function") return;
    subscribed = true;
    try {
      root.subscribe.call(root, (event: Record<string, unknown>) => {
        const type = typeof event.type === "string" ? event.type : "";
        // The tree only changes on a branch or when a turn appended entries;
        // everything else keeps the last publish standing.
        if (
          type !== "agent_end" &&
          type !== "auto_compaction_end" &&
          type !== "session_branch" &&
          type !== "session_before_branch"
        )
          return;
        try {
          publish();
        } catch {
          /* a publish failure must never surface in the session */
        }
      });
    } catch {
      subscribed = false;
    }
  }

  function captureRoot(candidate: TreeSession): boolean {
    if (rootSession === null) {
      rootSession = candidate;
      subscribeEvents(candidate);
      return true;
    }
    return candidate === rootSession;
  }

  function utf8Length(text: string): number {
    let bytes = 0;
    for (let i = 0; i < text.length; i++) {
      const code = text.charCodeAt(i);
      if (code < 0x80) bytes += 1;
      else if (code < 0x800) bytes += 2;
      else if (code >= 0xd800 && code <= 0xdbff) {
        bytes += 4;
        i++;
      } else bytes += 3;
    }
    return bytes;
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: TreeSession, ...a: unknown[]) => unknown;
      prototype.prompt = function (this: TreeSession, ...args: unknown[]): unknown {
        captureRoot(this);
        return call.apply(this, args);
      };
    }
  } catch {
    /* missing root binding: every publish degrades to unavailable */
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui session tree snapshot and navigation",
    handler: async (args: string, ctx: { ui: TreeUi }) => {
      ui = ctx.ui;
      const trimmed = typeof args === "string" ? args.trim() : "";
      if (trimmed === "" || trimmed === "show") {
        publish();
        return;
      }
      const navigateMatch = /^navigate\\s+(\\S+)(\\s+summarize)?$/.exec(trimmed);
      if (navigateMatch === null) {
        publish();
        return;
      }
      const entryId = navigateMatch[1];
      const summarize = navigateMatch[2] !== undefined;
      const root = rootSession;
      if (root === null || typeof root.navigateTree !== "function") {
        navigation = { entryId, ok: false, error: "navigateTree is not available in this omp build" };
        publishUnavailable("missing-api");
        return;
      }
      if (isBusy()) {
        navigation = { entryId, ok: false, error: BUSY_REFUSAL };
        publish();
        return;
      }
      try {
        const result = asRecord(await root.navigateTree.call(root, entryId, { summarize }));
        const cancelled = result?.cancelled === true;
        navigation = cancelled
          ? { entryId, ok: false, error: "A session hook cancelled the navigation", aborted: true }
          : { entryId, ok: true };
      } catch (error) {
        navigation = { entryId, ok: false, error: String(error) };
      }
      publish();
    },
  });
}
`;
}

/**
 * Writes the tree bridge into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an
 * older omp-ui build can never outvote the current wire contract.
 */
export function writeTreeExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, treeExtensionPath(lineageDir), extensionSource());
}
