import * as path from "node:path";
import {
  VIBE_ARGS_BYTE_LIMIT,
  VIBE_COMMAND,
  VIBE_COMMAND_ARG_PREFIX,
  VIBE_LIFECYCLE_CUSTOM_TYPE,
  VIBE_MODE_TRANSITION_KEY,
  VIBE_POLL_MS,
  VIBE_STATUS_BYTE_LIMIT,
  VIBE_STATUS_KEY,
  VIBE_TOOL_NAMES,
} from "./vibe";
import { writeLineageArtifact } from "./lineage-artifact";
import {
  generatedAsRecordSource,
  generatedModeTransitionSource,
  generatedPollTimerSource,
  generatedSessionIdSource,
  generatedShutdownCleanupSource,
  generatedUtf8LengthSource,
} from "./generated-extension-source";

/**
 * omp's vibe mode is reachable over rpc-ui only through its own parts: the
 * `vibe_*` tools mount when the mode is on (`activateVibeTools`), the session
 * carries the armed flag (`getVibeModeState`/`setVibeModeState`), and the mode
 * round-trips through `appendModeChange`. There is no rpc slash command, so a
 * `/vibe` line would reach the model as literal prompt text.
 *
 * This generated extension therefore owns the vibe lifecycle inside the owned
 * OMP process (ADR-0007/0008 delivery): enter/exit through omp's own runtime
 * surface, worker commands through the mounted tools' `execute` — omp owns
 * every worker semantic, omp-ui owns none — and the roster it reads back from
 * `vibe_list` details plus the transcript's lifecycle entries after a resume.
 * Worker transcripts reach the existing subagent frames on their own: vibe
 * spawns pass the rpc subagent event bus to the task executor, so the Agents
 * pane's click-through works with no bridge involvement (proven live on the
 * 18.4.2 runtime, issue #683 Phase 0).
 *
 * Activation is admitted through one root-local mode-transition chain shared
 * with the plan bridge under `Symbol.for("omp-ui:mode-transition")`;
 * the chain is never held across a worker tool call. Exit runs the per-worker
 * kill instead of omp's `killAll` (unreachable from the shim's module map):
 * explicit-kill tombstones instead of mode-exit ones — the accepted delta in
 * the plan. Resume reconstructs a parked roster from the transcript's own
 * `vibe-session-lifecycle` entries; omp's rehydrate lives on the runtime
 * singleton, which the shim does not export, so parked workers stay read-only
 * until exit or a fresh spawn replaces them.
 *
 * Every API this needs is unsupported surface, so every one is probed: a
 * missing method publishes `unavailable` with the reason and leaves ordinary
 * prompting untouched, rather than faking a mode or driving an unowned tool.
 */

/** The extension file lives beside the transcript so it dies with the lineage. */
const EXTENSION_NAME = "omp-ui-vibe.ts";

export function vibeExtensionPath(lineageDir: string): string {
  return path.join(lineageDir, EXTENSION_NAME);
}

/**
 * The generated source imports nothing; the wire constants are interpolated
 * from vibe.ts so the publishing side can never drift from the parser the main
 * process and the renderers share.
 */
function extensionSource(): string {
  return `// Generated by omp-ui. Rewritten on every spawn; edits are not preserved.
const STATUS_KEY = ${JSON.stringify(VIBE_STATUS_KEY)};
const COMMAND = ${JSON.stringify(VIBE_COMMAND)};
const ARG_PREFIX = ${JSON.stringify(VIBE_COMMAND_ARG_PREFIX)};
const ARM_MESSAGE = "/" + COMMAND;
const ARGS_LIMIT = ${VIBE_ARGS_BYTE_LIMIT};
const BYTE_LIMIT = ${VIBE_STATUS_BYTE_LIMIT};
const POLL_MS = ${VIBE_POLL_MS};
const TRANSITION_KEY = ${JSON.stringify(VIBE_MODE_TRANSITION_KEY)};
const LIFECYCLE_TYPE = ${JSON.stringify(VIBE_LIFECYCLE_CUSTOM_TYPE)};
const TOOL_NAMES = ${JSON.stringify(VIBE_TOOL_NAMES)};
const PLAN_KEEP = "Exit plan mode before entering vibe mode.";
const GOAL_KEEP = "Exit or drop the current goal before entering vibe mode.";
const BUSY_REFUSAL = "Stop the current turn before entering vibe mode.";
const SESSION_APIS = [
  "getVibeModeState",
  "setVibeModeState",
  "activateVibeTools",
  "deactivateVibeTools",
  "runModeExitTeardown",
  "getToolByName",
  "getEnabledToolNames",
  "getPlanModeState",
  "getGoalModeState",
  "getAgentId",
];
const MANAGER_APIS = ["getSessionId", "appendModeChange"];

${generatedPollTimerSource()}

interface StatusUi {
  setStatus: (key: string, text: string | undefined) => void;
  notify: (message: string, level?: "info" | "warning" | "error") => void;
}

interface SessionLike {
  isStreaming?: unknown;
  isAborting?: unknown;
  isCompacting?: unknown;
  hasPostPromptWork?: unknown;
  queuedMessageCount?: unknown;
  sessionManager?: Record<string, unknown>;
  getVibeModeState?: () => unknown;
  setVibeModeState?: (state: unknown) => void;
  activateVibeTools?: (keep: string[]) => Promise<unknown>;
  deactivateVibeTools?: (restore: string[]) => Promise<unknown>;
  runModeExitTeardown?: (work: () => Promise<unknown>) => Promise<unknown>;
  getToolByName?: (name: string) => unknown;
  getEnabledToolNames?: () => unknown;
  getPlanModeState?: () => unknown;
  getGoalModeState?: () => unknown;
  getAgentId?: () => unknown;
  hasBuiltInTool?: (name: string) => unknown;
  subscribe?: (listener: (event: Record<string, unknown>) => void) => unknown;
}

interface ToolLike {
  execute: (...args: unknown[]) => unknown;
}

interface CommandRequest {
  requestId: string;
  sessionId: string;
  processKey: string;
  command: string;
  args: string;
}

interface CommandResult {
  requestId: string;
  ok: boolean;
  text: string;
}

interface RosterRow {
  id: string;
  cli: string;
  state: string;
  killed: boolean;
  model: string | null;
  turns: number;
  queued: number;
  turnMessage: string | null;
  currentTool: string | null;
  lastIntent: string | null;
  createdAt: number;
}

interface ExtensionApi {
  pi?: { AgentSession?: { prototype?: Record<string, unknown> } };
  registerCommand: (
    name: string,
    options: {
      description?: string;
      handler: (args: string, ctx: { ui: StatusUi }) => Promise<void>;
    },
  ) => void;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

${generatedAsRecordSource()}

${generatedUtf8LengthSource()}

export default function (pi: ExtensionApi) {
  const processKey = "omp-ui-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2);

  let rootSession: SessionLike | null = null;
  let ui: StatusUi | null = null;
  let revision = 0;
  let lastDigest = "";
  /** Set only by a probe that failed; null means the bridge can drive vibe. */
  let broken: string | null = null;
  /** Module-resolution failures, keyed by import; non-empty wins availability. */
  const importFailures = new Map<string, string>();
  /** The tools mounted by the last enter; empty whenever the mode is off. */
  const mounted = new Map<string, ToolLike>();
  /** The pre-enter roster, needed by deactivate; null once restored from disk. */
  let previousTools: string[] | null = null;
  /** Parked workers reconstructed from the transcript after resume. */
  let parked: RosterRow[] = [];
  /** The roster of the last digest, reused while an async list settles. */
  let lastRows: RosterRow[] = [];
  let pollTimer: PollTimer | null = null;
  let lastResult: CommandResult | null = null;
  let lastResultSessionId: string | null = null;
  let restoring: Promise<void> | null = null;
  let restoredSessionId: string | null = null;
  const unsubscribe = new Array<() => void>();

  // ---------------------------------------------------------------- readers

  ${generatedSessionIdSource("SessionLike")}
  function modeOn(): boolean {
    const read = rootSession?.getVibeModeState;
    if (typeof read !== "function") return false;
    try {
      return asRecord(read.call(rootSession))?.enabled === true;
    } catch {
      return false;
    }
  }

  function planOn(): boolean {
    const read = rootSession?.getPlanModeState;
    if (typeof read !== "function") return false;
    try {
      return asRecord(read.call(rootSession))?.enabled === true;
    } catch {
      return false;
    }
  }

  /** An unfinished goal owns the mode slot: active, paused, or budget-limited. */
  function goalOn(): boolean {
    const read = rootSession?.getGoalModeState;
    if (typeof read !== "function") return false;
    try {
      const goal = asRecord(asRecord(read.call(rootSession))?.goal);
      if (goal === null) return false;
      const status = goal.status;
      return status !== "complete" && status !== "dropped";
    } catch {
      return false;
    }
  }

  function enabledTools(): string[] | null {
    const read = rootSession?.getEnabledToolNames;
    if (typeof read !== "function") return null;
    try {
      const names = read.call(rootSession);
      return Array.isArray(names) ? (names as unknown[]).filter(isString) : null;
    } catch {
      return null;
    }
  }

  function busy(): boolean {
    const session = rootSession;
    if (session === null) return true;
    try {
      return (
        session.isStreaming === true ||
        session.isAborting === true ||
        session.isCompacting === true ||
        session.hasPostPromptWork === true ||
        (typeof session.queuedMessageCount === "number" && session.queuedMessageCount > 0)
      );
    } catch {
      return true;
    }
  }

  // ------------------------------------------------------- the shared chain

  ${generatedModeTransitionSource("modeTransitionChain")}

  // ------------------------------------------------------------- modules

  // @ts-expect-error -- literal specifier resolves through omp's shim (ADR-0036)
  void import("@oh-my-pi/pi-coding-agent/tools/vibe").then(
    () => publish(false),
    (error: unknown) => {
      importFailures.set("vibe tools", String(error));
      publish(true);
    },
  );

  // --------------------------------------------------------------- roster

  function isThenable(value: unknown): value is PromiseLike<unknown> {
    return (
      typeof value === "object" &&
      value !== null &&
      typeof (value as { then?: unknown }).then === "function"
    );
  }

  /** Screen rows out of a tool outcome's details; null when absent. */
  function rowsOf(outcome: unknown): RosterRow[] | null {
    const details = asRecord(asRecord(outcome)?.details);
    const screens = details?.screens;
    if (!Array.isArray(screens)) return null;
    const rows: RosterRow[] = [];
    for (const entry of screens as unknown[]) {
      const screen = asRecord(entry);
      if (screen === null || !isString(screen.id) || !/^[A-Za-z0-9_-]+$/.test(screen.id)) continue;
      rows.push({
        id: screen.id,
        cli: screen.cli === "good" ? "good" : "fast",
        state: screen.killed === true ? "dead" : isString(screen.state) ? screen.state : "idle",
        killed: screen.killed === true,
        model: isString(screen.model) ? screen.model : null,
        turns: typeof screen.turns === "number" ? screen.turns : 0,
        queued: typeof screen.queued === "number" ? screen.queued : 0,
        turnMessage: isString(screen.turnMessage) ? screen.turnMessage : null,
        currentTool: isString(screen.currentTool) ? screen.currentTool : null,
        lastIntent: isString(screen.lastIntent) ? screen.lastIntent : null,
        createdAt: typeof screen.createdAt === "number" ? screen.createdAt : 0,
      });
    }
    return rows;
  }

  /** The live screen rows while the mode is on; null when unreadable. */
  function liveRows(): RosterRow[] | null {
    const tool = mounted.get("vibe_list");
    if (tool === undefined) return null;
    try {
      const outcome = tool.execute();
      return isThenable(outcome) ? null : rowsOf(outcome);
    } catch {
      return null;
    }
  }

  /** The roster the snapshot carries: live rows while on, parked after resume. */
  function rosterRows(): RosterRow[] {
    if (modeOn()) {
      const live = liveRows();
      if (live !== null) return live;
      // A list tool that answers asynchronously fills in on the next poll;
      // the previous digest carries the rows until then.
      return lastRows;
    }
    return parked;
  }

  // --------------------------------------------------------------- publish

  function brokenReason(): string | null {
    if (broken !== null) return broken;
    if (importFailures.size > 0) {
      return [...importFailures].map(([name, reason]) => name + ": " + reason).join("; ");
    }
    if (rootSession === null) return "no omp session has prompted yet";
    const session = rootSession as unknown as Record<string, unknown>;
    const missing = SESSION_APIS.filter((name) => typeof session[name] !== "function");
    if (missing.length > 0) return "omp session is missing: " + missing.join(", ");
    const manager = asRecord(session.sessionManager);
    const missingManager = manager === null
      ? MANAGER_APIS
      : MANAGER_APIS.filter((name) => typeof manager[name] !== "function");
    if (missingManager.length > 0) return "sessionManager is missing: " + missingManager.join(", ");
    return null;
  }

  function digestOf(rows: RosterRow[], enabled: boolean, result: CommandResult | null): string {
    return JSON.stringify([
      sessionIdOf(rootSession),
      brokenReason() === null,
      enabled,
      rows.map((row) => [
        row.id,
        row.cli,
        row.state,
        row.killed,
        row.model,
        row.turns,
        row.queued,
        row.turnMessage,
        row.currentTool,
        row.lastIntent,
      ]),
      result === null ? null : [result.requestId, result.ok, result.text],
    ]);
  }

  function publish(force: boolean): void {
    if (ui === null) return;
    const reason = brokenReason();
    const enabled = reason === null && modeOn();
    const rows = enabled ? rosterRows() : parked;
    const result = sessionIdOf(rootSession) === lastResultSessionId ? lastResult : null;
    const digest = digestOf(rows, enabled, result);
    if (!force && digest === lastDigest) return;
    lastRows = rows;
    const snapshot: Record<string, unknown> = {
      version: 1,
      processKey,
      sessionId: sessionIdOf(rootSession) ?? "",
      revision: revision + 1,
      available: reason === null,
      unavailable: reason,
      enabled,
      workers: rows,
      result,
    };
    // An impossible payload is published as unavailable, never as half a
    // roster: no worker is ever dropped to fit the channel.
    let json = JSON.stringify(snapshot);
    if (utf8Length(json) > BYTE_LIMIT) {
      snapshot.available = false;
      snapshot.unavailable = "vibe snapshot exceeded " + BYTE_LIMIT + " bytes";
      snapshot.enabled = false;
      snapshot.workers = [];
      json = JSON.stringify(snapshot);
    }
    revision += 1;
    lastDigest = digest;
    ui.setStatus(STATUS_KEY, json);
  }

  /**
   * The list tool's async path: when the sync read produced nothing and the
   * mode is on, take the tool's own promise and republish when it settles.
   */
  async function refreshRows(): Promise<void> {
    if (!modeOn()) return;
    const tool = mounted.get("vibe_list");
    if (tool === undefined) return;
    try {
      const outcome = await Promise.resolve(tool.execute());
      const rows = rowsOf(outcome);
      if (rows === null) return;
      lastRows = rows;
      publish(true);
    } catch {
      /* a failing list is reported by the next command that needs it */
    }
  }

  // ------------------------------------------------------------- polling

  /** Quiet unless the mode is on: workers move on their own clock. */
  function ensurePolling(): void {
    if (!modeOn()) {
      stopPolling();
      return;
    }
    if (pollTimer !== null) return;
    const timer = setInterval(() => {
      try {
        publish(false);
        void refreshRows();
      } catch {
        /* a failing poll keeps the timer; a broken publish reports itself */
      }
    }, POLL_MS);
    pollTimer = timer as unknown as PollTimer;
    try {
      pollTimer.unref?.();
    } catch {
      /* an unref-less runtime keeps the timer as-is */
    }
  }

  function stopPolling(): void {
    if (pollTimer === null) return;
    try {
      clearInterval(pollTimer as unknown as number);
    } catch {
      /* a runtime that refuses clearInterval still loses its handle */
    }
    pollTimer = null;
  }

  // ------------------------------------------------------------- reporting

  function settle(request: CommandRequest, ok: boolean, text: string): void {
    lastResult = { requestId: request.requestId, ok, text };
    lastResultSessionId = sessionIdOf(rootSession);
    try {
      publish(true);
    } catch {
      /* a command always settles as a published status, never a prompt failure */
    }
  }

  // ------------------------------------------------------------- admission

  function refusal(): string | null {
    if (planOn()) return PLAN_KEEP;
    if (goalOn()) return GOAL_KEEP;
    return null;
  }

  // -------------------------------------------------------- enter and exit

  /** The enter body; every caller holds the shared chain already. */
  async function enterLocked(): Promise<string | null> {
    const session = rootSession;
    if (session === null) return "no omp session";
    const again = refusal();
    if (again !== null) return again;
    const keep = ["read"];
    const builtin = session.hasBuiltInTool;
    if (typeof builtin === "function" && builtin.call(session, "todo") === true) keep.push("todo");
    const before = enabledTools();
    if (before === null) return "This omp build cannot report its tool roster.";
    const activate = session.activateVibeTools;
    if (typeof activate !== "function") return "activateVibeTools is not a function";
    await Promise.resolve(activate.call(session, keep));
    const tools = new Map<string, ToolLike>();
    for (const name of TOOL_NAMES) {
      const tool = asRecord(session.getToolByName?.(name));
      if (tool === null || typeof tool.execute !== "function") {
        return "the vibe tool " + name + " did not mount";
      }
      tools.set(name, tool as unknown as ToolLike);
    }
    // The mode flips only after every tool resolved, so a partial mount
    // leaves the session exactly as it was found.
    mounted.clear();
    for (const [name, tool] of tools) mounted.set(name, tool);
    previousTools = before;
    session.setVibeModeState?.({ enabled: true });
    const manager = asRecord(session.sessionManager);
    if (manager !== null && typeof manager.appendModeChange === "function") {
      await Promise.resolve(manager.appendModeChange.call(manager, "vibe", { previousTools: before }));
    }
    return null;
  }

  function enter(): Promise<string | null> {
    return inTransition(enterLocked);
  }

  /** The exit body; every caller holds the shared chain already. */
  async function exitLocked(): Promise<string | null> {
    const session = rootSession;
    if (session === null) return "no omp session";
    const runTeardown = session.runModeExitTeardown;
    const work = async (): Promise<string | null> => {
      const killTool = mounted.get("vibe_kill");
      const listTool = mounted.get("vibe_list");
      if (killTool !== undefined && listTool !== undefined) {
        let rows = rowsOf(listTool.execute());
        if (rows === null) rows = rowsOf(await Promise.resolve(listTool.execute()));
        for (const row of rows ?? []) {
          if (row.killed) continue;
          try {
            await Promise.resolve(killTool.execute(undefined, { session: row.id }));
          } catch {
            /* a worker that refuses to die is reported by the settle list */
          }
        }
      }
      const restore = previousTools ?? enabledTools() ?? [];
      const deactivate = session.deactivateVibeTools;
      if (typeof deactivate !== "function") return "deactivateVibeTools is not a function";
      await Promise.resolve(deactivate.call(session, restore));
      session.setVibeModeState?.(undefined);
      const manager = asRecord(session.sessionManager);
      if (manager !== null && typeof manager.appendModeChange === "function") {
        await Promise.resolve(manager.appendModeChange.call(manager, "none", {}));
      }
      mounted.clear();
      previousTools = null;
      parked = [];
      return null;
    };
    if (typeof runTeardown === "function") {
      // omp's runModeExitTeardown awaits the body but returns undefined, so
      // the work's own verdict travels through a box, not through the call.
      let problem: string | null = null;
      await Promise.resolve(runTeardown.call(session, async () => {
        problem = await work();
      }));
      return problem;
    }
    return await work();
  }

  function exit(): Promise<string | null> {
    return inTransition(exitLocked);
  }

  // ------------------------------------------------------------ restoration

  /**
   * Replay omp's own lifecycle entries into a parked roster: spawn adds, an
   * explicit kill removes (that worker was deleted on purpose), a mode-exit
   * tombstone keeps it parked, tombstone-revoked re-parks. omp's rehydrate is
   * runtime-singleton surface the shim does not export, so parked workers are
   * read-only. Runs inside the shared chain so a Plan entry can never read a
   * half-restored mode.
   */
  function restore(): Promise<void> {
    const pending = restoring;
    if (pending !== null) return pending;
    const task = inTransition(async () => {
      const session = rootSession;
      if (session === null) return;
      const manager = asRecord(session.sessionManager);
      const id = sessionIdOf(session);
      parked = [];
      mounted.clear();
      previousTools = null;
      let transcriptMode: unknown;
      const spawns = new Map<string, { cli: string; createdAt: number }>();
      const settledTurns = new Map<string, number>();
      if (manager !== null) {
        const getEntries = manager.getEntries;
        if (typeof getEntries === "function") {
          const entries = getEntries.call(manager);
          if (Array.isArray(entries)) {
            for (const entry of entries as unknown[]) {
              const record = asRecord(entry);
              if (record === null) continue;
              if (record.type === "mode_change") transcriptMode = record.mode;
              if (record.customType !== LIFECYCLE_TYPE) continue;
              const data = asRecord(record.data);
              if (data === null || !isString(data.id) || !/^[A-Za-z0-9_-]+$/.test(data.id)) continue;
              if (data.action === "spawn") {
                spawns.set(data.id, {
                  cli: data.cli === "good" ? "good" : "fast",
                  createdAt: typeof data.createdAt === "number" ? data.createdAt : 0,
                });
              } else if (data.action === "turn-settled") {
                settledTurns.set(data.id, (settledTurns.get(data.id) ?? 0) + 1);
              } else if (data.action === "tombstone" && data.reason === "explicit-kill") {
                spawns.delete(data.id);
              }
            }
          }
        }
      }
      parked = [...spawns].map(([workerId, meta]) => ({
        id: workerId,
        cli: meta.cli,
        state: "parked",
        killed: false,
        model: null,
        turns: settledTurns.get(workerId) ?? 0,
        queued: 0,
        turnMessage: null,
        currentTool: null,
        lastIntent: null,
        createdAt: meta.createdAt,
      }));
      if (transcriptMode === "vibe") {
        // The transcript says the mode never exited: re-arm it over the dead
        // scope. Workers stay parked (read-only) until exit or a fresh spawn.
        const problem = await enterLocked();
        if (problem !== null) broken = "the saved vibe mode could not be re-armed: " + problem;
      } else if (modeOn()) {
        session.setVibeModeState?.(undefined);
        mounted.clear();
      }
      restoredSessionId = id;
    })
      .catch((error: unknown) => {
        broken = "vibe restoration failed: " + String(error);
      })
      .then(() => {
        restoring = null;
        try {
          publish(true);
          ensurePolling();
        } catch {
          /* a restored session still publishes on the next event */
        }
      });
    restoring = task;
    return task;
  }

  // --------------------------------------------------------------- verbs

  function parseJsonArgs(args: string): Record<string, unknown> | null {
    const trimmed = args.trim();
    if (trimmed === "") return {};
    return asRecord(safeParse(trimmed));
  }

  async function callTool(request: CommandRequest, name: string, toolArgs: unknown[]): Promise<void> {
    const tool = mounted.get(name);
    if (tool === undefined) {
      settle(request, false, "Vibe mode is not active; nothing is mounted.");
      return;
    }
    try {
      const outcome = asRecord(await Promise.resolve(tool.execute(...toolArgs)));
      const first = asRecord((outcome?.content as unknown[] | undefined)?.[0]);
      const text = first !== null && isString(first.text) ? first.text : "";
      settle(request, true, text);
    } catch (error) {
      settle(request, false, error instanceof Error ? error.message : String(error));
    }
    await refreshRows();
  }

  function rosterText(rows: RosterRow[]): string {
    if (rows.length === 0) return "No vibe workers.";
    return rows
      .map((row) =>
        "- " + row.id + " [" + row.cli + "] " + row.state +
        (row.turnMessage === null ? "" : " — " + row.turnMessage))
      .join("\\n");
  }

  async function runCommand(request: CommandRequest): Promise<void> {
    if (request.command === "list") {
      return settle(request, true, rosterText(rosterRows()));
    }
    const brokenNow = brokenReason();
    if (brokenNow !== null) return settle(request, false, "Vibe commands are unavailable: " + brokenNow);
    const args = parseJsonArgs(request.args);
    if (request.command === "toggle") {
      if (args === null) return settle(request, false, "toggle takes no arguments.");
      if (modeOn()) {
        const problem = await exit();
        stopPolling();
        if (problem !== null) return settle(request, false, problem);
        return settle(request, true, "Vibe mode exited; workers were killed.");
      }
      if (busy()) return settle(request, false, BUSY_REFUSAL);
      const refusalReason = refusal();
      if (refusalReason !== null) return settle(request, false, refusalReason);
      const problem = await enter();
      ensurePolling();
      if (problem !== null) return settle(request, false, problem);
      return settle(request, true, "Vibe mode on. The director keeps read and todo; workers answer through vibe tools.");
    }
    if (request.command === "off") {
      if (!modeOn()) {
        parked = [];
        publish(true);
        return settle(request, true, "Vibe mode is already off.");
      }
      const problem = await exit();
      stopPolling();
      if (problem !== null) return settle(request, false, problem);
      return settle(request, true, "Vibe mode exited; workers were killed.");
    }
    if (!modeOn()) return settle(request, false, "Vibe mode is off. Use /vibe to turn it on.");
    if (args === null) return settle(request, false, "The command arguments are not valid JSON.");
    if (request.command === "spawn") {
      const cli = args.cli === "good" ? "good" : "fast";
      const prompt = isString(args.prompt) ? args.prompt.trim() : "";
      if (prompt === "") return settle(request, false, "spawn needs a prompt.");
      const spawnArgs: Record<string, unknown> = { cli, prompt };
      if (isString(args.name) && /^[A-Za-z0-9_-]{1,32}$/.test(args.name.trim())) {
        spawnArgs.name = args.name.trim();
      }
      return callTool(request, "vibe_spawn", [undefined, spawnArgs]);
    }
    if (request.command === "send") {
      const session = isString(args.session) ? args.session.trim() : "";
      const message = isString(args.message) ? args.message : "";
      if (session === "" || message.trim() === "") {
        return settle(request, false, "send needs a session and a message.");
      }
      return callTool(request, "vibe_send", [undefined, { session, message }]);
    }
    if (request.command === "wait") {
      const waitArgs: Record<string, unknown> = {};
      if (Array.isArray(args.sessions)) {
        const sessions = (args.sessions as unknown[]).filter(isString);
        if (sessions.length > 0) waitArgs.sessions = sessions;
      }
      waitArgs.timeout = typeof args.timeout === "number" && Number.isFinite(args.timeout)
        ? Math.max(1, Math.min(600, Math.floor(args.timeout)))
        : 120;
      return callTool(request, "vibe_wait", [undefined, waitArgs]);
    }
    if (request.command === "kill") {
      const session = isString(args.session) ? args.session.trim() : "";
      if (session === "") return settle(request, false, "kill needs a session.");
      const killTool = mounted.get("vibe_kill");
      if (killTool === undefined) return settle(request, false, "Vibe mode is not active; nothing is mounted.");
      const problem = await inTransition(async () => {
        try {
          await Promise.resolve(killTool.execute(undefined, { session }));
          return null;
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      });
      await refreshRows();
      return problem === null
        ? settle(request, true, "Killed session " + session + ".")
        : settle(request, false, problem);
    }
    return settle(request, false, "unknown vibe command: " + request.command);
  }

  // -------------------------------------------------------------- command

  function parseRequest(json: string): CommandRequest | null {
    const record = asRecord(safeParse(json));
    if (record === null) return null;
    const requestId = isString(record.requestId) && record.requestId.length > 0 ? record.requestId : null;
    const sessionId = isString(record.sessionId) && record.sessionId.length > 0 ? record.sessionId : null;
    const process = isString(record.processKey) && record.processKey.length > 0 ? record.processKey : null;
    if (requestId === null || sessionId === null || process === null) return null;
    if (!isString(record.command) || record.command.length === 0) return null;
    if (!isString(record.args)) return null;
    return { requestId, sessionId, processKey: process, command: record.command, args: record.args };
  }

  function safeParse(text: string): unknown {
    try {
      return JSON.parse(text);
    } catch {
      return null;
    }
  }

  async function handleCommand(request: CommandRequest): Promise<void> {
    const session = rootSession;
    const id = sessionIdOf(session);
    if (session === null || request.processKey !== processKey) {
      // Another bridge instance's request, or ours after a restart: never applied.
      ui?.notify("omp-ui-vibe: ignoring a command addressed to another process", "warning");
      return;
    }
    if (id !== null && request.sessionId !== id) {
      settle(request, false, "The session changed before this command ran.");
      return;
    }
    const brokenNow = brokenReason();
    if (brokenNow !== null) {
      publish(true);
      return settle(request, false, "Vibe commands are unavailable: " + brokenNow);
    }
    if (utf8Length(request.args) > ARGS_LIMIT) {
      return settle(request, false, "Vibe command arguments exceed " + ARGS_LIMIT + " bytes.");
    }
    await runCommand(request);
    ensurePolling();
  }

  // --------------------------------------------------------------- events

  function onEvent(event: Record<string, unknown>): void {
    try {
      const type = event.type;
      if (type === "tool_execution_end" || type === "agent_end") {
        publish(false);
        void refreshRows();
        ensurePolling();
      }
    } catch {
      /* a bridge event handler must never take down the session's stream */
    }
  }

  function bindRoot(session: SessionLike): void {
    if (rootSession !== null) return;
    rootSession = session;
    bindShutdown(session);
    const subscribe = session.subscribe;
    if (typeof subscribe === "function") {
      try {
        const off = subscribe.call(session, (event) => onEvent(asRecord(event) ?? {}));
        if (typeof off === "function") unsubscribe.push(off as () => void);
      } catch {
        /* an unsubscribable session still answers commands */
      }
    }
  }

  /** Same root-shutdown discipline every generated bridge uses. */
  ${generatedShutdownCleanupSource("SessionLike")}

  function teardown(): void {
    stopPolling();
    for (const off of unsubscribe.splice(0)) {
      try {
        off();
      } catch {
        /* a runtime that refuses unsubscribe is leaving anyway */
      }
    }
  }

  try {
    const prototype = pi.pi?.AgentSession?.prototype;
    const originalPrompt = prototype?.prompt;
    if (prototype !== undefined && typeof originalPrompt === "function") {
      const call = originalPrompt as (this: SessionLike, ...args: unknown[]) => unknown;
      prototype.prompt = function (this: SessionLike, ...args: unknown[]): unknown {
        const isRoot = rootSession === null || this === rootSession;
        const text = isString(args[0]) ? args[0].trim() : null;
        const bridge = text !== null && (text === ARM_MESSAGE || text.startsWith(ARM_MESSAGE + " " + ARG_PREFIX));
        const invoke = (): unknown => call.apply(this, args);
        if (!isRoot) return invoke();
        bindRoot(this);
        const pending = restoring;
        if (pending === null || bridge) return invoke();
        // Ordinary prompting waits for restoration so the model never sees a
        // half-restored mode; the arm/command must not wait on it.
        return pending.then(invoke, invoke);
      };
    }
  } catch (error) {
    broken = "could not hook AgentSession.prompt: " + String(error);
  }

  pi.registerCommand(COMMAND, {
    description: "omp-ui vibe mode control",
    handler: async (args: string, ctx: { ui: StatusUi }) => {
      ui = ctx.ui;
      const trimmed = isString(args) ? args.trim() : "";
      if (trimmed === "") {
        const id = sessionIdOf(rootSession);
        if (id !== null && id !== restoredSessionId) await restore();
        publish(true);
        ensurePolling();
        return;
      }
      if (!trimmed.startsWith(ARG_PREFIX)) {
        throw new Error("omp-ui-vibe: unsupported command args");
      }
      const request = parseRequest(trimmed.slice(ARG_PREFIX.length));
      if (request === null) {
        throw new Error("omp-ui-vibe: malformed vibe command request");
      }
      await handleCommand(request);
    },
  });
}
`;
}

/**
 * Writes the vibe bridge into the lineage dir and returns its path, to be
 * passed to omp as `-e`. Rewritten on every spawn so a stale copy from an older
 * omp-ui build can never outvote the current wire contract.
 */
export function writeVibeExtension(lineageDir: string): string {
  return writeLineageArtifact(lineageDir, vibeExtensionPath(lineageDir), extensionSource());
}
